// Generated by tools/gen-vex-width-test.py -- do not edit.
//
// The width-changing VEX ops against their SSE forms (see the generator).
#pragma GCC target("avx2")
#include <stdint.h>
#include <stdio.h>
#include <string.h>
static unsigned long checks, bad;
static void check(const char *what, int k, const uint8_t *got, const uint8_t *want, unsigned gf, unsigned wf) {
    checks++;
    if ((memcmp(got, want, 32) != 0 || gf != wf) && bad++ < 40) {
        printf("FAIL %s (%d): flags %#x want %#x\n  got ", what, k, gf, wf);
        for (int i = 31; i >= 0; i--) printf("%s%02x", i % 8 == 7 ? " " : "", got[i]);
        printf("\n  want");
        for (int i = 31; i >= 0; i--) printf("%s%02x", i % 8 == 7 ? " " : "", want[i]);
        printf("\n");
    }
}
static uint64_t rs = 0x9e3779b97f4a7c15ull;
static uint64_t rnd(void) { rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }
static void ldmx(unsigned v) { __asm__ volatile("ldmxcsr %0" :: "m"(v)); }
static unsigned stmx(void) { unsigned v; __asm__ volatile("stmxcsr %0" : "=m"(v)); return v; }
struct st { uint8_t a[32], b[32], d[32], out[32], m[64]; } __attribute__((aligned(32)));
static void fill(uint8_t *p, int n, int dbl) {
    for (int i = 0; i < n; i += 8) {
        uint64_t v = rnd();
        if ((v & 7) == 0) v = (v & 0x800fffffffffffffull) | ((uint64_t) ((v >> 40) & 1 ? 0x7ff : 0) << 52);
        else if (dbl) v = (v & 0x800fffffffffffffull) | ((uint64_t) (((v >> 52) % 400) + 800) << 52);
        memcpy(p + i, &v, 8);
    }
}

static void r_cvtps2pd(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n cvtps2pd %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_cvtdq2pd(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n cvtdq2pd %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_pmovsxbw(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n pmovsxbw %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_pmovsxbd(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n pmovsxbd %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_pmovsxbq(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n pmovsxbq %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_pmovsxwd(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n pmovsxwd %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_pmovsxwq(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n pmovsxwq %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_pmovsxdq(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n pmovsxdq %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_pmovzxbw(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n pmovzxbw %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_pmovzxbd(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n pmovzxbd %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_pmovzxbq(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n pmovzxbq %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_pmovzxwd(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n pmovzxwd %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_pmovzxwq(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n pmovzxwq %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_pmovzxdq(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n pmovzxdq %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_cvtpd2ps(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n cvtpd2ps %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_cvtpd2dq(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n cvtpd2dq %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_cvttpd2dq(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n cvttpd2dq %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_cvtss2sd(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n cvtss2sd %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
static void r_cvtsd2ss(const uint8_t *x, const uint8_t *y, uint8_t *r) { __asm__ volatile("movdqu (%0), %%xmm0\n movdqu (%1), %%xmm1\n cvtsd2ss %%xmm1, %%xmm0\n movdqu %%xmm0, (%2)" :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }
__attribute__((noinline)) static void f0(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtps2pd %%xmm3, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f1(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtps2pd 128(%0), %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f2(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtps2pd %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f3(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtps2pd 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f4(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtdq2pd %%xmm3, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f5(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtdq2pd 128(%0), %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f6(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtdq2pd %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f7(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtdq2pd 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f8(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxbw %%xmm3, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f9(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxbw 128(%0), %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f10(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxbw %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f11(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxbw 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f12(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxbd %%xmm3, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f13(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxbd 128(%0), %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f14(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxbd %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f15(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxbd 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f16(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxbq %%xmm3, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f17(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxbq 128(%0), %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f18(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxbq %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f19(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxbq 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f20(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxwd %%xmm3, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f21(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxwd 128(%0), %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f22(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxwd %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f23(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxwd 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f24(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxwq %%xmm3, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f25(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxwq 128(%0), %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f26(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxwq %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f27(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxwq 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f28(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxdq %%xmm3, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f29(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxdq 128(%0), %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f30(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxdq %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f31(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovsxdq 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f32(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxbw %%xmm3, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f33(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxbw 128(%0), %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f34(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxbw %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f35(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxbw 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f36(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxbd %%xmm3, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f37(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxbd 128(%0), %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f38(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxbd %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f39(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxbd 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f40(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxbq %%xmm3, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f41(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxbq 128(%0), %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f42(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxbq %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f43(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxbq 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f44(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxwd %%xmm3, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f45(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxwd 128(%0), %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f46(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxwd %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f47(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxwd 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f48(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxwq %%xmm3, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f49(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxwq 128(%0), %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f50(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxwq %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f51(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxwq 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f52(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxdq %%xmm3, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f53(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxdq 128(%0), %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f54(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxdq %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f55(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vpmovzxdq 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f56(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtpd2ps %%ymm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f57(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtpd2psy 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f58(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtpd2ps %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f59(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtpd2psx 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f60(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtpd2dq %%ymm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f61(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtpd2dqy 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f62(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtpd2dq %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f63(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtpd2dqx 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f64(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvttpd2dq %%ymm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f65(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvttpd2dqy 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f66(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvttpd2dq %%xmm3, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f67(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvttpd2dqx 128(%0), %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f68(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtss2sd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f69(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtss2sd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f70(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtsd2ss %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f71(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vcvtsd2ss 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
static const struct { const char *name; void (*fn)(struct st *); void (*ref)(const uint8_t *, const uint8_t *, uint8_t *); int kind, step, L; char src; int fp; } forms[] = {
    {"vcvtps2pd 256 reg", f0, r_cvtps2pd, 0, 8, 256, 'b', 1},
    {"vcvtps2pd 256 mem", f1, r_cvtps2pd, 0, 8, 256, 'm', 1},
    {"vcvtps2pd 128 reg", f2, r_cvtps2pd, 0, 8, 128, 'b', 1},
    {"vcvtps2pd 128 mem", f3, r_cvtps2pd, 0, 8, 128, 'm', 1},
    {"vcvtdq2pd 256 reg", f4, r_cvtdq2pd, 0, 8, 256, 'b', 1},
    {"vcvtdq2pd 256 mem", f5, r_cvtdq2pd, 0, 8, 256, 'm', 1},
    {"vcvtdq2pd 128 reg", f6, r_cvtdq2pd, 0, 8, 128, 'b', 1},
    {"vcvtdq2pd 128 mem", f7, r_cvtdq2pd, 0, 8, 128, 'm', 1},
    {"vpmovsxbw 256 reg", f8, r_pmovsxbw, 0, 8, 256, 'b', 0},
    {"vpmovsxbw 256 mem", f9, r_pmovsxbw, 0, 8, 256, 'm', 0},
    {"vpmovsxbw 128 reg", f10, r_pmovsxbw, 0, 8, 128, 'b', 0},
    {"vpmovsxbw 128 mem", f11, r_pmovsxbw, 0, 8, 128, 'm', 0},
    {"vpmovsxbd 256 reg", f12, r_pmovsxbd, 0, 4, 256, 'b', 0},
    {"vpmovsxbd 256 mem", f13, r_pmovsxbd, 0, 4, 256, 'm', 0},
    {"vpmovsxbd 128 reg", f14, r_pmovsxbd, 0, 4, 128, 'b', 0},
    {"vpmovsxbd 128 mem", f15, r_pmovsxbd, 0, 4, 128, 'm', 0},
    {"vpmovsxbq 256 reg", f16, r_pmovsxbq, 0, 2, 256, 'b', 0},
    {"vpmovsxbq 256 mem", f17, r_pmovsxbq, 0, 2, 256, 'm', 0},
    {"vpmovsxbq 128 reg", f18, r_pmovsxbq, 0, 2, 128, 'b', 0},
    {"vpmovsxbq 128 mem", f19, r_pmovsxbq, 0, 2, 128, 'm', 0},
    {"vpmovsxwd 256 reg", f20, r_pmovsxwd, 0, 8, 256, 'b', 0},
    {"vpmovsxwd 256 mem", f21, r_pmovsxwd, 0, 8, 256, 'm', 0},
    {"vpmovsxwd 128 reg", f22, r_pmovsxwd, 0, 8, 128, 'b', 0},
    {"vpmovsxwd 128 mem", f23, r_pmovsxwd, 0, 8, 128, 'm', 0},
    {"vpmovsxwq 256 reg", f24, r_pmovsxwq, 0, 4, 256, 'b', 0},
    {"vpmovsxwq 256 mem", f25, r_pmovsxwq, 0, 4, 256, 'm', 0},
    {"vpmovsxwq 128 reg", f26, r_pmovsxwq, 0, 4, 128, 'b', 0},
    {"vpmovsxwq 128 mem", f27, r_pmovsxwq, 0, 4, 128, 'm', 0},
    {"vpmovsxdq 256 reg", f28, r_pmovsxdq, 0, 8, 256, 'b', 0},
    {"vpmovsxdq 256 mem", f29, r_pmovsxdq, 0, 8, 256, 'm', 0},
    {"vpmovsxdq 128 reg", f30, r_pmovsxdq, 0, 8, 128, 'b', 0},
    {"vpmovsxdq 128 mem", f31, r_pmovsxdq, 0, 8, 128, 'm', 0},
    {"vpmovzxbw 256 reg", f32, r_pmovzxbw, 0, 8, 256, 'b', 0},
    {"vpmovzxbw 256 mem", f33, r_pmovzxbw, 0, 8, 256, 'm', 0},
    {"vpmovzxbw 128 reg", f34, r_pmovzxbw, 0, 8, 128, 'b', 0},
    {"vpmovzxbw 128 mem", f35, r_pmovzxbw, 0, 8, 128, 'm', 0},
    {"vpmovzxbd 256 reg", f36, r_pmovzxbd, 0, 4, 256, 'b', 0},
    {"vpmovzxbd 256 mem", f37, r_pmovzxbd, 0, 4, 256, 'm', 0},
    {"vpmovzxbd 128 reg", f38, r_pmovzxbd, 0, 4, 128, 'b', 0},
    {"vpmovzxbd 128 mem", f39, r_pmovzxbd, 0, 4, 128, 'm', 0},
    {"vpmovzxbq 256 reg", f40, r_pmovzxbq, 0, 2, 256, 'b', 0},
    {"vpmovzxbq 256 mem", f41, r_pmovzxbq, 0, 2, 256, 'm', 0},
    {"vpmovzxbq 128 reg", f42, r_pmovzxbq, 0, 2, 128, 'b', 0},
    {"vpmovzxbq 128 mem", f43, r_pmovzxbq, 0, 2, 128, 'm', 0},
    {"vpmovzxwd 256 reg", f44, r_pmovzxwd, 0, 8, 256, 'b', 0},
    {"vpmovzxwd 256 mem", f45, r_pmovzxwd, 0, 8, 256, 'm', 0},
    {"vpmovzxwd 128 reg", f46, r_pmovzxwd, 0, 8, 128, 'b', 0},
    {"vpmovzxwd 128 mem", f47, r_pmovzxwd, 0, 8, 128, 'm', 0},
    {"vpmovzxwq 256 reg", f48, r_pmovzxwq, 0, 4, 256, 'b', 0},
    {"vpmovzxwq 256 mem", f49, r_pmovzxwq, 0, 4, 256, 'm', 0},
    {"vpmovzxwq 128 reg", f50, r_pmovzxwq, 0, 4, 128, 'b', 0},
    {"vpmovzxwq 128 mem", f51, r_pmovzxwq, 0, 4, 128, 'm', 0},
    {"vpmovzxdq 256 reg", f52, r_pmovzxdq, 0, 8, 256, 'b', 0},
    {"vpmovzxdq 256 mem", f53, r_pmovzxdq, 0, 8, 256, 'm', 0},
    {"vpmovzxdq 128 reg", f54, r_pmovzxdq, 0, 8, 128, 'b', 0},
    {"vpmovzxdq 128 mem", f55, r_pmovzxdq, 0, 8, 128, 'm', 0},
    {"vcvtpd2ps 256 reg", f56, r_cvtpd2ps, 1, 0, 256, 'b', 1},
    {"vcvtpd2ps 256 mem", f57, r_cvtpd2ps, 1, 0, 256, 'm', 1},
    {"vcvtpd2ps 128 reg", f58, r_cvtpd2ps, 1, 0, 128, 'b', 1},
    {"vcvtpd2ps 128 mem", f59, r_cvtpd2ps, 1, 0, 128, 'm', 1},
    {"vcvtpd2dq 256 reg", f60, r_cvtpd2dq, 1, 0, 256, 'b', 1},
    {"vcvtpd2dq 256 mem", f61, r_cvtpd2dq, 1, 0, 256, 'm', 1},
    {"vcvtpd2dq 128 reg", f62, r_cvtpd2dq, 1, 0, 128, 'b', 1},
    {"vcvtpd2dq 128 mem", f63, r_cvtpd2dq, 1, 0, 128, 'm', 1},
    {"vcvttpd2dq 256 reg", f64, r_cvttpd2dq, 1, 0, 256, 'b', 1},
    {"vcvttpd2dq 256 mem", f65, r_cvttpd2dq, 1, 0, 256, 'm', 1},
    {"vcvttpd2dq 128 reg", f66, r_cvttpd2dq, 1, 0, 128, 'b', 1},
    {"vcvttpd2dq 128 mem", f67, r_cvttpd2dq, 1, 0, 128, 'm', 1},
    {"vcvtss2sd reg", f68, r_cvtss2sd, 2, 0, 128, 'b', 1},
    {"vcvtss2sd mem", f69, r_cvtss2sd, 2, 0, 128, 'm', 1},
    {"vcvtsd2ss reg", f70, r_cvtsd2ss, 2, 0, 128, 'b', 1},
    {"vcvtsd2ss mem", f71, r_cvtsd2ss, 2, 0, 128, 'm', 1},
};
#define NFORMS 72
static const unsigned modes[] = {0x1f80, 0x7f80, 0x9fc0};

int main(void) {
    static struct st t;
    for (int k = 0; k < 300; k++) {
        for (unsigned mi = 0; mi < 3; mi++) {
            for (int fi = 0; fi < NFORMS; fi++) {
                if (!forms[fi].fp && mi) continue;
                fill(t.a, 32, k & 1); fill(t.b, 32, k & 1); fill(t.d, 32, k & 1); fill(t.m, 64, k & 1);
                if (k & 2) for (int i = 0; i < 32; i += 4) { uint32_t v = (uint32_t) rnd(); if ((v & 3) == 0) v = 0x7fc00000 | (v & 0x80000000); memcpy(t.b + i, &v, 4); memcpy(t.m + i, &v, 4); }
                struct st in = t;
                ldmx(modes[mi]);
                forms[fi].fn(&t);
                unsigned gf = stmx() & 0x3f, wf = 0;
                const uint8_t *s = forms[fi].src == 'm' ? in.m : in.b;
                uint8_t want[32] = {0}, tmp[16], adv[32] = {0};
                if (forms[fi].kind == 0) {
                    ldmx(modes[mi]); forms[fi].ref(in.d, s, want); wf = stmx() & 0x3f;
                    if (forms[fi].L == 256) {
                        memcpy(adv, s + forms[fi].step, 16);
                        ldmx(modes[mi]); forms[fi].ref(in.d, adv, want + 16); wf |= stmx() & 0x3f;
                    }
                } else if (forms[fi].kind == 1) {
                    ldmx(modes[mi]); forms[fi].ref(in.d, s, tmp); wf = stmx() & 0x3f;
                    memcpy(want, tmp, 8);
                    if (forms[fi].L == 256) {
                        ldmx(modes[mi]); forms[fi].ref(in.d, s + 16, tmp); wf |= stmx() & 0x3f;
                        memcpy(want + 8, tmp, 8);
                    }
                } else {
                    ldmx(modes[mi]); forms[fi].ref(in.a, s, want); wf = stmx() & 0x3f;
                }
                check(forms[fi].name, k, t.out, want, gf, wf);
            }
        }
    }
    ldmx(0x1f80);
    printf("amd64_vex_width: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NFORMS, checks, bad);
    return bad != 0;
}