// Generated by tools/gen-amd64-sse-int-test.py --i386 -- do not edit.
//
// The SSE2 and MMX packed-integer ops (add/sub with and without saturation,
// compares, logic, min/max, average, the multiplies, PMADDWD, PSADBW, the
// unpacks and packs) -- XMM (66) and MMX, register and memory sources,
// xmm1, built -m32 -- against byte-array models; checked against real hardware (an
// AMD Ryzen). Vectorisation is off: the model must not become SSE itself.
#pragma GCC optimize("no-tree-vectorize")
#pragma GCC target("mmx,sse2")
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static unsigned long checks, bad;
static void check(const char *what, long k, uint64_t got, uint64_t want) {
    checks++;
    if (got != want && bad++ < 40)
        printf("FAIL %s (%ld): %#llx, want %#llx\n", what, k, (unsigned long long) got, (unsigned long long) want);
}
static uint64_t rs = 0x243f6a8885a308d3ull;
static uint64_t rnd(void) { rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }

static uint64_t get(const uint8_t *p, int lb) { uint64_t v = 0; for (int b = 0; b < lb; b++) v |= (uint64_t) p[b] << (8 * b); return v; }
static void put(uint8_t *p, int lb, uint64_t v) { for (int b = 0; b < lb; b++) p[b] = (uint8_t) (v >> (8 * b)); }
static int64_t sx(uint64_t v, int lb) { int s = 64 - 8 * lb; return lb == 8 ? (int64_t) v : (int64_t) (v << s) >> s; }
static int64_t clamp(int64_t v, int64_t lo, int64_t hi) { return v < lo ? lo : v > hi ? hi : v; }
// a * b, unsigned, by shift and add: no multiply instruction in the model
static uint64_t mulu(uint64_t a, uint64_t b) { uint64_t r = 0; for (int i = 0; i < 64; i++) if ((b >> i) & 1) r += a << i; return r; }
static int64_t muls(int64_t a, int64_t b) { int n = (a < 0) != (b < 0); uint64_t r = mulu(a < 0 ? -(uint64_t) a : a, b < 0 ? -(uint64_t) b : b); return n ? -(int64_t) r : (int64_t) r; }

static void model(const char *m, int lb, int nb, const uint8_t *d, const uint8_t *s, uint8_t *out) {
    int n = nb / lb;
    uint64_t mask = lb == 8 ? ~0ull : (1ull << (8 * lb)) - 1;
    int64_t smax = (int64_t) (mask >> 1), smin = -smax - 1;
    if (!strcmp(m, "unpckl") || !strcmp(m, "unpckh")) {
        int base = !strcmp(m, "unpckh") ? n / 2 : 0;
        for (int i = 0; i < n / 2; i++) {
            put(out + (2 * i) * lb, lb, get(d + (base + i) * lb, lb));
            put(out + (2 * i + 1) * lb, lb, get(s + (base + i) * lb, lb));
        }
        return;
    }
    if (!strcmp(m, "packss") || !strcmp(m, "packus")) {   // lb = source lane; out lanes lb/2
        int ob = lb / 2, us = !strcmp(m, "packus");
        int64_t lo = us ? 0 : -(1ll << (8 * ob - 1)), hi = us ? (1ll << (8 * ob)) - 1 : (1ll << (8 * ob - 1)) - 1;
        for (int i = 0; i < n; i++) put(out + i * ob, ob, (uint64_t) clamp(sx(get(d + i * lb, lb), lb), lo, hi));
        for (int i = 0; i < n; i++) put(out + (n + i) * ob, ob, (uint64_t) clamp(sx(get(s + i * lb, lb), lb), lo, hi));
        return;
    }
    if (!strcmp(m, "sadbw")) {
        for (int q = 0; q < nb / 8; q++) {
            uint64_t sum = 0;
            for (int b = 0; b < 8; b++) { int x = d[q * 8 + b], y = s[q * 8 + b]; sum += x > y ? x - y : y - x; }
            put(out + q * 8, 8, sum);
        }
        return;
    }
    if (!strcmp(m, "maddwd")) {
        for (int i = 0; i < n; i++) {
            int64_t a = muls(sx(get(d + i * 4, 2), 2), sx(get(s + i * 4, 2), 2));
            int64_t b = muls(sx(get(d + i * 4 + 2, 2), 2), sx(get(s + i * 4 + 2, 2), 2));
            put(out + i * 4, 4, (uint64_t) (a + b));
        }
        return;
    }
    if (!strcmp(m, "muludq")) {
        for (int i = 0; i < n; i++) put(out + i * 8, 8, mulu(get(d + i * 8, 4), get(s + i * 8, 4)));
        return;
    }
    for (int i = 0; i < n; i++) {
        uint64_t a = get(d + i * lb, lb), b = get(s + i * lb, lb), r;
        int64_t sa = sx(a, lb), sb = sx(b, lb);
        if (!strcmp(m, "add")) r = a + b;
        else if (!strcmp(m, "sub")) r = a - b;
        else if (!strcmp(m, "adds")) r = (uint64_t) clamp(sa + sb, smin, smax);
        else if (!strcmp(m, "subs")) r = (uint64_t) clamp(sa - sb, smin, smax);
        else if (!strcmp(m, "addus")) r = a + b > mask ? mask : a + b;
        else if (!strcmp(m, "subus")) r = a < b ? 0 : a - b;
        else if (!strcmp(m, "eq")) r = a == b ? mask : 0;
        else if (!strcmp(m, "gt")) r = sa > sb ? mask : 0;
        else if (!strcmp(m, "and")) r = a & b;
        else if (!strcmp(m, "andn")) r = ~a & b;
        else if (!strcmp(m, "or")) r = a | b;
        else if (!strcmp(m, "xor")) r = a ^ b;
        else if (!strcmp(m, "minu")) r = a < b ? a : b;
        else if (!strcmp(m, "maxu")) r = a > b ? a : b;
        else if (!strcmp(m, "mins")) r = sa < sb ? a : b;
        else if (!strcmp(m, "maxs")) r = sa > sb ? a : b;
        else if (!strcmp(m, "avg")) r = (a + b + 1) >> 1;
        else if (!strcmp(m, "mullo")) r = (uint64_t) muls(sa, sb);
        else if (!strcmp(m, "mulhs")) r = (uint64_t) (muls(sa, sb) >> 16);
        else if (!strcmp(m, "mulhu")) r = mulu(a, b) >> 16;
        else r = 0;
        put(out + i * lb, lb, r & mask);
    }
}

__attribute__((noinline)) static void f0(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddb %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f1(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddb (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f2(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddb %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f3(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddb (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f4(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f5(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f6(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f7(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f8(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddd %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f9(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddd (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f10(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddd %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f11(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddd (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f12(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddq %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f13(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddq (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f14(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddq %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f15(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddq (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f16(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubb %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f17(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubb (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f18(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubb %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f19(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubb (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f20(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f21(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f22(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f23(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f24(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubd %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f25(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubd (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f26(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubd %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f27(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubd (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f28(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubq %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f29(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubq (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f30(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubq %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f31(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubq (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f32(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddsb %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f33(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddsb (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f34(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddsb %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f35(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddsb (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f36(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddsw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f37(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddsw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f38(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddsw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f39(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddsw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f40(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddusb %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f41(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddusb (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f42(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddusb %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f43(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddusb (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f44(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddusw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f45(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n paddusw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f46(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddusw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f47(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n paddusw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f48(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubsb %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f49(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubsb (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f50(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubsb %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f51(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubsb (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f52(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubsw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f53(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubsw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f54(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubsw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f55(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubsw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f56(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubusb %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f57(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubusb (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f58(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubusb %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f59(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubusb (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f60(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubusw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f61(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psubusw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f62(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubusw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f63(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psubusw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f64(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pcmpeqb %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f65(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pcmpeqb (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f66(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pcmpeqb %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f67(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pcmpeqb (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f68(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pcmpeqw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f69(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pcmpeqw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f70(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pcmpeqw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f71(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pcmpeqw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f72(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pcmpeqd %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f73(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pcmpeqd (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f74(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pcmpeqd %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f75(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pcmpeqd (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f76(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pcmpgtb %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f77(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pcmpgtb (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f78(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pcmpgtb %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f79(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pcmpgtb (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f80(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pcmpgtw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f81(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pcmpgtw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f82(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pcmpgtw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f83(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pcmpgtw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f84(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pcmpgtd %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f85(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pcmpgtd (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f86(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pcmpgtd %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f87(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pcmpgtd (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f88(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pand %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f89(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pand (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f90(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pand %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f91(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pand (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f92(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pandn %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f93(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pandn (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f94(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pandn %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f95(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pandn (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f96(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n por %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f97(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n por (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f98(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n por %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f99(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n por (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f100(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pxor %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f101(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pxor (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f102(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pxor %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f103(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pxor (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f104(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pminub %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f105(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pminub (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f106(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pminub %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f107(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pminub (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f108(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pmaxub %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f109(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pmaxub (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f110(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pmaxub %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f111(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pmaxub (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f112(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pminsw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f113(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pminsw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f114(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pminsw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f115(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pminsw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f116(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pmaxsw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f117(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pmaxsw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f118(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pmaxsw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f119(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pmaxsw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f120(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pavgb %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f121(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pavgb (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f122(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pavgb %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f123(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pavgb (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f124(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pavgw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f125(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pavgw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f126(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pavgw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f127(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pavgw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f128(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pmullw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f129(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pmullw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f130(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pmullw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f131(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pmullw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f132(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pmulhw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f133(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pmulhw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f134(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pmulhw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f135(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pmulhw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f136(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pmulhuw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f137(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pmulhuw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f138(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pmulhuw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f139(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pmulhuw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f140(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pmuludq %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f141(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pmuludq (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f142(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pmuludq %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f143(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pmuludq (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f144(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pmaddwd %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f145(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n pmaddwd (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f146(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pmaddwd %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f147(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n pmaddwd (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f148(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psadbw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f149(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n psadbw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f150(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psadbw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f151(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n psadbw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f152(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpcklbw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f153(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpcklbw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f154(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n punpcklbw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f155(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n punpcklbw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f156(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpcklwd %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f157(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpcklwd (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f158(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n punpcklwd %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f159(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n punpcklwd (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f160(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpckldq %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f161(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpckldq (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f162(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n punpckldq %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f163(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n punpckldq (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f164(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpckhbw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f165(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpckhbw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f166(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n punpckhbw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f167(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n punpckhbw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f168(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpckhwd %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f169(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpckhwd (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f170(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n punpckhwd %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f171(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n punpckhwd (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f172(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpckhdq %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f173(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpckhdq (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f174(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n punpckhdq %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f175(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n punpckhdq (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f176(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpcklqdq %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f177(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpcklqdq (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f178(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpckhqdq %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f179(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n punpckhqdq (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f180(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n packsswb %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f181(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n packsswb (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f182(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n packsswb %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f183(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n packsswb (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f184(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n packssdw %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f185(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n packssdw (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f186(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n packssdw %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f187(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n packssdw (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f188(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n packuswb %%xmm2, %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f189(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movdqu (%0), %%xmm1\n movdqu (%1), %%xmm2\n packuswb (%%edi), %%xmm1\n movdqu %%xmm1, (%0)"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f190(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n packuswb %%mm2, %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
__attribute__((noinline)) static void f191(uint8_t *v, uint8_t *src) {
    __asm__ volatile("movq (%0), %%mm1\n movq (%1), %%mm2\n packuswb (%%edi), %%mm1\n movq %%mm1, (%0)\n emms"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2");
}
struct form { const char *name, *m; int lb, x; void (*fn)(uint8_t *, uint8_t *); };
static const struct form forms[] = {
    {"paddb xmm1,xmm2", "add", 1, 1, f0},
    {"paddb mem,xmm1", "add", 1, 1, f1},
    {"paddb mm1,mm2", "add", 1, 0, f2},
    {"paddb mem,mm1", "add", 1, 0, f3},
    {"paddw xmm1,xmm2", "add", 2, 1, f4},
    {"paddw mem,xmm1", "add", 2, 1, f5},
    {"paddw mm1,mm2", "add", 2, 0, f6},
    {"paddw mem,mm1", "add", 2, 0, f7},
    {"paddd xmm1,xmm2", "add", 4, 1, f8},
    {"paddd mem,xmm1", "add", 4, 1, f9},
    {"paddd mm1,mm2", "add", 4, 0, f10},
    {"paddd mem,mm1", "add", 4, 0, f11},
    {"paddq xmm1,xmm2", "add", 8, 1, f12},
    {"paddq mem,xmm1", "add", 8, 1, f13},
    {"paddq mm1,mm2", "add", 8, 0, f14},
    {"paddq mem,mm1", "add", 8, 0, f15},
    {"psubb xmm1,xmm2", "sub", 1, 1, f16},
    {"psubb mem,xmm1", "sub", 1, 1, f17},
    {"psubb mm1,mm2", "sub", 1, 0, f18},
    {"psubb mem,mm1", "sub", 1, 0, f19},
    {"psubw xmm1,xmm2", "sub", 2, 1, f20},
    {"psubw mem,xmm1", "sub", 2, 1, f21},
    {"psubw mm1,mm2", "sub", 2, 0, f22},
    {"psubw mem,mm1", "sub", 2, 0, f23},
    {"psubd xmm1,xmm2", "sub", 4, 1, f24},
    {"psubd mem,xmm1", "sub", 4, 1, f25},
    {"psubd mm1,mm2", "sub", 4, 0, f26},
    {"psubd mem,mm1", "sub", 4, 0, f27},
    {"psubq xmm1,xmm2", "sub", 8, 1, f28},
    {"psubq mem,xmm1", "sub", 8, 1, f29},
    {"psubq mm1,mm2", "sub", 8, 0, f30},
    {"psubq mem,mm1", "sub", 8, 0, f31},
    {"paddsb xmm1,xmm2", "adds", 1, 1, f32},
    {"paddsb mem,xmm1", "adds", 1, 1, f33},
    {"paddsb mm1,mm2", "adds", 1, 0, f34},
    {"paddsb mem,mm1", "adds", 1, 0, f35},
    {"paddsw xmm1,xmm2", "adds", 2, 1, f36},
    {"paddsw mem,xmm1", "adds", 2, 1, f37},
    {"paddsw mm1,mm2", "adds", 2, 0, f38},
    {"paddsw mem,mm1", "adds", 2, 0, f39},
    {"paddusb xmm1,xmm2", "addus", 1, 1, f40},
    {"paddusb mem,xmm1", "addus", 1, 1, f41},
    {"paddusb mm1,mm2", "addus", 1, 0, f42},
    {"paddusb mem,mm1", "addus", 1, 0, f43},
    {"paddusw xmm1,xmm2", "addus", 2, 1, f44},
    {"paddusw mem,xmm1", "addus", 2, 1, f45},
    {"paddusw mm1,mm2", "addus", 2, 0, f46},
    {"paddusw mem,mm1", "addus", 2, 0, f47},
    {"psubsb xmm1,xmm2", "subs", 1, 1, f48},
    {"psubsb mem,xmm1", "subs", 1, 1, f49},
    {"psubsb mm1,mm2", "subs", 1, 0, f50},
    {"psubsb mem,mm1", "subs", 1, 0, f51},
    {"psubsw xmm1,xmm2", "subs", 2, 1, f52},
    {"psubsw mem,xmm1", "subs", 2, 1, f53},
    {"psubsw mm1,mm2", "subs", 2, 0, f54},
    {"psubsw mem,mm1", "subs", 2, 0, f55},
    {"psubusb xmm1,xmm2", "subus", 1, 1, f56},
    {"psubusb mem,xmm1", "subus", 1, 1, f57},
    {"psubusb mm1,mm2", "subus", 1, 0, f58},
    {"psubusb mem,mm1", "subus", 1, 0, f59},
    {"psubusw xmm1,xmm2", "subus", 2, 1, f60},
    {"psubusw mem,xmm1", "subus", 2, 1, f61},
    {"psubusw mm1,mm2", "subus", 2, 0, f62},
    {"psubusw mem,mm1", "subus", 2, 0, f63},
    {"pcmpeqb xmm1,xmm2", "eq", 1, 1, f64},
    {"pcmpeqb mem,xmm1", "eq", 1, 1, f65},
    {"pcmpeqb mm1,mm2", "eq", 1, 0, f66},
    {"pcmpeqb mem,mm1", "eq", 1, 0, f67},
    {"pcmpeqw xmm1,xmm2", "eq", 2, 1, f68},
    {"pcmpeqw mem,xmm1", "eq", 2, 1, f69},
    {"pcmpeqw mm1,mm2", "eq", 2, 0, f70},
    {"pcmpeqw mem,mm1", "eq", 2, 0, f71},
    {"pcmpeqd xmm1,xmm2", "eq", 4, 1, f72},
    {"pcmpeqd mem,xmm1", "eq", 4, 1, f73},
    {"pcmpeqd mm1,mm2", "eq", 4, 0, f74},
    {"pcmpeqd mem,mm1", "eq", 4, 0, f75},
    {"pcmpgtb xmm1,xmm2", "gt", 1, 1, f76},
    {"pcmpgtb mem,xmm1", "gt", 1, 1, f77},
    {"pcmpgtb mm1,mm2", "gt", 1, 0, f78},
    {"pcmpgtb mem,mm1", "gt", 1, 0, f79},
    {"pcmpgtw xmm1,xmm2", "gt", 2, 1, f80},
    {"pcmpgtw mem,xmm1", "gt", 2, 1, f81},
    {"pcmpgtw mm1,mm2", "gt", 2, 0, f82},
    {"pcmpgtw mem,mm1", "gt", 2, 0, f83},
    {"pcmpgtd xmm1,xmm2", "gt", 4, 1, f84},
    {"pcmpgtd mem,xmm1", "gt", 4, 1, f85},
    {"pcmpgtd mm1,mm2", "gt", 4, 0, f86},
    {"pcmpgtd mem,mm1", "gt", 4, 0, f87},
    {"pand xmm1,xmm2", "and", 8, 1, f88},
    {"pand mem,xmm1", "and", 8, 1, f89},
    {"pand mm1,mm2", "and", 8, 0, f90},
    {"pand mem,mm1", "and", 8, 0, f91},
    {"pandn xmm1,xmm2", "andn", 8, 1, f92},
    {"pandn mem,xmm1", "andn", 8, 1, f93},
    {"pandn mm1,mm2", "andn", 8, 0, f94},
    {"pandn mem,mm1", "andn", 8, 0, f95},
    {"por xmm1,xmm2", "or", 8, 1, f96},
    {"por mem,xmm1", "or", 8, 1, f97},
    {"por mm1,mm2", "or", 8, 0, f98},
    {"por mem,mm1", "or", 8, 0, f99},
    {"pxor xmm1,xmm2", "xor", 8, 1, f100},
    {"pxor mem,xmm1", "xor", 8, 1, f101},
    {"pxor mm1,mm2", "xor", 8, 0, f102},
    {"pxor mem,mm1", "xor", 8, 0, f103},
    {"pminub xmm1,xmm2", "minu", 1, 1, f104},
    {"pminub mem,xmm1", "minu", 1, 1, f105},
    {"pminub mm1,mm2", "minu", 1, 0, f106},
    {"pminub mem,mm1", "minu", 1, 0, f107},
    {"pmaxub xmm1,xmm2", "maxu", 1, 1, f108},
    {"pmaxub mem,xmm1", "maxu", 1, 1, f109},
    {"pmaxub mm1,mm2", "maxu", 1, 0, f110},
    {"pmaxub mem,mm1", "maxu", 1, 0, f111},
    {"pminsw xmm1,xmm2", "mins", 2, 1, f112},
    {"pminsw mem,xmm1", "mins", 2, 1, f113},
    {"pminsw mm1,mm2", "mins", 2, 0, f114},
    {"pminsw mem,mm1", "mins", 2, 0, f115},
    {"pmaxsw xmm1,xmm2", "maxs", 2, 1, f116},
    {"pmaxsw mem,xmm1", "maxs", 2, 1, f117},
    {"pmaxsw mm1,mm2", "maxs", 2, 0, f118},
    {"pmaxsw mem,mm1", "maxs", 2, 0, f119},
    {"pavgb xmm1,xmm2", "avg", 1, 1, f120},
    {"pavgb mem,xmm1", "avg", 1, 1, f121},
    {"pavgb mm1,mm2", "avg", 1, 0, f122},
    {"pavgb mem,mm1", "avg", 1, 0, f123},
    {"pavgw xmm1,xmm2", "avg", 2, 1, f124},
    {"pavgw mem,xmm1", "avg", 2, 1, f125},
    {"pavgw mm1,mm2", "avg", 2, 0, f126},
    {"pavgw mem,mm1", "avg", 2, 0, f127},
    {"pmullw xmm1,xmm2", "mullo", 2, 1, f128},
    {"pmullw mem,xmm1", "mullo", 2, 1, f129},
    {"pmullw mm1,mm2", "mullo", 2, 0, f130},
    {"pmullw mem,mm1", "mullo", 2, 0, f131},
    {"pmulhw xmm1,xmm2", "mulhs", 2, 1, f132},
    {"pmulhw mem,xmm1", "mulhs", 2, 1, f133},
    {"pmulhw mm1,mm2", "mulhs", 2, 0, f134},
    {"pmulhw mem,mm1", "mulhs", 2, 0, f135},
    {"pmulhuw xmm1,xmm2", "mulhu", 2, 1, f136},
    {"pmulhuw mem,xmm1", "mulhu", 2, 1, f137},
    {"pmulhuw mm1,mm2", "mulhu", 2, 0, f138},
    {"pmulhuw mem,mm1", "mulhu", 2, 0, f139},
    {"pmuludq xmm1,xmm2", "muludq", 8, 1, f140},
    {"pmuludq mem,xmm1", "muludq", 8, 1, f141},
    {"pmuludq mm1,mm2", "muludq", 8, 0, f142},
    {"pmuludq mem,mm1", "muludq", 8, 0, f143},
    {"pmaddwd xmm1,xmm2", "maddwd", 4, 1, f144},
    {"pmaddwd mem,xmm1", "maddwd", 4, 1, f145},
    {"pmaddwd mm1,mm2", "maddwd", 4, 0, f146},
    {"pmaddwd mem,mm1", "maddwd", 4, 0, f147},
    {"psadbw xmm1,xmm2", "sadbw", 8, 1, f148},
    {"psadbw mem,xmm1", "sadbw", 8, 1, f149},
    {"psadbw mm1,mm2", "sadbw", 8, 0, f150},
    {"psadbw mem,mm1", "sadbw", 8, 0, f151},
    {"punpcklbw xmm1,xmm2", "unpckl", 1, 1, f152},
    {"punpcklbw mem,xmm1", "unpckl", 1, 1, f153},
    {"punpcklbw mm1,mm2", "unpckl", 1, 0, f154},
    {"punpcklbw mem,mm1", "unpckl", 1, 0, f155},
    {"punpcklwd xmm1,xmm2", "unpckl", 2, 1, f156},
    {"punpcklwd mem,xmm1", "unpckl", 2, 1, f157},
    {"punpcklwd mm1,mm2", "unpckl", 2, 0, f158},
    {"punpcklwd mem,mm1", "unpckl", 2, 0, f159},
    {"punpckldq xmm1,xmm2", "unpckl", 4, 1, f160},
    {"punpckldq mem,xmm1", "unpckl", 4, 1, f161},
    {"punpckldq mm1,mm2", "unpckl", 4, 0, f162},
    {"punpckldq mem,mm1", "unpckl", 4, 0, f163},
    {"punpckhbw xmm1,xmm2", "unpckh", 1, 1, f164},
    {"punpckhbw mem,xmm1", "unpckh", 1, 1, f165},
    {"punpckhbw mm1,mm2", "unpckh", 1, 0, f166},
    {"punpckhbw mem,mm1", "unpckh", 1, 0, f167},
    {"punpckhwd xmm1,xmm2", "unpckh", 2, 1, f168},
    {"punpckhwd mem,xmm1", "unpckh", 2, 1, f169},
    {"punpckhwd mm1,mm2", "unpckh", 2, 0, f170},
    {"punpckhwd mem,mm1", "unpckh", 2, 0, f171},
    {"punpckhdq xmm1,xmm2", "unpckh", 4, 1, f172},
    {"punpckhdq mem,xmm1", "unpckh", 4, 1, f173},
    {"punpckhdq mm1,mm2", "unpckh", 4, 0, f174},
    {"punpckhdq mem,mm1", "unpckh", 4, 0, f175},
    {"punpcklqdq xmm1,xmm2", "unpckl", 8, 1, f176},
    {"punpcklqdq mem,xmm1", "unpckl", 8, 1, f177},
    {"punpckhqdq xmm1,xmm2", "unpckh", 8, 1, f178},
    {"punpckhqdq mem,xmm1", "unpckh", 8, 1, f179},
    {"packsswb xmm1,xmm2", "packss", 2, 1, f180},
    {"packsswb mem,xmm1", "packss", 2, 1, f181},
    {"packsswb mm1,mm2", "packss", 2, 0, f182},
    {"packsswb mem,mm1", "packss", 2, 0, f183},
    {"packssdw xmm1,xmm2", "packss", 4, 1, f184},
    {"packssdw mem,xmm1", "packss", 4, 1, f185},
    {"packssdw mm1,mm2", "packss", 4, 0, f186},
    {"packssdw mem,mm1", "packss", 4, 0, f187},
    {"packuswb xmm1,xmm2", "packus", 2, 1, f188},
    {"packuswb mem,xmm1", "packus", 2, 1, f189},
    {"packuswb mm1,mm2", "packus", 2, 0, f190},
    {"packuswb mem,mm1", "packus", 2, 0, f191},
};
#define NFORMS 192

int main(void) {
    static uint8_t v[16] __attribute__((aligned(16))), src[16] __attribute__((aligned(16))), d0[16], want[16];
    for (int k = 0; k < 1500; k++) {
        for (int fi = 0; fi < NFORMS; fi++) {
            const struct form *f = &forms[fi];
            for (int i = 0; i < 16; i++) { v[i] = (uint8_t) rnd(); src[i] = (uint8_t) rnd(); }
            switch (k % 6) {
            case 0: memcpy(src, v, 16); break;                              // equal lanes
            case 1: for (int i = 0; i < 16; i++) { v[i] |= 0x80; src[i] |= 0x7f; } break;  // saturating
            case 2: for (int i = 0; i < 16; i += 2) src[i] = v[i]; break;   // some equal
            case 3: memset(src, 0xff, 16); break;
            }
            memcpy(d0, v, 16);
            f->fn(v, src);
            int nb = f->x ? 16 : 8;
            memcpy(want, d0, 16);
            model(f->m, f->lb, nb, d0, src, want);
            uint64_t g0, g1, w0, w1;
            memcpy(&g0, v, 8); memcpy(&g1, v + 8, 8); memcpy(&w0, want, 8); memcpy(&w1, want + 8, 8);
            check(f->name, fi * 10000 + k, g0, w0);
            if (f->x) check(f->name, fi * 10000 + k, g1, w1);
        }
    }
    printf("i386_sse_int: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NFORMS, checks, bad);
    return bad != 0;
}