// Generated by tools/gen-vex-fma-test.py --i386 -- do not edit.
//
// FMA3 against an AMD Ryzen's results and MXCSR flags, hashed per op and
// mode (see the generator).
#pragma GCC target("avx2,fma")
#include <stdint.h>
#include <stdio.h>
#include <string.h>
static uint64_t rs;
static uint64_t rnd(void) { rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }
static void ldmx(unsigned v) { __asm__ volatile("ldmxcsr %0" :: "m"(v)); }
static unsigned stmx(void) { unsigned v; __asm__ volatile("stmxcsr %0" : "=m"(v)); return v; }
struct st { uint8_t a[32], b[32], d[32], out[32], m[64]; } __attribute__((aligned(32)));
static const uint32_t sv[] = {0, 0x80000000, 0x3f800000, 0xbf800000, 0x7f800000, 0xff800000, 0x7fc00000, 0xffc00001,
    0x7f800001, 0xff812345, 0x00000001, 0x807fffff, 0x00400000, 0x7f7fffff, 0x00800000, 0x00800001, 0x3f7fffff, 0x33800000};
static const uint64_t dv[] = {0, 0x8000000000000000ull, 0x3ff0000000000000ull, 0xbff0000000000000ull, 0x7ff0000000000000ull,
    0xfff0000000000000ull, 0x7ff8000000000000ull, 0xfff8000000000001ull, 0x7ff0000000000001ull, 0xfff0000012345678ull, 1,
    0x800fffffffffffffull, 0x0008000000000000ull, 0x7fefffffffffffffull, 0x0010000000000000ull, 0x0010000000000001ull,
    0x3fefffffffffffffull, 0x3ca0000000000000ull};
static void fill(uint8_t *p, int n, int dbl) {
    for (int i = 0; i < n; i += dbl ? 8 : 4) {
        uint64_t r = rnd();
        if ((r & 3) == 0) {
            if (dbl) { uint64_t v = dv[(r >> 8) % 18]; memcpy(p + i, &v, 8); }
            else { uint32_t v = sv[(r >> 8) % 18]; memcpy(p + i, &v, 4); }
        } else if (dbl) {
            uint64_t v = (r & 0x800fffffffffffffull) | ((uint64_t) (((r >> 52) % 64) + 990 + ((r >> 20) & 1 ? 0 : -40)) << 52);
            if ((r & 31) == 1) v = (v & 0x800fffffffffffffull) | (1ull << 52);
            memcpy(p + i, &v, 8);
        } else {
            uint32_t v = (uint32_t) (r & 0x807fffff) | (uint32_t) (((r >> 23) % 40 + 100 - ((r >> 40) & 1 ? 0 : 90)) << 23);
            if ((r & 31) == 1) v = (v & 0x807fffff) | (1u << 23);
            memcpy(p + i, &v, 4);
        }
    }
}

__attribute__((noinline)) static void f0(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd132ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f1(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd132ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f2(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd132ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f3(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd132ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f4(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd132pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f5(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd132pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f6(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd132pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f7(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd132pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f8(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub132ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f9(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub132ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f10(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub132ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f11(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub132ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f12(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub132pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f13(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub132pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f14(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub132pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f15(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub132pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f16(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd132ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f17(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd132ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f18(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd132ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f19(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd132ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f20(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd132pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f21(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd132pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f22(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd132pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f23(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd132pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f24(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub132ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f25(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub132ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f26(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub132ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f27(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub132ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f28(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub132pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f29(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub132pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f30(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub132pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f31(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub132pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f32(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub132ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f33(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub132ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f34(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub132ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f35(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub132ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f36(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub132pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f37(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub132pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f38(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub132pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f39(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub132pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f40(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd132ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f41(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd132ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f42(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd132ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f43(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd132ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f44(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd132pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f45(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd132pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f46(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd132pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f47(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd132pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f48(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd132ss %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f49(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd132ss 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f50(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd132sd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f51(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd132sd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f52(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub132ss %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f53(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub132ss 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f54(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub132sd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f55(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub132sd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f56(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd132ss %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f57(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd132ss 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f58(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd132sd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f59(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd132sd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f60(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub132ss %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f61(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub132ss 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f62(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub132sd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f63(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub132sd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f64(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd213ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f65(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd213ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f66(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd213ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f67(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd213ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f68(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd213pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f69(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd213pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f70(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd213pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f71(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd213pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f72(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub213ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f73(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub213ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f74(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub213ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f75(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub213ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f76(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub213pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f77(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub213pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f78(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub213pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f79(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub213pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f80(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd213ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f81(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd213ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f82(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd213ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f83(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd213ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f84(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd213pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f85(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd213pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f86(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd213pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f87(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd213pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f88(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub213ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f89(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub213ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f90(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub213ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f91(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub213ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f92(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub213pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f93(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub213pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f94(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub213pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f95(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub213pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f96(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub213ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f97(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub213ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f98(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub213ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f99(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub213ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f100(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub213pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f101(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub213pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f102(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub213pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f103(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub213pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f104(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd213ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f105(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd213ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f106(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd213ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f107(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd213ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f108(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd213pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f109(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd213pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f110(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd213pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f111(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd213pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f112(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd213ss %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f113(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd213ss 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f114(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd213sd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f115(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd213sd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f116(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub213ss %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f117(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub213ss 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f118(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub213sd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f119(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub213sd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f120(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd213ss %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f121(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd213ss 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f122(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd213sd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f123(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd213sd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f124(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub213ss %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f125(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub213ss 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f126(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub213sd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f127(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub213sd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f128(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd231ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f129(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd231ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f130(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd231ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f131(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd231ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f132(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd231pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f133(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd231pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f134(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd231pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f135(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd231pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f136(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub231ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f137(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub231ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f138(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub231ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f139(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub231ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f140(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub231pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f141(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub231pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f142(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub231pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f143(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub231pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f144(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd231ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f145(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd231ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f146(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd231ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f147(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd231ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f148(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd231pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f149(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd231pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f150(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd231pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f151(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd231pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f152(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub231ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f153(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub231ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f154(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub231ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f155(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub231ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f156(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub231pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f157(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub231pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f158(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub231pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f159(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub231pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f160(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub231ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f161(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub231ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f162(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub231ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f163(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub231ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f164(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub231pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f165(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub231pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f166(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub231pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f167(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmaddsub231pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f168(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd231ps %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f169(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd231ps 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f170(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd231ps %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f171(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd231ps 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f172(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd231pd %%ymm3, %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f173(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd231pd 128(%0), %%ymm2, %%ymm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f174(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd231pd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f175(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsubadd231pd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f176(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd231ss %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f177(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd231ss 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f178(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd231sd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f179(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmadd231sd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f180(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub231ss %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f181(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub231ss 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f182(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub231sd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f183(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfmsub231sd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f184(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd231ss %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f185(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd231ss 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f186(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd231sd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f187(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmadd231sd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f188(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub231ss %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f189(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub231ss 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f190(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub231sd %%xmm3, %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
__attribute__((noinline)) static void f191(struct st *t) {
    __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n"
                     "vfnmsub231sd 128(%0), %%xmm2, %%xmm1\n vmovdqu %%ymm1, 96(%0)\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}
static const struct { const char *name; void (*fn)(struct st *); int L, mem, dbl; } forms[] = {
    {"vfmadd132ps 256 reg", f0, 256, 0, 0},
    {"vfmadd132ps 256 mem", f1, 256, 1, 0},
    {"vfmadd132ps 128 reg", f2, 128, 0, 0},
    {"vfmadd132ps 128 mem", f3, 128, 1, 0},
    {"vfmadd132pd 256 reg", f4, 256, 0, 1},
    {"vfmadd132pd 256 mem", f5, 256, 1, 1},
    {"vfmadd132pd 128 reg", f6, 128, 0, 1},
    {"vfmadd132pd 128 mem", f7, 128, 1, 1},
    {"vfmsub132ps 256 reg", f8, 256, 0, 0},
    {"vfmsub132ps 256 mem", f9, 256, 1, 0},
    {"vfmsub132ps 128 reg", f10, 128, 0, 0},
    {"vfmsub132ps 128 mem", f11, 128, 1, 0},
    {"vfmsub132pd 256 reg", f12, 256, 0, 1},
    {"vfmsub132pd 256 mem", f13, 256, 1, 1},
    {"vfmsub132pd 128 reg", f14, 128, 0, 1},
    {"vfmsub132pd 128 mem", f15, 128, 1, 1},
    {"vfnmadd132ps 256 reg", f16, 256, 0, 0},
    {"vfnmadd132ps 256 mem", f17, 256, 1, 0},
    {"vfnmadd132ps 128 reg", f18, 128, 0, 0},
    {"vfnmadd132ps 128 mem", f19, 128, 1, 0},
    {"vfnmadd132pd 256 reg", f20, 256, 0, 1},
    {"vfnmadd132pd 256 mem", f21, 256, 1, 1},
    {"vfnmadd132pd 128 reg", f22, 128, 0, 1},
    {"vfnmadd132pd 128 mem", f23, 128, 1, 1},
    {"vfnmsub132ps 256 reg", f24, 256, 0, 0},
    {"vfnmsub132ps 256 mem", f25, 256, 1, 0},
    {"vfnmsub132ps 128 reg", f26, 128, 0, 0},
    {"vfnmsub132ps 128 mem", f27, 128, 1, 0},
    {"vfnmsub132pd 256 reg", f28, 256, 0, 1},
    {"vfnmsub132pd 256 mem", f29, 256, 1, 1},
    {"vfnmsub132pd 128 reg", f30, 128, 0, 1},
    {"vfnmsub132pd 128 mem", f31, 128, 1, 1},
    {"vfmaddsub132ps 256 reg", f32, 256, 0, 0},
    {"vfmaddsub132ps 256 mem", f33, 256, 1, 0},
    {"vfmaddsub132ps 128 reg", f34, 128, 0, 0},
    {"vfmaddsub132ps 128 mem", f35, 128, 1, 0},
    {"vfmaddsub132pd 256 reg", f36, 256, 0, 1},
    {"vfmaddsub132pd 256 mem", f37, 256, 1, 1},
    {"vfmaddsub132pd 128 reg", f38, 128, 0, 1},
    {"vfmaddsub132pd 128 mem", f39, 128, 1, 1},
    {"vfmsubadd132ps 256 reg", f40, 256, 0, 0},
    {"vfmsubadd132ps 256 mem", f41, 256, 1, 0},
    {"vfmsubadd132ps 128 reg", f42, 128, 0, 0},
    {"vfmsubadd132ps 128 mem", f43, 128, 1, 0},
    {"vfmsubadd132pd 256 reg", f44, 256, 0, 1},
    {"vfmsubadd132pd 256 mem", f45, 256, 1, 1},
    {"vfmsubadd132pd 128 reg", f46, 128, 0, 1},
    {"vfmsubadd132pd 128 mem", f47, 128, 1, 1},
    {"vfmadd132ss 128 reg", f48, 128, 0, 0},
    {"vfmadd132ss 128 mem", f49, 128, 1, 0},
    {"vfmadd132sd 128 reg", f50, 128, 0, 1},
    {"vfmadd132sd 128 mem", f51, 128, 1, 1},
    {"vfmsub132ss 128 reg", f52, 128, 0, 0},
    {"vfmsub132ss 128 mem", f53, 128, 1, 0},
    {"vfmsub132sd 128 reg", f54, 128, 0, 1},
    {"vfmsub132sd 128 mem", f55, 128, 1, 1},
    {"vfnmadd132ss 128 reg", f56, 128, 0, 0},
    {"vfnmadd132ss 128 mem", f57, 128, 1, 0},
    {"vfnmadd132sd 128 reg", f58, 128, 0, 1},
    {"vfnmadd132sd 128 mem", f59, 128, 1, 1},
    {"vfnmsub132ss 128 reg", f60, 128, 0, 0},
    {"vfnmsub132ss 128 mem", f61, 128, 1, 0},
    {"vfnmsub132sd 128 reg", f62, 128, 0, 1},
    {"vfnmsub132sd 128 mem", f63, 128, 1, 1},
    {"vfmadd213ps 256 reg", f64, 256, 0, 0},
    {"vfmadd213ps 256 mem", f65, 256, 1, 0},
    {"vfmadd213ps 128 reg", f66, 128, 0, 0},
    {"vfmadd213ps 128 mem", f67, 128, 1, 0},
    {"vfmadd213pd 256 reg", f68, 256, 0, 1},
    {"vfmadd213pd 256 mem", f69, 256, 1, 1},
    {"vfmadd213pd 128 reg", f70, 128, 0, 1},
    {"vfmadd213pd 128 mem", f71, 128, 1, 1},
    {"vfmsub213ps 256 reg", f72, 256, 0, 0},
    {"vfmsub213ps 256 mem", f73, 256, 1, 0},
    {"vfmsub213ps 128 reg", f74, 128, 0, 0},
    {"vfmsub213ps 128 mem", f75, 128, 1, 0},
    {"vfmsub213pd 256 reg", f76, 256, 0, 1},
    {"vfmsub213pd 256 mem", f77, 256, 1, 1},
    {"vfmsub213pd 128 reg", f78, 128, 0, 1},
    {"vfmsub213pd 128 mem", f79, 128, 1, 1},
    {"vfnmadd213ps 256 reg", f80, 256, 0, 0},
    {"vfnmadd213ps 256 mem", f81, 256, 1, 0},
    {"vfnmadd213ps 128 reg", f82, 128, 0, 0},
    {"vfnmadd213ps 128 mem", f83, 128, 1, 0},
    {"vfnmadd213pd 256 reg", f84, 256, 0, 1},
    {"vfnmadd213pd 256 mem", f85, 256, 1, 1},
    {"vfnmadd213pd 128 reg", f86, 128, 0, 1},
    {"vfnmadd213pd 128 mem", f87, 128, 1, 1},
    {"vfnmsub213ps 256 reg", f88, 256, 0, 0},
    {"vfnmsub213ps 256 mem", f89, 256, 1, 0},
    {"vfnmsub213ps 128 reg", f90, 128, 0, 0},
    {"vfnmsub213ps 128 mem", f91, 128, 1, 0},
    {"vfnmsub213pd 256 reg", f92, 256, 0, 1},
    {"vfnmsub213pd 256 mem", f93, 256, 1, 1},
    {"vfnmsub213pd 128 reg", f94, 128, 0, 1},
    {"vfnmsub213pd 128 mem", f95, 128, 1, 1},
    {"vfmaddsub213ps 256 reg", f96, 256, 0, 0},
    {"vfmaddsub213ps 256 mem", f97, 256, 1, 0},
    {"vfmaddsub213ps 128 reg", f98, 128, 0, 0},
    {"vfmaddsub213ps 128 mem", f99, 128, 1, 0},
    {"vfmaddsub213pd 256 reg", f100, 256, 0, 1},
    {"vfmaddsub213pd 256 mem", f101, 256, 1, 1},
    {"vfmaddsub213pd 128 reg", f102, 128, 0, 1},
    {"vfmaddsub213pd 128 mem", f103, 128, 1, 1},
    {"vfmsubadd213ps 256 reg", f104, 256, 0, 0},
    {"vfmsubadd213ps 256 mem", f105, 256, 1, 0},
    {"vfmsubadd213ps 128 reg", f106, 128, 0, 0},
    {"vfmsubadd213ps 128 mem", f107, 128, 1, 0},
    {"vfmsubadd213pd 256 reg", f108, 256, 0, 1},
    {"vfmsubadd213pd 256 mem", f109, 256, 1, 1},
    {"vfmsubadd213pd 128 reg", f110, 128, 0, 1},
    {"vfmsubadd213pd 128 mem", f111, 128, 1, 1},
    {"vfmadd213ss 128 reg", f112, 128, 0, 0},
    {"vfmadd213ss 128 mem", f113, 128, 1, 0},
    {"vfmadd213sd 128 reg", f114, 128, 0, 1},
    {"vfmadd213sd 128 mem", f115, 128, 1, 1},
    {"vfmsub213ss 128 reg", f116, 128, 0, 0},
    {"vfmsub213ss 128 mem", f117, 128, 1, 0},
    {"vfmsub213sd 128 reg", f118, 128, 0, 1},
    {"vfmsub213sd 128 mem", f119, 128, 1, 1},
    {"vfnmadd213ss 128 reg", f120, 128, 0, 0},
    {"vfnmadd213ss 128 mem", f121, 128, 1, 0},
    {"vfnmadd213sd 128 reg", f122, 128, 0, 1},
    {"vfnmadd213sd 128 mem", f123, 128, 1, 1},
    {"vfnmsub213ss 128 reg", f124, 128, 0, 0},
    {"vfnmsub213ss 128 mem", f125, 128, 1, 0},
    {"vfnmsub213sd 128 reg", f126, 128, 0, 1},
    {"vfnmsub213sd 128 mem", f127, 128, 1, 1},
    {"vfmadd231ps 256 reg", f128, 256, 0, 0},
    {"vfmadd231ps 256 mem", f129, 256, 1, 0},
    {"vfmadd231ps 128 reg", f130, 128, 0, 0},
    {"vfmadd231ps 128 mem", f131, 128, 1, 0},
    {"vfmadd231pd 256 reg", f132, 256, 0, 1},
    {"vfmadd231pd 256 mem", f133, 256, 1, 1},
    {"vfmadd231pd 128 reg", f134, 128, 0, 1},
    {"vfmadd231pd 128 mem", f135, 128, 1, 1},
    {"vfmsub231ps 256 reg", f136, 256, 0, 0},
    {"vfmsub231ps 256 mem", f137, 256, 1, 0},
    {"vfmsub231ps 128 reg", f138, 128, 0, 0},
    {"vfmsub231ps 128 mem", f139, 128, 1, 0},
    {"vfmsub231pd 256 reg", f140, 256, 0, 1},
    {"vfmsub231pd 256 mem", f141, 256, 1, 1},
    {"vfmsub231pd 128 reg", f142, 128, 0, 1},
    {"vfmsub231pd 128 mem", f143, 128, 1, 1},
    {"vfnmadd231ps 256 reg", f144, 256, 0, 0},
    {"vfnmadd231ps 256 mem", f145, 256, 1, 0},
    {"vfnmadd231ps 128 reg", f146, 128, 0, 0},
    {"vfnmadd231ps 128 mem", f147, 128, 1, 0},
    {"vfnmadd231pd 256 reg", f148, 256, 0, 1},
    {"vfnmadd231pd 256 mem", f149, 256, 1, 1},
    {"vfnmadd231pd 128 reg", f150, 128, 0, 1},
    {"vfnmadd231pd 128 mem", f151, 128, 1, 1},
    {"vfnmsub231ps 256 reg", f152, 256, 0, 0},
    {"vfnmsub231ps 256 mem", f153, 256, 1, 0},
    {"vfnmsub231ps 128 reg", f154, 128, 0, 0},
    {"vfnmsub231ps 128 mem", f155, 128, 1, 0},
    {"vfnmsub231pd 256 reg", f156, 256, 0, 1},
    {"vfnmsub231pd 256 mem", f157, 256, 1, 1},
    {"vfnmsub231pd 128 reg", f158, 128, 0, 1},
    {"vfnmsub231pd 128 mem", f159, 128, 1, 1},
    {"vfmaddsub231ps 256 reg", f160, 256, 0, 0},
    {"vfmaddsub231ps 256 mem", f161, 256, 1, 0},
    {"vfmaddsub231ps 128 reg", f162, 128, 0, 0},
    {"vfmaddsub231ps 128 mem", f163, 128, 1, 0},
    {"vfmaddsub231pd 256 reg", f164, 256, 0, 1},
    {"vfmaddsub231pd 256 mem", f165, 256, 1, 1},
    {"vfmaddsub231pd 128 reg", f166, 128, 0, 1},
    {"vfmaddsub231pd 128 mem", f167, 128, 1, 1},
    {"vfmsubadd231ps 256 reg", f168, 256, 0, 0},
    {"vfmsubadd231ps 256 mem", f169, 256, 1, 0},
    {"vfmsubadd231ps 128 reg", f170, 128, 0, 0},
    {"vfmsubadd231ps 128 mem", f171, 128, 1, 0},
    {"vfmsubadd231pd 256 reg", f172, 256, 0, 1},
    {"vfmsubadd231pd 256 mem", f173, 256, 1, 1},
    {"vfmsubadd231pd 128 reg", f174, 128, 0, 1},
    {"vfmsubadd231pd 128 mem", f175, 128, 1, 1},
    {"vfmadd231ss 128 reg", f176, 128, 0, 0},
    {"vfmadd231ss 128 mem", f177, 128, 1, 0},
    {"vfmadd231sd 128 reg", f178, 128, 0, 1},
    {"vfmadd231sd 128 mem", f179, 128, 1, 1},
    {"vfmsub231ss 128 reg", f180, 128, 0, 0},
    {"vfmsub231ss 128 mem", f181, 128, 1, 0},
    {"vfmsub231sd 128 reg", f182, 128, 0, 1},
    {"vfmsub231sd 128 mem", f183, 128, 1, 1},
    {"vfnmadd231ss 128 reg", f184, 128, 0, 0},
    {"vfnmadd231ss 128 mem", f185, 128, 1, 0},
    {"vfnmadd231sd 128 reg", f186, 128, 0, 1},
    {"vfnmadd231sd 128 mem", f187, 128, 1, 1},
    {"vfnmsub231ss 128 reg", f188, 128, 0, 0},
    {"vfnmsub231ss 128 mem", f189, 128, 1, 0},
    {"vfnmsub231sd 128 reg", f190, 128, 0, 1},
    {"vfnmsub231sd 128 mem", f191, 128, 1, 1},
};
#define NF 192
static const unsigned modes[] = {0x1f80, 0x3f80, 0x5f80, 0x7f80, 0x9fc0};
static const uint64_t want[NF][5] = {
    {0xabc68eb0f3e8c64cull, 0x6af13e043bf0a336ull, 0xca7521e6acf2fc74ull, 0x2884dcd1754bf7e3ull, 0x7234297fdc8155f9ull},
    {0xb4aff7c0bf931167ull, 0xc795b5dccb7066f2ull, 0x6bb0abc177b1a0c8ull, 0x81bc443de07cfee1ull, 0x9d6e0610ecd45da8ull},
    {0xcb6aea380a99720dull, 0xb36e3d193747319ull, 0xc58166f46e928162ull, 0x2ba2baffdd799c53ull, 0xb113fdd90c3f19caull},
    {0xc5f6ea50536e458ull, 0x90fec5729fc145b7ull, 0xe4bb82b8bf1112b9ull, 0xd827d02cf2963daull, 0x2f499a29cb668118ull},
    {0xba1614c4d33e4a19ull, 0x540a1101f598699dull, 0x193a6db8826a4638ull, 0x474ad5f82ae237f1ull, 0x62cf91fe91b2d012ull},
    {0x3af187d3339353cdull, 0x6964b5c6d8f080edull, 0x4eeeb7ea6a232bdull, 0x86e66b783a604c3cull, 0x453f09853353003bull},
    {0x5bb1e434cd91e8f7ull, 0xedaa8a6ac2f43859ull, 0x6deb6256c25383d1ull, 0xfc4edac3d89dcd36ull, 0xce8acd1896395abfull},
    {0xdf251d48bb7ba77dull, 0xb41cd9b8cf0eae31ull, 0x3c864dca24476c40ull, 0xd66d06e99cec9cedull, 0x166ad55a84b6a432ull},
    {0x6569b89192ad318full, 0x642ab971dfb062d7ull, 0x23b4eb672d1cd31bull, 0xfbfcc9b5ac48ba1dull, 0xdad584b9dfc8bbe8ull},
    {0x350381cb7d1e8c9cull, 0x99c04a95d6c452afull, 0x72537e26ec2bc801ull, 0xad54d83bca1e7a4aull, 0x2851fa906761c523ull},
    {0x77edc5ca290a6a5aull, 0x7db397b821cf3757ull, 0xf733b9fda255d65eull, 0xcbb7bb02ba0e12abull, 0xe404711b88acafabull},
    {0xeca13cf886d707cdull, 0x1493d1e533bd9fadull, 0x29493f856ab61fddull, 0xfa7e0976c69e79bull, 0xd7e802e2bf162c0bull},
    {0xfe7107fdf5730435ull, 0xad10242a3d61fc4cull, 0x636f4074722d6ad6ull, 0xc435aab5fc3bdc5ull, 0xb87a691005906b4full},
    {0xf66131d66a75abull, 0x260965de7b527f08ull, 0xf4c9bf3cb90fe70eull, 0xb81dc9a2242503f2ull, 0x5b459ee02a128849ull},
    {0x5a43fcd6605b8282ull, 0x33c3216c57bc0153ull, 0x793b3bd54aac90e5ull, 0x35cca912e52f9efbull, 0xfede2224ce46efebull},
    {0xd50d3dc73268471dull, 0x6c414c524575520aull, 0x75f80b6d1b2525fdull, 0xa82b506a6e2f1478ull, 0x886428043c708f84ull},
    {0x4c95bde23e83df8dull, 0x815ae0f807a95847ull, 0x995f5ef9f84752fcull, 0xe2b2270058c32ffeull, 0xe6b5ab3a090a0f93ull},
    {0x6fe135f5d9a63c33ull, 0x1d587252411709e4ull, 0xf0a6cff28c39d3acull, 0x568d804965277418ull, 0x4eac553ce102bd45ull},
    {0x128caed4ba58a85aull, 0x9cf712cdb912ff47ull, 0x93e5a7b01fd7a274ull, 0x1a156e4515b885cbull, 0x16ed399a1d5b4c70ull},
    {0xe15aeb9b39590624ull, 0xc0f7b6e669ad428bull, 0x2b6e4473db63dfb9ull, 0xfa1e0fa5ad21ce87ull, 0x9ff952b55bd6f0f0ull},
    {0xc2e2a6fb54a75769ull, 0x437be16a2315f4a3ull, 0xe32994055a759fa9ull, 0xdcf3402d42a022b8ull, 0x6f9fc14cbdefdc14ull},
    {0x974415d3818bd4beull, 0x55e875f821d7cb8bull, 0xd537b272f3835e6cull, 0xa8bcadf24f1d66a1ull, 0xdf276a781aa23b89ull},
    {0xe57b02f3edfdf8a8ull, 0x7c66f4b0bd1b6b69ull, 0xcd5aacfe2e4ba3d8ull, 0x75c11023de05799ull, 0x3b6d5a8b719227feull},
    {0xef82a8e5e397e86full, 0x8deaed0f5d8ee887ull, 0x5b5c9f0a1d26dfd1ull, 0xdf7b20186b7a2b8eull, 0xcef3b78e5098aa1bull},
    {0xc3aa2a7dedba4ec3ull, 0xd2ac5552e349dab5ull, 0x54b1a2baf4d9fd21ull, 0x2063f966edec40daull, 0xca8755b312de1106ull},
    {0x95e4d9bd51af7d63ull, 0x246a09f229a8b28aull, 0x669bb8219e6d87f5ull, 0xbb08671a32d6e727ull, 0x92b972b2fcb15890ull},
    {0x6f7a954bf007d3a3ull, 0xc6c2a5b8e9830abdull, 0x60ce90e0b8162b41ull, 0x73740be20f1baceeull, 0x4a12a3806d65a5b0ull},
    {0x2592fb07eb88f821ull, 0x9299f065eaed7bd1ull, 0xfc05012a31b9872dull, 0xdc72049d44a127c4ull, 0x35de47d2b522f160ull},
    {0x8ee6f2000ca9eb99ull, 0xd993d82df0d7059aull, 0x8b5e0dbcf1d27f41ull, 0x6cef65b63592b02dull, 0xb7afc7ce9ce04f6aull},
    {0x675206c46323a5bbull, 0x777a073c72b91d68ull, 0x3d62bcd5e55a2a32ull, 0xbcd04d9f13e8decbull, 0xdfbad0d94f66285ull},
    {0x5315e02865ef09aeull, 0x913f7f6cee4ba6d0ull, 0xddde5b0892788f4ull, 0xb09ffe08ad9501d6ull, 0xc346f0f2ce2d9875ull},
    {0x1f8566a05e8c717eull, 0x8e6a09c380371f88ull, 0xe4a6289fc1cc4b0full, 0x16dd06dbbfcdc034ull, 0x85e28a515577dc16ull},
    {0x654137e4beba8481ull, 0xeac7d1db809162d4ull, 0x4c740236a86f1f65ull, 0x94130bbc632b4c43ull, 0x187a63aabe5d88caull},
    {0x128ae36340dbf528ull, 0xcdc8852de3054e66ull, 0x6b3e75dc7d2efc2dull, 0x630338c209b814d9ull, 0x4c51c565a17adadbull},
    {0x395fa75df727ff4bull, 0x91268e19d1e9e7efull, 0xf1090ebca8c5b11cull, 0x502aaffa0b6bbffcull, 0x40d70c67dddd090eull},
    {0xe47158c441c2cd02ull, 0xdf43511f0aace918ull, 0x71be9fee83ecefe7ull, 0xeb652b2aabd7c143ull, 0x7673f5ffae9381f2ull},
    {0xf040a021e98b2e2aull, 0xf9aba915f63bd413ull, 0xa0ae9267ecff3f4full, 0xdb1a552993879e56ull, 0x73c00ebcaec52650ull},
    {0x18d1cf06eda48588ull, 0x5c091fa496fa47d0ull, 0x3a9d41c0d64ba013ull, 0xbea3855008c26093ull, 0xa9f2f128081ca12ull},
    {0xc351ce91e3849201ull, 0xe2055789ce848f9dull, 0x8ac50acea95d7875ull, 0xe6b7649a967391eaull, 0xeb833306996af6c7ull},
    {0x4b7f78b8d39ab610ull, 0x10b4f553c7c5c339ull, 0xb6ccf084e9026a2dull, 0x950b0b217baec597ull, 0xdedb690ded1570e3ull},
    {0x2cafbee00b7e5bbull, 0x831e4910dc19413aull, 0x952a1cabd9a82d1full, 0x4fa15689daf9e855ull, 0xe18b0abb0426fba5ull},
    {0x372fc0ebc0ec7cebull, 0xc363585aefb17f3eull, 0xffaf54e61fb9842bull, 0xf7e590f25bd63a75ull, 0x7c20b8f7114e6c2eull},
    {0xf99ad72c84df2ec0ull, 0x9884138a7494026dull, 0x330c2f1801e63848ull, 0xa3a97118f0b4a4c4ull, 0x11d04cdc27c210f0ull},
    {0x34245605889b8398ull, 0x3077d6c95bc32b4aull, 0x6f75216017f10f8cull, 0xb8c5ee28958de1cfull, 0x159164d642a0119bull},
    {0xd76dff3d2c067670ull, 0x44bd7b097f3b565ull, 0x31621d565338bd97ull, 0xfcb8b13d4d2ec905ull, 0x226db04bb1b0892aull},
    {0x68fdbfe9a0907320ull, 0xc7a05ccd622dad2bull, 0xf9a9d8d2e523a8e1ull, 0xffab7596c148ab11ull, 0x85e7de10b22752e7ull},
    {0xd35260e7fde0d14ull, 0x79157450f8993bc5ull, 0xb3d585d27616586dull, 0x209fc2fd718413d8ull, 0xbdb3b711e5898f0aull},
    {0xd27189a7d56c6c35ull, 0x991ac2ebbab59a80ull, 0x77daf07efefb7fbeull, 0x10a11ba10de6b85bull, 0xa3a68e442180c5e9ull},
    {0xd5b0f3adcb2529dfull, 0xdc6708aa93127b1dull, 0x20d4b440adf39d3cull, 0xca92cbc2d6b8ade9ull, 0xdaf6115a12080b89ull},
    {0xaadfe7e7cce8bfd6ull, 0x27431989a24bfb68ull, 0xaf4e0d7d6e4e5d9dull, 0x35dd3a23d27ea8f5ull, 0x8062768462d4b39cull},
    {0x499f1f03e667d8dfull, 0x85251a16bd9220bull, 0x549a2d170dcea013ull, 0xe5ad88198fcf3a0cull, 0x7aab4a20e582290aull},
    {0x38dab46ad80050bfull, 0xf3c2ceff135f1920ull, 0x67901c170ce9bc23ull, 0x84a568ad3b96d150ull, 0x3c1cc5a1c069efe9ull},
    {0xcf7276988a638147ull, 0xd3d8f7b942b92588ull, 0xf6e6c1a08ed9e880ull, 0x54c7eaa32e8dd6ccull, 0xab07cf73e5440329ull},
    {0x9ec6d404c5ed316bull, 0xfef90e3eab71e03full, 0x689fae893d30ce77ull, 0xeb65b11fa0754bf3ull, 0x2dbe5ec05dfa9e59ull},
    {0x4b240ce1381c7dc9ull, 0x1fcba12c5bd150aull, 0x827f4bac4351c68eull, 0x3a3e1ee8892fa382ull, 0x93401f0e02977dcull},
    {0x3f77c34d5a00aca8ull, 0xe808a8d396deb683ull, 0x76cca759bed995e8ull, 0xfd2ccb13721712f2ull, 0x7692ba6f2bccfdf1ull},
    {0x6db6cfb96ac0250full, 0xf661f81dc8527f72ull, 0x16c866ff783efbf0ull, 0xb2bbf50a424be952ull, 0xe2269d8aafb177c2ull},
    {0x215d95a0d1320b82ull, 0x2f738abd8f2abca9ull, 0xbaa0bc9d33ab926eull, 0x3412982ac82828feull, 0xb4fd054a5ecf5847ull},
    {0xdc1d7ca232fbd3a1ull, 0xf19c20e393206d25ull, 0xb84103b24c3cef7aull, 0x49311ffaa0b861c0ull, 0xd35bf86cd82780ccull},
    {0x8c3889572ebe9ab9ull, 0xc87123264afb39f1ull, 0xd8298451c4531415ull, 0x941382d9330e9f93ull, 0xf7a2185350c92d7cull},
    {0x4747de41c9722268ull, 0x69349d5002e3778dull, 0x3b3bc590a10c9cd1ull, 0x66a71c0ab6576bdeull, 0x4501923ae951f79dull},
    {0xd889adcd09899755ull, 0x2545d3ce14935e05ull, 0x2dff123e566b8e1cull, 0xb08d51f0403b4848ull, 0x7441491280a2df3full},
    {0x98bff889f4836e27ull, 0xb6199f00b13609c0ull, 0xa8ca2a576ed6339cull, 0x2888eb759ec3d703ull, 0x18d097e06210a385ull},
    {0xed31bcef40e72e67ull, 0x9df93913612cf484ull, 0x1a5c94b48397935eull, 0xd7488404638b994eull, 0xa1f8faa4fc09dc52ull},
    {0x585420096450025cull, 0x97b68d3d949c519full, 0x5f1ee9eae6d2e2a8ull, 0x2945bfa92fbff782ull, 0xecf81e9fb425391ull},
    {0xe97aab961367b212ull, 0x76e772a3433434cbull, 0x33dfedf9abd7c10ull, 0x96584585a88c5879ull, 0x1bc7544089bee9bull},
    {0xd51673038e9d0737ull, 0x802ca1a0df65003cull, 0x678a16277f990858ull, 0xf901519cf56ffdb7ull, 0x7310ce7d55b73864ull},
    {0x18d34c66aa63afa3ull, 0x965f7c496344c969ull, 0xf784bcda2c8a8ea3ull, 0xcede38a4ff5b0b15ull, 0xcb5d52fdf3709d61ull},
    {0x38642fc6a4965c6full, 0x6dab5bf1118c63c0ull, 0xc79d54fee95f759dull, 0x79d372c219b6d3aaull, 0x80afd70b3d3aeeaaull},
    {0x6a3e3ee9ff6a1db4ull, 0xe64171bd65e91396ull, 0xd08ed9f9b344f6e7ull, 0xc409d896e0d9ea14ull, 0xdd4db6466d12fef3ull},
    {0x1d5999f88e66d5a0ull, 0xe0372246d3ba4f92ull, 0x8b7ded15572f3c8bull, 0x13b7e89c804e8f71ull, 0x173c8d6e3b89d712ull},
    {0x4c2ea83a5a8d988ull, 0x5d86775216dd4ebdull, 0x53438901c2da47adull, 0x7174f7b43c6a0bf7ull, 0x48ddf23c4afe1696ull},
    {0xf7f168876a1666a4ull, 0xb0e948174601a32eull, 0x32cb477268bd7f7bull, 0x9ae842daedbf2d52ull, 0x3409f5b56d93443cull},
    {0x57988749f57a262eull, 0x51629a4b0cd77cb4ull, 0x481e3591a5d64039ull, 0xa9045e92cbc2dcbbull, 0x907f10c4fbbf99abull},
    {0xc41cd5881c4f239full, 0x45686c07d9ce1bf9ull, 0x9508a591d4767a6eull, 0xb371f2a128f16eefull, 0xc7df4cac49f26cc2ull},
    {0xb35a85ab04b25ff1ull, 0x93dfd69a3979ae68ull, 0x2f100d95cec75478ull, 0xae7d4193ea18d0afull, 0x58c8162baf052052ull},
    {0xe28c48739aa78813ull, 0x7e7b11df89f5c4f0ull, 0xff15df3e46742465ull, 0xa39b96b5536374a5ull, 0x8090a72dbd6930c5ull},
    {0xbf4d1f2bc5eca516ull, 0x5d64b55ab75d1349ull, 0xff0f9a379416df6ull, 0x2908882cb7756cdeull, 0x4b0b5debe2032229ull},
    {0xc5196bdfd179cd3ull, 0x9534f78176123639ull, 0xe50e55ad46eec790ull, 0x21038031b08fcc91ull, 0x36e5020cdcca1be1ull},
    {0xa959091b559b66d3ull, 0xcb0e0d0aa8c1ef6bull, 0x3d005670eef58605ull, 0xd6e8629dae43123aull, 0x6faed1bb6f80408ull},
    {0xbaefe4feb51b50c3ull, 0x206a853090017389ull, 0x5a131028944c4129ull, 0xf6021dcbcd935c86ull, 0x16595894ca5c1406ull},
    {0xff2c539aac4e8550ull, 0xa20938d81f2bf533ull, 0x33186e35c8bf7d85ull, 0x977184d48d48afc8ull, 0xf9a57ff5237be3d6ull},
    {0xb84907c1491476cdull, 0x794ca67c25eaa2ffull, 0x1befddb15ab5132ull, 0x695d6eb03054f7b9ull, 0x7887cbcea8eecf31ull},
    {0xccfacbc5d04ba28ull, 0x742d6e0aae6ded4full, 0xd96842efd7241523ull, 0x74e05105840cd94bull, 0x3c9ee41ee36551c1ull},
    {0xbb0aba4f75c1829ull, 0xda32ece8d5d5d8ebull, 0x28a2acbca0d021c9ull, 0xb01207d5b5187994ull, 0xef1f03997bc68cefull},
    {0x4165a901c0d9bc2bull, 0x91f830b0ad704e2aull, 0x84360798ba46c34ull, 0x66e98503ed0ce7f8ull, 0x64373c1d597b62d4ull},
    {0x64c158bb660f3903ull, 0xf472d19e9f57308cull, 0x99c232bff10e709dull, 0x647c90ff924e4f66ull, 0xcc1c616ed6cd47e0ull},
    {0xfd97d32cbff9f5b0ull, 0x847ea1e6917eec46ull, 0x45aafb283ee43473ull, 0xef5b33fd9b588673ull, 0x84ae5cb7f9df3a07ull},
    {0x3678f682625cbcd9ull, 0x4aaf4c08693c97b8ull, 0x567e3afd44ec4a7bull, 0x98fb287df7011a93ull, 0x2342ec895bfbab85ull},
    {0xf195b724a237b458ull, 0x44e99c0e4126733cull, 0x382a23d9f720898aull, 0x199dcf35be0ed44aull, 0x3aedae51358c978cull},
    {0x16a75df36c5f93bull, 0xe946fb4ed5c66924ull, 0x8cf375dd124ff957ull, 0x2ab1bdbb83779c1eull, 0x899d6acbaf7221e5ull},
    {0x54d0bd9663e87c48ull, 0xd4321470fddee039ull, 0xb6e3145bcbbaf1f8ull, 0x71edcb125d2b73ull, 0x218e4123c1369eb1ull},
    {0x90188ba1b45a03c9ull, 0xb7773e4da2108950ull, 0x65f8a933faa93a65ull, 0x9a12689aafbcf055ull, 0x9048615d6b050cb3ull},
    {0x9858f5d458e811e3ull, 0x29179d5db09a8cafull, 0x2598d1dd3adcb34cull, 0x7385104d76dc5023ull, 0x8d2843a9dbebaafull},
    {0xa9536803bb65e491ull, 0x26875902338e385aull, 0x9c1ca7b388f5356eull, 0xbb7ac291995171d2ull, 0xf121206305adb475ull},
    {0xcd6b337276cac9e1ull, 0x6c135634ac74694dull, 0x10f7fed5869b2765ull, 0xbddb4cb914c98c50ull, 0x213e9fc71db973bull},
    {0x37e4f7a07e940b64ull, 0xc2ee2cebc19eba82ull, 0xbf5c9b947fc623c8ull, 0x89856eca9f3447dfull, 0x4ba649814b9a9fc7ull},
    {0x233cf9b3c28f1561ull, 0x2e9311b3dca2f41eull, 0x90c7615494c6b560ull, 0x8c135da4b6dbc2cull, 0x1317b9b3c9b5b1b2ull},
    {0x3cd3172d64f25614ull, 0x5297b0ac083c9caeull, 0x79b1a0a08437bbb0ull, 0x6e3dd554497589b2ull, 0x1f0199941c3fdd0aull},
    {0x588891a3488b2dbaull, 0x1654039fe90b541bull, 0x202001de429eeb64ull, 0xc7a9b56e9ddaa291ull, 0xf83189f2fed47e6full},
    {0x8f0ad84ef545bad3ull, 0x5529f8f7fe2e6842ull, 0xc48f6c5e19b4aa95ull, 0xc55db0ddd78b86a9ull, 0xc9dd932d9689fdd2ull},
    {0x31921e7d8d8dc68eull, 0xe752a273bfd30940ull, 0xcddc2f58b77cf1cdull, 0x866e8d90442b8a4cull, 0x21d9ada96a2c18aeull},
    {0xbb7f97e5e4858921ull, 0x269bd9b7daea73ull, 0xacfbf5d1cbd7e153ull, 0xa6f7f88049116d75ull, 0xb6a073455632981aull},
    {0x3b9c9a6070f27c4bull, 0xfd1c22465c145421ull, 0xa188a2d5e780d0c2ull, 0xfcd5a0632b1121d2ull, 0x9c65ed9f82f255aaull},
    {0x99f9e8573010600bull, 0x5c45ab443fc7d472ull, 0x4bde7fb6a12ef652ull, 0x7aaf188cfd9fd055ull, 0xa46867cfb57678adull},
    {0x53cd7358eeaa5253ull, 0x63436ed5d261a156ull, 0x7c3c4850992e2401ull, 0x9f01452c7fa8b30full, 0x4804b26d62800c9cull},
    {0x4a6e0d728f7be36cull, 0x3a3f292179530577ull, 0x4c5df9433fb109d9ull, 0x692370dfb19c1c7cull, 0xe6b643477a742c8dull},
    {0xb31543e27be5baf8ull, 0x4ff9b00a37b5029bull, 0x275538f03a9b666bull, 0x67fe83b27b25191eull, 0xe732e5c1f8f7d3d8ull},
    {0x86cc87fbf27be6ccull, 0xdd81a4eeaa37b774ull, 0x1c86b95bb803fc21ull, 0xd311bbccf4b2077full, 0x246e81162010652aull},
    {0x9e8d566864432abfull, 0x2ffd8077d752514ull, 0xc3da908f8aed252bull, 0x75e29dcde3425c76ull, 0x4b60e140f00d6313ull},
    {0x38640c5612f349c1ull, 0xd5f46d392c80831ull, 0x1a69f195b5897211ull, 0xe85f603ae709b0bcull, 0x53f9bb10897a8799ull},
    {0x2f66c66fa32422edull, 0xa3129f7e3f5b7186ull, 0x46154ebb545cc4cdull, 0xfbce8d30ab7e5d2full, 0xdc9051a4c03a70b6ull},
    {0x72ecac00b18ca541ull, 0xd485314f506b5f79ull, 0x205889f674ad7b3dull, 0x6319c5f92a01d26aull, 0x9f1638c524a629dull},
    {0x6ae78b73c85ede98ull, 0xf68a0dafa2595020ull, 0xe98609180b55ae91ull, 0xa7679f0c2a87b3b1ull, 0xaf1578825d847462ull},
    {0xf9718397df3ad23eull, 0x43534d97db56817full, 0x936d623f0cb9ee23ull, 0xed174c69738aa023ull, 0xc2ae1933256220a1ull},
    {0xd34ffbdfc1edda03ull, 0x8a623d1ab5585bb4ull, 0x4f5cb6b2cf2de863ull, 0x95b0cf7522e32c92ull, 0xa4486edb781347c2ull},
    {0x8b08dcd71515ea56ull, 0x9059b16b30ad4069ull, 0x521e37adff92abaaull, 0xd847ca861c1909f6ull, 0x1011ddd9f335a4d7ull},
    {0xc752faefd80d80d0ull, 0x3afc0c78e72bb853ull, 0x702cfc673aa94393ull, 0x2c2156b6ede605aeull, 0x281954a6088cd8d9ull},
    {0x2c120275124820f2ull, 0xa4aaddb8c0b253e8ull, 0xf81ecefc08a20cf3ull, 0x94e9cc550478bec1ull, 0x7f5fa1efc4c0864full},
    {0xc4f401b936948263ull, 0x2958ae6dc1515c1dull, 0x65de556ce4159fc4ull, 0xedcd49ae773c098eull, 0xa9e6e20788f5ece7ull},
    {0x6a5e851f9228f463ull, 0xd6922680fc819ec8ull, 0xd3b4015143422480ull, 0x236b7bf79e717df4ull, 0x2db8a7d01506eaf7ull},
    {0x665b24746ebd4d9ull, 0x361c9bcf7380a840ull, 0xfa72cdf090852590ull, 0x163b244c5e906320ull, 0xe7295f41b726ea29ull},
    {0x899a473dc1f3bde9ull, 0x4f18c5019fd4ac15ull, 0x58179fd9513d988aull, 0xa10f0e3037e98dc8ull, 0xc2eef867681e4965ull},
    {0xd7e55d4c2a3eeb9full, 0xb23996d0b08d089aull, 0x158cc48eabffae8ull, 0x470416dc5acec28cull, 0xc5206e7653f4f99cull},
    {0x7e322a4e650f35e6ull, 0x220d4b33ef48a65dull, 0x2d7231360d8e8ce8ull, 0x48c3108004d76f4ull, 0xaf15ef240a16d57eull},
    {0x9113382355292f41ull, 0x5585f1a192b6e670ull, 0x75ab978f0657d8aeull, 0xabf993e5f703cfb7ull, 0xcffb7f96f16e660aull},
    {0x3791aecc7c533be2ull, 0x11a7e5ff15943053ull, 0x432ad36d93f5237ull, 0x3a127119f53c966full, 0xf08969a6294d3099ull},
    {0xfc179e0dd6e021f6ull, 0xea54f51fb6a46168ull, 0x448fa569add9fa35ull, 0x1c19cc0518a140f7ull, 0x6de7a371026d7e3eull},
    {0xa6e5b500b1c501f9ull, 0xd2d285cc368cd11dull, 0xf4a18880f611d745ull, 0xe83ddfdbacb299c9ull, 0x2328ff60d8ef09e4ull},
    {0x2bcbb7a27cdeb63bull, 0x72b342b3001d1668ull, 0x79186a5484a39502ull, 0x9919188715d4455dull, 0xbee69be1048d98d8ull},
    {0xd68a3c425e2cd4e8ull, 0x189eedce04093c9cull, 0xe56e43951fed0c1dull, 0xfacb5011ba70c861ull, 0xcf6b4c567d42759ull},
    {0xad95e9bde3921321ull, 0xc293f0cb154b4be5ull, 0x1404596bbf080c5bull, 0x21edfc908d98bde4ull, 0xac3d5f0732870c58ull},
    {0x4b44dec6247295d3ull, 0x18f89cab96f9958aull, 0x4cc2519732791f83ull, 0x682864aa4af650ffull, 0x2b067c3ac7261adull},
    {0x194bb1f185304aa4ull, 0x3d534f72eb770b6full, 0xc79ecbda4f53fd77ull, 0xaab507a1d27a1d7ull, 0xa390861321b5149full},
    {0x44bd9e2420569317ull, 0xf396232da219f788ull, 0xa5acc8ad4b97bfa8ull, 0x92adb0ccff2a62f5ull, 0xedd807df8d37df14ull},
    {0xeddd2fe3231dd4ebull, 0xe94bb2d3ef6ccaeeull, 0x654a6b48f398ef16ull, 0x9f7f359527f38cb6ull, 0x93e43aa409889967ull},
    {0xf89802b52418f9a9ull, 0x8d1cfc6614100599ull, 0x4d6b4620b862b319ull, 0xd7df247bcfdf0675ull, 0xe64554a8e38f82f9ull},
    {0x2ad3175950ff1b3dull, 0xc3fb6fd6ebc07ddaull, 0xaaef24870799bd1cull, 0x72c7036d3ba6de20ull, 0x50bc04a0d1213eccull},
    {0x2f8afea45ebe043bull, 0x7eecd17b6f27439bull, 0x174421c862667920ull, 0x444374ceebe5c6cull, 0x3563497875d0cb0dull},
    {0x80c2b0ca697f85abull, 0x235c823ce21b0563ull, 0x488164556fdfa7efull, 0x8f9be56b463bca43ull, 0x24059ad8b5c9e21full},
    {0x15a2210980dfe93bull, 0xa41485a29d918493ull, 0x234acf5d38a25125ull, 0x75c8e9869136da44ull, 0x2d955b5da6c20460ull},
    {0xefebf2e11c81fcc4ull, 0xa564fb88a7a66b03ull, 0x5d7a34832790cde8ull, 0x88641ee31f686ddeull, 0xfa546f5d36fda047ull},
    {0xe53d24c1fc9b95beull, 0xca636a1ef84820e2ull, 0x3a295632217e08f8ull, 0xe6fb346ade960a8full, 0xd172feff2ff7f9ddull},
    {0xb05309e1c75aff58ull, 0xfbd8dc7e99a72ecbull, 0x67d42a7c1a25a1ceull, 0x435edec19159b241ull, 0xa21adcd1d18dadc4ull},
    {0xc507e88bbb2e8c7bull, 0xe382f0a584089c7dull, 0x977995c312738010ull, 0x9352aa4393642514ull, 0xd5aec1263be31307ull},
    {0xe0595769f88f095bull, 0x92b08bc3176adfa0ull, 0xeeb7392a1777fb62ull, 0xd80cd89815ebc59aull, 0xe96b6b60d84ccaaull},
    {0x3f3747be136c403bull, 0xdc99468ce92cc2adull, 0xf57cb303eb411ac3ull, 0x8b86f79e693cd214ull, 0x861645747041e7c2ull},
    {0xdd65469f42f8cdb6ull, 0x5d94db885534d04eull, 0xd3679544630a3abeull, 0xae5ab5fda1b2fec4ull, 0xfeea05fc80a5d58bull},
    {0x9392764e3710972ull, 0xc2aaae66751cd9e5ull, 0x336a9d890a856908ull, 0x53155bce8f3f835eull, 0x7f4373a9acee6a9bull},
    {0x5ac494d3612535b4ull, 0xd46e36d6432ae933ull, 0x518af70e6cc1307ull, 0x21d0a5c7c8a39d5dull, 0x6e4a1424b0940b61ull},
    {0xef88b5506457f365ull, 0xf84e0bd421ae30ccull, 0xa1150f2951aa6378ull, 0xac2e0c0d42f1ed4eull, 0xba8a2d0f90e876aeull},
    {0x39ee2fdefa8ef9a3ull, 0x86da61b0e64cc669ull, 0x388279f4d6d329c2ull, 0x8be2db3c7eb9491aull, 0xfa2cf3815ec0e73aull},
    {0x8fefa5d935302bebull, 0x21c3b3048a60aa89ull, 0xd47498026b7351a7ull, 0x87da50a5ecfa49f1ull, 0x8ae7116c286f3ffaull},
    {0xa070a8e7e7a2e067ull, 0x41a66c7d5f1979ecull, 0xc5b6365004ed724full, 0x142669f7107c88afull, 0x9942a920abf876deull},
    {0xb137c03b7f559932ull, 0x7199f158b00bce63ull, 0x63e77341be878956ull, 0xd3ba07b6fd86d8dcull, 0x9bf24f6fc195f822ull},
    {0xdfbf0ec0eff699fcull, 0xb65b31b5e775c674ull, 0xc0b7fea6ea59a95aull, 0x8221b5e3dc62f447ull, 0x91a2d84f2394e49cull},
    {0x62f3f4d95c272737ull, 0x5888b9baa1d6a0c8ull, 0xeac57482a6203b10ull, 0x1d57f10120a47448ull, 0xa62fce7f5e226fc9ull},
    {0x80904e5f6c0ae96cull, 0x6b68552cf4a86c7aull, 0xf603b397fbe7cf1bull, 0x354f1986ab80e76cull, 0xf00beb573467a575ull},
    {0x122a4e4eccd930e4ull, 0x87aa58d8d44fe803ull, 0x6809ed12727dedf8ull, 0x584cbb7c5e108f5full, 0x2cfbcd24b8eaaa6cull},
    {0xde8629b652ad1215ull, 0x46f722c307f17d17ull, 0x26d95604ef72941dull, 0x6d3f852c8ca432d6ull, 0x475b001bbfb1a892ull},
    {0x794c9e31d8f739ddull, 0x9b66efd9a4ed81e6ull, 0x4f1c13beb84ad4bbull, 0x929d3903a8a1cd97ull, 0x8fb5bbca2f5cae5dull},
    {0xa5531175cf40a65dull, 0x33ccf7b62f34cf10ull, 0x55dbb6b93b1b7713ull, 0x9450dac30e0b7c53ull, 0x41cc291921a241d6ull},
    {0xce3e460fd57fb914ull, 0x3121371fcc073d6ull, 0xf8669d99a77bdc14ull, 0x7a1f1ef29e566184ull, 0xf7a51e461def6c04ull},
    {0xd9fd2aa663d2eb97ull, 0xe37b805a0f6d0684ull, 0x346ea73382adc2deull, 0x76ecaa4c08b910dull, 0x17f2a0b11f64b155ull},
    {0xa7c6e10d1ac42df0ull, 0xf8060c69a0368cc8ull, 0xee63fbb2927701d0ull, 0x15f42e2fb79613eeull, 0xba13b9ff3991d041ull},
    {0xf6f6cbcd4c619b08ull, 0x856b4d1ad4b74f22ull, 0xc78384817dfe79beull, 0xf7e087de2c4d282dull, 0x734770f9779e4443ull},
    {0xa71238395d86011cull, 0xd1bfa9a99fe4d6full, 0x49b0f264b277fd9dull, 0xe225dfbd250e1a3ull, 0xe26815379bb5610bull},
    {0xe873c411581b0d25ull, 0x92324a827ae65af8ull, 0x6ad8aa95f44476feull, 0x18dc24290641ce80ull, 0x290ec14ae040de07ull},
    {0xec650aa5a77ed29full, 0x9071a12c47a38082ull, 0x89dc6d844a52e825ull, 0x1d3899156e042639ull, 0x340820045bb442cdull},
    {0xc63245c1678d62b2ull, 0x166340a7d5b64358ull, 0x7e7f340e4de39366ull, 0xaa8b020fb76ba0b0ull, 0xc801740d41c348feull},
    {0xde112ec5d67b1eeaull, 0x1a038e77677699deull, 0x4f8451a32f12ec9ull, 0xb07330abed7928e0ull, 0x8eee96378d708b78ull},
    {0x56b2022067eca4d3ull, 0xaaa2cfadf1e86d2bull, 0xa22c624d31e58feeull, 0x1261f41201d1a0a1ull, 0x15519feea9f53141ull},
    {0xb52368c1d4a8aa37ull, 0xdd70411f334218faull, 0x4531d53f564fce6cull, 0x8481c72ea3d7608bull, 0x66fecaadc64dfbb8ull},
    {0x754acdbaad13c133ull, 0x663d016ec3c70fc6ull, 0x5c589dcaf89a9d5bull, 0xdcba99b630bd8333ull, 0x49bdf90d7ed85f4ull},
    {0xa58edc3151cc974bull, 0x4fa266a3e5c5a5eaull, 0x4f8ee8c8cf26bb88ull, 0x1acca4f0f286c6e7ull, 0xa120b76252e99ff2ull},
    {0x52058268cfd65eb0ull, 0x4fd09ea3466d9d27ull, 0x420ebc84c4a0ce6eull, 0xbc25e39414c613bfull, 0xf8d8578e60b568d9ull},
    {0xf2fdd6db8e596a86ull, 0xd170b33e32237010ull, 0x60410f30f4b88e25ull, 0x33e750882056206aull, 0x4d22a34930c8bc7bull},
    {0x9cb5cb4da0de3a59ull, 0xbcf81824e4c3ad26ull, 0xb0be00679c70cc5dull, 0xbb762bc450d08ad9ull, 0x2c5ffe5b73206440ull},
    {0xb0e0e59a3449343cull, 0xfd4909c5fff545ceull, 0x6539e1496eb630a8ull, 0x33c5e20028900c72ull, 0x8f675534350ef0fcull},
    {0x9dd3f23e883d19faull, 0xd09ad0bbe7834cc3ull, 0x50a8f76549d890e7ull, 0xa6554a0c125a0b92ull, 0xb173fec8d3a24f71ull},
    {0x3c66b398cd5f4170ull, 0xfb7f5f6362e28838ull, 0x91265259244f663aull, 0xa84cdb5435b166ull, 0xdb83c8b61821297bull},
    {0xc8d0c1c1fb772ba8ull, 0x65cf8f60ccc78b8bull, 0x4d9c1a9e93e464ddull, 0x5c29410a8bef6f3eull, 0xae5906998e34643dull},
    {0x120f17fd827dd2a1ull, 0x9fc8e89b55135715ull, 0xcfdc27eaed97293dull, 0xdb0637209a13f2full, 0x42eb862d5a9dd9f0ull},
    {0xdb04fd047169033bull, 0xa4268f36940fd835ull, 0xd1559fe82187a150ull, 0xf869b25ef7a99fc1ull, 0xaa1535b74ff5306eull},
    {0x2f15453fa53771eull, 0xe1584753f2a9573aull, 0xdec423bffb148aaull, 0xcc71ba8299f48487ull, 0xee372b168a4d49dbull},
    {0xd6438e6b74e8a208ull, 0x42288e0c9818911aull, 0x872ab0d1b77c52fcull, 0x89698386016b6a3eull, 0xdfbbd3163001de94ull},
    {0xd2a08dd9d0c39a63ull, 0xa73d2271d53c5801ull, 0x61a2ed8676ca7a49ull, 0x70f031cd01210f04ull, 0x9fb472b8956b00d5ull},
    {0xde1aab8b49c15e1ull, 0xc18d63160a8258a0ull, 0x807b208632ed11a8ull, 0xda25d1c92364c097ull, 0xaf692ed926d1063full},
    {0x2c5344c90355224bull, 0xa4f837cc791b5e1bull, 0x2bbc36a87c710d5bull, 0x55213b2b0d08baadull, 0x301870db678d29b0ull},
    {0xd4cd8c511577a0a9ull, 0xe3fa350f625fa82dull, 0x4dec0078273bb2feull, 0x37a4d59e0719f592ull, 0xed6aa82fbe5f5806ull},
    {0xf94a2e6859206e2cull, 0x8caf331356aab92bull, 0x9d8d4f38c0bd08a0ull, 0x1d3be481a3c0ade1ull, 0xf49ff8ed2cd314c3ull},
    {0xf36fcbe54b1a271aull, 0x65c8e54b8f2e2391ull, 0x5050ee37c00d1e3eull, 0x288fb24337596bd0ull, 0x5ff0d56a9f01da4ull},
};

int main(int argc, char **argv) {
    int print = argc > 1 && !strcmp(argv[1], "hashes"), dump = argc > 1 && !strcmp(argv[1], "dump");
    unsigned long checks = 0, bad = 0;
    static struct st t;
    for (int fi = 0; fi < NF; fi++) {
        for (int mi = 0; mi < 5; mi++) {
            uint64_t h = 0xcbf29ce484222325ull;
            rs = 0x9e3779b97f4a7c15ull ^ (uint64_t) fi * 0x100000001b3ull ^ (uint64_t) mi << 40;
            for (int k = 0; k < 300; k++) {
                fill(t.a, 32, forms[fi].dbl); fill(t.b, 32, forms[fi].dbl); fill(t.d, 32, forms[fi].dbl); fill(t.m, 64, forms[fi].dbl);
                ldmx(modes[mi]);
                forms[fi].fn(&t);
                unsigned f = stmx() & 0x3f;
                for (int i = 0; i < 32; i++) h = (h ^ t.out[i]) * 0x100000001b3ull;
                h = (h ^ f) * 0x100000001b3ull;
                if (dump) {
                    printf("%d %d %d:", fi, mi, k);
                    for (int i = 31; i >= 0; i--) printf("%02x", t.out[i]);
                    printf(" %x\n", f);
                }
            }
            if (print) printf("%d.%d %#llx\n", fi, mi, (unsigned long long) h);
            checks++;
            if (!print && !dump && h != want[fi][mi] && bad++ < 40)
                printf("FAIL %s, mxcsr %#x\n", forms[fi].name, modes[mi]);
        }
    }
    ldmx(0x1f80);
    if (!print && !dump)
        printf("i386_vex_fma: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NF, checks, bad);
    return bad != 0;
}