// Generated by tools/gen-sse-tiny-test.py --i386 -- do not edit.
//
// Results that round up to +-the smallest normal: UE and FTZ by x86's
// after-rounding tininess, against an AMD Ryzen's results and MXCSR flags,
// hashed per op and mode (see the generator).
#pragma GCC target("avx")
#include <stdint.h>
#include <stdio.h>
#include <string.h>
static const struct { char k; uint64_t a, b; } cases[] = {
    {'s', 0x35a9735aull, 0xa4160bdull},
    {'s', 0x35a9735aull, 0xa4160beull},
    {'s', 0x35f953a6ull, 0xa036d09ull},
    {'s', 0x35934f06ull, 0xa5e71c6ull},
    {'s', 0x35934f06ull, 0xa5e71c7ull},
    {'s', 0xb5b28993ull, 0xa378928ull},
    {'s', 0x35d351d2ull, 0xa1b104eull},
    {'s', 0x35862e3full, 0xa743544ull},
    {'s', 0xb5862e3full, 0xa743545ull},
    {'s', 0xb5894597ull, 0xa6eb575ull},
    {'s', 0x35894597ull, 0xa6eb576ull},
    {'s', 0xb5e91f84ull, 0xa0c8f98ull},
    {'s', 0x35c497c8ull, 0xa26adf1ull},
    {'s', 0xb58c0c74ull, 0xa69f9d0ull},
    {'s', 0xb5aecee4ull, 0xa3b7381ull},
    {'s', 0xb5ca98ccull, 0xa21bd6bull},
    {'s', 0xb5876c82ull, 0xa71f759ull},
    {'s', 0x35876c82ull, 0xa71f75aull},
    {'s', 0xb5f4712eull, 0xa060d5cull},
    {'s', 0xb5c0f3a7ull, 0xa29d327ull},
    {'s', 0x359b7b3aull, 0xa52c07full},
    {'s', 0x359b7b3aull, 0xa52c080ull},
    {'s', 0xb584cca8ull, 0xa76bf7eull},
    {'s', 0x358b0051ull, 0xa6bbd28ull},
    {'S', 0x85f66aull, 0x3f85f66bull},
    {'S', 0xc740caull, 0x3fc740cbull},
    {'S', 0xede24aull, 0x3fede24bull},
    {'S', 0x910bdeull, 0x3f910bdfull},
    {'S', 0xa511e9ull, 0x3fa511eaull},
    {'S', 0xb5a658ull, 0x3fb5a659ull},
    {'S', 0x9276f2ull, 0x3f9276f3ull},
    {'S', 0xc53530ull, 0x3fc53531ull},
    {'S', 0x8f13cfull, 0x3f8f13d0ull},
    {'S', 0xc913b2ull, 0x3fc913b3ull},
    {'S', 0xa77c54ull, 0x3fa77c55ull},
    {'S', 0xc7b681ull, 0x3fc7b682ull},
    {'S', 0xe876d3ull, 0x3fe876d4ull},
    {'S', 0xd74bdcull, 0x3fd74bddull},
    {'S', 0x972209ull, 0x3f97220aull},
    {'S', 0x8d30ecull, 0x3f8d30edull},
    {'d', 0x3eb923a794e3bf91ull, 0x1445dd56407b717ull},
    {'d', 0x3eb30185a38fd547ull, 0x14af05e4aa8efdfull},
    {'d', 0xbeb18f135f557203ull, 0x14d28b5836d8a77ull},
    {'d', 0x3eb18f135f557203ull, 0x14d28b5836d8a78ull},
    {'d', 0xbebb64ce8c38fb29ull, 0x142b0bc83d9f367ull},
    {'d', 0xbeb907a71012f037ull, 0x144749e551a7573ull},
    {'d', 0x3eb907a71012f037ull, 0x144749e551a7574ull},
    {'d', 0x3eb9e7760f4205b4ull, 0x143c3e29a318f3aull},
    {'d', 0xbeb7f15034b9b5dfull, 0x145626b6166e4f1ull},
    {'d', 0x3eb881edae2eb154ull, 0x144e43baf1b6aedull},
    {'d', 0xbeb881edae2eb154ull, 0x144e43baf1b6aeeull},
    {'d', 0x3ebc6f876d76b07eull, 0x142016c698a2f86ull},
    {'d', 0xbebc6f876d76b07eull, 0x142016c698a2f87ull},
    {'d', 0x3eb7731a506bf2efull, 0x145d583cb262262ull},
    {'d', 0xbebec66a95e761d1ull, 0x140a30857e35921ull},
    {'d', 0x3eb5c90a7403e430ull, 0x14780879cabd028ull},
    {'D', 0x19be4b49b64a07ull, 0x3ff9be4b49b64a08ull},
    {'D', 0x112bd4faecbd37ull, 0x3ff12bd4faecbd38ull},
    {'D', 0x1830e01e398f0full, 0x3ff830e01e398f10ull},
    {'D', 0x12a3af6b0a18e7ull, 0x3ff2a3af6b0a18e8ull},
    {'D', 0x15790fc1d3fcfeull, 0x3ff5790fc1d3fcffull},
    {'D', 0x1eeeac26e87554ull, 0x3ffeeeac26e87555ull},
    {'D', 0x16bf467d2caf81ull, 0x3ff6bf467d2caf82ull},
    {'D', 0x1f646e0a097c96ull, 0x3fff646e0a097c97ull},
    {'D', 0x113deeab1031cfull, 0x3ff13deeab1031d0ull},
    {'D', 0x18ede0c3baea9dull, 0x3ff8ede0c3baea9eull},
    {'D', 0x1ca02192b1d3f1ull, 0x3ffca02192b1d3f2ull},
    {'D', 0x1d17f9e01f5056ull, 0x3ffd17f9e01f5057ull},
    {'c', 0x380fffffffffffffull, 0x0ull},
    {'c', 0xb80fffffffffffffull, 0x0ull},
    {'c', 0x380ffffffffffffeull, 0x0ull},
    {'c', 0xb80ffffffffffffeull, 0x0ull},
    {'c', 0x380ffffffffffffdull, 0x0ull},
    {'c', 0xb80ffffffffffffdull, 0x0ull},
    {'c', 0x380ffffffff00000ull, 0x0ull},
    {'c', 0xb80ffffffff00000ull, 0x0ull},
    {'c', 0x380ffffff0000000ull, 0x0ull},
    {'c', 0xb80ffffff0000000ull, 0x0ull},
    {'c', 0x380fffffe0000001ull, 0x0ull},
    {'c', 0xb80fffffe0000001ull, 0x0ull},
    {'c', 0x380fffffe0000000ull, 0x0ull},
    {'c', 0xb80fffffe0000000ull, 0x0ull},
    {'c', 0x380fffffdfffffffull, 0x0ull},
    {'c', 0xb80fffffdfffffffull, 0x0ull},
    {'c', 0x380fffffc0000000ull, 0x0ull},
    {'c', 0xb80fffffc0000000ull, 0x0ull},
};
#define NC 86
struct st { uint8_t x[32], y[32], o[32]; unsigned mx, st; } __attribute__((aligned(32)));
__attribute__((noinline)) static void f0(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n mulss %%xmm1,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f1(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n mulps %%xmm1,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f2(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n vmulss %%xmm1,%%xmm0,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f3(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n vmulps %%ymm1,%%ymm0,%%ymm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f4(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n mulps 32(%1),%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f5(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n vmulps 32(%1),%%ymm0,%%ymm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f6(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n dpps $0xf1,%%xmm1,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f7(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n vdpps $0xf1,%%ymm1,%%ymm0,%%ymm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f8(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n divss %%xmm1,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f9(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n divps %%xmm1,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f10(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n vdivss %%xmm1,%%xmm0,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f11(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n vdivps %%ymm1,%%ymm0,%%ymm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f12(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n mulsd %%xmm1,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f13(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n mulpd %%xmm1,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f14(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n vmulpd %%ymm1,%%ymm0,%%ymm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f15(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n dppd $0x31,%%xmm1,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f16(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n divsd %%xmm1,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f17(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n divpd %%xmm1,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f18(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n vdivpd %%ymm1,%%ymm0,%%ymm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f19(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n cvtsd2ss %%xmm0,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f20(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n cvtpd2ps %%xmm0,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f21(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n vcvtpd2psy %%ymm0,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
__attribute__((noinline)) static void f22(struct st *t) {
    __asm__ volatile("vmovdqu (%1), %%ymm0\n vmovdqu 32(%1), %%ymm1\n ldmxcsr 96(%1)\n vcvtsd2ss %%xmm0,%%xmm0,%%xmm0\n"
                     "stmxcsr 100(%1)\n vmovdqu %%ymm0, 64(%1)\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}
static const struct { const char *name; void (*fn)(struct st *); char k; int lane, zero; } ops[] = {
    {"mulss", f0, 's', 0, 0},
    {"mulps", f1, 's', 3, 0},
    {"vmulss", f2, 's', 0, 0},
    {"vmulps", f3, 's', 6, 0},
    {"mulps m", f4, 's', 1, 0},
    {"vmulps m", f5, 's', 2, 0},
    {"dpps", f6, 's', 2, 1},
    {"vdpps", f7, 's', 5, 1},
    {"divss", f8, 'S', 0, 0},
    {"divps", f9, 'S', 2, 0},
    {"vdivss", f10, 'S', 0, 0},
    {"vdivps", f11, 'S', 5, 0},
    {"mulsd", f12, 'd', 0, 0},
    {"mulpd", f13, 'd', 1, 0},
    {"vmulpd", f14, 'd', 3, 0},
    {"dppd", f15, 'd', 1, 1},
    {"divsd", f16, 'D', 0, 0},
    {"divpd", f17, 'D', 1, 0},
    {"vdivpd", f18, 'D', 2, 0},
    {"cvtsd2ss", f19, 'c', 0, 0},
    {"cvtpd2ps", f20, 'c', 1, 0},
    {"vcvtpd2ps", f21, 'c', 3, 0},
    {"vcvtsd2ss", f22, 'c', 0, 0},
};
#define NO 23
static const unsigned modes[] = {0x1f80, 0x3f80, 0x5f80, 0x7f80, 0x9f80, 0xbf80, 0xdf80, 0xff80};
static const uint64_t want[NO][8] = {
    {0x9b33d8a9821ed95cull, 0xa16928895bb0178cull, 0x8a62b53114f9471cull, 0xa3cb81d43bbca7e5ull, 0x616e4aad47f24aa5ull, 0x5ae1d349040e915ull, 0xf33601b675de5485ull, 0xc62daecdac2f08e5ull},
    {0x76c170d0c8f70de4ull, 0x902f4532b9d9274ull, 0x53a17c8ba2b98084ull, 0x1049820536e7865ull, 0xa442c733d0a84765ull, 0x939334c230400e75ull, 0x3a187a2a91a9de65ull, 0x5eca225cdf7c00e5ull},
    {0x8dc182e6cb67a01cull, 0xb060d2726cac78cull, 0xc99855c7621ed69cull, 0x4ea0ee55d079abe5ull, 0x7ddacf9977090a5ull, 0xe84903b07b007c95ull, 0x4ef4c91ada5a485ull, 0xf6ecf09305e625e5ull},
    {0xf42071a2f16d35dcull, 0x8bba4089abe7b70cull, 0x1a6619b64cf7821cull, 0x9749cdfdfefc00e5ull, 0xc964951303741ba5ull, 0x46ec831e4f1a9a15ull, 0xe6d8a8f261590385ull, 0xd3fd9767000763e5ull},
    {0x85e3e6a597a72864ull, 0xfa92aef4ae65d7f4ull, 0xa264915cd2bf7c84ull, 0x6fe0589015817365ull, 0x2286f751c8782c65ull, 0x673c8491b734f175ull, 0xffd5d14ddeadb65ull, 0x5edeabeb3a626de5ull},
    {0xb5c5890afe31bcdcull, 0xb08ff31da31ade0cull, 0xb336e291522e41cull, 0xcf83b17e6a128de5ull, 0xa3a6c3996d4a70a5ull, 0x44e13bb5fbfcd015ull, 0xbf167680d2941a85ull, 0xb5a682a4100cb3e5ull},
    {0x7ac7b45b498a58e2ull, 0x41df536e09c5951eull, 0xc97d8d6d32dfe32aull, 0x7dc06e05b83f3205ull, 0xbe8402c4483d8ea5ull, 0x1c69bf79e7d81e95ull, 0xa569eeafab21eb85ull, 0xabdd747279d563e5ull},
    {0xa238e95854041fa2ull, 0xd1c806a30f66aadeull, 0x8bcaee18f8090deaull, 0xc05f5d45d9422605ull, 0xd421d5f78fab1a5ull, 0xaca86adf567ee595ull, 0x78734bd5be64b85ull, 0xabdd747279d563e5ull},
    {0xf5a9e9e7d51bfca5ull, 0x4ada7f9b8120cea5ull, 0xe89858fcd2bbc2a5ull, 0xe718f0603be9d0a5ull, 0x170cafc874cfe8a5ull, 0x33aea67cd4a086a5ull, 0xe85952ea749f12a5ull, 0xdefd069b7d7af6a5ull},
    {0x22d9d1885bec74a5ull, 0xb5b2df047a4b16a5ull, 0x3cdbed46399636a5ull, 0xaa0da0b8e29230a5ull, 0x236e924515928a5ull, 0xcaae14ee8462fea5ull, 0x595ab310046280a5ull, 0x81bf1db6cec86ea5ull},
    {0x63d10687b21a3aa5ull, 0x23fd5ee337c6a6a5ull, 0xd8d03b28510250a5ull, 0xd19216152c86b2a5ull, 0x8cefe1656e70a0a5ull, 0x5d9c5d5ad655faa5ull, 0xb7bf21771ffa48a5ull, 0xa9b4317ab5874aa5ull},
    {0xde8db29c202529a5ull, 0x5b5a868b882417a5ull, 0x44049fb39ce9f7a5ull, 0x821bff46301b1ba5ull, 0x8577fc0884b180a5ull, 0x25b4ef3ccb13cca5ull, 0xa87168076af9c6a5ull, 0xbc2a0c71599ed2a5ull},
    {0x77a06da44466865ull, 0xc28824db7eb347b0ull, 0xb03e046a65e55ad0ull, 0x39cea627d30d3a25ull, 0xc866ba0f4626d925ull, 0xb089f2134c4bdf25ull, 0xebe05937d5a41245ull, 0xf949046ec8fbb325ull},
    {0x12066182151e9865ull, 0x30492b4b51919600ull, 0x4dbd942444488860ull, 0x6cd1cac8dfc65325ull, 0x51f743d430ab6625ull, 0x2bafdc83a1ad0325ull, 0x6d38e6a958293da5ull, 0x7c9d4eb658300c25ull},
    {0xa97b96c2d6e14e65ull, 0xc8d2e9a3f9bec020ull, 0xbcd2a5aea1077ec0ull, 0x76658ff0069c0325ull, 0x7a48ef932355e325ull, 0x6fa7174881fb0a25ull, 0x13575b760e64d625ull, 0xa2f18a83afa3f725ull},
    {0x68699558204a2f3dull, 0x7562c068be392d36ull, 0x6c89a5ad494091aaull, 0xa3020df7b1cd69a5ull, 0xfb9f8560effbcce5ull, 0x65f8b58f6c4d37a5ull, 0xd6655fccc6f8f5c5ull, 0x3ef80bf2f7f2ea5ull},
    {0x725ee5e03a1df845ull, 0x830cd05fb4f805ull, 0x32c1504fb48d6545ull, 0x262b78305b603b85ull, 0xce404d22b9c7ff45ull, 0x95e3ce89fca41805ull, 0x5951b46bc71fe845ull, 0xae7de9b39fd81f85ull},
    {0xc8efad6ccf2333c5ull, 0x258a73247795f545ull, 0x9de3d42bb0072b45ull, 0xcade9a0a2ae46e45ull, 0xa977ed060d24c245ull, 0xd27a61af4dcd205ull, 0xf4f3a884ad1161c5ull, 0x70b905ca4a5f6405ull},
    {0x83808e634c834545ull, 0xa8a511afe8e2b805ull, 0x478f40c348927f45ull, 0x8949be5098c7a505ull, 0xf1eae8deaaec1c45ull, 0x9b92d35385a63705ull, 0x4c0faa3abf323945ull, 0x1b9fd0290f9ce685ull},
    {0xf914c36767183a35ull, 0x11fac77812f81dc5ull, 0x49b14c73ff6a7445ull, 0x3dcf4daa24fdc725ull, 0xb8fd16b2acb97575ull, 0xa333759a9bbd9935ull, 0xab5bfcf5af41e075ull, 0xa461a9dd554dde15ull},
    {0x87b2ef6b88172f35ull, 0xd605b65da1fec815ull, 0xf055d00357d9b9b5ull, 0x158ff8d7a2f46575ull, 0x85be6074f4e74475ull, 0xed0030d6932d2d75ull, 0x227c91e864803e75ull, 0xb5da6f370d8f5355ull},
    {0x413f3c4077b8aa15ull, 0xaab64d3add325f55ull, 0x11092d1d6b7d87f5ull, 0x9e16af2fed41e6b5ull, 0x15282ddf52a0f575ull, 0x7820402da37616d5ull, 0xa71e8be6a3968755ull, 0xdf4bbcdfaf751435ull},
    {0xdbe052f47af7aff5ull, 0xc78f72ea7a4eab45ull, 0x936bb1ecc7e96f45ull, 0x7e0ce6c450d69025ull, 0xb8be415fd632935ull, 0xea6d23ffcb82fb75ull, 0xf182d4c2ea352cb5ull, 0x18883fd38e7a31d5ull},
};

int main(int argc, char **argv) {
    int print = argc > 1 && !strcmp(argv[1], "hashes"), dump = argc > 1 && !strcmp(argv[1], "dump");
    unsigned long checks = 0, bad = 0;
    static struct st t;
    for (int oi = 0; oi < NO; oi++) {
        int dbl = ops[oi].k != 's' && ops[oi].k != 'S';
        for (int mi = 0; mi < 8; mi++) {
            uint64_t h = 0xcbf29ce484222325ull;
            for (int c = 0; c < NC; c++) {
                if (cases[c].k != ops[oi].k) continue;
                for (int l = 0; l < (dbl ? 4 : 8); l++) {
                    if (dbl) { double v = ops[oi].zero ? 0 : 1; memcpy(t.x + 8 * l, &v, 8); memcpy(t.y + 8 * l, &v, 8); }
                    else { float v = ops[oi].zero ? 0 : 1; memcpy(t.x + 4 * l, &v, 4); memcpy(t.y + 4 * l, &v, 4); }
                }
                int L = ops[oi].lane;
                if (dbl) { memcpy(t.x + 8 * L, &cases[c].a, 8); memcpy(t.y + 8 * L, &cases[c].b, 8); }
                else { uint32_t a = cases[c].a, b = cases[c].b; memcpy(t.x + 4 * L, &a, 4); memcpy(t.y + 4 * L, &b, 4); }
                t.mx = modes[mi];
                ops[oi].fn(&t);
                unsigned f = t.st;                   /* all of MXCSR: a gadget once lost its controls */
                for (int i = 0; i < 32; i++) h = (h ^ t.o[i]) * 0x100000001b3ull;
                for (int i = 0; i < 4; i++) h = (h ^ ((f >> (8 * i)) & 0xff)) * 0x100000001b3ull;
                if (dump) {
                    printf("%s %#x %d:", ops[oi].name, modes[mi], c);
                    for (int i = 31; i >= 0; i--) printf("%02x", t.o[i]);
                    printf(" %02x\n", f);
                }
            }
            if (print) printf("%d.%d %#llx\n", oi, mi, (unsigned long long) h);
            checks++;
            if (!print && !dump && h != want[oi][mi] && bad++ < 40)
                printf("FAIL %s, mxcsr %#x\n", ops[oi].name, modes[mi]);
        }
    }
    if (!print && !dump)
        printf("i386_sse_tiny: %s (%d ops, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NO, checks, bad);
    return bad != 0;
}