// Generated by tools/gen-vex-gpr-test.py --i386 -- do not edit.
//
// The VEX ops between vector and general registers or EFLAGS (see the
// generator).
#pragma GCC target("avx2")
#include <stdint.h>
#include <stdio.h>
#include <string.h>
static unsigned long checks, bad;
static uint64_t rs = 0x9e3779b97f4a7c15ull;
static uint64_t rnd(void) { rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }
static void ldmx(unsigned v) { __asm__ volatile("ldmxcsr %0" :: "m"(v)); }
static unsigned stmx(void) { unsigned v; __asm__ volatile("stmxcsr %0" : "=m"(v)); return v; }
struct st { uint8_t a[32], b[32], d[32], out[32], m[64]; uint64_t g, gout, fl; } __attribute__((aligned(32)));
#define GMASK 0xffffffffull

__attribute__((noinline)) static void f0(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcvtss2si %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r0(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "cvtss2si %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f1(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcvtss2si 128(%0), %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r1(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "cvtss2si 128(%0), %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f2(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcvttss2si %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r2(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "cvttss2si %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f3(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcvttss2si 128(%0), %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r3(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "cvttss2si 128(%0), %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f4(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcvtsi2ssl %%edx, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r4(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n cvtsi2ssl %%edx, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f5(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcvtsi2ssl 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r5(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n cvtsi2ssl 128(%0), %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f6(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcomiss %%xmm3, %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r6(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "comiss %%xmm3, %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f7(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcomiss 128(%0), %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r7(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "comiss 128(%0), %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f8(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vucomiss %%xmm3, %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r8(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "ucomiss %%xmm3, %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f9(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vucomiss 128(%0), %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r9(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "ucomiss 128(%0), %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f10(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcvtsd2si %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r10(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "cvtsd2si %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f11(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcvtsd2si 128(%0), %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r11(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "cvtsd2si 128(%0), %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f12(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcvttsd2si %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r12(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "cvttsd2si %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f13(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcvttsd2si 128(%0), %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r13(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "cvttsd2si 128(%0), %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f14(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcvtsi2sdl %%edx, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r14(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n cvtsi2sdl %%edx, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f15(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcvtsi2sdl 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r15(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n cvtsi2sdl 128(%0), %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f16(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcomisd %%xmm3, %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r16(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "comisd %%xmm3, %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f17(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vcomisd 128(%0), %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r17(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "comisd 128(%0), %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f18(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vucomisd %%xmm3, %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r18(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "ucomisd %%xmm3, %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f19(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vucomisd 128(%0), %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r19(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "ucomisd 128(%0), %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f20(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovmskps %%ymm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m20(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; for (int i = 0; i < 32; i += 4) go |= (uint64_t) (b[i + 3] >> 7) << (i / 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f21(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovmskpd %%ymm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m21(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; for (int i = 0; i < 32; i += 8) go |= (uint64_t) (b[i + 7] >> 7) << (i / 8);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f22(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpmovmskb %%ymm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m22(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; for (int i = 0; i < 32; i++) go |= (uint64_t) (b[i] >> 7) << i;
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f23(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vptest %%ymm3, %%ymm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m23(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    int z = 1, c = 1; for (int i = 0; i < 32; i++) { uint8_t mm = 0xff; if (a[i] & b[i] & mm) z = 0; if (~a[i] & b[i] & mm) c = 0; } fo = (z ? 0x40 : 0) | (c ? 1 : 0);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f24(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vptest 128(%0), %%ymm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m24(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    int z = 1, c = 1; for (int i = 0; i < 32; i++) { uint8_t mm = 0xff; if (a[i] & m[i] & mm) z = 0; if (~a[i] & m[i] & mm) c = 0; } fo = (z ? 0x40 : 0) | (c ? 1 : 0);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f25(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vtestps %%ymm3, %%ymm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m25(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    int z = 1, c = 1; for (int i = 0; i < 32; i++) { uint8_t mm = ((i % 4) == 4 - 1 ? 0x80 : 0); if (a[i] & b[i] & mm) z = 0; if (~a[i] & b[i] & mm) c = 0; } fo = (z ? 0x40 : 0) | (c ? 1 : 0);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f26(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vtestps 128(%0), %%ymm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m26(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    int z = 1, c = 1; for (int i = 0; i < 32; i++) { uint8_t mm = ((i % 4) == 4 - 1 ? 0x80 : 0); if (a[i] & m[i] & mm) z = 0; if (~a[i] & m[i] & mm) c = 0; } fo = (z ? 0x40 : 0) | (c ? 1 : 0);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f27(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vtestpd %%ymm3, %%ymm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m27(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    int z = 1, c = 1; for (int i = 0; i < 32; i++) { uint8_t mm = ((i % 8) == 8 - 1 ? 0x80 : 0); if (a[i] & b[i] & mm) z = 0; if (~a[i] & b[i] & mm) c = 0; } fo = (z ? 0x40 : 0) | (c ? 1 : 0);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f28(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vtestpd 128(%0), %%ymm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m28(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    int z = 1, c = 1; for (int i = 0; i < 32; i++) { uint8_t mm = ((i % 8) == 8 - 1 ? 0x80 : 0); if (a[i] & m[i] & mm) z = 0; if (~a[i] & m[i] & mm) c = 0; } fo = (z ? 0x40 : 0) | (c ? 1 : 0);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f29(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovmskps %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m29(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; for (int i = 0; i < 16; i += 4) go |= (uint64_t) (b[i + 3] >> 7) << (i / 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f30(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovmskpd %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m30(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; for (int i = 0; i < 16; i += 8) go |= (uint64_t) (b[i + 7] >> 7) << (i / 8);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f31(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpmovmskb %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m31(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; for (int i = 0; i < 16; i++) go |= (uint64_t) (b[i] >> 7) << i;
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f32(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vptest %%xmm3, %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m32(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    int z = 1, c = 1; for (int i = 0; i < 16; i++) { uint8_t mm = 0xff; if (a[i] & b[i] & mm) z = 0; if (~a[i] & b[i] & mm) c = 0; } fo = (z ? 0x40 : 0) | (c ? 1 : 0);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f33(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vptest 128(%0), %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m33(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    int z = 1, c = 1; for (int i = 0; i < 16; i++) { uint8_t mm = 0xff; if (a[i] & m[i] & mm) z = 0; if (~a[i] & m[i] & mm) c = 0; } fo = (z ? 0x40 : 0) | (c ? 1 : 0);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f34(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vtestps %%xmm3, %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m34(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    int z = 1, c = 1; for (int i = 0; i < 16; i++) { uint8_t mm = ((i % 4) == 4 - 1 ? 0x80 : 0); if (a[i] & b[i] & mm) z = 0; if (~a[i] & b[i] & mm) c = 0; } fo = (z ? 0x40 : 0) | (c ? 1 : 0);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f35(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vtestps 128(%0), %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m35(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    int z = 1, c = 1; for (int i = 0; i < 16; i++) { uint8_t mm = ((i % 4) == 4 - 1 ? 0x80 : 0); if (a[i] & m[i] & mm) z = 0; if (~a[i] & m[i] & mm) c = 0; } fo = (z ? 0x40 : 0) | (c ? 1 : 0);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f36(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vtestpd %%xmm3, %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m36(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    int z = 1, c = 1; for (int i = 0; i < 16; i++) { uint8_t mm = ((i % 8) == 8 - 1 ? 0x80 : 0); if (a[i] & b[i] & mm) z = 0; if (~a[i] & b[i] & mm) c = 0; } fo = (z ? 0x40 : 0) | (c ? 1 : 0);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f37(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vtestpd 128(%0), %%xmm2" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m37(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    int z = 1, c = 1; for (int i = 0; i < 16; i++) { uint8_t mm = ((i % 8) == 8 - 1 ? 0x80 : 0); if (a[i] & m[i] & mm) z = 0; if (~a[i] & m[i] & mm) c = 0; } fo = (z ? 0x40 : 0) | (c ? 1 : 0);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f38(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrb $0, %%edx, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m38(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 0, &g, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f39(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrb $0, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m39(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 0, m, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f40(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrb $5, %%edx, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m40(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 5, &g, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f41(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrb $5, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m41(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 5, m, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f42(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrb $15, %%edx, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m42(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 15, &g, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f43(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrb $15, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m43(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 15, m, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f44(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrb $19, %%edx, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m44(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 3, &g, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f45(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrb $19, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m45(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 3, m, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f46(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrw $0, %%edx, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m46(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 0, &g, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f47(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrw $0, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m47(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 0, m, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f48(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrw $3, %%edx, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m48(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 6, &g, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f49(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrw $3, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m49(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 6, m, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f50(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrw $7, %%edx, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m50(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 14, &g, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f51(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrw $7, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m51(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 14, m, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f52(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrw $9, %%edx, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m52(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 2, &g, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f53(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrw $9, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m53(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 2, m, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f54(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrd $0, %%edx, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m54(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 0, &g, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f55(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrd $0, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m55(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 0, m, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f56(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrd $1, %%edx, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m56(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 4, &g, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f57(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrd $1, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m57(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 4, m, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f58(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrd $3, %%edx, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m58(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 12, &g, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f59(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrd $3, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m59(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 12, m, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f60(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrd $6, %%edx, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m60(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 8, &g, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f61(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpinsrd $6, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m61(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(o, a, 16); memcpy(o + 8, m, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f62(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $0, %%xmm3, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r62(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $0, %%xmm3, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f63(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $0, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r63(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $0, 128(%0), %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f64(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $16, %%xmm3, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r64(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $16, %%xmm3, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f65(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $16, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r65(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $16, 128(%0), %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f66(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $37, %%xmm3, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r66(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $37, %%xmm3, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f67(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $37, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r67(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $37, 128(%0), %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f68(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $58, %%xmm3, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r68(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $58, %%xmm3, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f69(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $58, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r69(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $58, 128(%0), %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f70(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $79, %%xmm3, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r70(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $79, %%xmm3, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f71(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $79, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r71(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $79, 128(%0), %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f72(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $192, %%xmm3, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r72(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $192, %%xmm3, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f73(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $192, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r73(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $192, 128(%0), %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f74(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $255, %%xmm3, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r74(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $255, %%xmm3, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f75(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $255, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r75(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $255, 128(%0), %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f76(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $154, %%xmm3, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r76(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $154, %%xmm3, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f77(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $154, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r77(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $154, 128(%0), %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f78(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $48, %%xmm3, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r78(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $48, %%xmm3, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f79(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $48, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r79(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $48, 128(%0), %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f80(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $225, %%xmm3, %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r80(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $225, %%xmm3, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f81(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vinsertps $225, 128(%0), %%xmm2, %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void r81(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vmovdqa %%xmm2, %%xmm1\n insertps $225, 128(%0), %%xmm1" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
__attribute__((noinline)) static void f82(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrb $0, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m82(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 0, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f83(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrb $0, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m83(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 0, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f84(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrb $7, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m84(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 7, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f85(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrb $7, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m85(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 7, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f86(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrb $15, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m86(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 15, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f87(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrb $15, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m87(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 15, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f88(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrb $17, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m88(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 1, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f89(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrb $17, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m89(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 1, 1);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f90(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrw $0, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m90(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 0, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f91(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrw $0, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m91(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 0, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f92(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrw $3, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m92(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 6, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f93(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrw $3, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m93(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 6, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f94(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrw $7, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m94(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 14, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f95(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrw $7, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m95(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 14, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f96(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrw $9, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m96(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 2, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f97(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrw $9, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m97(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 2, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f98(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrd $0, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m98(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 0, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f99(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrd $0, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m99(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 0, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f100(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrd $1, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m100(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 4, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f101(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrd $1, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m101(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 4, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f102(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrd $3, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m102(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 12, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f103(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrd $3, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m103(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 12, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f104(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrd $5, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m104(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 4, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f105(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vpextrd $5, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m105(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 4, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f106(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vextractps $0, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m106(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 0, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f107(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vextractps $0, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m107(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 0, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f108(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vextractps $2, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m108(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 8, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f109(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vextractps $2, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m109(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 8, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f110(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vextractps $3, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m110(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 12, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f111(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vextractps $3, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m111(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 12, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f112(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vextractps $6, %%xmm3, %%edx" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m112(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 8, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f113(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" "vextractps $6, %%xmm3, 128(%0)" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m113(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    memcpy(mo, b + 8, 4);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f114(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" ".byte 0xc5, 0xf9, 0xc5, 0xd3, 0" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m114(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 0, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f115(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" ".byte 0xc5, 0xf9, 0xc5, 0xd3, 3" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m115(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 6, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f116(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" ".byte 0xc5, 0xf9, 0xc5, 0xd3, 7" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m116(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 14, 2);
    *gop = go; *fop = fo;
}
__attribute__((noinline)) static void f117(struct st *t) { __asm__ volatile("vmovdqu (%0), %%ymm2\n vmovdqu 32(%0), %%ymm3\n vmovdqu 64(%0), %%ymm1\n mov 192(%0), %%edx\n push $0x8d7\n popf\n" ".byte 0xc5, 0xf9, 0xc5, 0xd3, 12" "\n pushf\n pop 208(%0)\n vmovdqu %%ymm1, 96(%0)\n mov %%edx, 200(%0)\n vzeroupper" :: "r"(t) : "memory", "cc", "edx", "xmm1", "xmm2", "xmm3"); }
static void m117(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    go = 0; memcpy(&go, b + 8, 2);
    *gop = go; *fop = fo;
}
static const struct { const char *name; void (*fn)(struct st *); void (*ref)(struct st *); void (*model)(const uint8_t *, const uint8_t *, const uint8_t *, const uint8_t *, uint64_t, uint8_t *, uint8_t *, uint64_t *, uint64_t *); int vec_out; } forms[] = {
    {"vcvtss2si32 reg", f0, r0, NULL, 0},
    {"vcvtss2si32 mem", f1, r1, NULL, 0},
    {"vcvttss2si32 reg", f2, r2, NULL, 0},
    {"vcvttss2si32 mem", f3, r3, NULL, 0},
    {"vcvtsi2ssl reg", f4, r4, NULL, 1},
    {"vcvtsi2ssl mem", f5, r5, NULL, 1},
    {"vcomiss reg", f6, r6, NULL, 0},
    {"vcomiss mem", f7, r7, NULL, 0},
    {"vucomiss reg", f8, r8, NULL, 0},
    {"vucomiss mem", f9, r9, NULL, 0},
    {"vcvtsd2si32 reg", f10, r10, NULL, 0},
    {"vcvtsd2si32 mem", f11, r11, NULL, 0},
    {"vcvttsd2si32 reg", f12, r12, NULL, 0},
    {"vcvttsd2si32 mem", f13, r13, NULL, 0},
    {"vcvtsi2sdl reg", f14, r14, NULL, 1},
    {"vcvtsi2sdl mem", f15, r15, NULL, 1},
    {"vcomisd reg", f16, r16, NULL, 0},
    {"vcomisd mem", f17, r17, NULL, 0},
    {"vucomisd reg", f18, r18, NULL, 0},
    {"vucomisd mem", f19, r19, NULL, 0},
    {"vmovmskps 256", f20, NULL, m20, 0},
    {"vmovmskpd 256", f21, NULL, m21, 0},
    {"vpmovmskb 256", f22, NULL, m22, 0},
    {"vptest 256 reg", f23, NULL, m23, 0},
    {"vptest 256 mem", f24, NULL, m24, 0},
    {"vtestps 256 reg", f25, NULL, m25, 0},
    {"vtestps 256 mem", f26, NULL, m26, 0},
    {"vtestpd 256 reg", f27, NULL, m27, 0},
    {"vtestpd 256 mem", f28, NULL, m28, 0},
    {"vmovmskps 128", f29, NULL, m29, 0},
    {"vmovmskpd 128", f30, NULL, m30, 0},
    {"vpmovmskb 128", f31, NULL, m31, 0},
    {"vptest 128 reg", f32, NULL, m32, 0},
    {"vptest 128 mem", f33, NULL, m33, 0},
    {"vtestps 128 reg", f34, NULL, m34, 0},
    {"vtestps 128 mem", f35, NULL, m35, 0},
    {"vtestpd 128 reg", f36, NULL, m36, 0},
    {"vtestpd 128 mem", f37, NULL, m37, 0},
    {"vpinsrb 0 reg", f38, NULL, m38, 1},
    {"vpinsrb 0 mem", f39, NULL, m39, 1},
    {"vpinsrb 5 reg", f40, NULL, m40, 1},
    {"vpinsrb 5 mem", f41, NULL, m41, 1},
    {"vpinsrb 15 reg", f42, NULL, m42, 1},
    {"vpinsrb 15 mem", f43, NULL, m43, 1},
    {"vpinsrb 19 reg", f44, NULL, m44, 1},
    {"vpinsrb 19 mem", f45, NULL, m45, 1},
    {"vpinsrw 0 reg", f46, NULL, m46, 1},
    {"vpinsrw 0 mem", f47, NULL, m47, 1},
    {"vpinsrw 3 reg", f48, NULL, m48, 1},
    {"vpinsrw 3 mem", f49, NULL, m49, 1},
    {"vpinsrw 7 reg", f50, NULL, m50, 1},
    {"vpinsrw 7 mem", f51, NULL, m51, 1},
    {"vpinsrw 9 reg", f52, NULL, m52, 1},
    {"vpinsrw 9 mem", f53, NULL, m53, 1},
    {"vpinsrd 0 reg", f54, NULL, m54, 1},
    {"vpinsrd 0 mem", f55, NULL, m55, 1},
    {"vpinsrd 1 reg", f56, NULL, m56, 1},
    {"vpinsrd 1 mem", f57, NULL, m57, 1},
    {"vpinsrd 3 reg", f58, NULL, m58, 1},
    {"vpinsrd 3 mem", f59, NULL, m59, 1},
    {"vpinsrd 6 reg", f60, NULL, m60, 1},
    {"vpinsrd 6 mem", f61, NULL, m61, 1},
    {"vinsertps 0x0 reg", f62, r62, NULL, 1},
    {"vinsertps 0x0 mem", f63, r63, NULL, 1},
    {"vinsertps 0x10 reg", f64, r64, NULL, 1},
    {"vinsertps 0x10 mem", f65, r65, NULL, 1},
    {"vinsertps 0x25 reg", f66, r66, NULL, 1},
    {"vinsertps 0x25 mem", f67, r67, NULL, 1},
    {"vinsertps 0x3a reg", f68, r68, NULL, 1},
    {"vinsertps 0x3a mem", f69, r69, NULL, 1},
    {"vinsertps 0x4f reg", f70, r70, NULL, 1},
    {"vinsertps 0x4f mem", f71, r71, NULL, 1},
    {"vinsertps 0xc0 reg", f72, r72, NULL, 1},
    {"vinsertps 0xc0 mem", f73, r73, NULL, 1},
    {"vinsertps 0xff reg", f74, r74, NULL, 1},
    {"vinsertps 0xff mem", f75, r75, NULL, 1},
    {"vinsertps 0x9a reg", f76, r76, NULL, 1},
    {"vinsertps 0x9a mem", f77, r77, NULL, 1},
    {"vinsertps 0x30 reg", f78, r78, NULL, 1},
    {"vinsertps 0x30 mem", f79, r79, NULL, 1},
    {"vinsertps 0xe1 reg", f80, r80, NULL, 1},
    {"vinsertps 0xe1 mem", f81, r81, NULL, 1},
    {"vpextrb 0 reg", f82, NULL, m82, 0},
    {"vpextrb 0 mem", f83, NULL, m83, 0},
    {"vpextrb 7 reg", f84, NULL, m84, 0},
    {"vpextrb 7 mem", f85, NULL, m85, 0},
    {"vpextrb 15 reg", f86, NULL, m86, 0},
    {"vpextrb 15 mem", f87, NULL, m87, 0},
    {"vpextrb 17 reg", f88, NULL, m88, 0},
    {"vpextrb 17 mem", f89, NULL, m89, 0},
    {"vpextrw 0 reg", f90, NULL, m90, 0},
    {"vpextrw 0 mem", f91, NULL, m91, 0},
    {"vpextrw 3 reg", f92, NULL, m92, 0},
    {"vpextrw 3 mem", f93, NULL, m93, 0},
    {"vpextrw 7 reg", f94, NULL, m94, 0},
    {"vpextrw 7 mem", f95, NULL, m95, 0},
    {"vpextrw 9 reg", f96, NULL, m96, 0},
    {"vpextrw 9 mem", f97, NULL, m97, 0},
    {"vpextrd 0 reg", f98, NULL, m98, 0},
    {"vpextrd 0 mem", f99, NULL, m99, 0},
    {"vpextrd 1 reg", f100, NULL, m100, 0},
    {"vpextrd 1 mem", f101, NULL, m101, 0},
    {"vpextrd 3 reg", f102, NULL, m102, 0},
    {"vpextrd 3 mem", f103, NULL, m103, 0},
    {"vpextrd 5 reg", f104, NULL, m104, 0},
    {"vpextrd 5 mem", f105, NULL, m105, 0},
    {"vextractps 0 reg", f106, NULL, m106, 0},
    {"vextractps 0 mem", f107, NULL, m107, 0},
    {"vextractps 2 reg", f108, NULL, m108, 0},
    {"vextractps 2 mem", f109, NULL, m109, 0},
    {"vextractps 3 reg", f110, NULL, m110, 0},
    {"vextractps 3 mem", f111, NULL, m111, 0},
    {"vextractps 6 reg", f112, NULL, m112, 0},
    {"vextractps 6 mem", f113, NULL, m113, 0},
    {"vpextrw c5 0", f114, NULL, m114, 0},
    {"vpextrw c5 3", f115, NULL, m115, 0},
    {"vpextrw c5 7", f116, NULL, m116, 0},
    {"vpextrw c5 12", f117, NULL, m117, 0},
};
#define NFORMS 118

static const unsigned modes[] = {0x1f80, 0x7f80, 0x9fc0};
int main(void) {
    static struct st t, u;
    for (int k = 0; k < 400; k++) {
        for (int fi = 0; fi < NFORMS; fi++) {
            for (unsigned mi = 0; mi < (forms[fi].ref ? 3u : 1u); mi++) {
                for (int i = 0; i < 32; i += 4) {
                    uint32_t v = (uint32_t) rnd();
                    static const uint32_t sp[] = {0x7fc00000, 0x7f800001, 0xff800000, 0x00000001, 0x80000000, 0x4f000000, 0xcf000001, 0x3fc00000, 0x5f000000, 0xdf000000};
                    if ((v & 7) == 0) v = sp[(v >> 3) % 10];
                    else if (k & 1) v = (v & 0x807fffff) | (((v >> 23) % 70 + 100) << 23);
                    memcpy(t.a + i, &v, 4); v = (uint32_t) rnd(); if ((v & 7) == 0) v = sp[(v >> 3) % 10]; else if (k & 1) v = (v & 0x807fffff) | (((v >> 23) % 70 + 100) << 23);
                    memcpy(t.b + i, &v, 4); v = (uint32_t) rnd(); memcpy(t.d + i, &v, 4);
                }
                if (k % 5 == 2) memcpy(t.b, t.a, 32);
                for (int i = 0; i < 64; i++) t.m[i] = (uint8_t) rnd();
                if (k & 2) memcpy(t.m, t.b, 32);
                t.g = rnd() & GMASK; if (k % 3 == 0) t.g = (uint64_t) (int64_t) (int32_t) t.g & GMASK;
                t.gout = 0; t.fl = 0;
                u = t;
                ldmx(modes[mi]);
                forms[fi].fn(&t);
                unsigned gf = stmx() & 0x3f, wf;
                uint8_t o[32], mo[64];
                uint64_t go, fo;
                if (forms[fi].ref) {
                    ldmx(modes[mi]);
                    forms[fi].ref(&u);
                    wf = stmx() & 0x3f;
                    memcpy(o, u.out, 32);
                    if (forms[fi].vec_out) memset(o + 16, 0, 16);
                    memcpy(mo, u.m, 64); go = u.gout; fo = u.fl;
                } else {
                    memcpy(mo, u.m, 64);
                    forms[fi].model(u.a, u.b, u.d, u.m, u.g, o, mo, &go, &fo);
                    if (forms[fi].vec_out) memset(o + 16, 0, 16);
                    wf = gf;
                }
                go &= GMASK;
                checks++;
                if ((memcmp(t.out, o, 32) || memcmp(t.m, mo, 64) || (t.gout & GMASK) != go || (t.fl & 0x8d5) != (fo & 0x8d5) || gf != wf) && bad++ < 40) {
                    printf("FAIL %s (%d, mode %#x): gpr %llx want %llx, flags %llx want %llx, mxcsr %#x want %#x, mem %s\n  got ",
                           forms[fi].name, k, modes[mi], (unsigned long long) t.gout, (unsigned long long) go,
                           (unsigned long long) (t.fl & 0x8d5), (unsigned long long) (fo & 0x8d5), gf, wf, memcmp(t.m, mo, 64) ? "DIFFERS" : "ok");
                    for (int i = 31; i >= 0; i--) printf("%s%02x", i % 8 == 7 ? " " : "", t.out[i]);
                    printf("\n  want");
                    for (int i = 31; i >= 0; i--) printf("%s%02x", i % 8 == 7 ? " " : "", o[i]);
                    printf("\n");
                }
            }
        }
    }
    ldmx(0x1f80);
    printf("i386_vex_gpr: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NFORMS, checks, bad);
    return bad != 0;
}