// Generated by tools/gen-avx512-kmask-test.py --i386 -- do not edit.
//
// The AVX-512 opmask instructions against Intel SDE (see the generator).
#define _GNU_SOURCE
#include <setjmp.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
static uint64_t rs;
static uint64_t rnd(void) { rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }
struct st { uint64_t k1, k2, k3, gpr; uint8_t m[16]; uint64_t ok1, ogpr, oflags; uint8_t om[16]; };
static sigjmp_buf jb;
static volatile int sig;
static void handler(int s) { sig = s; siglongjmp(jb, 1); }
// (no target pragma: the harness itself must not use AVX-512, which the i386
// guest's compiler would otherwise do for its 64-bit arithmetic)

__attribute__((noinline)) static void f0(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kandb %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f1(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kandw %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f2(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kandd %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f3(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kandq %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f4(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kandnb %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f5(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kandnw %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f6(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kandnd %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f7(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kandnq %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f8(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n korb %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f9(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n korw %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f10(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kord %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f11(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n korq %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f12(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kxnorb %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f13(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kxnorw %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f14(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kxnord %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f15(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kxnorq %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f16(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kxorb %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f17(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kxorw %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f18(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kxord %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f19(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kxorq %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f20(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kaddb %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f21(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kaddw %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f22(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kaddd %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f23(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kaddq %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f24(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n knotb %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f25(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n knotw %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f26(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n knotd %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f27(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n knotq %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f28(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kunpckbw %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f29(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kunpckwd %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f30(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kunpckdq %%k3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f31(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovb %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f32(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovb 32(%0), %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f33(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovb %%k2, 32(%0)\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f34(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n xor %%ecx, %%ecx\n add $0, %%ecx\n kortestb %%k3, %%k2\n pushf\n pop %%ecx\n mov %%ecx, 64(%0)\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f35(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n xor %%ecx, %%ecx\n add $0, %%ecx\n ktestb %%k3, %%k2\n pushf\n pop %%ecx\n mov %%ecx, 64(%0)\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f36(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovw %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f37(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovw 32(%0), %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f38(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovw %%k2, 32(%0)\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f39(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n xor %%ecx, %%ecx\n add $0, %%ecx\n kortestw %%k3, %%k2\n pushf\n pop %%ecx\n mov %%ecx, 64(%0)\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f40(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n xor %%ecx, %%ecx\n add $0, %%ecx\n ktestw %%k3, %%k2\n pushf\n pop %%ecx\n mov %%ecx, 64(%0)\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f41(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovd %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f42(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovd 32(%0), %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f43(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovd %%k2, 32(%0)\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f44(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n xor %%ecx, %%ecx\n add $0, %%ecx\n kortestd %%k3, %%k2\n pushf\n pop %%ecx\n mov %%ecx, 64(%0)\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f45(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n xor %%ecx, %%ecx\n add $0, %%ecx\n ktestd %%k3, %%k2\n pushf\n pop %%ecx\n mov %%ecx, 64(%0)\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f46(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovq %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f47(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovq 32(%0), %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f48(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovq %%k2, 32(%0)\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f49(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n xor %%ecx, %%ecx\n add $0, %%ecx\n kortestq %%k3, %%k2\n pushf\n pop %%ecx\n mov %%ecx, 64(%0)\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f50(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n xor %%ecx, %%ecx\n add $0, %%ecx\n ktestq %%k3, %%k2\n pushf\n pop %%ecx\n mov %%ecx, 64(%0)\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f51(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovb %%ecx, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f52(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovb %%k2, %%ecx\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f53(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovw %%ecx, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f54(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovw %%k2, %%ecx\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f55(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovd %%ecx, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f56(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kmovd %%k2, %%ecx\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f57(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlb $0, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f58(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlb $1, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f59(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlb $3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f60(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlb $7, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f61(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlb $8, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f62(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlb $9, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f63(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlb $64, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f64(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlb $255, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f65(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlw $0, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f66(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlw $1, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f67(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlw $3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f68(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlw $15, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f69(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlw $16, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f70(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlw $17, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f71(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlw $64, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f72(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlw $255, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f73(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftld $0, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f74(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftld $1, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f75(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftld $3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f76(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftld $31, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f77(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftld $32, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f78(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftld $33, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f79(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftld $64, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f80(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftld $255, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f81(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlq $0, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f82(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlq $1, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f83(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlq $3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f84(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlq $63, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f85(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlq $64, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f86(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlq $65, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f87(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlq $64, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f88(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftlq $255, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f89(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrb $0, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f90(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrb $1, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f91(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrb $3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f92(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrb $7, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f93(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrb $8, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f94(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrb $9, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f95(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrb $64, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f96(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrb $255, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f97(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrw $0, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f98(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrw $1, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f99(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrw $3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f100(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrw $15, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f101(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrw $16, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f102(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrw $17, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f103(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrw $64, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f104(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrw $255, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f105(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrd $0, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f106(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrd $1, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f107(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrd $3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f108(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrd $31, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f109(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrd $32, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f110(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrd $33, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f111(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrd $64, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f112(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrd $255, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f113(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrq $0, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f114(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrq $1, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f115(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrq $3, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f116(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrq $63, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f117(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrq $64, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f118(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrq $65, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f119(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrq $64, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f120(struct st *t) {
    __asm__ volatile("kmovq (%0), %%k1\n kmovq 8(%0), %%k2\n kmovq 16(%0), %%k3\n mov 24(%0), %%ecx\n kshiftrq $255, %%k2, %%k1\n kmovq %%k1, 48(%0)\n mov %%ecx, 56(%0)" :: "r"(t) : "memory", "ecx", "cc");
}
__attribute__((noinline)) static void f121(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc5, 0xe8, 0x41, 0xca\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
__attribute__((noinline)) static void f122(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc5, 0xec, 0x41, 0xca\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
__attribute__((noinline)) static void f123(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc5, 0xec, 0x41, 0x08\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
__attribute__((noinline)) static void f124(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc5, 0xfc, 0x44, 0xca\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
__attribute__((noinline)) static void f125(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc5, 0xe8, 0x44, 0xca\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
__attribute__((noinline)) static void f126(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc5, 0xe8, 0x90, 0xca\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
__attribute__((noinline)) static void f127(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc5, 0xf8, 0x91, 0xca\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
__attribute__((noinline)) static void f128(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc4, 0xe1, 0xed, 0x4b, 0xca\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
__attribute__((noinline)) static void f129(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc4, 0xe1, 0xf9, 0x92, 0xc8\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
__attribute__((noinline)) static void f130(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc4, 0xe1, 0xf8, 0x92, 0xc8\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
__attribute__((noinline)) static void f131(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc5, 0xfc, 0x98, 0xca\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
__attribute__((noinline)) static void f132(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc4, 0xe3, 0xfd, 0x32, 0xca, 0x01\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
__attribute__((noinline)) static void f133(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc4, 0xe3, 0xf8, 0x30, 0xca, 0x01\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
__attribute__((noinline)) static void f134(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc5, 0xe8, 0x4a, 0xca\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
__attribute__((noinline)) static void f135(struct st *t) {
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\n kxorq %%k2, %%k2, %%k2\n mov %0, %%" "eax" "\n .byte 0xc4, 0xe3, 0xf9, 0x30, 0x08, 0x01\n" :: "r"(t->m) : "memory", "eax", "ecx");
}
static const struct { const char *name; void (*fn)(struct st *); int ud, g64; } forms[] = {
    {"kandb", f0, 0, 0},
    {"kandw", f1, 0, 0},
    {"kandd", f2, 0, 0},
    {"kandq", f3, 0, 0},
    {"kandnb", f4, 0, 0},
    {"kandnw", f5, 0, 0},
    {"kandnd", f6, 0, 0},
    {"kandnq", f7, 0, 0},
    {"korb", f8, 0, 0},
    {"korw", f9, 0, 0},
    {"kord", f10, 0, 0},
    {"korq", f11, 0, 0},
    {"kxnorb", f12, 0, 0},
    {"kxnorw", f13, 0, 0},
    {"kxnord", f14, 0, 0},
    {"kxnorq", f15, 0, 0},
    {"kxorb", f16, 0, 0},
    {"kxorw", f17, 0, 0},
    {"kxord", f18, 0, 0},
    {"kxorq", f19, 0, 0},
    {"kaddb", f20, 0, 0},
    {"kaddw", f21, 0, 0},
    {"kaddd", f22, 0, 0},
    {"kaddq", f23, 0, 0},
    {"knotb", f24, 0, 0},
    {"knotw", f25, 0, 0},
    {"knotd", f26, 0, 0},
    {"knotq", f27, 0, 0},
    {"kunpckbw", f28, 0, 0},
    {"kunpckwd", f29, 0, 0},
    {"kunpckdq", f30, 0, 0},
    {"kmovb k,k", f31, 0, 0},
    {"kmovb k,m", f32, 0, 0},
    {"kmovb m,k", f33, 0, 0},
    {"kortestb", f34, 0, 0},
    {"ktestb", f35, 0, 0},
    {"kmovw k,k", f36, 0, 0},
    {"kmovw k,m", f37, 0, 0},
    {"kmovw m,k", f38, 0, 0},
    {"kortestw", f39, 0, 0},
    {"ktestw", f40, 0, 0},
    {"kmovd k,k", f41, 0, 0},
    {"kmovd k,m", f42, 0, 0},
    {"kmovd m,k", f43, 0, 0},
    {"kortestd", f44, 0, 0},
    {"ktestd", f45, 0, 0},
    {"kmovq k,k", f46, 0, 0},
    {"kmovq k,m", f47, 0, 0},
    {"kmovq m,k", f48, 0, 0},
    {"kortestq", f49, 0, 0},
    {"ktestq", f50, 0, 0},
    {"kmovb k,r", f51, 0, 0},
    {"kmovb r,k", f52, 0, 0},
    {"kmovw k,r", f53, 0, 0},
    {"kmovw r,k", f54, 0, 0},
    {"kmovd k,r", f55, 0, 0},
    {"kmovd r,k", f56, 0, 0},
    {"kshiftlb $0", f57, 0, 0},
    {"kshiftlb $1", f58, 0, 0},
    {"kshiftlb $3", f59, 0, 0},
    {"kshiftlb $7", f60, 0, 0},
    {"kshiftlb $8", f61, 0, 0},
    {"kshiftlb $9", f62, 0, 0},
    {"kshiftlb $64", f63, 0, 0},
    {"kshiftlb $255", f64, 0, 0},
    {"kshiftlw $0", f65, 0, 0},
    {"kshiftlw $1", f66, 0, 0},
    {"kshiftlw $3", f67, 0, 0},
    {"kshiftlw $15", f68, 0, 0},
    {"kshiftlw $16", f69, 0, 0},
    {"kshiftlw $17", f70, 0, 0},
    {"kshiftlw $64", f71, 0, 0},
    {"kshiftlw $255", f72, 0, 0},
    {"kshiftld $0", f73, 0, 0},
    {"kshiftld $1", f74, 0, 0},
    {"kshiftld $3", f75, 0, 0},
    {"kshiftld $31", f76, 0, 0},
    {"kshiftld $32", f77, 0, 0},
    {"kshiftld $33", f78, 0, 0},
    {"kshiftld $64", f79, 0, 0},
    {"kshiftld $255", f80, 0, 0},
    {"kshiftlq $0", f81, 0, 0},
    {"kshiftlq $1", f82, 0, 0},
    {"kshiftlq $3", f83, 0, 0},
    {"kshiftlq $63", f84, 0, 0},
    {"kshiftlq $64", f85, 0, 0},
    {"kshiftlq $65", f86, 0, 0},
    {"kshiftlq $64", f87, 0, 0},
    {"kshiftlq $255", f88, 0, 0},
    {"kshiftrb $0", f89, 0, 0},
    {"kshiftrb $1", f90, 0, 0},
    {"kshiftrb $3", f91, 0, 0},
    {"kshiftrb $7", f92, 0, 0},
    {"kshiftrb $8", f93, 0, 0},
    {"kshiftrb $9", f94, 0, 0},
    {"kshiftrb $64", f95, 0, 0},
    {"kshiftrb $255", f96, 0, 0},
    {"kshiftrw $0", f97, 0, 0},
    {"kshiftrw $1", f98, 0, 0},
    {"kshiftrw $3", f99, 0, 0},
    {"kshiftrw $15", f100, 0, 0},
    {"kshiftrw $16", f101, 0, 0},
    {"kshiftrw $17", f102, 0, 0},
    {"kshiftrw $64", f103, 0, 0},
    {"kshiftrw $255", f104, 0, 0},
    {"kshiftrd $0", f105, 0, 0},
    {"kshiftrd $1", f106, 0, 0},
    {"kshiftrd $3", f107, 0, 0},
    {"kshiftrd $31", f108, 0, 0},
    {"kshiftrd $32", f109, 0, 0},
    {"kshiftrd $33", f110, 0, 0},
    {"kshiftrd $64", f111, 0, 0},
    {"kshiftrd $255", f112, 0, 0},
    {"kshiftrq $0", f113, 0, 0},
    {"kshiftrq $1", f114, 0, 0},
    {"kshiftrq $3", f115, 0, 0},
    {"kshiftrq $63", f116, 0, 0},
    {"kshiftrq $64", f117, 0, 0},
    {"kshiftrq $65", f118, 0, 0},
    {"kshiftrq $64", f119, 0, 0},
    {"kshiftrq $255", f120, 0, 0},
    {"ud kandw L0", f121, 1, 0},
    {"ud kandw ok", f122, 1, 0},
    {"ud kandw mem", f123, 1, 0},
    {"ud knotw L1", f124, 1, 0},
    {"ud knotw vvvv", f125, 1, 0},
    {"ud kmovw vvvv", f126, 1, 0},
    {"ud kmovw st reg", f127, 1, 0},
    {"ud kunpck 66 W1", f128, 1, 0},
    {"ud kmov 92 66 W1", f129, 1, 0},
    {"ud kmov 92 0F W1", f130, 1, 0},
    {"ud kortestw L1", f131, 1, 0},
    {"ud kshiftlw L1", f132, 1, 0},
    {"ud kshift 30 pp0", f133, 1, 0},
    {"ud kaddw L0", f134, 1, 0},
    {"ud kshiftrw mem", f135, 1, 0},
};
#define NF 136
static const uint64_t want[NF] = {
    0x583395fa1ba15b72ull,   // kandb
    0x6f13c475d9a85f78ull,   // kandw
    0x3e3bc423e114edf7ull,   // kandd
    0x4c99734c0c5fb0dfull,   // kandq
    0xfaa6ada49cfb28aaull,   // kandnb
    0x3d181488919fb72aull,   // kandnw
    0xc2a8f9bf2ea68940ull,   // kandnd
    0xa52d053da2e7cb45ull,   // kandnq
    0x7974c489c8ab679full,   // korb
    0x4e7b429c776906f8ull,   // korw
    0xdaaeb3968438442bull,   // kord
    0xd7578cf70a6ccf5cull,   // korq
    0xc0c3862c8fe8f51aull,   // kxnorb
    0x713e0b8282d62fbeull,   // kxnorw
    0xedc0a6d936f17fafull,   // kxnord
    0x3f28050951278041ull,   // kxnorq
    0x947c9c6b5e5d0b05ull,   // kxorb
    0xb7c6801b0a5767edull,   // kxorw
    0x5b8ffc3d9a019160ull,   // kxord
    0x69811f220fb652dfull,   // kxorq
    0x2c40e9f31a1f8011ull,   // kaddb
    0x6d230a0fe18a49deull,   // kaddw
    0x47f50f70c6db815bull,   // kaddd
    0xb0d78cbeb2a4bbe5ull,   // kaddq
    0xc9be0dae6ff819b7ull,   // knotb
    0x73daedfb0d3a1d68ull,   // knotw
    0xe2345a8d1beb5af1ull,   // knotd
    0x69da9d49fe48489eull,   // knotq
    0xb352ec8cc5de8448ull,   // kunpckbw
    0x8b5769c9224110afull,   // kunpckwd
    0x47172b340df017f9ull,   // kunpckdq
    0xc7351ddbe480353dull,   // kmovb k,k
    0xa26ea8dbb06a96b5ull,   // kmovb k,m
    0xd5c69da7bcb99fb6ull,   // kmovb m,k
    0xf150236a92280058ull,   // kortestb
    0x95edb91bea936a24ull,   // ktestb
    0x500bf9aa0b38ee58ull,   // kmovw k,k
    0xec458ad637fa5659ull,   // kmovw k,m
    0x4519bd047292de92ull,   // kmovw m,k
    0x8213f172e39a2c9full,   // kortestw
    0x8f55052501f066c2ull,   // ktestw
    0xfbb9f46b77bf5474ull,   // kmovd k,k
    0x8592ff0117ab9a3full,   // kmovd k,m
    0x625a6bad17f8c72dull,   // kmovd m,k
    0xf495ff3ac2c12348ull,   // kortestd
    0x56695b5bf7d673ecull,   // ktestd
    0x147596099aa2ce6ull,   // kmovq k,k
    0xd5023dc621b5febbull,   // kmovq k,m
    0x693a99891037d1a7ull,   // kmovq m,k
    0xc6ceeb6e43ef0762ull,   // kortestq
    0x531e81c4aa075947ull,   // ktestq
    0x6fbb8f901abd8814ull,   // kmovb k,r
    0xa05ee9723b446f03ull,   // kmovb r,k
    0x9e136cf6c7da63fbull,   // kmovw k,r
    0xf24b2241b21e83ull,   // kmovw r,k
    0x9b236cf971860fdcull,   // kmovd k,r
    0xa9f358ed11c2b5f3ull,   // kmovd r,k
    0xcf40c21695675e7cull,   // kshiftlb $0
    0x5afb45d4c6a695dfull,   // kshiftlb $1
    0xb38322603bd5b7e7ull,   // kshiftlb $3
    0xade6c3d321459a46ull,   // kshiftlb $7
    0xfd82ff208fc3bfc4ull,   // kshiftlb $8
    0x6df7eb121ad78b6dull,   // kshiftlb $9
    0xf7522feb9b907551ull,   // kshiftlb $64
    0x2b89da919be9ed4aull,   // kshiftlb $255
    0x3d408adb9ece849aull,   // kshiftlw $0
    0xf6c8691eaf9e0c92ull,   // kshiftlw $1
    0x15a2de37a2378acfull,   // kshiftlw $3
    0xcebd711efe238a8bull,   // kshiftlw $15
    0x711b05bbe3cda6f2ull,   // kshiftlw $16
    0xa599be8e6ae2ce56ull,   // kshiftlw $17
    0xee2343a46219c2b3ull,   // kshiftlw $64
    0x7ae6220a8e36fa2full,   // kshiftlw $255
    0x1bc4b1e527ead99eull,   // kshiftld $0
    0xf5932e2c277ff45dull,   // kshiftld $1
    0x57894053527630beull,   // kshiftld $3
    0xe8382544d659e776ull,   // kshiftld $31
    0x134607e1eb27aa4full,   // kshiftld $32
    0x8f8d7be04d209190ull,   // kshiftld $33
    0x39b62016301e0adull,   // kshiftld $64
    0x11cf3df04b46ed48ull,   // kshiftld $255
    0xed0158f0eca2e6a7ull,   // kshiftlq $0
    0x2d4b0406b92037acull,   // kshiftlq $1
    0x91147b211fa23408ull,   // kshiftlq $3
    0x550c25c212c7df3ull,   // kshiftlq $63
    0xd9dd53f574fae220ull,   // kshiftlq $64
    0x1e27ce7cfb9a981cull,   // kshiftlq $65
    0xd9dd53f574fae220ull,   // kshiftlq $64
    0xc5f029fa2c5fb5a6ull,   // kshiftlq $255
    0x28b8274451e4f22bull,   // kshiftrb $0
    0x551e3f75b9b05ae3ull,   // kshiftrb $1
    0x51106758f02264bbull,   // kshiftrb $3
    0x55e7d148483cbb14ull,   // kshiftrb $7
    0xeb8a43550ba6782full,   // kshiftrb $8
    0xacd8577b883f94dull,   // kshiftrb $9
    0xa0e53996c470477eull,   // kshiftrb $64
    0xd4cad3f6d15ddbdbull,   // kshiftrb $255
    0xf181043beb057791ull,   // kshiftrw $0
    0x510a0a092d84021full,   // kshiftrw $1
    0x7e26b96ad5b4eb0full,   // kshiftrw $3
    0xe589946c2c1a3a07ull,   // kshiftrw $15
    0xba8e95bfebb6b3e3ull,   // kshiftrw $16
    0xe88238f8df70299ull,   // kshiftrw $17
    0xd9b62b87df015740ull,   // kshiftrw $64
    0xf627845fd18d23b7ull,   // kshiftrw $255
    0x5549745d1972d208ull,   // kshiftrd $0
    0xf68a248ef3afd470ull,   // kshiftrd $1
    0xe66668f0805c1a8cull,   // kshiftrd $3
    0x70c6e831290128d7ull,   // kshiftrd $31
    0xde6489dd1d8f0e93ull,   // kshiftrd $32
    0xc294497df51ef875ull,   // kshiftrd $33
    0xd473fe16b55ad27eull,   // kshiftrd $64
    0x6083ffc920a3d51dull,   // kshiftrd $255
    0x1dd3b2b8e0fdcdf0ull,   // kshiftrq $0
    0xa9f9b1cc8acdafd8ull,   // kshiftrq $1
    0xc6eeadbbcd6c9cb8ull,   // kshiftrq $3
    0x9616a8ade198213cull,   // kshiftrq $63
    0x6fab2eb4b9ff46cdull,   // kshiftrq $64
    0x2beaf2f7356f934full,   // kshiftrq $65
    0x6fab2eb4b9ff46cdull,   // kshiftrq $64
    0x3e9443c38bea5610ull,   // kshiftrq $255
    0xc84f6c52fd99a00full,   // ud kandw L0
    0x7a22df6fe4f51e18ull,   // ud kandw ok
    0x980e842932c98d52ull,   // ud kandw mem
    0x1042a2f6ec782045ull,   // ud knotw L1
    0x7a4888f48a095ed9ull,   // ud knotw vvvv
    0x7eee7b4829780ebfull,   // ud kmovw vvvv
    0x67382a6319b5bf94ull,   // ud kmovw st reg
    0x4a41a8df44f85acbull,   // ud kunpck 66 W1
    0xb0eb8c8a82054758ull,   // ud kmov 92 66 W1
    0x14393df8a437c429ull,   // ud kmov 92 0F W1
    0x818d371d04942997ull,   // ud kortestw L1
    0x782dbd1ec4af06e7ull,   // ud kshiftlw L1
    0x708ef68d21fc8859ull,   // ud kshift 30 pp0
    0xeb7ddb415140fb30ull,   // ud kaddw L0
    0x8086c780ad87e89cull,   // ud kshiftrw mem
};

static int run(void (*fn)(struct st *), struct st *t) {
    sig = 0;
    if (!sigsetjmp(jb, 1))
        fn(t);
    return sig;
}

int main(int argc, char **argv) {
    int print = argc > 1 && !strcmp(argv[1], "hashes"), dump = argc > 1 && !strcmp(argv[1], "dump");
    unsigned long checks = 0, bad = 0;
    static struct st t;
    signal(SIGILL, handler);
    signal(SIGSEGV, handler);
    for (int fi = 0; fi < NF; fi++) {
        uint64_t h = 0xcbf29ce484222325ull;
        rs = 0x9e3779b97f4a7c15ull;
        for (const char *c = forms[fi].name; *c; c++) rs = (rs ^ (uint8_t) *c) * 0x100000001b3ull;
        if (!rs) rs = 1;
        for (int k = 0; k < (forms[fi].ud ? 1 : 200); k++) {
            t.k1 = rnd(); t.k2 = rnd(); t.k3 = rnd(); t.gpr = rnd();
            if ((k & 7) == 1) t.k3 = t.k2;               /* equal, zero and all-ones operands */
            if ((k & 7) == 2) t.k2 = 0;
            if ((k & 7) == 3) { t.k2 = ~0ull; t.k3 = ~0ull; }
            if ((k & 7) == 4) t.k3 = ~t.k2;
            uint64_t r = rnd(); memcpy(t.m, &r, 8); r = rnd(); memcpy(t.m + 8, &r, 8);
            t.ok1 = t.ogpr = t.oflags = 0;
            int sg = run(forms[fi].fn, &t);
            uint64_t out[4] = {t.ok1, t.ogpr, t.oflags & 0x8d5, (uint64_t) sg};
            if (forms[fi].ud) { out[0] = out[1] = out[2] = 0; }
            if (!forms[fi].g64) out[1] &= 0xffffffffull;   /* (the i386 test has 32-bit GPRs) */
            for (int i = 0; i < 4; i++) for (int b = 0; b < 8; b++) h = (h ^ ((out[i] >> (8 * b)) & 0xff)) * 0x100000001b3ull;
            for (int i = 0; i < 16; i++) h = (h ^ t.m[i]) * 0x100000001b3ull;
            if (dump)
                printf("%s %d: k1 %016llx gpr %016llx flags %03llx sig %d m %016llx\n", forms[fi].name, k,
                       (unsigned long long) out[0], (unsigned long long) out[1], (unsigned long long) out[2], sg,
                       (unsigned long long) *(uint64_t *) t.m);
        }
        if (print) printf("%s %#llx\n", forms[fi].name, (unsigned long long) h);
        checks++;
        if (!print && !dump && h != want[fi] && bad++ < 40)
            printf("FAIL %s\n", forms[fi].name);
    }
    if (!print && !dump)
        printf("i386_avx512_kmask: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NF, checks, bad);
    return bad != 0;
}