#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_vex_fma.c, or with --i386 i386_vex_fma.c
# (usage: this script [--i386] [--answers FILE] OUT.c).
#
# FMA3, every op (VFMADD VFMSUB VFNMADD VFNMSUB VFMADDSUB VFMSUBADD x
# 132/213/231 x ps/pd/ss/sd), VEX.128 and VEX.256, register and memory,
# under five MXCSR modes (the roundings, FTZ, DAZ), on special and random
# operands: each op's results and MXCSR flags hashed and checked against
# the hashes an AMD Ryzen gives (camd: run the test with "hashes" to print
# them, and pass that output to the generator with --answers). "dump"
# prints every case, for diffing a failure against camd's.
import sys
I386 = '--i386' in sys.argv
args = [a for a in sys.argv[1:] if a != '--i386']
answers = {}
if '--answers' in args:
    i = args.index('--answers')
    for line in open(args[i + 1]):
        k, v = line.split()
        answers[k] = v
    del args[i:i + 2]
NAME = 'i386_vex_fma' if I386 else 'amd64_vex_fma'
FORMS = []
for form in (132, 213, 231):
    for op in ('madd', 'msub', 'nmadd', 'nmsub', 'maddsub', 'msubadd'):
        for t in ('ps', 'pd'):
            for L, x in ((256, 'ymm'), (128, 'xmm')):
                for mem in (0, 1):
                    FORMS.append((f'vf{op}{form}{t}', L, x, mem, t))
    for op in ('madd', 'msub', 'nmadd', 'nmsub'):
        for t in ('ss', 'sd'):
            for mem in (0, 1):
                FORMS.append((f'vf{op}{form}{t}', 128, 'xmm', mem, t))
MODES = [0x1f80, 0x3f80, 0x5f80, 0x7f80, 0x9fc0]
o = []; w = o.append
w(f'''// Generated by tools/gen-vex-fma-test.py{" --i386" if I386 else ""} -- do not edit.
//
// FMA3 against an AMD Ryzen's results and MXCSR flags, hashed per op and
// mode (see the generator).
#pragma GCC target("avx2,fma")
#include <stdint.h>
#include <stdio.h>
#include <string.h>
static uint64_t rs;
static uint64_t rnd(void) {{ rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }}
static void ldmx(unsigned v) {{ __asm__ volatile("ldmxcsr %0" :: "m"(v)); }}
static unsigned stmx(void) {{ unsigned v; __asm__ volatile("stmxcsr %0" : "=m"(v)); return v; }}
struct st {{ uint8_t a[32], b[32], d[32], out[32], m[64]; }} __attribute__((aligned(32)));
static const uint32_t sv[] = {{0, 0x80000000, 0x3f800000, 0xbf800000, 0x7f800000, 0xff800000, 0x7fc00000, 0xffc00001,
    0x7f800001, 0xff812345, 0x00000001, 0x807fffff, 0x00400000, 0x7f7fffff, 0x00800000, 0x00800001, 0x3f7fffff, 0x33800000}};
static const uint64_t dv[] = {{0, 0x8000000000000000ull, 0x3ff0000000000000ull, 0xbff0000000000000ull, 0x7ff0000000000000ull,
    0xfff0000000000000ull, 0x7ff8000000000000ull, 0xfff8000000000001ull, 0x7ff0000000000001ull, 0xfff0000012345678ull, 1,
    0x800fffffffffffffull, 0x0008000000000000ull, 0x7fefffffffffffffull, 0x0010000000000000ull, 0x0010000000000001ull,
    0x3fefffffffffffffull, 0x3ca0000000000000ull}};
static void fill(uint8_t *p, int n, int dbl) {{
    for (int i = 0; i < n; i += dbl ? 8 : 4) {{
        uint64_t r = rnd();
        if ((r & 3) == 0) {{
            if (dbl) {{ uint64_t v = dv[(r >> 8) % 18]; memcpy(p + i, &v, 8); }}
            else {{ uint32_t v = sv[(r >> 8) % 18]; memcpy(p + i, &v, 4); }}
        }} else if (dbl) {{
            uint64_t v = (r & 0x800fffffffffffffull) | ((uint64_t) (((r >> 52) % 64) + 990 + ((r >> 20) & 1 ? 0 : -40)) << 52);
            if ((r & 31) == 1) v = (v & 0x800fffffffffffffull) | (1ull << 52);
            memcpy(p + i, &v, 8);
        }} else {{
            uint32_t v = (uint32_t) (r & 0x807fffff) | (uint32_t) (((r >> 23) % 40 + 100 - ((r >> 40) & 1 ? 0 : 90)) << 23);
            if ((r & 31) == 1) v = (v & 0x807fffff) | (1u << 23);
            memcpy(p + i, &v, 4);
        }}
    }}
}}
''')
for i, (op, L, x, mem, t) in enumerate(FORMS):
    src = '128(%0)' if mem else f'%%{x}3'
    w(f'''__attribute__((noinline)) static void f{i}(struct st *t) {{
    __asm__ volatile("vmovdqu (%0), %%ymm2\\n vmovdqu 32(%0), %%ymm3\\n vmovdqu 64(%0), %%ymm1\\n"
                     "{op} {src}, %%{x}2, %%{x}1\\n vmovdqu %%ymm1, 96(%0)\\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}}''')
w('static const struct { const char *name; void (*fn)(struct st *); int L, mem, dbl; } forms[] = {')
for i, (op, L, x, mem, t) in enumerate(FORMS):
    w(f'    {{"{op} {L} {"mem" if mem else "reg"}", f{i}, {L}, {mem}, {1 if t.endswith("d") else 0}}},')
w('};')
w(f'#define NF {len(FORMS)}')
w(f'static const unsigned modes[] = {{{", ".join(hex(m) for m in MODES)}}};')
keys = [f'{i}.{mi}' for i in range(len(FORMS)) for mi in range(len(MODES))]
if answers:
    w('static const uint64_t want[NF][5] = {')
    for i in range(len(FORMS)):
        w('    {' + ', '.join(answers[f'{i}.{mi}'] + 'ull' for mi in range(len(MODES))) + '},')
    w('};')
else:
    w('static const uint64_t want[NF][5];   // (run with "hashes" on camd)')
w(r'''
int main(int argc, char **argv) {
    int print = argc > 1 && !strcmp(argv[1], "hashes"), dump = argc > 1 && !strcmp(argv[1], "dump");
    unsigned long checks = 0, bad = 0;
    static struct st t;
    for (int fi = 0; fi < NF; fi++) {
        for (int mi = 0; mi < 5; mi++) {
            uint64_t h = 0xcbf29ce484222325ull;
            rs = 0x9e3779b97f4a7c15ull ^ (uint64_t) fi * 0x100000001b3ull ^ (uint64_t) mi << 40;
            for (int k = 0; k < 300; k++) {
                fill(t.a, 32, forms[fi].dbl); fill(t.b, 32, forms[fi].dbl); fill(t.d, 32, forms[fi].dbl); fill(t.m, 64, forms[fi].dbl);
                ldmx(modes[mi]);
                forms[fi].fn(&t);
                unsigned f = stmx() & 0x3f;
                for (int i = 0; i < 32; i++) h = (h ^ t.out[i]) * 0x100000001b3ull;
                h = (h ^ f) * 0x100000001b3ull;
                if (dump) {
                    printf("%d %d %d:", fi, mi, k);
                    for (int i = 31; i >= 0; i--) printf("%02x", t.out[i]);
                    printf(" %x\n", f);
                }
            }
            if (print) printf("%d.%d %#llx\n", fi, mi, (unsigned long long) h);
            checks++;
            if (!print && !dump && h != want[fi][mi] && bad++ < 40)
                printf("FAIL %s, mxcsr %#x\n", forms[fi].name, modes[mi]);
        }
    }
    ldmx(0x1f80);
    if (!print && !dump)
        printf("NAME: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NF, checks, bad);
    return bad != 0;
}''')
open(args[0], 'w').write('\n'.join(o).replace('NAME: %s', NAME + ': %s'))
print(len(FORMS), 'forms')
