#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_pcmpstr.c (usage: this script OUT.c), or
# with --i386 tests/manual/x86/i386_pcmpstr.c: the same, built -m32, which
# also checks ESI, EDI and EBP come through.
#
# PCMPESTRI, PCMPESTRM, PCMPISTRI, PCMPISTRM (66 0F 3A 60-63): every imm8
# that matters (format, aggregation, polarity, index/mask selection: bits
# 0-6), register and memory forms, explicit lengths in range, past it and
# negative, strings with and without terminators -- against the SDM's
# algorithm written out in C, and real hardware (an AMD Ryzen): ECX or XMM0,
# and CF ZF SF OF (AF PF cleared).
import sys
I386 = '--i386' in sys.argv
ARGS = [a for a in sys.argv[1:] if a != '--i386']

o = []; w = o.append
w(r'''// Generated by tools/gen-amd64-pcmpstr-test.py -- do not edit.
//
// PCMPESTRI/ESTRM/ISTRI/ISTRM, imm bits 0-6 (format, aggregation, polarity,
// output selection), register and memory, lengths in range, past it and
// negative, against the SDM's algorithm and real hardware (an AMD Ryzen).
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static unsigned long checks, bad;
static void check(const char *what, int imm, long k, uint64_t got, uint64_t want) {
    checks++;
    if (got != want && bad++ < 40)
        printf("FAIL %s imm %#x (%ld): %#llx, want %#llx\n", what, imm, k, (unsigned long long) got, (unsigned long long) want);
}
static uint64_t rs = 0x243f6a8885a308d3ull;
static uint64_t rnd(void) { rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }

// element e of a 16-byte operand: bytes or words, signed or not
static int64_t el(const uint8_t *v, int words, int sgn, int e) {
    if (words) { uint16_t x; memcpy(&x, v + 2 * e, 2); return sgn ? (int16_t) x : x; }
    return sgn ? (int8_t) v[e] : v[e];
}
// the SDM: IntRes2, its valid length bookkeeping, the flags
static uint32_t model(const uint8_t *a, const uint8_t *b, int imm, int explicit_len, int64_t la, int64_t lb,
                      int *len1, int *len2) {
    int words = imm & 1, sgn = (imm >> 1) & 1, agg = (imm >> 2) & 3, pol = (imm >> 4) & 3;
    int n = words ? 8 : 16;
    int l1, l2;
    if (explicit_len) {
        int64_t x = la < 0 ? -la : la, y = lb < 0 ? -lb : lb;
        if (la == INT64_MIN) x = n;
        if (lb == INT64_MIN) y = n;
        l1 = x > n ? n : (int) x;
        l2 = y > n ? n : (int) y;
    } else {
        l1 = n; l2 = n;
        for (int i = 0; i < n; i++) if (el(a, words, 0, i) == 0) { l1 = i; break; }
        for (int i = 0; i < n; i++) if (el(b, words, 0, i) == 0) { l2 = i; break; }
    }
    *len1 = l1; *len2 = l2;
    uint32_t r1 = 0;
    for (int i = 0; i < n; i++) {                 // i: element of b (xmm2/m128), j: of a (xmm1)
        int bit = 0;
        if (agg == 0) {
            for (int j = 0; j < l1; j++) if (i < l2 && el(a, words, sgn, j) == el(b, words, sgn, i)) bit = 1;
        } else if (agg == 1) {
            for (int j = 0; j + 1 < n; j += 2)
                if (j + 1 < l1 && i < l2 && el(a, words, sgn, j) <= el(b, words, sgn, i) && el(b, words, sgn, i) <= el(a, words, sgn, j + 1))
                    bit = 1;
            // a lone lower bound (j valid, j+1 not) matches nothing
        } else if (agg == 2) {
            int va = i < l1, vb = i < l2;
            bit = !va && !vb ? 1 : va != vb ? 0 : el(a, words, sgn, i) == el(b, words, sgn, i);
        } else {
            bit = 1;
            for (int k = 0; k + i < n; k++) {
                int va = k < l1, vb = i + k < l2, eq;
                if (!va) eq = 1;
                else if (!vb) eq = 0;
                else eq = el(a, words, sgn, k) == el(b, words, sgn, i + k);
                bit &= eq;
            }
        }
        r1 |= (uint32_t) bit << i;
    }
    uint32_t full = (1u << n) - 1, r2 = r1;
    if (pol == 1) r2 = ~r1 & full;
    else if (pol == 3) r2 = r1 ^ (((1u << l2) - 1) & full);
    return r2;
}
''')
INSNS = [('pcmpestri', 1, 0), ('pcmpestrm', 1, 1), ('pcmpistri', 0, 0), ('pcmpistrm', 0, 1)]
if I386:
    # one operand, the state's address in EBX: ESI and EBP are set to known
    # values and read back, EDI is the memory operand's address
    w('struct st { uint8_t a[16], b[16], x0[16]; int32_t la, lb; uint32_t ecx, fl, esi, edi, ebp; };')
    for name, ex, mask in INSNS:
        for mem in (0, 1):
            src = '(%%edi)' if mem else '%%xmm2'
            w(f'__attribute__((noinline)) static void {name}{mem}(int imm, struct st *t) {{\n    switch (imm) {{')
            for imm in range(128):
                asm = (f'movdqu (%0), %%xmm1\\n movdqu 16(%0), %%xmm2\\n lea 16(%0), %%edi\\n mov 48(%0), %%eax\\n mov 52(%0), %%edx\\n'
                       f' movdqu 32(%0), %%xmm0\\n mov $0x5555, %%ecx\\n mov $0x13579bdf, %%esi\\n push %%ebp\\n mov $0x2468ace0, %%ebp\\n'
                       f' push $0x8d7\\n popfl\\n {name} ${imm}, {src}, %%xmm1\\n pushfl\\n pop 60(%0)\\n mov %%ebp, 72(%0)\\n pop %%ebp\\n'
                       f' mov %%ecx, 56(%0)\\n mov %%esi, 64(%0)\\n mov %%edi, 68(%0)\\n movdqu %%xmm0, 32(%0)')
                w(f'    case {imm}: __asm__ volatile("{asm}" :: "b"(t) : "memory", "cc", "eax", "ecx", "edx", "esi", "edi", "xmm0", "xmm1", "xmm2"); break;')
            w('    }\n}')
for name, ex, mask in ([] if I386 else INSNS):
    for mem in (0, 1):
        src = '(%%rdi)' if mem else '%%xmm2'
        w(f'''__attribute__((noinline)) static void {name}{mem}(int imm, uint8_t *a, uint8_t *b, int64_t la, int64_t lb, uint64_t *rcx, uint8_t *x0, uint64_t *fl) {{
    switch (imm) {{''')
        for imm in range(128):
            asm = (f'movdqu (%2), %%xmm1\\n movdqu (%3), %%xmm2\\n mov %3, %%rdi\\n mov %4, %%rax\\n mov %5, %%rdx\\n'
                   f' movdqu (%6), %%xmm0\\n mov $0x5555, %%ecx\\n push $0x8d7\\n popfq\\n {name} ${imm}, {src}, %%xmm1\\n'
                   f' pushfq\\n pop %1\\n mov %%rcx, %0\\n movdqu %%xmm0, (%6)')
            w(f'    case {imm}: __asm__ volatile("{asm}" : "=r"(*rcx), "=r"(*fl) : "r"(a), "r"(b), "r"(la), "r"(lb), "r"(x0) : "memory", "cc", "rax", "rcx", "rdx", "rdi", "xmm0", "xmm1", "xmm2"); break;')
        w('    }\n}')
w(r'''
int main(void) {
    static uint8_t a[16] __attribute__((aligned(16))), b[16] __attribute__((aligned(16))), x0[16], x0w[16];
    static void (*const fns[4][2])(int, uint8_t *, uint8_t *, int64_t, int64_t, uint64_t *, uint8_t *, uint64_t *) = {
        {pcmpestri0, pcmpestri1}, {pcmpestrm0, pcmpestrm1}, {pcmpistri0, pcmpistri1}, {pcmpistrm0, pcmpistrm1}};
    static const char *const names[4] = {"pcmpestri", "pcmpestrm", "pcmpistri", "pcmpistrm"};
    for (int k = 0; k < 120; k++) {
        for (int imm = 0; imm < 128; imm++) {
            // small alphabets so the compares match; nulls planted
            int alpha = 1 + (int) (rnd() % 6);
            for (int i = 0; i < 16; i++) { a[i] = (uint8_t) ('a' + rnd() % alpha); b[i] = (uint8_t) ('a' + rnd() % alpha); }
            if (k % 3 == 0) a[rnd() % 16] = 0;
            if (k % 3 == 1) b[rnd() % 16] = 0;
            if (k % 5 == 0) { a[0] = 'a'; a[1] = 'c'; a[2] = 'x'; a[3] = 'z'; }           // ranges
            if (k % 7 == 0) memcpy(b + rnd() % 8, a, 4);                                    // substrings
            int64_t la = (int64_t) (rnd() % 20) - 2, lb = (int64_t) (rnd() % 20) - 2;
            if (k % 11 == 0) la = -la * 3;
            if (k % 13 == 0) lb = INT64_MIN + (int64_t) (rnd() % 3);
            for (int f = 0; f < 4; f++) {
                int ex = f < 2, msk = f == 1 || f == 3;
                for (int mem = 0; mem < 2; mem++) {
                    for (int i = 0; i < 16; i++) x0[i] = (uint8_t) rnd();
                    memcpy(x0w, x0, 16);
                    uint64_t rcx = 0, fl = 0;
                    CALL;
                    int l1, l2;
                    // the explicit lengths: EAX/EDX, 32-bit (no REX.W here)
                    uint32_t r2 = model(a, b, imm, ex, (int32_t) la, (int32_t) lb, &l1, &l2);
                    int n = (imm & 1) ? 8 : 16;
                    uint64_t wf = 0x2 | (r2 ? 1 : 0) | (l2 < n ? 0x40 : 0) | (l1 < n ? 0x80 : 0) | ((r2 & 1) ? 0x800 : 0);
                    long id = k * 1000 + f * 10 + mem;
                    check(names[f], imm, id, fl & 0x8d5, wf & 0x8d5);
                    if (!msk) {
                        uint32_t idx = (uint32_t) n;
                        if (r2) idx = (imm & 0x40) ? 31 - (uint32_t) __builtin_clz(r2) : (uint32_t) __builtin_ctz(r2);
                        check(names[f], imm, id, rcx, idx);      // ECX written, RCX's top half zeroed
                        check(names[f], imm, id + 5000000, *(uint64_t *) x0, *(uint64_t *) x0w);
                    } else {
                        uint8_t want[16] = {0};
                        if (imm & 0x40) {
                            for (int i = 0; i < n; i++) if ((r2 >> i) & 1) memset(want + i * (16 / n), 0xff, 16 / n);
                        } else {
                            memcpy(want, &r2, 4);
                            if (n == 8) want[1] = 0;
                        }
                        uint64_t g0, g1, w0, w1;
                        memcpy(&g0, x0, 8); memcpy(&g1, x0 + 8, 8); memcpy(&w0, want, 8); memcpy(&w1, want + 8, 8);
                        check(names[f], imm, id, g0, w0);
                        check(names[f], imm, id, g1, w1);
                        check(names[f], imm, id + 7000000, rcx, 0x5555);
                    }
                }
            }
        }
    }
    printf("amd64_pcmpstr: %s (%lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", checks, bad);
    return bad != 0;
}''')
text = '\n'.join(o)
if I386:
    text = text.replace('Generated by tools/gen-amd64-pcmpstr-test.py', 'Generated by tools/gen-amd64-pcmpstr-test.py --i386')
    text = text.replace("// negative, against the SDM's algorithm and real hardware (an AMD Ryzen).",
                        "// negative, built -m32 (ESI, EDI, EBP kept), against the SDM's algorithm and\n// real hardware (an AMD Ryzen).")
    text = text.replace('#include <stdint.h>', '#pragma GCC target("sse4.2")\n#include <stdint.h>', 1)
    text = text.replace('    static void (*const fns[4][2])(int, uint8_t *, uint8_t *, int64_t, int64_t, uint64_t *, uint8_t *, uint64_t *) = {',
                        '    static struct st t __attribute__((aligned(16)));\n    static void (*const fns[4][2])(int, struct st *) = {')
    text = text.replace('INT64_MIN + (int64_t) (rnd() % 3)', 'INT32_MIN + (int64_t) (rnd() % 3)')
    text = text.replace('                    CALL;', '\n'.join([
        '                    memcpy(t.a, a, 16); memcpy(t.b, b, 16); memcpy(t.x0, x0, 16);',
        '                    t.la = (int32_t) la; t.lb = (int32_t) lb;',
        '                    fns[f][mem](imm, &t);',
        '                    memcpy(x0, t.x0, 16); rcx = t.ecx; fl = t.fl;',
        '                    check("esi", imm, k * 1000 + f * 10 + mem, t.esi, 0x13579bdf);',
        '                    check("ebp", imm, k * 1000 + f * 10 + mem, t.ebp, 0x2468ace0);',
        '                    check("edi", imm, k * 1000 + f * 10 + mem, t.edi, (uint32_t) (uintptr_t) t.b);']))
    text = text.replace('"amd64_pcmpstr: %s', '"i386_pcmpstr: %s')
else:
    text = text.replace('                    CALL;', '                    fns[f][mem](imm, a, b, la, lb, &rcx, x0, &fl);')
open(ARGS[0], 'w').write(text)
