#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_sse_tiny.c, or with --i386 i386_sse_tiny.c
# (usage: this script [--i386] [--answers FILE] OUT.c).
#
# Tininess at the bottom of the normal range. x86 decides it after rounding
# (to the precision, the exponent unbounded), so a result that rounds up to
# +-the smallest normal from just below it may or may not be tiny: that sets
# UE, and under FTZ flushes the result to a signed zero. MUL, DIV, the
# narrowing CVTs and the DP products (SSE and VEX), on operand pairs whose
# exact result lies just below +-minnorm, under the four roundings with FTZ
# off and on: each op's results and MXCSR flags hashed per mode and checked
# against the hashes an AMD Ryzen gives (camd: run the test with "hashes" to
# print them, and pass that output to the generator with --answers). "dump"
# prints every case, for diffing a failure against camd's.
import random, sys
from fractions import Fraction as F
I386 = '--i386' in sys.argv
args = [a for a in sys.argv[1:] if a != '--i386']
answers = {}
if '--answers' in args:
    i = args.index('--answers')
    for line in open(args[i + 1]):
        k, v = line.split()
        answers[k] = v
    del args[i:i + 2]
NAME = 'i386_sse_tiny' if I386 else 'amd64_sse_tiny'

random.seed(7)
def fr(b, eb, mb):                       # the value of a float's bits
    e = (b >> mb) & ((1 << eb) - 1); man = b & ((1 << mb) - 1)
    bias = (1 << (eb - 1)) - 1
    v = F(man + (1 << mb), 1 << mb) * F(2) ** (e - bias) if e else F(man, 1 << mb) * F(2) ** (1 - bias)
    return -v if b >> (eb + mb) else v
def near(tgt, eb, mb):                   # the floats around tgt (normal)
    bias = (1 << (eb - 1)) - 1
    e = 0
    while F(2) ** (e + 1) <= tgt: e += 1
    while F(2) ** e > tgt: e -= 1
    man = int(tgt / F(2) ** e * (1 << mb))
    return [((e + bias) << mb) | (mm - (1 << mb)) for mm in (man - 1, man, man + 1) if (1 << mb) <= mm < (2 << mb)]
def pairs(n, eb, mb, div):
    bias = (1 << (eb - 1)) - 1
    m = F(2) ** (1 - bias)
    out = []
    while len(out) < n:
        # mul: a in [2^-20, 2^-19), b near m / a; div: b in [1, 2), a near m * b
        x = (((bias - (0 if div else 20)) << mb) | random.getrandbits(mb))
        for y in near(m * fr(x, eb, mb) if div else m / fr(x, eb, mb), eb, mb):
            a, b = (y, x) if div else (x, y)
            r = fr(a, eb, mb) / fr(b, eb, mb) if div else fr(a, eb, mb) * fr(b, eb, mb)
            if m * (1 - F(1, 1 << mb)) < r < m:
                out.append((a, b))
    return out[:n]
CASES = []
for a, b in pairs(24, 8, 23, 0): CASES.append(('s', a ^ (random.getrandbits(1) << 31), b))
for a, b in pairs(16, 8, 23, 1): CASES.append(('S', a, b))
for a, b in pairs(16, 11, 52, 0): CASES.append(('d', a ^ (random.getrandbits(1) << 63), b))
for a, b in pairs(12, 11, 52, 1): CASES.append(('D', a, b))
import struct
for k in (1, 2, 3, 1 << 20, 1 << 28, (1 << 29) - 1, 1 << 29, (1 << 29) + 1, 1 << 30):
    x = 2.0 ** -126 * (1 - k * 2.0 ** -53)
    for v in (x, -x):
        CASES.append(('c', struct.unpack('<Q', struct.pack('<d', v))[0], 0))
OPS = [  # kind, name, lane, zero fill, insn
    ('s', 'mulss', 0, 0, 'mulss %%xmm1,%%xmm0'), ('s', 'mulps', 3, 0, 'mulps %%xmm1,%%xmm0'),
    ('s', 'vmulss', 0, 0, 'vmulss %%xmm1,%%xmm0,%%xmm0'), ('s', 'vmulps', 6, 0, 'vmulps %%ymm1,%%ymm0,%%ymm0'),
    ('s', 'mulps m', 1, 0, 'mulps 32(%1),%%xmm0'), ('s', 'vmulps m', 2, 0, 'vmulps 32(%1),%%ymm0,%%ymm0'),
    ('s', 'dpps', 2, 1, 'dpps $0xf1,%%xmm1,%%xmm0'), ('s', 'vdpps', 5, 1, 'vdpps $0xf1,%%ymm1,%%ymm0,%%ymm0'),
    ('S', 'divss', 0, 0, 'divss %%xmm1,%%xmm0'), ('S', 'divps', 2, 0, 'divps %%xmm1,%%xmm0'),
    ('S', 'vdivss', 0, 0, 'vdivss %%xmm1,%%xmm0,%%xmm0'), ('S', 'vdivps', 5, 0, 'vdivps %%ymm1,%%ymm0,%%ymm0'),
    ('d', 'mulsd', 0, 0, 'mulsd %%xmm1,%%xmm0'), ('d', 'mulpd', 1, 0, 'mulpd %%xmm1,%%xmm0'),
    ('d', 'vmulpd', 3, 0, 'vmulpd %%ymm1,%%ymm0,%%ymm0'), ('d', 'dppd', 1, 1, 'dppd $0x31,%%xmm1,%%xmm0'),
    ('D', 'divsd', 0, 0, 'divsd %%xmm1,%%xmm0'), ('D', 'divpd', 1, 0, 'divpd %%xmm1,%%xmm0'),
    ('D', 'vdivpd', 2, 0, 'vdivpd %%ymm1,%%ymm0,%%ymm0'),
    ('c', 'cvtsd2ss', 0, 0, 'cvtsd2ss %%xmm0,%%xmm0'), ('c', 'cvtpd2ps', 1, 0, 'cvtpd2ps %%xmm0,%%xmm0'),
    ('c', 'vcvtpd2ps', 3, 0, 'vcvtpd2psy %%ymm0,%%xmm0'), ('c', 'vcvtsd2ss', 0, 0, 'vcvtsd2ss %%xmm0,%%xmm0,%%xmm0'),
]
MODES = [0x1f80 | rc << 13 | ftz << 15 for ftz in (0, 1) for rc in range(4)]
o = []; w = o.append
w(f'''// Generated by tools/gen-sse-tiny-test.py{" --i386" if I386 else ""} -- do not edit.
//
// Results that round up to +-the smallest normal: UE and FTZ by x86's
// after-rounding tininess, against an AMD Ryzen's results and MXCSR flags,
// hashed per op and mode (see the generator).
#pragma GCC target("avx")
#include <stdint.h>
#include <stdio.h>
#include <string.h>
static const struct {{ char k; uint64_t a, b; }} cases[] = {{''')
for k, a, b in CASES:
    w(f"    {{'{k}', {a:#x}ull, {b:#x}ull}},")
w('};')
w(f'#define NC {len(CASES)}')
w('struct st { uint8_t x[32], y[32], o[32]; unsigned mx, st; } __attribute__((aligned(32)));')
for i, (k, name, lane, z, insn) in enumerate(OPS):
    w(f'''__attribute__((noinline)) static void f{i}(struct st *t) {{
    __asm__ volatile("vmovdqu (%1), %%ymm0\\n vmovdqu 32(%1), %%ymm1\\n ldmxcsr 96(%1)\\n {insn}\\n"
                     "stmxcsr 100(%1)\\n vmovdqu %%ymm0, 64(%1)\\n vzeroupper" : "=m"(*t) : "r"(t) : "memory", "xmm0", "xmm1");
}}''')
w('static const struct { const char *name; void (*fn)(struct st *); char k; int lane, zero; } ops[] = {')
for i, (k, name, lane, z, insn) in enumerate(OPS):
    w(f'    {{"{name}", f{i}, \'{k}\', {lane}, {z}}},')
w('};')
w(f'#define NO {len(OPS)}')
w(f'static const unsigned modes[] = {{{", ".join(hex(m) for m in MODES)}}};')
if answers:
    w('static const uint64_t want[NO][8] = {')
    for i in range(len(OPS)):
        w('    {' + ', '.join(answers[f'{i}.{mi}'] + 'ull' for mi in range(len(MODES))) + '},')
    w('};')
else:
    w('static const uint64_t want[NO][8];   // (run with "hashes" on camd)')
w(r'''
int main(int argc, char **argv) {
    int print = argc > 1 && !strcmp(argv[1], "hashes"), dump = argc > 1 && !strcmp(argv[1], "dump");
    unsigned long checks = 0, bad = 0;
    static struct st t;
    for (int oi = 0; oi < NO; oi++) {
        int dbl = ops[oi].k != 's' && ops[oi].k != 'S';
        for (int mi = 0; mi < 8; mi++) {
            uint64_t h = 0xcbf29ce484222325ull;
            for (int c = 0; c < NC; c++) {
                if (cases[c].k != ops[oi].k) continue;
                for (int l = 0; l < (dbl ? 4 : 8); l++) {
                    if (dbl) { double v = ops[oi].zero ? 0 : 1; memcpy(t.x + 8 * l, &v, 8); memcpy(t.y + 8 * l, &v, 8); }
                    else { float v = ops[oi].zero ? 0 : 1; memcpy(t.x + 4 * l, &v, 4); memcpy(t.y + 4 * l, &v, 4); }
                }
                int L = ops[oi].lane;
                if (dbl) { memcpy(t.x + 8 * L, &cases[c].a, 8); memcpy(t.y + 8 * L, &cases[c].b, 8); }
                else { uint32_t a = cases[c].a, b = cases[c].b; memcpy(t.x + 4 * L, &a, 4); memcpy(t.y + 4 * L, &b, 4); }
                t.mx = modes[mi];
                ops[oi].fn(&t);
                unsigned f = t.st & 0x3f;
                for (int i = 0; i < 32; i++) h = (h ^ t.o[i]) * 0x100000001b3ull;
                h = (h ^ f) * 0x100000001b3ull;
                if (dump) {
                    printf("%s %#x %d:", ops[oi].name, modes[mi], c);
                    for (int i = 31; i >= 0; i--) printf("%02x", t.o[i]);
                    printf(" %02x\n", f);
                }
            }
            if (print) printf("%d.%d %#llx\n", oi, mi, (unsigned long long) h);
            checks++;
            if (!print && !dump && h != want[oi][mi] && bad++ < 40)
                printf("FAIL %s, mxcsr %#x\n", ops[oi].name, modes[mi]);
        }
    }
    if (!print && !dump)
        printf("NAME: %s (%d ops, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NO, checks, bad);
    return bad != 0;
}''')
open(args[0], 'w').write('\n'.join(o).replace('NAME: %s', NAME + ': %s'))
print(len(CASES), 'cases', len(OPS), 'ops')
