#!/usr/bin/env python3
"""Generate the syscall numbers a natively-compiled program can issue.

Why this is generated
---------------------
kernel/native_syscall.h used to carry a hand-written enum holding "only what
the shim uses". That is the same shape of mistake tools/check-native-libc.py
exists to prevent: a list of what somebody thought of. It went stale --
77 numbers named against 217 syscalls AOK actually implements -- so the second
native program (bash) found 140 kernel calls it could not reach, none of which
were missing for any reason except that nobody had needed them yet.

The syscall table IS the completeness oracle. So the numbers come from it, and
this runs at build time: the header cannot drift from the kernel it sits on,
and adding a syscall to AOK makes it reachable from native code the same day
with nothing to remember.

What is safe here and what is not
---------------------------------
The NUMBER always comes from kernel/calls.c's arm64 table, so it cannot be
wrong. The NAME is derived from the handler AOK chose (sys_fchmod -> fchmod),
which is a readability aid rather than an ABI fact -- a bad name is a confusing
identifier, never a call landing somewhere unintended. Where derivation would
be misleading, OVERRIDES below says so explicitly, and where two numbers share
a handler it is an error unless OVERRIDES resolves it. That is deliberate: the
new entry has to be looked at by a person once.

Stub entries are excluded. An unimplemented syscall should fail as ENOSYS
through the dispatcher, not look reachable in a header.

Usage:
  gen-native-syscalls.py <kernel/calls.c> <output.h>
  gen-native-syscalls.py <kernel/calls.c> --list      # numbers and names
"""
import re
import sys
from collections import Counter

# Handlers that stand in for "not implemented"; see the module docstring.
STUBS = {"syscall_stub", "syscall_stub_silent", "syscall_success_stub"}

# Suffixes AOK puts on a handler to say which struct shape it speaks, not which
# syscall it is. Stripped for the name only.
SUFFIXES = ("_amd64", "_guest", "_off_pair", "_pair")

# Where the handler name does not give the syscall's name. Every entry is here
# because a person checked it, and the reason is recorded.
OVERRIDES = {
    61:  "getdents64",   # sys_getdents is the 64-bit form at this number
    72:  "pselect6",     # the six-argument spelling, as the shim already calls it
    83:  "fdatasync",    # shares sys_fsync with 82; calls.c says so at the entry
    174: "getuid",       # sys_getuid32 is the 32-bit-uid handler, not the name
    175: "geteuid",
    176: "getgid",
    177: "getegid",
    193: "semop",        # shares sys_semtimedop with 192; "semop = semtimedop
                         # without timeout" per calls.c
    439: "faccessat2",   # shares sys_faccessat with 48; calls.c labels it so on
                         # the i386 table. Takes a flags argument 48 does not.
}

# Handlers whose struct layout follows the CALLING TASK's ABI rather than the
# asm-generic one, so a native caller -- which always speaks asm-generic -- has
# to marshal deliberately. Named by handler because that is what carries the
# property. See the block comment in kernel/native_syscall.h.
ABI_SENSITIVE_HANDLERS = ("_amd64", "_guest", "_off_pair")


def parse_table(path):
    src = open(path).read()
    m = re.search(r"static syscall_t arm64_syscall_table\[\d+\] = \{(.*?)\n\};",
                  src, re.S)
    if m is None:
        raise SystemExit("gen-native-syscalls: arm64_syscall_table not found in "
                         + path)
    table = {}
    for entry in re.finditer(r"\[(\d+)\]\s*=\s*\(syscall_t\)\s*([A-Za-z_]\w*)",
                             m.group(1)):
        table[int(entry.group(1))] = entry.group(2)
    return table


def derive(handler):
    name = handler[4:] if handler.startswith("sys_") else handler
    for suffix in SUFFIXES:
        if name.endswith(suffix):
            name = name[:-len(suffix)]
            break
    return name


def build(table):
    calls = {}
    for num, handler in sorted(table.items()):
        if handler in STUBS:
            continue
        calls[num] = (OVERRIDES.get(num) or derive(handler), handler)

    clashes = [n for n, c in Counter(n for n, _ in calls.values()).items() if c > 1]
    if clashes:
        offenders = sorted(num for num, (name, _) in calls.items()
                           if name in clashes)
        raise SystemExit(
            "gen-native-syscalls: two syscalls would get the same name "
            + ", ".join(sorted(clashes))
            + "\n  at numbers: " + ", ".join(str(n) for n in offenders)
            + "\n  Add an entry to OVERRIDES naming each one, with the reason.")
    return calls


HEADER = """\
/* GENERATED by tools/gen-native-syscalls.py from kernel/calls.c -- do not edit.
 *
 * Every syscall AOK genuinely implements on the asm-generic (arm64) table, so
 * that a native program can reach all of the kernel rather than the part
 * somebody happened to need. Stubs are left out: an unimplemented call should
 * fail as ENOSYS through the dispatcher, not look available here.
 *
 * The numbering is asm-generic WHATEVER the calling task's guest ABI --
 * syscall_dispatch_native (kernel/calls.c) is what makes that true. Handlers
 * marked "ABI" below are the exception to watch: their struct layout follows
 * current->abi, so a native caller has to marshal the shape the task expects
 * rather than assuming the 64-bit one.
 */
#ifndef KERNEL_NATIVE_SYSCALL_NUMS_H
#define KERNEL_NATIVE_SYSCALL_NUMS_H

enum {
"""

FOOTER = """};

#endif
"""


def emit(calls):
    out = [HEADER]
    for num, (name, handler) in sorted(calls.items()):
        note = "  // ABI" if any(handler.endswith(s)
                                 for s in ABI_SENSITIVE_HANDLERS) else ""
        out.append(f"    NATIVE_SYS_{name} = {num},{note}\n")
    out.append(FOOTER)
    return "".join(out)


def main(argv):
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    calls = build(parse_table(argv[1]))
    if argv[2] == "--list":
        for num, (name, handler) in sorted(calls.items()):
            print(f"{num:4d} {name:<28} {handler}")
        print(f"\n{len(calls)} syscalls reachable from native code")
        return 0
    text = emit(calls)
    # Only rewrite when the content changes, so ninja does not rebuild the world
    # on every configure.
    try:
        if open(argv[2]).read() == text:
            return 0
    except OSError:
        pass
    open(argv[2], "w").write(text)
    return 0


sys.exit(main(sys.argv))
