#!/usr/bin/env python3
"""Write tests/manual/riscv64/rcache_run.c: random straight-line RV64I/M ALU
sequences with their expected results computed here, by a Python model of the
ISA -- an oracle independent of the emulator -- for the register-cached runs
(gen.c gen_riscv64_try_rcache_run, jit/guest-riscv64/rcache.S).

    python3 tools/gen-rv-rcache-test.py [OUTPUT]

Each case loads six registers, runs 1-24 instructions over them (sometimes
more than the cache's four registers, so runs split; x0 as a source and as
a destination; immediates at their edges) and stores the six back. Fixed seed:
the output is deterministic.
"""

import random
import sys

M = (1 << 64) - 1
REGS = ['t0', 't1', 't2', 'a2', 'a3', 'a4']

def s64(v):
    v &= M
    return v - (1 << 64) if v >> 63 else v

def sx32(v):
    v &= 0xffffffff
    return (v - (1 << 32) if v >> 31 else v) & M

RR = {
    'add': lambda a, b: a + b,
    'sub': lambda a, b: a - b,
    'sll': lambda a, b: a << (b & 63),
    'slt': lambda a, b: int(s64(a) < s64(b)),
    'sltu': lambda a, b: int(a < b),
    'xor': lambda a, b: a ^ b,
    'srl': lambda a, b: a >> (b & 63),
    'sra': lambda a, b: s64(a) >> (b & 63),
    'or': lambda a, b: a | b,
    'and': lambda a, b: a & b,
    'mul': lambda a, b: a * b,
    'mulh': lambda a, b: (s64(a) * s64(b)) >> 64,
    'mulhu': lambda a, b: (a * b) >> 64,
    'addw': lambda a, b: sx32(a + b),
    'subw': lambda a, b: sx32(a - b),
    'sllw': lambda a, b: sx32(a << (b & 31)),
    'srlw': lambda a, b: sx32((a & 0xffffffff) >> (b & 31)),
    'sraw': lambda a, b: sx32(s64(sx32(a)) >> (b & 31)),
    'mulw': lambda a, b: sx32(a * b),
}
RI = {
    'addi': (lambda a, i: a + i, (-2048, 2047)),
    'slti': (lambda a, i: int(s64(a) < i), (-2048, 2047)),
    'sltiu': (lambda a, i: int(a < (i & M)), (-2048, 2047)),
    'xori': (lambda a, i: a ^ (i & M), (-2048, 2047)),
    'ori': (lambda a, i: a | (i & M), (-2048, 2047)),
    'andi': (lambda a, i: a & (i & M), (-2048, 2047)),
    'slli': (lambda a, i: a << i, (0, 63)),
    'srli': (lambda a, i: a >> i, (0, 63)),
    'srai': (lambda a, i: s64(a) >> i, (0, 63)),
    'addiw': (lambda a, i: sx32(a + i), (-2048, 2047)),
    'slliw': (lambda a, i: sx32(a << i), (0, 31)),
    'srliw': (lambda a, i: sx32((a & 0xffffffff) >> i), (0, 31)),
    'sraiw': (lambda a, i: sx32(s64(sx32(a)) >> i), (0, 31)),
}

EDGES = [0, 1, M, 1 << 63, (1 << 63) - 1, 0xffffffff, 0x80000000, 0x7fffffff, 0x100000000,
         0x123456789abcdef0, 0xfedcba9876543210]

def val(rng):
    return rng.choice(EDGES) if rng.random() < 0.4 else rng.getrandbits(64)

def imm(rng, lo, hi):
    return rng.choice([lo, hi, 0, 1, -1 if lo < 0 else 1, rng.randint(lo, hi)])

def main():
    rng = random.Random(0x5eed)
    cases = []
    for c in range(320):
        # A narrow register pool for most cases (fits the cache), all six for some.
        pool = REGS[:rng.choice([2, 3, 4, 4, 4, 5, 6])]
        regs = {r: val(rng) for r in REGS}
        init = dict(regs)
        lines = []
        for _ in range(rng.randint(1, 24)):
            k = rng.random()
            src = lambda: 'zero' if rng.random() < 0.08 else rng.choice(pool)
            rd = 'zero' if rng.random() < 0.04 else rng.choice(pool)
            get = lambda r: 0 if r == 'zero' else regs[r]
            if k < 0.5:
                op = rng.choice(list(RR))
                a, b = src(), src()
                v = RR[op](get(a), get(b))
                lines.append('%s %s, %s, %s' % (op, rd, a, b))
            elif k < 0.88:
                op = rng.choice(list(RI))
                fn, (lo, hi) = RI[op]
                a, i = src(), imm(rng, lo, hi)
                v = fn(get(a), i)
                lines.append('%s %s, %s, %d' % (op, rd, a, i))
            elif k < 0.94:
                i = rng.randint(0, 0xfffff)
                v = sx32(i << 12)
                lines.append('lui %s, %#x' % (rd, i))
            elif k < 0.97:
                i = rng.randint(-2048, 2047)
                v = i
                lines.append('li %s, %d' % (rd, i))
            else:
                a = src()
                v = get(a)
                lines.append('mv %s, %s' % (rd, a))
            if rd != 'zero':
                regs[rd] = v & M
        cases.append((init, lines, dict(regs)))

    o = []
    o.append('// GENERATED by tools/gen-rv-rcache-test.py -- do not edit; edit the generator.')
    o.append('//')
    o.append('// riscv64 register-cached runs (gen.c gen_riscv64_try_rcache_run, the "rcache"')
    o.append('// bit of /proc/ish/riscv64_jit_fuse): random straight-line ALU sequences whose')
    o.append('// expected results the generator computed with its own model of RV64I/M. Each')
    o.append('// case runs twice (the second time from the translated block). The bit is off')
    o.append('// by default, so the test turns it on (as root) and puts it back afterwards;')
    o.append('// run with ISH_RCACHE_TEST_OFF=1 to check the uncached gadgets instead.')
    o.append('#include <stdint.h>')
    o.append('#include <stdio.h>')
    o.append('#include <stdlib.h>')
    o.append('#include <string.h>')
    o.append('')
    o.append('#if defined(__riscv) && __riscv_xlen == 64')
    o.append('')
    load = ''.join('"ld %s, %d(%%0)\\n"' % (r, 8 * i) for i, r in enumerate(REGS))
    store = ''.join('"sd %s, %d(%%0)\\n"' % (r, 8 * i) for i, r in enumerate(REGS))
    clob = ', '.join('"%s"' % r for r in REGS)
    for i, (init, lines, _) in enumerate(cases):
        body = ''.join('"%s\\n"' % l for l in lines)
        o.append('static void case_%d(uint64_t *r) {' % i)
        o.append('    __asm__ volatile(%s' % load)
        o.append('                     %s' % body)
        o.append('                     %s' % store)
        o.append('                     :: "r"(r) : %s, "memory");' % clob)
        o.append('}')
    o.append('')
    o.append('static const struct { void (*fn)(uint64_t *); uint64_t in[6], want[6]; } cases[] = {')
    for i, (init, _, want) in enumerate(cases):
        o.append('    {case_%d, {%s}, {%s}},' % (i, ', '.join('%#xull' % init[r] for r in REGS),
                                               ', '.join('%#xull' % want[r] for r in REGS)))
    o.append('};')
    o.append('')
    o.append('// auipc reads the pc: two adjacent ones differ by exactly 4, and the run')
    o.append('// around them must keep that.')
    o.append('static uint64_t auipc_case(void) {')
    o.append('    uint64_t d;')
    o.append('    __asm__ volatile(".option push\\n .option norvc\\n auipc t0, 0\\n auipc t1, 0\\n"')
    o.append('                     " sub t2, t1, t0\\n addi t2, t2, 1\\n slli %0, t2, 2\\n .option pop"')
    o.append('                     : "=r"(d) :: "t0", "t1", "t2");')
    o.append('    return d;')
    o.append('}')
    o.append('')
    o.append('#define FUSE_NODE "/proc/ish/riscv64_jit_fuse"')
    o.append('// The node\'s "rcache on|off" line: 1, 0, or -1 when unreadable.')
    o.append('static int rcache_state(void) {')
    o.append('    FILE *f = fopen(FUSE_NODE, "r");')
    o.append('    char line[64];')
    o.append('    int on = -1;')
    o.append('    while (f != NULL && fgets(line, sizeof(line), f) != NULL)')
    o.append('        if (strncmp(line, "rcache ", 7) == 0)')
    o.append('            on = strncmp(line + 7, "on", 2) == 0;')
    o.append('    if (f != NULL)')
    o.append('        fclose(f);')
    o.append('    return on;')
    o.append('}')
    o.append('static void rcache_set(int on) {')
    o.append('    FILE *f = fopen(FUSE_NODE, "w");')
    o.append('    if (f != NULL) {')
    o.append('        fprintf(f, "rcache=%d\\n", on);')
    o.append('        fclose(f);')
    o.append('    }')
    o.append('}')
    o.append('')
    o.append('int main(void) {')
    o.append('    int fails = 0, n = sizeof(cases) / sizeof(cases[0]);')
    o.append('    int was = rcache_state(), want = getenv("ISH_RCACHE_TEST_OFF") == NULL;')
    o.append('    if (was >= 0 && was != want)')
    o.append('        rcache_set(want);')
    o.append('    if (was >= 0 && rcache_state() != want)')
    o.append('        printf("note: could not set rcache=%d (not root?)\\n", want);')
    o.append('    for (int i = 0; i < n; i++) {')
    o.append('        for (int rep = 0; rep < 2; rep++) {')
    o.append('            uint64_t r[6];')
    o.append('            for (int j = 0; j < 6; j++)')
    o.append('                r[j] = cases[i].in[j];')
    o.append('            cases[i].fn(r);')
    o.append('            for (int j = 0; j < 6; j++)')
    o.append('                if (r[j] != cases[i].want[j]) {')
    o.append('                    printf("FAIL: case %d rep %d reg %d: %#llx want %#llx\\n", i, rep, j,')
    o.append('                           (unsigned long long) r[j], (unsigned long long) cases[i].want[j]);')
    o.append('                    fails++;')
    o.append('                }')
    o.append('        }')
    o.append('    }')
    o.append('    uint64_t a = auipc_case();')
    o.append('    if (a != 20) {')
    o.append('        printf("FAIL: auipc run gave %llu, want 20\\n", (unsigned long long) a);')
    o.append('        fails++;')
    o.append('    }')
    o.append('    if (was >= 0 && was != want)')
    o.append('        rcache_set(was);')
    o.append('    printf("rcache_run: %s (%d cases, rcache %s)\\n", fails ? "FAIL" : "PASS", n + 1,')
    o.append('           want ? "on" : "off");')
    o.append('    return fails != 0;')
    o.append('}')
    o.append('')
    o.append('#else')
    o.append('int main(void) {')
    o.append('    printf("rcache_run: SKIP (riscv64 only)\\n");')
    o.append('    return 0;')
    o.append('}')
    o.append('#endif')
    path = sys.argv[1] if len(sys.argv) > 1 else 'tests/manual/riscv64/rcache_run.c'
    with open(path, 'w') as f:
        f.write('\n'.join(o) + '\n')

main()
