#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_vex_f16c.c, or with --i386 i386_vex_f16c.c
# (usage: this script [--i386] [--answers FILE] OUT.c).
#
# F16C: VCVTPH2PS on every half (xmm and ymm, register and memory) and
# VCVTPS2PH on special, boundary and random singles under all eight imm8
# rounding controls (xmm and ymm sources, a register or memory destination),
# under the MXCSR roundings, FTZ and DAZ: each form's results and MXCSR flags
# hashed per mode and checked against the hashes an AMD Ryzen gives (camd:
# run the test with "hashes" to print them, and pass that output to the
# generator with --answers). "dump" prints every case, for diffing a failure
# against camd's. Also fixed checks, as camd gives them: VEX.W1 and a vvvv
# other than 1111b are #UD, and a VCVTPS2PH whose store faults leaves MXCSR
# as it was (read from the signal frame: the handler starts with a fresh
# MXCSR) -- with a control whose earlier inexact op does show.
import sys
I386 = '--i386' in sys.argv
args = [a for a in sys.argv[1:] if a != '--i386']
answers = {}
if '--answers' in args:
    i = args.index('--answers')
    for line in open(args[i + 1]):
        k, v = line.split()
        answers[k] = v
    del args[i:i + 2]
NAME = 'i386_vex_f16c' if I386 else 'amd64_vex_f16c'
FORMS = []   # (asm, kind 0 ph2ps / 1 ps2ph, L, mem)
for L, x in ((128, 'xmm'), (256, 'ymm')):
    FORMS.append((f'vcvtph2ps %%xmm3, %%{x}1', 0, L, 0))
    FORMS.append((f'vcvtph2ps 32(%0), %%{x}1', 0, L, 1))
for imm in range(8):
    for L, x in ((128, 'xmm'), (256, 'ymm')):
        FORMS.append((f'vcvtps2ph ${imm}, %%{x}3, %%xmm1', 1, L, 0))
        FORMS.append((f'vcvtps2ph ${imm}, %%{x}3, 64(%0)', 1, L, 1))
MODES = [0x1f80, 0x3f80, 0x5f80, 0x7f80, 0x9f80, 0x1fc0, 0x9fc0]
o = []; w = o.append
w(f'''// Generated by tools/gen-vex-f16c-test.py{" --i386" if I386 else ""} -- do not edit.
//
// F16C against an AMD Ryzen's results and MXCSR flags, hashed per form and
// mode (see the generator).
#pragma GCC target("avx2,f16c")
#define _GNU_SOURCE
#include <setjmp.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <ucontext.h>
#include <sys/mman.h>
static uint64_t rs;
static uint64_t rnd(void) {{ rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }}
struct st {{ uint8_t a[32], b[32], d[32], out[32]; unsigned mx, f; }} __attribute__((aligned(32)));
static const uint32_t sv[] = {{0, 0x80000000, 0x3f800000, 0xbf800000, 0x7f800000, 0xff800000, 0x7fc00000, 0xffc00001,
    0x7f800001, 0xff812345, 0x7fbfffff, 0x7fc01fff, 0x00000001, 0x807fffff, 0x00400000, 0x00800000,
    0x477fe000, 0x477fefff, 0x477ff000, 0x477ff001, 0x477fffff, 0x47800000, 0xc77ff000, 0x7f7fffff,
    0x38800000, 0x387fffff, 0x387ff000, 0x387fefff, 0x387ff001, 0xb87ff000, 0x33800000, 0x337fffff,
    0x33000000, 0x33000001, 0x32ffffff, 0xb3000000, 0x33c00000, 0x3f801000, 0x3f803000, 0x3f801001}};
#define NSV (sizeof sv / sizeof *sv)
static uint32_t single(void) {{
    uint64_t r = rnd();
    switch (r & 7) {{
    case 0: return sv[(r >> 8) % NSV];
    case 1: case 2: {{          /* a tie or near-tie at the half's precision */
        uint32_t v = (uint32_t) (r >> 16) & 0x807fe000;
        v |= (uint32_t) ((r >> 40) % 44 + 96) << 23;
        int k = (r >> 60) & 3;
        return v | (k == 0 ? 0x1000 : k == 1 ? 0xfff : k == 2 ? 0x1001 : (uint32_t) (r >> 20) & 0x1fff);
    }}
    default: {{                 /* across the half's range and past it */
        uint32_t v = (uint32_t) (r >> 16) & 0x807fffff;
        return v | (uint32_t) ((r >> 40) % 56 + 90) << 23;
    }}
    }}
}}
''')
for i, (asm, kind, L, mem) in enumerate(FORMS):
    w(f'''__attribute__((noinline)) static void f{i}(struct st *t) {{
    __asm__ volatile("vmovdqu (%0), %%ymm1\\n vmovdqu 32(%0), %%ymm3\\n ldmxcsr 128(%0)\\n {asm}\\n"
                     "stmxcsr 132(%0)\\n vmovdqu %%ymm1, 96(%0)\\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm3");
}}''')
w('static const struct { const char *name; void (*fn)(struct st *); int kind, L, mem; } forms[] = {')
for i, (asm, kind, L, mem) in enumerate(FORMS):
    nm = asm.replace('%%', '').replace('(%0)', '(m)')
    w(f'    {{"{nm}", f{i}, {kind}, {L}, {mem}}},')
w('};')
w(f'#define NF {len(FORMS)}')
w(f'#define NM {len(MODES)}')
w(f'static const unsigned modes[] = {{{", ".join(hex(m) for m in MODES)}}};')
if answers:
    w('static const uint64_t want[NF][NM] = {')
    for i in range(len(FORMS)):
        w('    {' + ', '.join(answers[f'{i}.{mi}'] + 'ull' for mi in range(len(MODES))) + '},')
    w('};')
else:
    w('static const uint64_t want[NF][NM];   // (run with "hashes" on camd)')
w(r'''
static sigjmp_buf jb;
static volatile int sig;
static volatile unsigned fmx;
static void handler(int s, siginfo_t *si, void *ucv) {
    ucontext_t *uc = ucv;
    const unsigned char *fp = (const unsigned char *) uc->uc_mcontext.fpregs;
    (void) si;
    sig = s;
#ifdef __x86_64__
    memcpy((void *) &fmx, fp + 24, 4);
#else
    memcpy((void *) &fmx, fp + 136, 4);           /* past the legacy area, magic 0 */
#endif
    siglongjmp(jb, 1);
}
#define TRY(i, bytes) do { sig = 0; if (!sigsetjmp(jb, 1)) __asm__ volatile(bytes ::: "xmm0", "xmm1"); got[i] = sig; } while (0)
static unsigned long fixed_checks(unsigned long *checks) {
    unsigned long bad = 0;
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_sigaction = handler;
    sa.sa_flags = SA_SIGINFO;
    sigaction(SIGILL, &sa, 0);
    sigaction(SIGSEGV, &sa, 0);
    static const struct { const char *name; int sig; } ud[] = {
        {"vcvtps2ph W0", 0}, {"vcvtps2ph W1", SIGILL}, {"vcvtph2ps W0", 0}, {"vcvtph2ps W1", SIGILL},
        {"vcvtps2ph vvvv 1101b", SIGILL},
    };
    volatile int got[5];
    TRY(0, ".byte 0xc4,0xe3,0x79,0x1d,0xc1,0x00");
    TRY(1, ".byte 0xc4,0xe3,0xf9,0x1d,0xc1,0x00");
    TRY(2, ".byte 0xc4,0xe2,0x79,0x13,0xc1");
    TRY(3, ".byte 0xc4,0xe2,0xf9,0x13,0xc1");
    TRY(4, ".byte 0xc4,0xe3,0x71,0x1d,0xc1,0x00");
    for (int i = 0; i < 5; i++, (*checks)++)
        if (got[i] != ud[i].sig && bad++ < 40)
            printf("FAIL %s: signal %d, want %d\n", ud[i].name, got[i], ud[i].sig);
    char *ro = mmap(0, 4096, PROT_READ, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    static const float in[8] = {1.0001f, 1e-10f, 70000.f, 3.f, 1.0001f, 1e-10f, 70000.f, 3.f};
    static const float three = 3.f;
    unsigned mx = 0x1f80;
    for (volatile int ctl = 0; ctl < 2; ctl++)
        for (volatile int L = 0; L < 2; L++, (*checks)++) {
            fmx = 0;
            sig = 0;
            if (!sigsetjmp(jb, 1)) {
                if (L)
                    __asm__ volatile("ldmxcsr %1\n vmovups %0, %%ymm1\n vmovss %3, %%xmm2\n test %4, %4\n jz 1f\n"
                                     "vsqrtss %%xmm2, %%xmm2, %%xmm2\n 1: vcvtps2ph $0, %%ymm1, (%2)"
                                     :: "m"(in), "m"(mx), "r"(ro + 8), "m"(three), "r"(ctl) : "xmm1", "xmm2", "memory");
                else
                    __asm__ volatile("ldmxcsr %1\n vmovups %0, %%ymm1\n vmovss %3, %%xmm2\n test %4, %4\n jz 1f\n"
                                     "vsqrtss %%xmm2, %%xmm2, %%xmm2\n 1: vcvtps2ph $0, %%xmm1, (%2)"
                                     :: "m"(in), "m"(mx), "r"(ro + 8), "m"(three), "r"(ctl) : "xmm1", "xmm2", "memory");
            }
            unsigned want = ctl ? 0x1fa0 : 0x1f80;
            if ((sig != SIGSEGV || fmx != want) && bad++ < 40)
                printf("FAIL faulting vcvtps2ph L%d%s: signal %d, MXCSR %#x in the frame, want %#x\n",
                       L, ctl ? " (control)" : "", sig, fmx, want);
        }
    return bad;
}

int main(int argc, char **argv) {
    int print = argc > 1 && !strcmp(argv[1], "hashes"), dump = argc > 1 && !strcmp(argv[1], "dump");
    unsigned long checks = 0, bad = 0;
    static struct st t;
    for (int fi = 0; fi < NF; fi++) {
        int n = forms[fi].L / 32;                       /* the singles one op covers */
        for (int mi = 0; mi < NM; mi++) {
            uint64_t h = 0xcbf29ce484222325ull;
            rs = 0x9e3779b97f4a7c15ull ^ (uint64_t) fi * 0x100000001b3ull ^ (uint64_t) mi << 40;
            int iters = forms[fi].kind == 0 ? 65536 / n : 3000;
            for (int k = 0; k < iters; k++) {
                for (int i = 0; i < 32; i += 8) { uint64_t r = rnd(); memcpy(t.a + i, &r, 8); memcpy(t.d + i, &r, 8); }
                if (forms[fi].kind == 0) {              /* every half, n at a time */
                    for (int j = 0; j < n; j++) { uint16_t hv = (uint16_t) (k * n + j); memcpy(t.b + 2 * j, &hv, 2); }
                    for (int j = 2 * n; j < 32; j++) t.b[j] = (uint8_t) rnd();
                } else {
                    for (int j = 0; j < 8; j++) { uint32_t s = single(); memcpy(t.b + 4 * j, &s, 4); }
                }
                t.mx = modes[mi];
                forms[fi].fn(&t);
                unsigned f = t.f & 0x3f;
                const uint8_t *res = forms[fi].mem && forms[fi].kind == 1 ? t.d : t.out;
                for (int i = 0; i < 32; i++) h = (h ^ res[i]) * 0x100000001b3ull;
                h = (h ^ f) * 0x100000001b3ull;
                if (dump) {
                    printf("%d %d %d:", fi, mi, k);
                    for (int i = 31; i >= 0; i--) printf("%02x", res[i]);
                    printf(" %x\n", f);
                }
            }
            if (print) printf("%d.%d %#llx\n", fi, mi, (unsigned long long) h);
            checks++;
            if (!print && !dump && h != want[fi][mi] && bad++ < 40)
                printf("FAIL %s, mxcsr %#x\n", forms[fi].name, modes[mi]);
        }
    }
    if (!print && !dump)
        bad += fixed_checks(&checks);
    if (!print && !dump)
        printf("NAME: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NF, checks, bad);
    return bad != 0;
}''')
open(args[0], 'w').write('\n'.join(o).replace('NAME: %s', NAME + ': %s'))
print(len(FORMS), 'forms')
