#!/usr/bin/env python3
"""Write jit/guest-arm64/simd_spec3.S: the arm64 guest's AdvSIMD three-same
gadgets specialised by arrangement, and arm64_vs3_index, which maps each
generic gadget (simd_arith.S, simd.S's bitwise ones) to its table of them.

    python3 tools/gen-simd-spec3.py [OUTPUT]

The op lists below mirror simd_arith.S's instantiations (and the permutes,
simd_misc.S's permute_vec) and gen.c's validity classes; add an op to both.
"""

import sys

# name, host mnemonic, validity class: D = every size (.1d rejected by gen.c),
# NOD = no 64-bit elements, HS = 16/32-bit only, B = bytes only; ACC = reads Vd.
INT_OPS = """
vadd add D
vsub sub D
vmul mul NOD
vpmul pmul B
vcmeq cmeq D
vcmtst cmtst D
vcmgt cmgt D
vcmge cmge D
vcmhi cmhi D
vcmhs cmhs D
vsmax smax NOD
vsmin smin NOD
vumax umax NOD
vumin umin NOD
vsabd sabd NOD
vuabd uabd NOD
vshadd shadd NOD
vuhadd uhadd NOD
vsrhadd srhadd NOD
vurhadd urhadd NOD
vshsub shsub NOD
vuhsub uhsub NOD
vsshl sshl D
vushl ushl D
vsrshl srshl D
vurshl urshl D
vsqshl sqshl D
vuqshl uqshl D
vsqrshl sqrshl D
vuqrshl uqrshl D
vsqadd sqadd D
vuqadd uqadd D
vsqsub sqsub D
vuqsub uqsub D
vsqdmulh sqdmulh HS
vsqrdmulh sqrdmulh HS
vaddp addp D
vsmaxp smaxp NOD
vsminp sminp NOD
vumaxp umaxp NOD
vuminp uminp NOD
vmla mla NOD ACC
vmls mls NOD ACC
vsaba saba NOD ACC
vuaba uaba NOD ACC
vuzp1 uzp1 D
vuzp2 uzp2 D
vtrn1 trn1 D
vtrn2 trn2 D
vzip1 zip1 D
vzip2 zip2 D
"""

FP_OPS = """
vfadd fadd
vfsub fsub
vfmul fmul
vfdiv fdiv
vfmulx fmulx
vfmax fmax
vfmin fmin
vfmaxnm fmaxnm
vfminnm fminnm
vfaddp faddp
vfmaxp fmaxp
vfminp fminp
vfmaxnmp fmaxnmp
vfminnmp fminnmp
vfrecps frecps
vfrsqrts frsqrts
vfcmeq fcmeq
vfcmge fcmge
vfcmgt fcmgt
vfacge facge
vfacgt facgt
vfabd fabd
vfmla fmla ACC
vfmls fmls ACC
"""

# Bitwise: generic gadgets are per arrangement (<name>_8b, <name>_16b).
LOGIC_OPS = """
vand and
vbic bic
vorr orr
vorn orn
veor eor
vbsl bsl ACC
vbit bit ACC
vbif bif ACC
"""

# By-element (indexed) multiplies, vector: Vm.T[i] is loaded with ld1r from
# its precomputed offset and the plain vector op runs. FP = .2s/.4s/.2d,
# HS = .4h/.8h/.2s/.4s. Indexed by size*2+Q like the integer ops.
ELEM_OPS = """
velem_fmul fmul FP
velem_fmulx fmulx FP
velem_fmla fmla FP ACC
velem_fmls fmls FP ACC
velem_mul mul HS
velem_mla mla HS ACC
velem_mls mls HS ACC
"""

# Two-register misc, [gadget][d_off][n_off]: name, template, class. The
# template's {a} is the arrangement; class as above, or FP (sz*2+Q), or XTN
# (narrows: source is the double-width arrangement, the Q=1 form is the
# "2" variant writing the upper half and keeping the lower, so it reads Vd).
TWO_OPS = """
vabs|abs v0.{a}, v1.{a}|D
vneg|neg v0.{a}, v1.{a}|D
vcnt|cnt v0.{a}, v1.{a}|B
vrev64|rev64 v0.{a}, v1.{a}|NOD
vcmeq0|cmeq v0.{a}, v1.{a}, #0|D
vcmgt0|cmgt v0.{a}, v1.{a}, #0|D
vcmge0|cmge v0.{a}, v1.{a}, #0|D
vcmle0|cmle v0.{a}, v1.{a}, #0|D
vcmlt0|cmlt v0.{a}, v1.{a}, #0|D
vxtn|xtn|XTN
vscvtf|scvtf v0.{a}, v1.{a}|FP
vucvtf|ucvtf v0.{a}, v1.{a}|FP
vfcvtzs|fcvtzs v0.{a}, v1.{a}|FP
vfcvtzu|fcvtzu v0.{a}, v1.{a}|FP
vfabs|fabs v0.{a}, v1.{a}|FP
vfneg|fneg v0.{a}, v1.{a}|FP
vfsqrt|fsqrt v0.{a}, v1.{a}|FP
vfrintn|frintn v0.{a}, v1.{a}|FP
vfrintm|frintm v0.{a}, v1.{a}|FP
vfrintp|frintp v0.{a}, v1.{a}|FP
vfrintz|frintz v0.{a}, v1.{a}|FP
vfcmgt0|fcmgt v0.{a}, v1.{a}, #0.0|FP
vfcmge0|fcmge v0.{a}, v1.{a}, #0.0|FP
vfcmeq0|fcmeq v0.{a}, v1.{a}, #0.0|FP
vfcmle0|fcmle v0.{a}, v1.{a}, #0.0|FP
vfcmlt0|fcmlt v0.{a}, v1.{a}, #0.0|FP
"""
XTN_SRC = {"8b": "8h", "16b": "8h", "4h": "4s", "8h": "4s", "2s": "2d", "4s": "2d"}

INT_ARR = ["8b", "16b", "4h", "8h", "2s", "4s", None, "2d"]   # size*2+Q
FP_ARR = ["2s", "4s", None, "2d", None, None, None, None]      # sz*2+Q
LOGIC_ARR = ["8b", "16b", None, None, None, None, None, None]  # Q

HEADER = r"""// AArch64 guest AdvSIMD three-same gadgets specialised by arrangement, fed
// precomputed cpu_state offsets: the per-arrangement twins of simd_arith.S's
// generic three-same gadgets (and simd.S's bitwise ones), which decode
// Rd/Rn/Rm, size and Q on every execution and branch on the arrangement.
// Here the arrangement is in the gadget and the registers are offsets, so an
// `add v0.4s, v1.4s, v2.4s` is two loads, the host instruction and a store.
//
// GENERATED by tools/gen-simd-spec3.py from the op lists there; edit those.
//
// Code stream: [gadget][d_off][n_off][m_off], byte offsets of the V
// registers from _cpu, each its own word (plain loads beat unpacking one
// packed word; see alu_spec.S). A Q=0 arrangement's
// host op zeroes v0's upper half, as the architecture zeroes Vd's, so the
// whole q0 is stored either way. Accumulating ops (MLA, SABA, FMLA, BSL...)
// read Vd too.
//
// arm64_vs3_index pairs each generic gadget with its table of specialised
// ones, 8 entries: integer ops by size*2+Q (8b 16b 4h 8h 2s 4s - 2d), FP ops
// by sz*2+Q (2s 4s - 2d), bitwise ops by Q (8b 16b); 0 where the arrangement
// does not exist. gen.c's gen_arm64_vs3 looks the generic gadget up there
// when the "vspec" bit of /proc/ish/arm64_jit_fuse is on.
//
// arm64_vse_index does the same for the by-element (indexed) multiplies
// (FMUL/FMULX/FMLA/FMLS, MUL/MLA/MLS): the third offset is the element's,
// which the gadget replicates with ld1r before the plain vector op --
// exactly the indexed op's arithmetic.

#include "gadgets.h"

.macro vs3 name, op, arr
.gadget vs3_\name\()_\arr
    ldp x9, x10, [_ip]
    ldr x11, [_ip, #16]
    ldr q0, [_cpu, x10]
    ldr q1, [_cpu, x11]
    \op v0.\arr, v0.\arr, v1.\arr
    str q0, [_cpu, x9]
    gret 3
.endm

.macro vs3acc name, op, arr
.gadget vs3_\name\()_\arr
    ldp x9, x10, [_ip]
    ldr x11, [_ip, #16]
    ldr q0, [_cpu, x9]
    ldr q1, [_cpu, x10]
    ldr q2, [_cpu, x11]
    \op v0.\arr, v1.\arr, v2.\arr
    str q0, [_cpu, x9]
    gret 3
.endm

.macro vse name, op, arr
.gadget vse_\name\()_\arr
    ldp x9, x10, [_ip]
    ldr x11, [_ip, #16]
    add x11, _cpu, x11
    ldr q0, [_cpu, x10]
    ld1r {v1.\arr}, [x11]
    \op v0.\arr, v0.\arr, v1.\arr
    str q0, [_cpu, x9]
    gret 3
.endm

.macro vseacc name, op, arr
.gadget vse_\name\()_\arr
    ldp x9, x10, [_ip]
    ldr x11, [_ip, #16]
    add x11, _cpu, x11
    ldr q0, [_cpu, x9]
    ldr q1, [_cpu, x10]
    ld1r {v2.\arr}, [x11]
    \op v0.\arr, v1.\arr, v2.\arr
    str q0, [_cpu, x9]
    gret 3
.endm

.text
"""


def int_valid(cls, i):
    size = i // 2
    if INT_ARR[i] is None:
        return False
    return {"D": True, "NOD": size < 3, "HS": size in (1, 2), "B": size == 0}[cls]


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "jit/guest-arm64/simd_spec3.S"
    body, tables, index = [], [], []

    def emit(name, op, acc, arrs, generics):
        ents = []
        for a in arrs:
            if a is None:
                ents.append("0")
                continue
            body.append("%s %s, %s, %s" % ("vs3acc" if acc else "vs3", name, op, a))
            ents.append("NAME(gadget_arm64_vs3_%s_%s)" % (name, a))
        tables.append((name, ents))
        for g in generics:
            index.append((g, name))

    for line in INT_OPS.strip().splitlines():
        f = line.split()
        name, op, cls, acc = f[0], f[1], f[2], "ACC" in f[3:]
        emit(name, op, acc, [INT_ARR[i] if int_valid(cls, i) else None for i in range(8)], [name])
    for line in FP_OPS.strip().splitlines():
        f = line.split()
        emit(f[0], f[1], "ACC" in f[2:], FP_ARR, [f[0]])
    for line in LOGIC_OPS.strip().splitlines():
        f = line.split()
        emit(f[0], f[1], "ACC" in f[2:], LOGIC_ARR, [f[0] + "_8b", f[0] + "_16b"])

    etables, eindex = [], []
    for line in ELEM_OPS.strip().splitlines():
        f = line.split()
        name, op, cls, acc = f[0], f[1], f[2], "ACC" in f[3:]
        arrs = [None, None, "4h", "8h", "2s", "4s", None, "2d"]
        if cls == "FP":
            arrs[2] = arrs[3] = None
        else:
            arrs[7] = None
        ents = []
        for a in arrs:
            if a is None:
                ents.append("0")
                continue
            body.append("%s %s, %s, %s" % ("vseacc" if acc else "vse", name, op, a))
            ents.append("NAME(gadget_arm64_vse_%s_%s)" % (name, a))
        etables.append((name, ents))
        eindex.append((name, name))

    ttables, tindex = [], []
    for line in TWO_OPS.strip().splitlines():
        name, tmpl, cls = line.split("|")
        ents = []
        for i in range(8):
            if cls == "FP":
                a = FP_ARR[i]
            elif cls == "XTN":
                a = INT_ARR[i] if i < 6 else None
            else:
                a = INT_ARR[i] if int_valid(cls, i) else None
            if a is None:
                ents.append("0")
                continue
            acc = False
            if cls == "XTN":
                q = i & 1
                insn = ("xtn2 v0.%s, v1.%s" if q else "xtn v0.%s, v1.%s") % (a, XTN_SRC[a])
                acc = bool(q)
            else:
                insn = tmpl.format(a=a)
            g = "vs2_%s_%s" % (name, a)
            body.append(".gadget %s\n    ldp x9, x10, [_ip]\n%s    ldr q1, [_cpu, x10]\n    %s\n    str q0, [_cpu, x9]\n    gret 2"
                        % (g, "    ldr q0, [_cpu, x9]\n" if acc else "", insn))
            ents.append("NAME(gadget_arm64_%s)" % g)
        ttables.append((name, ents))
        tindex.append((name, name))

    out = [HEADER]
    out += body
    out.append("\n.data\n.balign 8")
    for name, ents in tables:
        out.append("Lvs3tab_%s:\n    .quad %s" % (name, ", ".join(ents)))
    out.append(".global NAME(arm64_vs3_index)\nNAME(arm64_vs3_index):")
    for generic, name in index:
        out.append("    .quad NAME(gadget_arm64_%s), Lvs3tab_%s" % (generic, name))
    out.append("    .quad 0, 0\n")
    for name, ents in etables:
        out.append("Lvsetab_%s:\n    .quad %s" % (name, ", ".join(ents)))
    out.append("// By-element ops: the element's offset is the third field.")
    out.append(".global NAME(arm64_vse_index)\nNAME(arm64_vse_index):")
    for generic, name in eindex:
        out.append("    .quad NAME(gadget_arm64_%s), Lvsetab_%s" % (generic, name))
    out.append("    .quad 0, 0\n")
    for name, ents in ttables:
        out.append("Lvs2tab_%s:\n    .quad %s" % (name, ", ".join(ents)))
    out.append("// Two-register misc: [gadget][d_off][n_off], indexed size*2+Q (FP: sz*2+Q).")
    out.append(".global NAME(arm64_vs2_index)\nNAME(arm64_vs2_index):")
    for generic, name in tindex:
        out.append("    .quad NAME(gadget_arm64_%s), Lvs2tab_%s" % (generic, name))
    out.append("    .quad 0, 0\n")
    with open(out_path, "w") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    main()
