#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_sse_int.c (usage: this script OUT.c).
#
# The packed-integer SSE2 and MMX ops, register and memory sources, xmm1/xmm9
# (REX) and mm1, against byte-array models (vectorisation off, so the model
# cannot become the instructions under test).
import sys

# (mnemonic, model, lane bytes, mmx form exists)
OPS = [
    ('paddb', 'add', 1, 1), ('paddw', 'add', 2, 1), ('paddd', 'add', 4, 1), ('paddq', 'add', 8, 1),
    ('psubb', 'sub', 1, 1), ('psubw', 'sub', 2, 1), ('psubd', 'sub', 4, 1), ('psubq', 'sub', 8, 1),
    ('paddsb', 'adds', 1, 1), ('paddsw', 'adds', 2, 1), ('paddusb', 'addus', 1, 1), ('paddusw', 'addus', 2, 1),
    ('psubsb', 'subs', 1, 1), ('psubsw', 'subs', 2, 1), ('psubusb', 'subus', 1, 1), ('psubusw', 'subus', 2, 1),
    ('pcmpeqb', 'eq', 1, 1), ('pcmpeqw', 'eq', 2, 1), ('pcmpeqd', 'eq', 4, 1),
    ('pcmpgtb', 'gt', 1, 1), ('pcmpgtw', 'gt', 2, 1), ('pcmpgtd', 'gt', 4, 1),
    ('pand', 'and', 8, 1), ('pandn', 'andn', 8, 1), ('por', 'or', 8, 1), ('pxor', 'xor', 8, 1),
    ('pminub', 'minu', 1, 1), ('pmaxub', 'maxu', 1, 1), ('pminsw', 'mins', 2, 1), ('pmaxsw', 'maxs', 2, 1),
    ('pavgb', 'avg', 1, 1), ('pavgw', 'avg', 2, 1),
    ('pmullw', 'mullo', 2, 1), ('pmulhw', 'mulhs', 2, 1), ('pmulhuw', 'mulhu', 2, 1),
    ('pmuludq', 'muludq', 8, 1), ('pmaddwd', 'maddwd', 4, 1), ('psadbw', 'sadbw', 8, 1),
    ('punpcklbw', 'unpckl', 1, 1), ('punpcklwd', 'unpckl', 2, 1), ('punpckldq', 'unpckl', 4, 1),
    ('punpckhbw', 'unpckh', 1, 1), ('punpckhwd', 'unpckh', 2, 1), ('punpckhdq', 'unpckh', 4, 1),
    ('punpcklqdq', 'unpckl', 8, 0), ('punpckhqdq', 'unpckh', 8, 0),
    ('packsswb', 'packss', 2, 1), ('packssdw', 'packss', 4, 1), ('packuswb', 'packus', 2, 1),
]
o = []; w = o.append
w('''// Generated by tools/gen-amd64-sse-int-test.py -- do not edit.
//
// The SSE2 and MMX packed-integer ops (add/sub with and without saturation,
// compares, logic, min/max, average, the multiplies, PMADDWD, PSADBW, the
// unpacks and packs) -- XMM (66) and MMX, register and memory sources,
// xmm1/xmm9 -- against byte-array models; checked against real hardware (an
// AMD Ryzen). Vectorisation is off: the model must not become SSE itself.
#pragma GCC optimize("no-tree-vectorize")
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static unsigned long checks, bad;
static void check(const char *what, long k, uint64_t got, uint64_t want) {
    checks++;
    if (got != want && bad++ < 40)
        printf("FAIL %s (%ld): %#llx, want %#llx\\n", what, k, (unsigned long long) got, (unsigned long long) want);
}
static uint64_t rs = 0x243f6a8885a308d3ull;
static uint64_t rnd(void) { rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }

static uint64_t get(const uint8_t *p, int lb) { uint64_t v = 0; for (int b = 0; b < lb; b++) v |= (uint64_t) p[b] << (8 * b); return v; }
static void put(uint8_t *p, int lb, uint64_t v) { for (int b = 0; b < lb; b++) p[b] = (uint8_t) (v >> (8 * b)); }
static int64_t sx(uint64_t v, int lb) { int s = 64 - 8 * lb; return lb == 8 ? (int64_t) v : (int64_t) (v << s) >> s; }
static int64_t clamp(int64_t v, int64_t lo, int64_t hi) { return v < lo ? lo : v > hi ? hi : v; }
// a * b, unsigned, by shift and add: no multiply instruction in the model
static uint64_t mulu(uint64_t a, uint64_t b) { uint64_t r = 0; for (int i = 0; i < 64; i++) if ((b >> i) & 1) r += a << i; return r; }
static int64_t muls(int64_t a, int64_t b) { int n = (a < 0) != (b < 0); uint64_t r = mulu(a < 0 ? -(uint64_t) a : a, b < 0 ? -(uint64_t) b : b); return n ? -(int64_t) r : (int64_t) r; }

static void model(const char *m, int lb, int nb, const uint8_t *d, const uint8_t *s, uint8_t *out) {
    int n = nb / lb;
    uint64_t mask = lb == 8 ? ~0ull : (1ull << (8 * lb)) - 1;
    int64_t smax = (int64_t) (mask >> 1), smin = -smax - 1;
    if (!strcmp(m, "unpckl") || !strcmp(m, "unpckh")) {
        int base = !strcmp(m, "unpckh") ? n / 2 : 0;
        for (int i = 0; i < n / 2; i++) {
            put(out + (2 * i) * lb, lb, get(d + (base + i) * lb, lb));
            put(out + (2 * i + 1) * lb, lb, get(s + (base + i) * lb, lb));
        }
        return;
    }
    if (!strcmp(m, "packss") || !strcmp(m, "packus")) {   // lb = source lane; out lanes lb/2
        int ob = lb / 2, us = !strcmp(m, "packus");
        int64_t lo = us ? 0 : -(1ll << (8 * ob - 1)), hi = us ? (1ll << (8 * ob)) - 1 : (1ll << (8 * ob - 1)) - 1;
        for (int i = 0; i < n; i++) put(out + i * ob, ob, (uint64_t) clamp(sx(get(d + i * lb, lb), lb), lo, hi));
        for (int i = 0; i < n; i++) put(out + (n + i) * ob, ob, (uint64_t) clamp(sx(get(s + i * lb, lb), lb), lo, hi));
        return;
    }
    if (!strcmp(m, "sadbw")) {
        for (int q = 0; q < nb / 8; q++) {
            uint64_t sum = 0;
            for (int b = 0; b < 8; b++) { int x = d[q * 8 + b], y = s[q * 8 + b]; sum += x > y ? x - y : y - x; }
            put(out + q * 8, 8, sum);
        }
        return;
    }
    if (!strcmp(m, "maddwd")) {
        for (int i = 0; i < n; i++) {
            int64_t a = muls(sx(get(d + i * 4, 2), 2), sx(get(s + i * 4, 2), 2));
            int64_t b = muls(sx(get(d + i * 4 + 2, 2), 2), sx(get(s + i * 4 + 2, 2), 2));
            put(out + i * 4, 4, (uint64_t) (a + b));
        }
        return;
    }
    if (!strcmp(m, "muludq")) {
        for (int i = 0; i < n; i++) put(out + i * 8, 8, mulu(get(d + i * 8, 4), get(s + i * 8, 4)));
        return;
    }
    for (int i = 0; i < n; i++) {
        uint64_t a = get(d + i * lb, lb), b = get(s + i * lb, lb), r;
        int64_t sa = sx(a, lb), sb = sx(b, lb);
        if (!strcmp(m, "add")) r = a + b;
        else if (!strcmp(m, "sub")) r = a - b;
        else if (!strcmp(m, "adds")) r = (uint64_t) clamp(sa + sb, smin, smax);
        else if (!strcmp(m, "subs")) r = (uint64_t) clamp(sa - sb, smin, smax);
        else if (!strcmp(m, "addus")) r = a + b > mask ? mask : a + b;
        else if (!strcmp(m, "subus")) r = a < b ? 0 : a - b;
        else if (!strcmp(m, "eq")) r = a == b ? mask : 0;
        else if (!strcmp(m, "gt")) r = sa > sb ? mask : 0;
        else if (!strcmp(m, "and")) r = a & b;
        else if (!strcmp(m, "andn")) r = ~a & b;
        else if (!strcmp(m, "or")) r = a | b;
        else if (!strcmp(m, "xor")) r = a ^ b;
        else if (!strcmp(m, "minu")) r = a < b ? a : b;
        else if (!strcmp(m, "maxu")) r = a > b ? a : b;
        else if (!strcmp(m, "mins")) r = sa < sb ? a : b;
        else if (!strcmp(m, "maxs")) r = sa > sb ? a : b;
        else if (!strcmp(m, "avg")) r = (a + b + 1) >> 1;
        else if (!strcmp(m, "mullo")) r = (uint64_t) muls(sa, sb);
        else if (!strcmp(m, "mulhs")) r = (uint64_t) (muls(sa, sb) >> 16);
        else if (!strcmp(m, "mulhu")) r = mulu(a, b) >> 16;
        else r = 0;
        put(out + i * lb, lb, r & mask);
    }
}
''')
forms = []
for mn, m, lb, mmx in OPS:
    for x in (1, 0):
        if not x and not mmx:
            continue
        regs = [('%%xmm1', '%%xmm2'), ('%%xmm9', '%%xmm10')] if x else [('%%mm1', '%%mm2')]
        for d, s in regs:
            forms.append(dict(name=f'{mn} {d[2:]},{s[2:]}', m=m, lb=lb, x=x, mem=0, d=d, s=s, asm=f'{mn} {s}, {d}'))
        forms.append(dict(name=f'{mn} mem,{regs[0][0][2:]}', m=m, lb=lb, x=x, mem=1, d=regs[0][0], s=regs[0][1], asm=f'{mn} (%%rdi), {regs[0][0]}'))
for i, f in enumerate(forms):
    ld = 'movdqu' if f['x'] else 'movq'
    tail = '' if f['x'] else '\\n emms'
    w(f'''__attribute__((noinline)) static void f{i}(uint8_t *v, uint8_t *src) {{
    __asm__ volatile("{ld} (%0), {f['d']}\\n {ld} (%1), {f['s']}\\n {f['asm']}\\n {ld} {f['d']}, (%0){tail}"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2", "xmm9", "xmm10", "mm1", "mm2");
}}''')
w('struct form { const char *name, *m; int lb, x; void (*fn)(uint8_t *, uint8_t *); };')
w('static const struct form forms[] = {')
for i, f in enumerate(forms):
    w(f'    {{"{f["name"]}", "{f["m"]}", {f["lb"]}, {f["x"]}, f{i}}},')
w('};')
w(f'#define NFORMS {len(forms)}')
w('''
int main(void) {
    static uint8_t v[16] __attribute__((aligned(16))), src[16] __attribute__((aligned(16))), d0[16], want[16];
    for (int k = 0; k < 1500; k++) {
        for (int fi = 0; fi < NFORMS; fi++) {
            const struct form *f = &forms[fi];
            for (int i = 0; i < 16; i++) { v[i] = (uint8_t) rnd(); src[i] = (uint8_t) rnd(); }
            switch (k % 6) {
            case 0: memcpy(src, v, 16); break;                              // equal lanes
            case 1: for (int i = 0; i < 16; i++) { v[i] |= 0x80; src[i] |= 0x7f; } break;  // saturating
            case 2: for (int i = 0; i < 16; i += 2) src[i] = v[i]; break;   // some equal
            case 3: memset(src, 0xff, 16); break;
            }
            memcpy(d0, v, 16);
            f->fn(v, src);
            int nb = f->x ? 16 : 8;
            memcpy(want, d0, 16);
            model(f->m, f->lb, nb, d0, src, want);
            uint64_t g0, g1, w0, w1;
            memcpy(&g0, v, 8); memcpy(&g1, v + 8, 8); memcpy(&w0, want, 8); memcpy(&w1, want + 8, 8);
            check(f->name, fi * 10000 + k, g0, w0);
            if (f->x) check(f->name, fi * 10000 + k, g1, w1);
        }
    }
    printf("amd64_sse_int: %s (%d forms, %lu checks, %lu mismatches)\\n", bad ? "FAIL" : "PASS", NFORMS, checks, bad);
    return bad != 0;
}''')
open(sys.argv[1], 'w').write('\n'.join(o))
print(len(forms), 'forms')
