#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_avx512_xform.c, or with --i386
# i386_avx512_xform.c (usage: this script [--i386] [--answers FILE] OUT.c).
#
# AVX-512 width-changing and element-gathering ops: VPMOVSX/ZX (every
# width), the narrowing moves VPMOV/VPMOVS/VPMOVUS (to a register, and to
# memory unmasked and masked), VPCOMPRESS*/VCOMPRESSPS/PD (to a register and
# to memory), VPEXPAND*/VEXPANDPS/PD (from a register and memory), VPLZCNT,
# VPOPCNT, VPCONFLICT, VPMOVM2*, VPMOV*2M: VL 128/256/512, unmasked, merge-
# and zero-masked. Then compress stores and expand loads near the end of a
# mapped page, which fault as SDE has them -- by the enabled elements'
# positions, not the packed ones they touch -- and write only the packed
# bytes; and encodings whose #UD-or-not is part of the answer. The destination's 64 bytes, k1, the memory and the
# signal are hashed per form and checked against Intel SDE's (`sde64
# -ptr-raise -spr -- ./test hashes` on camd, passed back with --answers);
# the i386 test takes the amd64 answers.
import sys
I386 = '--i386' in sys.argv
args = [a for a in sys.argv[1:] if a != '--i386']
answers = {}
if '--answers' in args:
    i = args.index('--answers')
    for line in open(args[i + 1]):
        k, v = line.rsplit(' ', 1)
        answers[k] = v.strip()
    del args[i:i + 2]
NAME = 'i386_avx512_xform' if I386 else 'amd64_avx512_xform'
VLS = {128: 'xmm', 256: 'ymm', 512: 'zmm'}
HALF = {128: 'xmm', 256: 'xmm', 512: 'ymm'}
MK = [('', ''), ('%{%%k1%}', 'm'), ('%{%%k1%}%{z%}', 'z')]
F = []
def add(name, asm):
    F.append((name, asm))
# extends: the source register is the narrower one
for s in ('sx', 'zx'):
    for n, ratio in (('bw', 2), ('bd', 4), ('bq', 8), ('wd', 2), ('wq', 4), ('dq', 2)):
        for L, x in VLS.items():
            src = 'xmm' if L // ratio <= 128 else 'ymm'
            for mk, mn in MK:
                add(f'vpmov{s}{n} {L} reg{mn}', f'vpmov{s}{n} %%{src}3, %%{x}1{mk}')
            add(f'vpmov{s}{n} {L} mem m', f'vpmov{s}{n} (%1), %%{x}1%{{%%k1%}}')
# narrowing: the destination register is the narrower one
for pre in ('', 's', 'us'):
    for n, ratio in (('wb', 2), ('db', 4), ('qb', 8), ('dw', 2), ('qw', 4), ('qd', 2)):
        op = f'vpmov{pre}{n}'
        for L, x in VLS.items():
            dst = 'xmm' if L // ratio <= 128 else 'ymm'
            for mk, mn in MK:
                add(f'{op} {L} reg{mn}', f'{op} %%{x}3, %%{dst}1{mk}')
            add(f'{op} {L} st', f'{op} %%{x}3, (%1)')
            add(f'{op} {L} st m', f'{op} %%{x}3, (%1)%{{%%k1%}}')
for op in ('vpcompressd', 'vpcompressq', 'vcompressps', 'vcompresspd', 'vpcompressb', 'vpcompressw'):
    for L, x in VLS.items():
        for mk, mn in MK:
            add(f'{op} {L} reg{mn}', f'{op} %%{x}3, %%{x}1{mk}')
        add(f'{op} {L} st', f'{op} %%{x}3, (%1)')
        add(f'{op} {L} st m', f'{op} %%{x}3, (%1)%{{%%k1%}}')
for op in ('vpexpandd', 'vpexpandq', 'vexpandps', 'vexpandpd', 'vpexpandb', 'vpexpandw'):
    for L, x in VLS.items():
        for mk, mn in MK:
            add(f'{op} {L} reg{mn}', f'{op} %%{x}3, %%{x}1{mk}')
            add(f'{op} {L} mem{mn}', f'{op} (%1), %%{x}1{mk}')
for op, bc in (('vplzcntd', 4), ('vplzcntq', 8), ('vpopcntd', 4), ('vpopcntq', 8), ('vpconflictd', 4), ('vpconflictq', 8)):
    for L, x in VLS.items():
        for mk, mn in MK:
            add(f'{op} {L} reg{mn}', f'{op} %%{x}3, %%{x}1{mk}')
        add(f'{op} {L} mem m', f'{op} (%1), %%{x}1%{{%%k1%}}')
        add(f'{op} {L} bcst z', f'{op} (%1)%{{1to{L // (8 * bc)}%}}, %%{x}1%{{%%k1%}}%{{z%}}')
for t in 'bwdq':
    for L, x in VLS.items():
        add(f'vpmovm2{t} {L}', f'vpmovm2{t} %%k1, %%{x}1')
        add(f'vpmov{t}2m {L}', f'vpmov{t}2m %%{x}3, %%k1')
UD = {'vpmovqb st z': '62 f2 7e c9 32 18', 'vpmovm2d mask': '62 f2 7e 49 38 c9', 'vpmovd2m mask': '62 f2 7e 49 39 cb',
      'vpmovm2d ok': '62 f2 7e 48 38 c9', 'vpmovd2m ok': '62 f2 7e 48 39 cb', 'vpmovd2m mem': '62 f2 7e 48 39 08',
      'vpcompressd st z': '62 f2 7d c9 8b 18', 'vpcompressd vvvv': '62 f2 75 48 8b d9',
      'vpmovsxbw vvvv': '62 f2 75 48 20 cb', 'vpmovsxdq W1': '62 f2 fd 48 25 cb', 'vpmovzxdq W1': '62 f2 fd 48 35 cb',
      'vpmovqd W1': '62 f2 fe 48 35 d9', 'vplzcntd bcst reg': '62 f2 7d 58 44 cb'}
for k, b in UD.items():
    F.append((f'ud {k}', 'ud:' + ', '.join('0x' + x for x in b.split())))
R = 'e' if I386 else 'r'
o = []; w = o.append
w(f'''// Generated by tools/gen-avx512-xform-test.py{" --i386" if I386 else ""} -- do not edit.
//
// AVX-512 width-changing and element-gathering ops against Intel SDE (see
// the generator). (No target pragma: the harness itself must not use AVX-512.)
#include <setjmp.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/mman.h>
static uint64_t rs;
static uint64_t rnd(void) {{ rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }}
struct st {{ uint8_t d[64], a[64], b[64], out[64], m[64]; uint64_t k, kout; }} __attribute__((aligned(64)));
static sigjmp_buf jb;
static volatile int sig;
static void handler(int s) {{ sig = s; siglongjmp(jb, 1); }}
#define LOAD "vmovdqu64 (%0), %%zmm1\\n vmovdqu64 64(%0), %%zmm2\\n vmovdqu64 128(%0), %%zmm3\\n kmovq 320(%0), %%k1\\n"
#define SAVE "\\n vmovdqu64 %%zmm1, 192(%0)\\n kmovq %%k1, 328(%0)"
''')
for i, (name, asm) in enumerate(F):
    if asm.startswith('ud:'):
        w(f'''__attribute__((noinline)) static void f{i}(struct st *t) {{
    __asm__ volatile(LOAD "mov %1, %%{R}ax\\n .byte {asm[3:]}" SAVE :: "r"(t), "r"(t->m) : "memory", "{R}ax", "xmm1", "xmm2", "xmm3");
}}''')
    else:
        w(f'''__attribute__((noinline)) static void f{i}(struct st *t) {{
    __asm__ volatile(LOAD "{asm}" SAVE :: "r"(t), "r"(t->m) : "memory", "xmm1", "xmm2", "xmm3");
}}''')
w('static const struct { const char *name; void (*fn)(struct st *); } forms[] = {')
for i, (name, asm) in enumerate(F):
    w(f'    {{"{name}", f{i}}},')
w('};')
w(f'#define NF {len(F)}')
if answers:
    w('static const uint64_t want[NF] = {')
    for name, asm in F:
        w(f'    {answers[name]}ull,')
    w('};')
else:
    w('static const uint64_t want[NF];   // (run with "hashes" under SDE)')
w(r'''
static int run(void (*fn)(struct st *), struct st *t) {
    sig = 0;
    if (!sigsetjmp(jb, 1))
        fn(t);
    return sig;
}
// a compress store and an expand load near a page end, the next page
// unmapped. As SDE has it (every model), these fault by the enabled
// elements' positions, not the packed ones they touch: k = 0x8421 enables
// elements 0, 5, 10, 15, so 16 bytes are packed, but element 15's bytes
// (48-63 past the start) must be mapped. Only the packed bytes are written.
static uint8_t *pg;
static int cx_store(int off, const uint64_t *k, const uint8_t *src) {
    sig = 0;
    if (!sigsetjmp(jb, 1))
        __asm__ volatile("kmovq %1, %%k2\n vmovdqu64 (%2), %%zmm4\n vpcompressd %%zmm4, (%0)%{%%k2%}"
                         :: "r"(pg + 4096 - off), "m"(*k), "r"(src) : "memory", "xmm4");
    return sig;
}
static int cx_load(int off, const uint64_t *k, uint8_t *out) {
    sig = 0;
    if (!sigsetjmp(jb, 1))
        __asm__ volatile("kmovq %1, %%k2\n vpxord %%zmm4, %%zmm4, %%zmm4\n vpexpandd (%0), %%zmm4%{%%k2%}%{z%}\n"
                         "vmovdqu64 %%zmm4, (%2)" :: "r"(pg + 4096 - off), "m"(*k), "r"(out) : "memory", "xmm4");
    return sig;
}
static int under_sde;
static unsigned long fixed_checks(unsigned long *checks) {
    unsigned long bad = 0;
    pg = mmap(0, 8192, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    munmap(pg + 4096, 4096);
    static uint8_t src[64], out[64];
    for (int i = 0; i < 64; i++) src[i] = (uint8_t) (0x90 + i);
    static const uint64_t k4 = 0x8421, k1 = 0x0001, k0 = 0;
    uint32_t packed[4] = {0};
    for (int i = 0, j = 0; i < 16; i++) if (k4 >> i & 1) memcpy(&packed[j++], src + 4 * i, 4);
    /* (offset from the page end, mask, the fault wanted) */
    static const struct { int off; const uint64_t *k; int want; } cs[] = {
        {64, &k4, 0}, {16, &k4, SIGSEGV}, {32, &k4, SIGSEGV}, {4, &k1, 0}, {4, &k0, 0},
    };
    for (unsigned c = 0; c < sizeof cs / sizeof cs[0]; c++) {
        memset(pg + 4096 - 64, 0x5a, 64);
        int sg = cx_store(cs[c].off, cs[c].k, src);
        int n = __builtin_popcountll(*cs[c].k & 0xffff), ok = 1;
        uint8_t *p = pg + 4096 - cs[c].off;
        for (int i = 0; i < 64; i++) {           /* the packed bytes written; nothing else (nothing at all on a fault) */
            uint8_t *q = pg + 4096 - 64 + i, want = 0x5a;
            if (!sg && q >= p && q < p + 4 * n) want = ((uint8_t *) packed)[q - p];
            if (*cs[c].k == k1 && !sg && q >= p && q < p + 4) want = src[q - p];
            ok &= *q == want;
        }
        (*checks)++;
        if ((sg != cs[c].want || !ok) && bad++ < 40)
            printf("FAIL vpcompressd store %d from a page end, k %#llx: signal %d (want %d)%s\n", cs[c].off,
                   (unsigned long long) *cs[c].k, sg, cs[c].want, ok ? "" : ", memory wrong");
        for (int i = 0; i < 64; i++) pg[4096 - 64 + i] = (uint8_t) (0x30 + i);
        memset(out, 0xee, 64);
        sg = cx_load(cs[c].off, cs[c].k, out);
        ok = 1;
        if (!sg)
            for (int i = 0, j = 0; i < 16; i++) {
                uint32_t v, wv = 0;
                memcpy(&v, out + 4 * i, 4);
                if (*cs[c].k >> i & 1) memcpy(&wv, p + 4 * j++, 4);
                ok &= v == wv;
            }
        (*checks)++;
        if ((sg != cs[c].want || !ok) && bad++ < 40)
            printf("FAIL vpexpandd load %d from a page end, k %#llx: signal %d (want %d)%s\n", cs[c].off,
                   (unsigned long long) *cs[c].k, sg, cs[c].want, ok ? "" : ", wrong data");
    }
    /* the start page unmapped, the one enabled element (4) on the next: the
       packed element lands on the unmapped page, so it faults (the hardware
       touches it). SDE can't run this one: it checks the enabled positions,
       then aborts ("Could not write memory") instead of raising the fault;
       "sde" as argv[1] skips it. */
    if (under_sde)
        return bad;
    static const uint64_t k10 = 0x0010;
    pg = mmap(0, 8192, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    munmap(pg, 4096);
    memset(pg + 4096, 0x5a, 64);
    int sg = cx_store(16, &k10, src), ok = 1;
    for (int i = 0; i < 64; i++) ok &= pg[4096 + i] == 0x5a;
    (*checks)++;
    if ((sg != SIGSEGV || !ok) && bad++ < 40)
        printf("FAIL vpcompressd store from an unmapped page, k 0x10: signal %d (want %d)%s\n", sg, SIGSEGV,
               ok ? "" : ", memory written");
    sg = cx_load(16, &k10, out);
    (*checks)++;
    if (sg != SIGSEGV && bad++ < 40)
        printf("FAIL vpexpandd load from an unmapped page, k 0x10: signal %d (want %d)\n", sg, SIGSEGV);
    return bad;
}

int main(int argc, char **argv) {
    int print = argc > 1 && !strcmp(argv[1], "hashes"), dump = argc > 1 && !strcmp(argv[1], "dump");
    under_sde = argc > 1 && !strcmp(argv[1], "sde");
    unsigned long checks = 0, bad = 0;
    static struct st t;
    signal(SIGILL, handler);
    signal(SIGSEGV, handler);
    for (int fi = 0; fi < NF; fi++) {
        uint64_t h = 0xcbf29ce484222325ull;
        rs = 0x9e3779b97f4a7c15ull;
        for (const char *c = forms[fi].name; *c; c++) rs = (rs ^ (uint8_t) *c) * 0x100000001b3ull;
        int ud = !strncmp(forms[fi].name, "ud ", 3);
        for (int k = 0; k < (ud ? 1 : 16); k++) {
            for (int i = 0; i < 64; i += 8) {
                uint64_t r;
                r = rnd(); memcpy(t.d + i, &r, 8);
                r = rnd(); memcpy(t.a + i, &r, 8);
                r = rnd(); memcpy(t.b + i, &r, 8);
                r = rnd(); memcpy(t.m + i, &r, 8);
            }
            if (k & 1)                           /* small and equal values: saturation, conflicts, counts */
                for (int i = 0; i < 64; i++) { t.b[i] &= 0x83; t.m[i] &= 0x83; }
            t.k = rnd();
            if (k == 2) t.k = 0;
            if (k == 3) t.k = ~0ull;
            t.kout = 0;
            memset(t.out, 0, 64);
            int sg = run(forms[fi].fn, &t);
            for (int i = 0; i < 64; i++) h = (h ^ t.out[i]) * 0x100000001b3ull;
            for (int i = 0; i < 64; i++) h = (h ^ t.m[i]) * 0x100000001b3ull;
            for (int b = 0; b < 8; b++) h = (h ^ ((t.kout >> (8 * b)) & 0xff)) * 0x100000001b3ull;
            h = (h ^ (unsigned) sg) * 0x100000001b3ull;
            if (dump) {
                printf("%s %d: sig %d k1 %016llx out ", forms[fi].name, k, sg, (unsigned long long) t.kout);
                for (int i = 63; i >= 0; i--) printf("%02x", t.out[i]);
                printf(" m ");
                for (int i = 63; i >= 0; i--) printf("%02x", t.m[i]);
                printf("\n");
            }
        }
        if (print) printf("%s %#llx\n", forms[fi].name, (unsigned long long) h);
        checks++;
        if (!print && !dump && h != want[fi] && bad++ < 40)
            printf("FAIL %s\n", forms[fi].name);
    }
    if (!print && !dump)
        bad += fixed_checks(&checks);
    if (!print && !dump)
        printf("NAME: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NF, checks, bad);
    return bad != 0;
}''')
open(args[0], 'w').write('\n'.join(o).replace('NAME: %s', NAME + ': %s'))
print(len(F), 'forms')
