#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_vex_gather.c, or with --i386 i386_vex_gather.c
# (usage: this script [--i386] [--answers FILE] OUT.c).
#
# AVX2 gathers (VPGATHERDD/DQ/QD/QQ, VGATHERDPS/DPD/QPS/QPD), VEX.128 and
# VEX.256, every scale, disp8 and disp32, with random masks (any bits besides
# the MSB) and signed indices around a base in the middle of a random buffer:
# dst, mask and the index register hashed per form and checked against the
# hashes an AMD Ryzen gives (camd: run the test with "hashes" to print them,
# and pass that output to the generator with --answers). "dump" prints every
# case. Also fixed checks as camd gives them: #UD when dst, mask and index are
# not three registers, for a register form and without a SIB; a masked-off
# element at an unmapped address does not fault; and a fault at an element
# leaves the ones below it done and their mask elements zeroed, the rest as
# they were (read from the signal frame's xmm registers).
import sys
I386 = '--i386' in sys.argv
args = [a for a in sys.argv[1:] if a != '--i386']
answers = {}
if '--answers' in args:
    i = args.index('--answers')
    for line in open(args[i + 1]):
        k, v = line.split()
        answers[k] = v
    del args[i:i + 2]
NAME = 'i386_vex_gather' if I386 else 'amd64_vex_gather'
OPS = [('vpgatherdd', 4, 4), ('vpgatherdq', 4, 8), ('vpgatherqd', 8, 4), ('vpgatherqq', 8, 8),
       ('vgatherdps', 4, 4), ('vgatherdpd', 4, 8), ('vgatherqps', 8, 4), ('vgatherqpd', 8, 8)]
FORMS = []
for op, isz, esz in OPS:
    for L in (128, 256):
        # the registers: dst, mask (data-sized), index
        if isz == esz:
            d = m = x = 'ymm' if L == 256 else 'xmm'
        elif isz == 4:                          # dword index, qword data
            d = m = 'ymm' if L == 256 else 'xmm'; x = 'xmm'
        else:                                   # qword index, dword data
            d = m = 'xmm'; x = 'ymm' if L == 256 else 'xmm'
        for scale in (1, 2, 4, 8):
            for disp in ('8', '-1032'):
                FORMS.append((f'{op} %%{m}2, {disp}(%1,%%{x}3,{scale}), %%{d}1', op, L, scale, isz, esz))
o = []; w = o.append
w(f'''// Generated by tools/gen-vex-gather-test.py{" --i386" if I386 else ""} -- do not edit.
//
// AVX2 gathers against an AMD Ryzen, hashed per form (see the generator).
#pragma GCC target("avx2")
#define _GNU_SOURCE
#include <setjmp.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <ucontext.h>
#include <sys/mman.h>
static uint64_t rs;
static uint64_t rnd(void) {{ rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }}
struct st {{ uint8_t d[32], m[32], x[32], od[32], om[32], ox[32]; }} __attribute__((aligned(32)));
static uint8_t buf[65536] __attribute__((aligned(64)));
''')
for i, (asm, op, L, scale, isz, esz) in enumerate(FORMS):
    w(f'''__attribute__((noinline)) static void f{i}(struct st *t, const uint8_t *base) {{
    __asm__ volatile("vmovdqu (%0), %%ymm1\\n vmovdqu 32(%0), %%ymm2\\n vmovdqu 64(%0), %%ymm3\\n {asm}\\n"
                     "vmovdqu %%ymm1, 96(%0)\\n vmovdqu %%ymm2, 128(%0)\\n vmovdqu %%ymm3, 160(%0)\\n vzeroupper"
                     :: "r"(t), "r"(base) : "memory", "xmm1", "xmm2", "xmm3");
}}''')
w('static const struct { const char *name; void (*fn)(struct st *, const uint8_t *); int scale, isz, esz; } forms[] = {')
for i, (asm, op, L, scale, isz, esz) in enumerate(FORMS):
    w(f'    {{"{asm.replace("%%", "").replace("(%1,", "(base,")}", f{i}, {scale}, {isz}, {esz}}},')
w('};')
w(f'#define NF {len(FORMS)}')
if answers:
    w('static const uint64_t want[NF] = {')
    for i in range(len(FORMS)):
        w(f'    {answers[str(i)]}ull,')
    w('};')
else:
    w('static const uint64_t want[NF];   // (run with "hashes" on camd)')
w(r'''
static sigjmp_buf jb;
static volatile int sig;
static uint32_t fx[8][4];
static void handler(int s, siginfo_t *si, void *ucv) {
    ucontext_t *uc = ucv;
    const unsigned char *fp = (const unsigned char *) uc->uc_mcontext.fpregs;
    (void) si;
#ifdef __x86_64__
    memcpy(fx, fp + 160, sizeof(fx));             /* the fxsave image's xmm0-7 */
#else
    memcpy(fx, fp + 272, sizeof(fx));
#endif
    sig = s;
    siglongjmp(jb, 1);
}
#ifdef __x86_64__
#define PTR "rax"
#else
#define PTR "eax"
#endif
#define UD(i, bytes) do { sig = 0; if (!sigsetjmp(jb, 1)) __asm__ volatile("vpxor %%xmm2,%%xmm2,%%xmm2\n vpcmpeqd %%xmm1,%%xmm1,%%xmm1\n" \
        "mov %0, %%" PTR "\n" bytes :: "r"(buf) : "xmm0", "xmm1", "xmm2", "eax", "memory"); got[i] = sig; } while (0)
static unsigned long fixed_checks(unsigned long *checks) {
    unsigned long bad = 0;
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_sigaction = handler;
    sa.sa_flags = SA_SIGINFO;
    sigaction(SIGILL, &sa, 0);
    sigaction(SIGSEGV, &sa, 0);
    static const char *const names[] = {"dst 0 mask 1 index 2", "dst = mask", "dst = index", "mask = index",
                                        "register form", "no SIB"};
    static const int want_sig[] = {0, SIGILL, SIGILL, SIGILL, SIGILL, SIGILL};
    volatile int got[6];
    UD(0, ".byte 0xc4,0xe2,0x71,0x90,0x04,0x90");
    UD(1, ".byte 0xc4,0xe2,0x71,0x90,0x0c,0x90");
    UD(2, ".byte 0xc4,0xe2,0x71,0x90,0x14,0x90");
    UD(3, ".byte 0xc4,0xe2,0x69,0x90,0x04,0x90");
    UD(4, ".byte 0xc4,0xe2,0x71,0x90,0xc2");
    UD(5, ".byte 0xc4,0xe2,0x71,0x90,0x00");
    for (int i = 0; i < 6; i++, (*checks)++)
        if (got[i] != want_sig[i] && bad++ < 40)
            printf("FAIL vpgatherdd %s: signal %d, want %d\n", names[i], got[i], want_sig[i]);
    /* element 2 of 4 at an unmapped page; element 1 masked off */
    char *pg = mmap(0, 8192, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    munmap(pg + 4096, 4096);
    for (int i = 0; i < 1024; i++)
        ((uint32_t *) pg)[i] = 0xa000 + i;
    static const int32_t idx[2][4] = {{1, 2, 1024 + 5, 3}, {1, 1024 + 9, 2, 3}};
    static const int32_t msk[4] = {-1, 0x7fffffff, -1, -1};
    static const uint32_t old[4] = {0x55, 0x66, 0x77, 0x88};
    static const uint32_t want[2][2][4] = {{{0xa001, 0x66, 0x77, 0x88}, {0, 0, 0xffffffff, 0xffffffff}},
                                           {{0xa001, 0x66, 0xa002, 0xa003}, {0, 0, 0, 0}}};
    static uint32_t out[2][4];
    for (volatile int t = 0; t < 2; t++, (*checks)++) {
        sig = 0;
        memset(fx, 0, sizeof(fx));
        if (!sigsetjmp(jb, 1))
            __asm__ volatile("vmovdqu %1, %%xmm2\n vmovdqu %2, %%xmm1\n vmovdqu %3, %%xmm0\n mov %0, %%" PTR "\n"
                             "vpgatherdd %%xmm1, (%%" PTR ",%%xmm2,4), %%xmm0\n vmovdqu %%xmm0, %4\n vmovdqu %%xmm1, 16+%4"
                             :: "r"(pg), "m"(idx[t]), "m"(msk), "m"(old), "m"(out) : "xmm0", "xmm1", "xmm2", "eax", "memory");
        const uint32_t *gd = t ? out[0] : fx[0], *gm = t ? out[1] : fx[1];
        if ((sig != (t ? 0 : SIGSEGV) || memcmp(gd, want[t][0], 16) || memcmp(gm, want[t][1], 16)) && bad++ < 40)
            printf("FAIL vpgatherdd %s: signal %d, dst %x %x %x %x mask %x %x %x %x\n", t ? "masked-off unmapped element" :
                   "fault at element 2", sig, gd[0], gd[1], gd[2], gd[3], gm[0], gm[1], gm[2], gm[3]);
    }
    return bad;
}

int main(int argc, char **argv) {
    int print = argc > 1 && !strcmp(argv[1], "hashes"), dump = argc > 1 && !strcmp(argv[1], "dump");
    unsigned long checks = 0, bad = 0;
    static struct st t;
    rs = 0x2545f4914f6cdd1dull;
    for (unsigned i = 0; i < sizeof(buf); i += 8) { uint64_t r = rnd(); memcpy(buf + i, &r, 8); }
    const uint8_t *base = buf + 32768;
    for (int fi = 0; fi < NF; fi++) {
        uint64_t h = 0xcbf29ce484222325ull;
        rs = 0x9e3779b97f4a7c15ull ^ (uint64_t) fi * 0x100000001b3ull;
        for (int k = 0; k < 400; k++) {
            for (int i = 0; i < 32; i += 8) {
                uint64_t r = rnd(); memcpy(t.d + i, &r, 8);
                r = rnd();
                int mode = k & 3;                   /* all set, none, random, random MSBs over random bits */
                if (mode == 0) r |= 0x8080808080808080ull;
                else if (mode == 1) r &= 0x7f7f7f7f7f7f7f7full;
                memcpy(t.m + i, &r, 8);
            }
            for (int i = 0; i < 32; i += forms[fi].isz) {     /* indices within +-2047 elements */
                int64_t v = (int64_t) (rnd() % 4095) - 2047;
                if (forms[fi].isz == 4) { int32_t v32 = (int32_t) v; memcpy(t.x + i, &v32, 4); }
                else memcpy(t.x + i, &v, 8);
            }
            forms[fi].fn(&t, base);
            for (int i = 0; i < 32; i++) h = (h ^ t.od[i]) * 0x100000001b3ull;
            for (int i = 0; i < 32; i++) h = (h ^ t.om[i]) * 0x100000001b3ull;
            for (int i = 0; i < 32; i++) h = (h ^ t.ox[i]) * 0x100000001b3ull;
            if (dump) {
                printf("%d %d:", fi, k);
                for (int i = 31; i >= 0; i--) printf("%02x", t.od[i]);
                printf(" ");
                for (int i = 31; i >= 0; i--) printf("%02x", t.om[i]);
                printf(" ");
                for (int i = 31; i >= 0; i--) printf("%02x", t.ox[i]);
                printf("\n");
            }
        }
        if (print) printf("%d %#llx\n", fi, (unsigned long long) h);
        checks++;
        if (!print && !dump && h != want[fi] && bad++ < 40)
            printf("FAIL %s\n", forms[fi].name);
    }
    if (!print && !dump)
        bad += fixed_checks(&checks);
    if (!print && !dump)
        printf("NAME: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NF, checks, bad);
    return bad != 0;
}''')
open(args[0], 'w').write('\n'.join(o).replace('NAME: %s', NAME + ': %s'))
print(len(FORMS), 'forms')
