#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_sse4_misc.c (usage: this script OUT.c).
#
# PTEST (flags), PEXTRB/W/D/Q and EXTRACTPS (to a GPR and to memory),
# PINSRB/D/Q and INSERTPS (from a GPR, from memory, xmm-xmm), CRC32 (r/m8,
# 16, 32, 64) -- against models: bits and bytes, and a bitwise CRC32C.
# Checked against real hardware (an AMD Ryzen).
import sys

F = []
def add(name, asm, model):
    F.append((name, asm, model))
add('ptest', 'ptest %%xmm2, %%xmm1', 'ptest')
add('ptest m', 'ptest (%%rdi), %%xmm1', 'ptestm')
add('ptest xmm9', 'movdqa %%xmm1, %%xmm9\\n movdqa %%xmm2, %%xmm10\\n ptest %%xmm10, %%xmm9', 'ptest')
for i in (0, 5, 15):
    add(f'pextrb {i} r', f'pextrb ${i}, %%xmm1, %%edx', f'pextr 1 {i} r')
    add(f'pextrb {i} m', f'pextrb ${i}, %%xmm1, (%%rdi)', f'pextr 1 {i} m')
    add(f'pinsrb {i} r', f'pinsrb ${i}, %%edx, %%xmm1', f'pinsr 1 {i} r')
    add(f'pinsrb {i} m', f'pinsrb ${i}, (%%rdi), %%xmm1', f'pinsr 1 {i} m')
for i in (0, 3, 7):
    add(f'pextrw3a {i} m', f'pextrw ${i}, %%xmm1, (%%rdi)', f'pextr 2 {i} m')
for i in (0, 1, 3):
    add(f'pextrd {i} r', f'pextrd ${i}, %%xmm1, %%edx', f'pextr 4 {i} r')
    add(f'pextrd {i} m', f'pextrd ${i}, %%xmm1, (%%rdi)', f'pextr 4 {i} m')
    add(f'pinsrd {i} r', f'pinsrd ${i}, %%edx, %%xmm1', f'pinsr 4 {i} r')
    add(f'pinsrd {i} m', f'pinsrd ${i}, (%%rdi), %%xmm1', f'pinsr 4 {i} m')
    add(f'extractps {i} r', f'extractps ${i}, %%xmm1, %%edx', f'pextr 4 {i} r')
    add(f'extractps {i} m', f'extractps ${i}, %%xmm1, (%%rdi)', f'pextr 4 {i} m')
for i in (0, 1):
    add(f'pextrq {i} r', f'pextrq ${i}, %%xmm1, %%rdx', f'pextr 8 {i} r')
    add(f'pextrq {i} m', f'pextrq ${i}, %%xmm1, (%%rdi)', f'pextr 8 {i} m')
    add(f'pinsrq {i} r', f'pinsrq ${i}, %%rdx, %%xmm1', f'pinsr 8 {i} r')
    add(f'pinsrq {i} m', f'pinsrq ${i}, (%%rdi), %%xmm1', f'pinsr 8 {i} m')
add('pextrd r9 xmm9', 'movdqa %%xmm1, %%xmm9\\n pextrd $2, %%xmm9, %%r9d\\n mov %%r9, %%rdx', 'pextr 4 2 r')
add('pinsrq r9 xmm9', 'movdqa %%xmm1, %%xmm9\\n mov %%rdx, %%r9\\n pinsrq $1, %%r9, %%xmm9\\n movdqa %%xmm9, %%xmm1', 'pinsr 8 1 r')
for imm in (0x00, 0x10, 0x25, 0x3a, 0x4f, 0xc0, 0xff, 0x9a):
    add(f'insertps {imm:#x}', f'insertps ${imm}, %%xmm2, %%xmm1', f'insertps {imm} r')
    add(f'insertps {imm:#x} m', f'insertps ${imm}, (%%rdi), %%xmm1', f'insertps {imm} m')
for w, sfx, src in ((1, 'b', '%%dl'), (2, 'w', '%%dx'), (4, 'l', '%%edx'), (8, 'q', '%%rdx')):
    dst = '%%rax' if w == 8 else '%%eax'
    add(f'crc32{sfx} r', f'mov %%rsi, %%rax\\n crc32{sfx} {src}, {dst}\\n mov %%rax, %%rdx', f'crc {w} r')
    add(f'crc32{sfx} m', f'mov %%rsi, %%rax\\n crc32{sfx} (%%rdi), {dst}\\n mov %%rax, %%rdx', f'crc {w} m')

o = []; w = o.append
w('''// Generated by tools/gen-amd64-sse4-misc-test.py -- do not edit.
//
// PTEST, PEXTRB/W/D/Q and EXTRACTPS, PINSRB/D/Q and INSERTPS, CRC32 (SSE4.1,
// SSE4.2): registers (xmm9/r9 too), memory, every lane or immediate kind
// that differs, against models (a bitwise CRC32C, no CRC instruction).
// Checked against real hardware (an AMD Ryzen).
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static unsigned long checks, bad;
static void check(const char *what, long k, uint64_t got, uint64_t want) {
    checks++;
    if (got != want && bad++ < 40)
        printf("FAIL %s (%ld): %#llx, want %#llx\\n", what, k, (unsigned long long) got, (unsigned long long) want);
}
static uint64_t rs = 0x243f6a8885a308d3ull;
static uint64_t rnd(void) { rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }
static uint32_t crc32c(uint32_t c, uint64_t v, int n) {
    for (int i = 0; i < 8 * n; i++) {
        int b = (int) ((c ^ (v >> i)) & 1);
        c = (c >> 1) ^ (b ? 0x82f63b78u : 0);
    }
    return c;
}
// the state: v = xmm1, s = xmm2, m = 16 bytes at rdi, g = rdx, a = rsi (crc's start)
struct st { uint8_t v[16], s[16], m[16]; uint64_t g, a, fl; };
''')
for i, (name, asm, model) in enumerate(F):
    w(f'''__attribute__((noinline)) static void f{i}(struct st *t) {{
    __asm__ volatile("movdqu (%0), %%xmm1\\n movdqu 16(%0), %%xmm2\\n lea 32(%0), %%rdi\\n mov 48(%0), %%rdx\\n mov 56(%0), %%rsi\\n"
                     " push $0x8d7\\n popfq\\n {asm}\\n pushfq\\n pop 64(%0)\\n movdqu %%xmm1, (%0)\\n mov %%rdx, 48(%0)"
                     :: "r"(t) : "memory", "cc", "rax", "rdx", "rsi", "rdi", "r9", "xmm1", "xmm2", "xmm9", "xmm10");
}}''')
w('static void (*const fns[])(struct st *) = {' + ', '.join(f'f{i}' for i in range(len(F))) + '};')
w('static const char *const names[] = {' + ', '.join(f'"{n}"' for n, _, _ in F) + '};')
w('static const char *const models[] = {' + ', '.join(f'"{m}"' for _, _, m in F) + '};')
w(f'#define NFORM {len(F)}')
w(r'''
static void model(const char *m, struct st *t) {
    int a, b; char kind[16], where;
    uint64_t g0 = t->g;
    if (!strcmp(m, "ptest") || !strcmp(m, "ptestm")) {
        const uint8_t *s = m[5] ? t->m : t->s;
        int zf = 1, cf = 1;
        for (int i = 0; i < 16; i++) { if (t->v[i] & s[i]) zf = 0; if (~t->v[i] & s[i]) cf = 0; }
        t->fl = (t->fl & ~0x8d5ull) | (zf ? 0x40 : 0) | (cf ? 1 : 0);
        return;
    }
    if (sscanf(m, "%15s %d %d %c", kind, &a, &b, &where) == 4 && !strcmp(kind, "pextr")) {
        uint64_t v = 0;
        memcpy(&v, t->v + a * b, a);
        if (where == 'r') t->g = v;                  // a 32/64-bit GPR write: zero-extended
        else memcpy(t->m, &v, a);
        return;
    }
    if (sscanf(m, "%15s %d %d %c", kind, &a, &b, &where) == 4 && !strcmp(kind, "pinsr")) {
        if (where == 'r') memcpy(t->v + a * b, &g0, a);
        else memcpy(t->v + a * b, t->m, a);
        return;
    }
    if (sscanf(m, "%15s %d %c", kind, &a, &where) == 3 && !strcmp(kind, "insertps")) {
        uint32_t src;
        if (where == 'r') memcpy(&src, t->s + 4 * ((a >> 6) & 3), 4);
        else memcpy(&src, t->m, 4);                  // memory: the dword at the address, imm[7:6] ignored
        memcpy(t->v + 4 * ((a >> 4) & 3), &src, 4);
        for (int i = 0; i < 4; i++) if ((a >> i) & 1) memset(t->v + 4 * i, 0, 4);
        return;
    }
    if (sscanf(m, "%15s %d %c", kind, &a, &where) == 3 && !strcmp(kind, "crc")) {
        uint64_t v = 0;
        if (where == 'r') v = g0; else memcpy(&v, t->m, 8);
        uint32_t c = crc32c((uint32_t) t->a, v, a);
        t->g = c;                                    // a 32-bit write zero-extends (crc32q too)
        return;
    }
}

int main(void) {
    static struct st t __attribute__((aligned(16))), want;
    for (int k = 0; k < 4000; k++) {
        for (int fi = 0; fi < NFORM; fi++) {
            for (int i = 0; i < 16; i++) { t.v[i] = (uint8_t) rnd(); t.s[i] = (uint8_t) rnd(); t.m[i] = (uint8_t) rnd(); }
            if (k % 5 == 0) for (int i = 0; i < 16; i++) { t.s[i] &= ~t.v[i]; t.m[i] &= ~t.v[i]; }   // ptest: ZF
            if (k % 5 == 1) for (int i = 0; i < 16; i++) { t.s[i] &= t.v[i]; t.m[i] &= t.v[i]; }     // ptest: CF
            if (k % 7 == 0) memset(t.s, 0, 16);
            t.g = rnd(); t.a = rnd(); t.fl = 0;
            want = t;
            fns[fi](&t);
            want.fl = 0x8d7 | 0x2;
            model(models[fi], &want);
            uint64_t x, y;
            for (int q = 0; q < 2; q++) { memcpy(&x, t.v + 8 * q, 8); memcpy(&y, want.v + 8 * q, 8); check(names[fi], fi * 10000 + k, x, y); }
            for (int q = 0; q < 2; q++) { memcpy(&x, t.m + 8 * q, 8); memcpy(&y, want.m + 8 * q, 8); check(names[fi], fi * 10000 + k, x, y); }
            check(names[fi], fi * 10000 + k, t.g, want.g);
            if (!strncmp(models[fi], "ptest", 5)) check(names[fi], fi * 10000 + k, t.fl & 0x8d5, want.fl & 0x8d5);
        }
    }
    printf("amd64_sse4_misc: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NFORM, checks, bad);
    return bad != 0;
}''')
open(sys.argv[1], 'w').write('\n'.join(o))
print(len(F), 'forms')
