#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_avx512_kmask.c, or with --i386
# i386_avx512_kmask.c (usage: this script [--i386] [--answers FILE] OUT.c).
#
# The AVX-512 opmask instructions (VEX-encoded): KAND/KANDN/KOR/KXNOR/KXOR/
# KADD/KNOT at every width, KUNPCKBW/WD/DQ, KMOV k<-k, k<-m, m<-k, k<-r and
# r<-k, KORTEST/KTEST (their flags), KSHIFTL/R across the counts, and a set
# of encodings whose #UD-or-not is part of the answer. Each form's outputs
# (all 64 bits of the k register, the stored bytes, the GPR, the flags, the
# signal) are hashed and checked against Intel SDE's (no real x86 here has
# AVX-512): on camd, `sde64 -spr -- ./test hashes`, passed to the generator
# with --answers. Forms are keyed and seeded by name, so the i386 test (no
# 64-bit GPR forms) takes the amd64 answers. "dump" prints every case.
import sys
I386 = '--i386' in sys.argv
args = [a for a in sys.argv[1:] if a != '--i386']
answers = {}
if '--answers' in args:
    i = args.index('--answers')
    for line in open(args[i + 1]):
        k, v = line.rsplit(' ', 1)
        answers[k] = v.strip()
    del args[i:i + 2]
NAME = 'i386_avx512_kmask' if I386 else 'amd64_avx512_kmask'
W = {'b': 8, 'w': 16, 'd': 32, 'q': 64}
F = []   # (name, kind, asm)
# kind: k3 (dst k1 from k2,k3), k2 (k1 from k2), mst (store k2 to mem), mld (k1 from mem),
#       r2k (k1 from GPR), k2r (GPR from k2), flags (k2,k3 -> flags), ud (raw bytes -> signal)
for op in ('kand', 'kandn', 'kor', 'kxnor', 'kxor', 'kadd'):
    for s in 'bwdq':
        F.append((f'{op}{s}', 'k3', f'{op}{s} %%k3, %%k2, %%k1'))
for s in 'bwdq':
    F.append((f'knot{s}', 'k2', f'knot{s} %%k2, %%k1'))
for s in ('bw', 'wd', 'dq'):
    F.append((f'kunpck{s}', 'k3', f'kunpck{s} %%k3, %%k2, %%k1'))
for s in 'bwdq':
    F.append((f'kmov{s} k,k', 'k2', f'kmov{s} %%k2, %%k1'))
    F.append((f'kmov{s} k,m', 'mld', f'kmov{s} 32(%0), %%k1'))
    F.append((f'kmov{s} m,k', 'mst', f'kmov{s} %%k2, 32(%0)'))
    F.append((f'kortest{s}', 'flags', f'kortest{s} %%k3, %%k2'))
    F.append((f'ktest{s}', 'flags', f'ktest{s} %%k3, %%k2'))
gprs = ('b', 'w', 'd') if I386 else ('b', 'w', 'd', 'q')
for s in gprs:
    r = '%%rcx' if s == 'q' else '%%ecx'
    F.append((f'kmov{s} k,r', 'r2k', f'kmov{s} {r}, %%k1'))
    F.append((f'kmov{s} r,k', 'k2r', f'kmov{s} %%k2, {r}'))
for d in ('l', 'r'):
    for s in 'bwdq':
        for imm in (0, 1, 3, W[s] - 1, W[s], W[s] + 1, 64, 255):
            F.append((f'kshift{d}{s} ${imm}', 'k2', f'kshift{d}{s} ${imm}, %%k2, %%k1'))
# encodings whose fault matters: L, vvvv, memory forms of register-only ops, W/pp holes
UD = {
    'kandw L0': 'c4 e1 6c 41 ca', 'kandw L1': 'c4 e1 6c 41 ca'.replace('6c', '6c'),
    'kandw ok': 'c5 ec 41 ca', 'kandw mem': 'c5 ec 41 08', 'knotw L1': 'c5 fc 44 ca',
    'knotw vvvv': 'c5 e8 44 ca', 'kmovw vvvv': 'c5 e8 90 ca', 'kmovw st reg': 'c5 f8 91 ca',
    'kunpck 66 W1': 'c4 e1 ed 4b ca', 'kmov 92 66 W1': 'c4 e1 f9 92 c8', 'kmov 92 0F W1': 'c4 e1 f8 92 c8',
    'kortestw L1': 'c5 fc 98 ca', 'kshiftlw L1': 'c4 e3 fd 32 ca 01', 'kshift 30 pp0': 'c4 e3 f8 30 ca 01',
    'kaddw L0': 'c5 e8 4a ca', 'kshiftrw mem': 'c4 e3 f9 30 08 01',
}
UD = {k: v for k, v in UD.items() if k != 'kandw L1'}
UD['kandw L0'] = 'c5 e8 41 ca'
if not I386:
    UD['kmovw REX.R'] = 'c4 61 78 90 ca'        # VEX.R=1 (k9?)
    UD['kmovw VEX.B'] = 'c4 c1 78 90 ca'
    UD['kandw vvvv bit3'] = 'c4 e1 2c 41 ca'
    UD.update({'kandw R': 'c4 61 6c 41 ca', 'kandw B': 'c4 c1 6c 41 ca', 'knotw R': 'c4 61 78 44 ca',
               'knotw B': 'c4 c1 78 44 ca', 'kmovw st R': 'c4 61 78 91 08', 'kmovw ld B': 'c4 c1 78 90 08',
               'kmov 92 R': 'c4 61 78 92 c8', 'kmov 92 B': 'c4 c1 78 92 c8', 'kmov 93 R': 'c4 61 78 93 c8',
               'kmov 93 B': 'c4 c1 78 93 c8', 'kortestw R': 'c4 61 78 98 ca', 'kortestw B': 'c4 c1 78 98 ca',
               'kshiftlw R': 'c4 63 f9 32 ca 01', 'kshiftlw B': 'c4 c3 f9 32 ca 01',
               'kunpckbw R': 'c4 61 6d 4b ca', 'kunpckbw B': 'c4 c1 6d 4b ca'})
for k, b in UD.items():
    F.append((f'ud {k}', 'ud', ', '.join('0x' + x for x in b.split())))
o = []; w = o.append
w(f'''// Generated by tools/gen-avx512-kmask-test.py{" --i386" if I386 else ""} -- do not edit.
//
// The AVX-512 opmask instructions against Intel SDE (see the generator).
#define _GNU_SOURCE
#include <setjmp.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
static uint64_t rs;
static uint64_t rnd(void) {{ rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }}
struct st {{ uint64_t k1, k2, k3, gpr; uint8_t m[16]; uint64_t ok1, ogpr, oflags; uint8_t om[16]; }};
static sigjmp_buf jb;
static volatile int sig;
static void handler(int s) {{ sig = s; siglongjmp(jb, 1); }}
// (no target pragma: the harness itself must not use AVX-512, which the i386
// guest's compiler would otherwise do for its 64-bit arithmetic)
''')
for i, (name, kind, asm) in enumerate(F):
    if kind == 'ud':
        w(f'''__attribute__((noinline)) static void f{i}(struct st *t) {{
    (void) t;
    __asm__ volatile("kxorq %%k1, %%k1, %%k1\\n kxorq %%k2, %%k2, %%k2\\n mov %0, %%" {'"eax"' if I386 else '"rax\\n mov %0, %%r8"'} "\\n .byte {asm}\\n" :: "r"(t->m) : "memory", "eax", "ecx"{'' if I386 else ', "r8", "r9"'});
}}''')
        continue
    gin = 'mov 24(%0), %%rcx' if not I386 else 'mov 24(%0), %%ecx'
    gout = 'mov %%rcx, 56(%0)' if not I386 else 'mov %%ecx, 56(%0)'
    flg = 'pushf\\n pop %%' + ('rcx' if not I386 else 'ecx') + '\\n mov %%' + ('rcx' if not I386 else 'ecx') + ', 64(%0)'
    pre = 'kmovq (%0), %%k1\\n kmovq 8(%0), %%k2\\n kmovq 16(%0), %%k3\\n ' + gin + '\\n'
    setf = 'xor %%ecx, %%ecx\\n add $0, %%ecx\\n'   # known flags before (ZF PF set)
    post = 'kmovq %%k1, 48(%0)\\n ' + gout
    if kind == 'flags':
        body = f'{setf} {asm}\\n {flg}'
    else:
        body = asm
    w(f'''__attribute__((noinline)) static void f{i}(struct st *t) {{
    __asm__ volatile("{pre} {body}\\n {post}" :: "r"(t) : "memory", "ecx", "cc");
}}''')
w('static const struct { const char *name; void (*fn)(struct st *); int ud, g64; } forms[] = {')
for i, (name, kind, asm) in enumerate(F):
    w(f'    {{"{name}", f{i}, {1 if kind == "ud" else 0}, {1 if name.startswith("kmovq") and ("r" in name.split()[1]) else 0}}},')
w('};')
w(f'#define NF {len(F)}')
if answers:
    w('static const uint64_t want[NF] = {')
    for name, kind, asm in F:
        w(f'    {answers[name]}ull,   // {name}')
    w('};')
else:
    w('static const uint64_t want[NF];   // (run with "hashes" under SDE)')
w(r'''
static int run(void (*fn)(struct st *), struct st *t) {
    sig = 0;
    if (!sigsetjmp(jb, 1))
        fn(t);
    return sig;
}

int main(int argc, char **argv) {
    int print = argc > 1 && !strcmp(argv[1], "hashes"), dump = argc > 1 && !strcmp(argv[1], "dump");
    unsigned long checks = 0, bad = 0;
    static struct st t;
    signal(SIGILL, handler);
    signal(SIGSEGV, handler);
    for (int fi = 0; fi < NF; fi++) {
        uint64_t h = 0xcbf29ce484222325ull;
        rs = 0x9e3779b97f4a7c15ull;
        for (const char *c = forms[fi].name; *c; c++) rs = (rs ^ (uint8_t) *c) * 0x100000001b3ull;
        if (!rs) rs = 1;
        for (int k = 0; k < (forms[fi].ud ? 1 : 200); k++) {
            t.k1 = rnd(); t.k2 = rnd(); t.k3 = rnd(); t.gpr = rnd();
            if ((k & 7) == 1) t.k3 = t.k2;               /* equal, zero and all-ones operands */
            if ((k & 7) == 2) t.k2 = 0;
            if ((k & 7) == 3) { t.k2 = ~0ull; t.k3 = ~0ull; }
            if ((k & 7) == 4) t.k3 = ~t.k2;
            uint64_t r = rnd(); memcpy(t.m, &r, 8); r = rnd(); memcpy(t.m + 8, &r, 8);
            t.ok1 = t.ogpr = t.oflags = 0;
            int sg = run(forms[fi].fn, &t);
            uint64_t out[4] = {t.ok1, t.ogpr, t.oflags & 0x8d5, (uint64_t) sg};
            if (forms[fi].ud) { out[0] = out[1] = out[2] = 0; }
            if (!forms[fi].g64) out[1] &= 0xffffffffull;   /* (the i386 test has 32-bit GPRs) */
            for (int i = 0; i < 4; i++) for (int b = 0; b < 8; b++) h = (h ^ ((out[i] >> (8 * b)) & 0xff)) * 0x100000001b3ull;
            for (int i = 0; i < 16; i++) h = (h ^ t.m[i]) * 0x100000001b3ull;
            if (dump)
                printf("%s %d: k1 %016llx gpr %016llx flags %03llx sig %d m %016llx\n", forms[fi].name, k,
                       (unsigned long long) out[0], (unsigned long long) out[1], (unsigned long long) out[2], sg,
                       (unsigned long long) *(uint64_t *) t.m);
        }
        if (print) printf("%s %#llx\n", forms[fi].name, (unsigned long long) h);
        checks++;
        if (!print && !dump && h != want[fi] && bad++ < 40)
            printf("FAIL %s\n", forms[fi].name);
    }
    if (!print && !dump)
        printf("NAME: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NF, checks, bad);
    return bad != 0;
}''')
open(args[0], 'w').write('\n'.join(o).replace('NAME: %s', NAME + ': %s'))
print(len(F), 'forms')
