#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_sse4_int.c (usage: this script OUT.c).
#
# The SSSE3 / SSE4.1 / SSE4.2 integer ops of the 0F 38 and 0F 3A maps --
# XMM (66) and, for SSSE3, MMX -- register and memory sources, xmm1/xmm9,
# against byte-array models (vectorisation off, so the model cannot become
# the instructions under test). Checked against real hardware (an AMD Ryzen).
import sys

# (mnemonic, model, lane bytes, mmx form, imm)
OPS = [
    ('pshufb', 'pshufb', 1, 1, None),
    ('phaddw', 'hadd', 2, 1, None), ('phaddd', 'hadd', 4, 1, None), ('phaddsw', 'hadds', 2, 1, None),
    ('phsubw', 'hsub', 2, 1, None), ('phsubd', 'hsub', 4, 1, None), ('phsubsw', 'hsubs', 2, 1, None),
    ('pmaddubsw', 'maddubsw', 2, 1, None), ('pmulhrsw', 'mulhrsw', 2, 1, None),
    ('psignb', 'sign', 1, 1, None), ('psignw', 'sign', 2, 1, None), ('psignd', 'sign', 4, 1, None),
    ('pabsb', 'abs', 1, 1, None), ('pabsw', 'abs', 2, 1, None), ('pabsd', 'abs', 4, 1, None),
    ('pmovsxbw', 'movx s1 2', 0, 0, None), ('pmovsxbd', 'movx s1 4', 0, 0, None), ('pmovsxbq', 'movx s1 8', 0, 0, None),
    ('pmovsxwd', 'movx s2 4', 0, 0, None), ('pmovsxwq', 'movx s2 8', 0, 0, None), ('pmovsxdq', 'movx s4 8', 0, 0, None),
    ('pmovzxbw', 'movx z1 2', 0, 0, None), ('pmovzxbd', 'movx z1 4', 0, 0, None), ('pmovzxbq', 'movx z1 8', 0, 0, None),
    ('pmovzxwd', 'movx z2 4', 0, 0, None), ('pmovzxwq', 'movx z2 8', 0, 0, None), ('pmovzxdq', 'movx z4 8', 0, 0, None),
    ('pmuldq', 'muldq', 8, 0, None), ('pcmpeqq', 'eq', 8, 0, None), ('pcmpgtq', 'gt', 8, 0, None),
    ('packusdw', 'packusdw', 4, 0, None),
    ('pminsb', 'mins', 1, 0, None), ('pminsd', 'mins', 4, 0, None), ('pminuw', 'minu', 2, 0, None), ('pminud', 'minu', 4, 0, None),
    ('pmaxsb', 'maxs', 1, 0, None), ('pmaxsd', 'maxs', 4, 0, None), ('pmaxuw', 'maxu', 2, 0, None), ('pmaxud', 'maxu', 4, 0, None),
    ('pmulld', 'mulld', 4, 0, None), ('phminposuw', 'minpos', 2, 0, None),
    ('pblendw', 'blendw', 2, 0, [0x00, 0xff, 0xa5, 0x3c]),
    ('palignr', 'alignr', 1, 1, [0, 3, 8, 15, 16, 20, 31, 32, 200, 250, 255]),
    ('mpsadbw', 'mpsadbw', 2, 0, [0, 1, 2, 3, 4, 5, 6, 7]),
]
o = []; w = o.append
w('''// Generated by tools/gen-amd64-sse4-int-test.py -- do not edit.
//
// SSSE3 / SSE4.1 / SSE4.2 integer ops (0F 38 and 0F 3A): PSHUFB, PHADD/PHSUB
// (and the saturating ones), PMADDUBSW, PMULHRSW, PSIGN, PABS, PMOVSX/ZX,
// PMULDQ, PCMPEQQ/GTQ, PACKUSDW, PMIN/PMAX (SB SD UW UD), PMULLD,
// PHMINPOSUW, PBLENDW, PALIGNR, MPSADBW -- XMM (66) and, where SSSE3 has
// them, MMX; register and memory sources, xmm1/xmm9 -- against byte-array
// models; checked against real hardware (an AMD Ryzen). Vectorisation is off:
// the model must not become SSE itself.
#pragma GCC optimize("no-tree-vectorize")
#include <setjmp.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

// One unknown instruction must not hide the rest: a SIGILL counts against its
// form and the run goes on.
static sigjmp_buf jb;
static void on_ill(int sig) { (void) sig; siglongjmp(jb, 1); }

static unsigned long checks, bad;
static void check(const char *what, long k, uint64_t got, uint64_t want) {
    checks++;
    if (got != want && bad++ < 40)
        printf("FAIL %s (%ld): %#llx, want %#llx\\n", what, k, (unsigned long long) got, (unsigned long long) want);
}
static uint64_t rs = 0x243f6a8885a308d3ull;
static uint64_t rnd(void) { rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }
static uint64_t get(const uint8_t *p, int lb) { uint64_t v = 0; for (int b = 0; b < lb; b++) v |= (uint64_t) p[b] << (8 * b); return v; }
static void put(uint8_t *p, int lb, uint64_t v) { for (int b = 0; b < lb; b++) p[b] = (uint8_t) (v >> (8 * b)); }
static int64_t sx(uint64_t v, int lb) { int s = 64 - 8 * lb; return lb == 8 ? (int64_t) v : (int64_t) (v << s) >> s; }
static int64_t clamp(int64_t v, int64_t lo, int64_t hi) { return v < lo ? lo : v > hi ? hi : v; }
static uint64_t mulu(uint64_t a, uint64_t b) { uint64_t r = 0; for (int i = 0; i < 64; i++) if ((b >> i) & 1) r += a << i; return r; }
static int64_t muls(int64_t a, int64_t b) { int n = (a < 0) != (b < 0); uint64_t r = mulu(a < 0 ? -(uint64_t) a : a, b < 0 ? -(uint64_t) b : b); return n ? -(int64_t) r : (int64_t) r; }

static void model(const char *m, int lb, int nb, const uint8_t *d, const uint8_t *s, int imm, uint8_t *out) {
    int n = lb ? nb / lb : 0;
    uint64_t mask = lb == 8 ? ~0ull : lb ? (1ull << (8 * lb)) - 1 : 0;
    if (!strcmp(m, "pshufb")) {
        for (int i = 0; i < nb; i++) out[i] = s[i] & 0x80 ? 0 : d[s[i] & (nb - 1)];
        return;
    }
    if (!strncmp(m, "hadd", 4) || !strncmp(m, "hsub", 4)) {
        int sub = m[1] == 's', sat = m[4] == 's';
        for (int half = 0; half < 2; half++) {
            const uint8_t *src = half ? s : d;
            for (int i = 0; i < n / 2; i++) {
                int64_t a = sx(get(src + 2 * i * lb, lb), lb), b = sx(get(src + (2 * i + 1) * lb, lb), lb);
                int64_t r = sub ? a - b : a + b;
                if (sat) r = clamp(r, -32768, 32767);
                put(out + (half * n / 2 + i) * lb, lb, (uint64_t) r);
            }
        }
        return;
    }
    if (!strcmp(m, "maddubsw")) {
        for (int i = 0; i < n; i++) {
            int64_t r = (int64_t) d[2 * i] * (int8_t) s[2 * i] + (int64_t) d[2 * i + 1] * (int8_t) s[2 * i + 1];
            put(out + 2 * i, 2, (uint64_t) clamp(r, -32768, 32767));
        }
        return;
    }
    if (!strcmp(m, "mulhrsw")) {
        for (int i = 0; i < n; i++) {
            int64_t p = muls(sx(get(d + 2 * i, 2), 2), sx(get(s + 2 * i, 2), 2));
            put(out + 2 * i, 2, (uint64_t) (((p >> 14) + 1) >> 1));
        }
        return;
    }
    if (!strncmp(m, "movx", 4)) {     // "movx s1 2": signed, source lane 1 byte, dest lane 2 bytes
        int sg = m[5] == 's', sl = m[6] - '0', dl = m[8] - '0';
        for (int i = 0; i < 16 / dl; i++) {
            uint64_t v = get(s + i * sl, sl);
            put(out + i * dl, dl, sg ? (uint64_t) sx(v, sl) : v);
        }
        return;
    }
    if (!strcmp(m, "muldq")) {
        for (int i = 0; i < 2; i++) put(out + 8 * i, 8, (uint64_t) muls(sx(get(d + 8 * i, 4), 4), sx(get(s + 8 * i, 4), 4)));
        return;
    }
    if (!strcmp(m, "packusdw")) {
        for (int i = 0; i < 4; i++) put(out + 2 * i, 2, (uint64_t) clamp(sx(get(d + 4 * i, 4), 4), 0, 65535));
        for (int i = 0; i < 4; i++) put(out + 8 + 2 * i, 2, (uint64_t) clamp(sx(get(s + 4 * i, 4), 4), 0, 65535));
        return;
    }
    if (!strcmp(m, "minpos")) {
        int best = 0;
        for (int i = 1; i < 8; i++) if (get(s + 2 * i, 2) < get(s + 2 * best, 2)) best = i;
        memset(out, 0, 16);
        put(out, 2, get(s + 2 * best, 2));
        put(out + 2, 2, (uint64_t) best);
        return;
    }
    if (!strcmp(m, "blendw")) {
        for (int i = 0; i < 8; i++) put(out + 2 * i, 2, get(((imm >> i) & 1 ? s : d) + 2 * i, 2));
        return;
    }
    if (!strcmp(m, "alignr")) {        // (dst:src) >> imm bytes, the low nb
        uint8_t cat[64] = {0};
        memcpy(cat, s, nb); memcpy(cat + nb, d, nb);
        for (int i = 0; i < nb; i++) out[i] = i + imm < 2 * nb ? cat[i + imm] : 0;
        return;
    }
    if (!strcmp(m, "mpsadbw")) {
        int so = (imm & 3) * 4, dof = ((imm >> 2) & 1) * 4;
        for (int i = 0; i < 8; i++) {
            int sum = 0;
            for (int j = 0; j < 4; j++) { int a = d[dof + i + j], b = s[so + j]; sum += a > b ? a - b : b - a; }
            put(out + 2 * i, 2, (uint64_t) sum);
        }
        return;
    }
    for (int i = 0; i < n; i++) {
        uint64_t a = get(d + i * lb, lb), b = get(s + i * lb, lb), r;
        int64_t sa = sx(a, lb), sb = sx(b, lb);
        if (!strcmp(m, "sign")) r = sb < 0 ? (uint64_t) -sa : sb == 0 ? 0 : a;
        else if (!strcmp(m, "abs")) r = sb < 0 ? (uint64_t) -sb : b;
        else if (!strcmp(m, "eq")) r = a == b ? mask : 0;
        else if (!strcmp(m, "gt")) r = sa > sb ? mask : 0;
        else if (!strcmp(m, "mins")) r = sa < sb ? a : b;
        else if (!strcmp(m, "maxs")) r = sa > sb ? a : b;
        else if (!strcmp(m, "minu")) r = a < b ? a : b;
        else if (!strcmp(m, "maxu")) r = a > b ? a : b;
        else if (!strcmp(m, "mulld")) r = (uint64_t) muls(sa, sb);
        else r = 0;
        put(out + i * lb, lb, r & mask);
    }
}
''')
forms = []
for mn, m, lb, mmx, imms in OPS:
    for x in (1, 0):
        if not x and not mmx:
            continue
        regs = [('%%xmm1', '%%xmm2'), ('%%xmm9', '%%xmm10')] if x else [('%%mm1', '%%mm2')]
        for imm in (imms or [None]):
            ia = '' if imm is None else f'${imm}, '
            for d, s in regs:
                forms.append(dict(name=f'{mn} {d[2:]}' + ('' if imm is None else f' {imm}'), m=m, lb=lb, x=x, imm=imm or 0, d=d, s=s, asm=f'{mn} {ia}{s}, {d}'))
            forms.append(dict(name=f'{mn} mem' + ('' if imm is None else f' {imm}') + ('' if x else ' mm'), m=m, lb=lb, x=x, imm=imm or 0, d=regs[0][0], s=regs[0][1], asm=f'{mn} {ia}(%%rdi), {regs[0][0]}'))
for i, f in enumerate(forms):
    ld = 'movdqu' if f['x'] else 'movq'
    tail = '' if f['x'] else '\\n emms'
    w(f'''__attribute__((noinline)) static void f{i}(uint8_t *v, uint8_t *src) {{
    __asm__ volatile("{ld} (%0), {f['d']}\\n {ld} (%1), {f['s']}\\n {f['asm']}\\n {ld} {f['d']}, (%0){tail}"
                     :: "S"(v), "D"(src) : "memory", "xmm1", "xmm2", "xmm9", "xmm10", "mm1", "mm2");
}}''')
w('struct form { const char *name, *m; int lb, x, imm; void (*fn)(uint8_t *, uint8_t *); };')
w('static const struct form forms[] = {')
for i, f in enumerate(forms):
    w(f'    {{"{f["name"]}", "{f["m"]}", {f["lb"]}, {f["x"]}, {f["imm"]}, f{i}}},')
w('};')
w(f'#define NFORMS {len(forms)}')
w('''
int main(void) {
    static uint8_t v[16] __attribute__((aligned(16))), src[16] __attribute__((aligned(16))), d0[16], want[16];
    struct sigaction sa;
    memset(&sa, 0, sizeof sa);
    sa.sa_handler = on_ill;
    sa.sa_flags = SA_NODEFER;
    sigaction(SIGILL, &sa, NULL);
    for (int k = 0; k < 1500; k++) {
        for (int fi = 0; fi < NFORMS; fi++) {
            const struct form *f = &forms[fi];
            for (int i = 0; i < 16; i++) { v[i] = (uint8_t) rnd(); src[i] = (uint8_t) rnd(); }
            switch (k % 6) {
            case 0: memcpy(src, v, 16); break;
            case 1: for (int i = 0; i < 16; i++) { v[i] |= 0x80; src[i] |= 0x7f; } break;
            case 2: for (int i = 0; i < 16; i += 2) src[i] = 0; break;
            case 3: memset(src, 0x80, 16); src[k % 16] = 0; break;
            case 4: for (int i = 0; i < 16; i++) src[i] &= 0x8f; break;    // pshufb: in-range indices
            }
            memcpy(d0, v, 16);
            if (sigsetjmp(jb, 1)) {
                check(f->name, fi * 10000 + k, 0xbad, 0);      // SIGILL
                __asm__ volatile("emms");
                continue;
            }
            f->fn(v, src);
            int nb = f->x ? 16 : 8;
            memcpy(want, d0, 16);
            model(f->m, f->lb, nb, d0, src, f->imm, want);
            uint64_t g0, g1, w0, w1;
            memcpy(&g0, v, 8); memcpy(&g1, v + 8, 8); memcpy(&w0, want, 8); memcpy(&w1, want + 8, 8);
            check(f->name, fi * 10000 + k, g0, w0);
            if (f->x) check(f->name, fi * 10000 + k, g1, w1);
        }
    }
    printf("amd64_sse4_int: %s (%d forms, %lu checks, %lu mismatches)\\n", bad ? "FAIL" : "PASS", NFORMS, checks, bad);
    return bad != 0;
}''')
open(sys.argv[1], 'w').write('\n'.join(o))
print(len(forms), 'forms')
