#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_alu_mem.c (usage: this script OUT.c): the
# x86 ALU with a memory operand in every form, against a model of the SDM.
import sys
OPS = ['add', 'or', 'adc', 'sbb', 'and', 'sub', 'xor', 'cmp']
SUF = {8: 'b', 16: 'w', 32: 'l', 64: 'q'}
REG = {8: '%b1', 16: '%w1', 32: '%k1', 64: '%q1'}
forms = []   # (name, op index, bits, kind, lock, asm)
for bits in (8, 16, 32, 64):
    s = SUF[bits]
    for i, op in enumerate(OPS):
        forms.append((f'{op}{s} r,m', i, bits, 'rm_dst', 0, f'{op}{s} {REG[bits]}, (%2)'))
        forms.append((f'{op}{s} m,r', i, bits, 'reg_dst', 0, f'{op}{s} (%2), {REG[bits]}'))
        forms.append((f'{op}{s} imm8,m', i, bits, 'imm8', 0, f'{op}{s} $IMM8, (%2)'))
        if bits > 8:
            forms.append((f'{op}{s} imm,m', i, bits, 'imm', 0, f'{op}{s} $IMM, (%2)'))
        if op != 'cmp':
            forms.append((f'lock {op}{s} r,m', i, bits, 'rm_dst', 1, f'lock {op}{s} {REG[bits]}, (%2)'))
            forms.append((f'lock {op}{s} imm8,m', i, bits, 'imm8', 1, f'lock {op}{s} $IMM8, (%2)'))
    forms.append((f'test{s} r,m', 8, bits, 'rm_dst', 0, f'test{s} {REG[bits]}, (%2)'))
    forms.append((f'test{s} imm,m', 8, bits, 'imm' if bits > 8 else 'imm8', 0,
                  f'test{s} $IMM, (%2)' if bits > 8 else f'test{s} $IMM8, (%2)'))
# register-register forms: dst %rcx-family, src %rdx-family, and the byte
# high/low combinations (ch,dh / cl,dh / ch,dl)
rr = []   # (name, op, bits, asm, dst_hi, src_hi)
RN = {8: ('%cl', '%dl'), 16: ('%cx', '%dx'), 32: ('%ecx', '%edx'), 64: ('%rcx', '%rdx')}
for bits in (8, 16, 32, 64):
    sfx = SUF[bits]
    for i, op in enumerate(OPS + ['test', 'mov']):
        d, sr = RN[bits]
        rr.append((f'{op}{sfx} {sr},{d}', i, bits, f'{op}{sfx} {sr}, {d}', 0, 0))
        if bits == 8:
            rr.append((f'{op}b %dh,%ch', i, 8, f'{op}b %dh, %ch', 1, 1))
            rr.append((f'{op}b %dh,%cl', i, 8, f'{op}b %dh, %cl', 0, 1))
            rr.append((f'{op}b %dl,%ch', i, 8, f'{op}b %dl, %ch', 1, 0))
o = []
w = o.append
w('''// Generated by tools/gen-amd64-alu-test.py -- do not edit.
//
// The x86 ALU with a memory operand -- ADD OR ADC SBB AND SUB XOR CMP and
// TEST, 8/16/32/64 bits, in the r/m,reg and reg,r/m directions and with
// imm8 and imm16/32 sources, with LOCK on the read-modify-write forms --
// against a model of the SDM: the memory or register result, and all six
// arithmetic flags (ADC/SBB with the carry in set and clear). Operands sit
// across page boundaries too, and a byte register may be AH..BH. LOCK on the
// misaligned operands, four threads adding to one counter, and LOCK CMP is
// #UD. The gadgets are math.S's amd64_alu_mem* and the narrower native
// families before them.
#define _GNU_SOURCE
#include <pthread.h>
#include <setjmp.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/mman.h>
#include <ucontext.h>

static unsigned long checks, bad;
static void check(const char *what, long k, uint64_t got, uint64_t want) {
    checks++;
    if (got != want && bad++ < 40)
        printf("FAIL %s (%ld): %#llx, want %#llx\\n", what, k, (unsigned long long) got, (unsigned long long) want);
}
#define CF 0x1
#define PF 0x4
#define AF 0x10
#define ZF 0x40
#define SF 0x80
#define OF 0x800
#define ARITH (CF | PF | AF | ZF | SF | OF)
static uint64_t rs = 0x9e3779b97f4a7c15ull;
static uint64_t rnd(void) { rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }

// the SDM: op 0 add 1 or 2 adc 3 sbb 4 and 5 sub 6 xor 7 cmp 8 test
static uint64_t model(int op, int bits, uint64_t a, uint64_t b, int cin, uint64_t *flags) {
    uint64_t m = bits == 64 ? ~0ull : (1ull << bits) - 1, sb = 1ull << (bits - 1), r;
    a &= m; b &= m;
    int c = (op == 2 || op == 3) ? cin : 0, cf = 0, of = 0, af = 0;
    if (op == 0 || op == 2) {
        unsigned __int128 full = (unsigned __int128) a + b + c;
        r = (uint64_t) full & m; cf = bits == 64 ? (int) (full >> 64) : (full >> bits) & 1;
        of = (~(a ^ b) & (a ^ r) & sb) != 0; af = ((a ^ b ^ r) & 0x10) != 0;
    } else if (op == 3 || op == 5 || op == 7) {
        r = (a - b - c) & m; cf = (unsigned __int128) b + c > a;
        of = ((a ^ b) & (a ^ r) & sb) != 0; af = ((a ^ b ^ r) & 0x10) != 0;
    } else {
        r = op == 1 ? a | b : op == 6 ? a ^ b : a & b;
    }
    uint64_t f = (cf ? CF : 0) | (of ? OF : 0) | (af ? AF : 0) | (r == 0 ? ZF : 0) | (r & sb ? SF : 0) |
                 (__builtin_parity((unsigned) (r & 0xff)) ? 0 : PF);
    *flags = f;
    return r;
}
''')
for i, f in enumerate(forms):
    name, op, bits, kind, lock, asm = f
    imm8 = 0x7b if op != 8 else 0x5a
    imm = 0x12345678 if bits > 16 else 0x1234
    if kind == 'imm8' and bits > 8:
        imm8 = -0x29  # sign-extended
    a = asm.replace('$IMM8', f'${imm8}').replace('$IMM', f'${imm}')
    cons = '"q"' if bits == 8 else '"r"'
    w(f'''__attribute__((noinline)) static void f{i}(uint8_t *p, uint64_t *reg, uint64_t *fl, int cin) {{
    uint64_t r = *reg, f;
    __asm__ volatile("test %3, %3\\n jz 1f\\n stc\\n jmp 2f\\n 1: clc\\n 2: {a}\\n pushfq\\n pop %0"
                     : "=&r"(f), "+{cons[1]}"(r) : "r"(p), "r"((long) cin) : "cc", "memory");
    *reg = r; *fl = f;
}}''')
for i, f in enumerate(rr):
    name, op, bits, asm, dh, sh = f
    asm = asm.replace('%', '%%')
    w(f'''__attribute__((noinline)) static void g{i}(uint64_t *c, uint64_t *d, uint64_t *fl, int cin) {{
    uint64_t rc = *c, rd = *d, f;
    __asm__ volatile("test %4, %4\\n jz 1f\\n stc\\n jmp 2f\\n 1: clc\\n 2: {asm}\\n pushfq\\n pop %0"
                     : "=&r"(f), "+c"(rc), "+d"(rd) : "0"(0), "r"((long) cin) : "cc");
    *c = rc; *d = rd; *fl = f;
}}''')
w('struct rrform { const char *name; int op, bits, dst_hi, src_hi; void (*fn)(uint64_t *, uint64_t *, uint64_t *, int); };')
w('static const struct rrform rrforms[] = {')
for i, f in enumerate(rr):
    name, op, bits, asm, dh, sh = f
    w(f'    {{"{name}", {op}, {bits}, {dh}, {sh}, g{i}}},')
w('};')
w(f'#define NRR {len(rr)}')
w('struct form { const char *name; int op, bits, kind, lock; void (*fn)(uint8_t *, uint64_t *, uint64_t *, int); long imm; };')
w('static const struct form forms[] = {')
for i, f in enumerate(forms):
    name, op, bits, kind, lock, asm = f
    imm8 = 0x7b if op != 8 else 0x5a
    if kind == 'imm8' and bits > 8: imm8 = -0x29
    imm = 0x12345678 if bits > 16 else 0x1234
    immv = imm8 if kind == 'imm8' else (imm if kind == 'imm' else 0)
    kk = {'rm_dst': 0, 'reg_dst': 1, 'imm8': 2, 'imm': 2}[kind]
    w(f'    {{"{name}", {op}, {bits}, {kk}, {lock}, f{i}, {immv}}},')
w('};')
w(f'#define NFORMS {len(forms)}')
w(open(sys.argv[0].replace('.py', '.tail.c')).read())
open(sys.argv[1], 'w').write('\n'.join(o))
print(len(forms), 'forms')
