#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_sse_ud.c: every 0F SSE/MMX opcode that
# takes a ModRM byte, under each prefix (none, 66, F3, F2), register, REX
# register and memory forms, run under a SIGILL/SIGSEGV/SIGFPE catcher; the
# signal each raises (or none) is checked against what real x86 hardware did.
#
#   tools/gen-amd64-sse-ud-test.py probe PROBE.c        # run PROBE on x86-64
#   tools/gen-amd64-sse-ud-test.py test ANSWERS OUT.c   # ANSWERS = its output
import sys

OPS = ([0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f] +
       list(range(0x50, 0x77)) + [0x7c, 0x7d, 0x7e, 0x7f, 0xc2, 0xc4, 0xc5, 0xc6, 0xd0] + list(range(0xd1, 0x100)))
IMM = {0x70, 0x71, 0x72, 0x73, 0xc2, 0xc4, 0xc5, 0xc6}
forms = []
# the three-byte maps too: 0F 38 xx (no imm) and 0F 3A xx (imm8), every op3
for m3, imm in ((0x38, False), (0x3a, True)):
    for op3 in range(256):
        for pfx in ([], [0x66], [0xf3], [0xf2]):
            for kind in ('reg', 'mem'):
                b = list(pfx) + [0x0f, m3, op3, 0x06 if kind == 'mem' else 0xc1] + ([0x03] if imm else [])
                forms.append((m3 << 8 | op3, pfx, kind, b))
for op in OPS:
    for pfx in ([], [0x66], [0xf3], [0xf2]):
        for kind in ('reg', 'mem', 'rexreg'):
            b = list(pfx) + ([0x4d] if kind == 'rexreg' else []) + [0x0f, op, 0x06 if kind == 'mem' else 0xc1]
            if op in IMM:
                b.append(0x03)
            forms.append((op, pfx, kind, b))

HEAD = r'''#include <setjmp.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
static sigjmp_buf jb;
static volatile int last;
static void h(int s) { last = s; siglongjmp(jb, 1); }
static uint8_t buf[64] __attribute__((aligned(64)));
'''

def body():
    o = []
    for i, (op, pfx, kind, b) in enumerate(forms):
        bs = ', '.join('0x%02x' % x for x in b)
        o.append(f'__attribute__((noinline)) static void f{i}(void) {{ __asm__ volatile("mov %0, %%rsi\\n xor %%eax, %%eax\\n .byte {bs}\\n emms" :: "r"(buf + 16) : "rsi", "rax", "rcx", "rdx", "memory", "cc", "xmm0", "xmm1", "xmm9", "mm0", "mm1"); }}')
    o.append('static void (*const fns[])(void) = {' + ', '.join(f'f{i}' for i in range(len(forms))) + '};')
    o.append('static const char *const names[] = {' + ', '.join('"%s %s %s"' % ('%04x' % op if op > 0xff else '%02x' % op, '/'.join('%02x' % p for p in pfx) or '-', kind) for op, pfx, kind, b in forms) + '};')
    o.append(f'#define NFORM {len(forms)}')
    return o

RUN = r'''
    struct sigaction sa;
    memset(&sa, 0, sizeof sa);
    sa.sa_handler = h;
    sa.sa_flags = SA_NODEFER;
    sigaction(SIGILL, &sa, NULL); sigaction(SIGSEGV, &sa, NULL);
    sigaction(SIGFPE, &sa, NULL); sigaction(SIGBUS, &sa, NULL);
    for (int i = 0; i < NFORM; i++) {
        last = 0;
        if (!sigsetjmp(jb, 1))
            fns[i]();
        RESULT
    }
'''

if sys.argv[1] == 'probe':
    o = [HEAD] + body() + ['int main(void) {', RUN.replace('RESULT', 'printf("%d\\n", last);'), '    return 0;\n}']
    open(sys.argv[2], 'w').write('\n'.join(o))
    print(len(forms), 'forms')
else:
    want = [int(x) for x in open(sys.argv[2]).read().split()]
    assert len(want) == len(forms)
    # What the AMD runs and AOK does not implement, so #UD here, as on a CPU
    # without them: SSE4A's MOVNTSS/MOVNTSD (F3/F2 0F 2B), SHA (0F 38 C8-CD,
    # 0F 3A CC), ADX (66/F3 0F 38 F6), MOVBE (0F 38 F0/F1, none or 66). (AES
    # and PCLMULQDQ run, as the AMD has them; *_avx512_ext.c checks them.)
    for i, (op, pfx, kind, b) in enumerate(forms):
        p = pfx[0] if pfx else 0
        if ((op == 0x2b and p in (0xf3, 0xf2) and kind == 'mem') or
                (0x38c8 <= op <= 0x38cd and p == 0) or (op == 0x3acc and p == 0) or
                (op == 0x38f6 and p in (0x66, 0xf3)) or
                (op in (0x38f0, 0x38f1) and p in (0, 0x66))):
            want[i] = 4
        # GFNI (66 0F 38 CF, 66 0F 3A CE/CF), which the AMD lacks: AOK runs it, as a
        # CPU with it does (tests/manual/x86/*_avx512_ext.c checks it against SDE)
        if op in (0x38cf, 0x3ace, 0x3acf) and p == 0x66:
            want[i] = 0
    o = ['''// Generated by tools/gen-amd64-sse-ud-test.py -- do not edit.
//
// Every 0F SSE/MMX opcode with a ModRM byte, and every op3 of the 0F 38 and
// 0F 3A maps, under each prefix, register,
// REX register and memory forms: the signal it raises -- SIGILL for an
// encoding x86 does not have, none for one it does -- against what an AMD
// Ryzen did -- but for what AOK does not implement (SSE4A, SHA, ADX, MOVBE),
// which the AMD runs and AOK, like a CPU without them, does not, and GFNI,
// which AOK runs and the AMD does not have. A valid instruction run as #UD,
// or an invalid one executed, fails here.''', HEAD] + body()
    o.append('static const unsigned char want[] = {' + ','.join(str(w) for w in want) + '};')
    o.append('int main(void) {\n    unsigned long checks = 0, bad = 0;')
    o.append(RUN.replace('RESULT', '''checks++;
        if (last != want[i] && bad++ < 40)
            printf("FAIL %s: signal %d, want %d\\n", names[i], last, want[i]);'''))
    o.append('    printf("amd64_sse_ud: %s (%d forms, %lu checks, %lu mismatches)\\n", bad ? "FAIL" : "PASS", NFORM, checks, bad);\n    return bad != 0;\n}')
    open(sys.argv[3], 'w').write('\n'.join(o))
    print(len(forms), 'forms')
