#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_vex_gpr.c, or with --i386 i386_vex_gpr.c
# (usage: this script [--i386] OUT.c).
#
# The VEX ops between vector and general registers or EFLAGS: VCVT(T)SS2SI/
# SD2SI and VCVTSI2SS/SD (against their SSE forms, MXCSR flags included),
# V(U)COMISS/SD (against SSE: EFLAGS and MXCSR), VMOVMSKPS/PD, VPMOVMSKB,
# VPTEST, VTESTPS/PD, VPINSRB/W/D/Q, VINSERTPS, VPEXTRB/W/D/Q, VEXTRACTPS
# (against byte models). camd runs it too.
import sys
I386 = '--i386' in sys.argv
ARGS = [a for a in sys.argv[1:] if a != '--i386']
NAME = 'i386_vex_gpr' if I386 else 'amd64_vex_gpr'
G = 'edx' if I386 else 'rdx'
G32 = 'edx'
F = []   # (name, vex asm, ref asm or None, model C or None, kind)
# kind: 'g' compare out+gpr; 'f' compare flags (eflags & 0x8d5) and mxcsr; 'v' vector out
def add(name, vex, ref=None, model=None):
    F.append((name, vex, ref, model))
for t, n in (('ss', 4), ('sd', 8)):
    for tr in ('', 't'):
        widths = [32] if I386 else [32, 64]
        for wd in widths:
            r = G32 if wd == 32 else 'rdx'
            add(f'vcvt{tr}{t}2si{wd} reg', f'vcvt{tr}{t}2si %%xmm3, %%{r}', f'cvt{tr}{t}2si %%xmm3, %%{r}')
            add(f'vcvt{tr}{t}2si{wd} mem', f'vcvt{tr}{t}2si 128(%0), %%{r}', f'cvt{tr}{t}2si 128(%0), %%{r}')
    widths = [('l', G32)] if I386 else [('l', G32), ('q', 'rdx')]
    for sfx, r in widths:
        add(f'vcvtsi2{t}{sfx} reg', f'vcvtsi2{t}{sfx} %%{r}, %%xmm2, %%xmm1', f'vmovdqa %%xmm2, %%xmm1\\n cvtsi2{t}{sfx} %%{r}, %%xmm1')
        add(f'vcvtsi2{t}{sfx} mem', f'vcvtsi2{t}{sfx} 128(%0), %%xmm2, %%xmm1', f'vmovdqa %%xmm2, %%xmm1\\n cvtsi2{t}{sfx} 128(%0), %%xmm1')
    for op in ('comi', 'ucomi'):
        add(f'v{op}{t} reg', f'v{op}{t} %%xmm3, %%xmm2', f'{op}{t} %%xmm3, %%xmm2')
        add(f'v{op}{t} mem', f'v{op}{t} 128(%0), %%xmm2', f'{op}{t} 128(%0), %%xmm2')
for L, x in ((256, 'ymm'), (128, 'xmm')):
    n = L // 8
    add(f'vmovmskps {L}', f'vmovmskps %%{x}3, %%{G32}', model=f'go = 0; for (int i = 0; i < {n}; i += 4) go |= (uint64_t) (b[i + 3] >> 7) << (i / 4);')
    add(f'vmovmskpd {L}', f'vmovmskpd %%{x}3, %%{G32}', model=f'go = 0; for (int i = 0; i < {n}; i += 8) go |= (uint64_t) (b[i + 7] >> 7) << (i / 8);')
    add(f'vpmovmskb {L}', f'vpmovmskb %%{x}3, %%{G32}', model=f'go = 0; for (int i = 0; i < {n}; i++) go |= (uint64_t) (b[i] >> 7) << i;')
    for op, mask in (('vptest', None), ('vtestps', 4), ('vtestpd', 8)):
        mk = '0xff' if mask is None else f'((i % {mask}) == {mask} - 1 ? 0x80 : 0)'
        model = (f'int z = 1, c = 1; for (int i = 0; i < {n}; i++) {{ uint8_t mm = {mk}; if (a[i] & S[i] & mm) z = 0; if (~a[i] & S[i] & mm) c = 0; }} '
                 'fo = (z ? 0x40 : 0) | (c ? 1 : 0);')
        add(f'{op} {L} reg', f'{op} %%{x}3, %%{x}2', model=model.replace('S', 'b'))
        add(f'{op} {L} mem', f'{op} 128(%0), %%{x}2', model=model.replace('S', 'm'))
for op, n, lanes in (('vpinsrb', 1, (0, 5, 15, 16 + 3)), ('vpinsrw', 2, (0, 3, 7, 9)), ('vpinsrd', 4, (0, 1, 3, 6)), ('vpinsrq', 8, (0, 1, 2, 3))):
    if I386 and op == 'vpinsrq':
        continue
    for i in lanes:
        li = i % (16 // n)
        r = 'rdx' if n == 8 else G32
        model = f'memcpy(o, a, 16); memcpy(o + {li * n}, &g, {n});'
        add(f'{op} {i} reg', f'{op} ${i}, %%{r}, %%xmm2, %%xmm1', model=model)
        add(f'{op} {i} mem', f'{op} ${i}, 128(%0), %%xmm2, %%xmm1', model=f'memcpy(o, a, 16); memcpy(o + {li * n}, m, {n});')
for imm in (0x00, 0x10, 0x25, 0x3a, 0x4f, 0xc0, 0xff, 0x9a, 0x30, 0xe1):
    add(f'vinsertps {imm:#x} reg', f'vinsertps ${imm}, %%xmm3, %%xmm2, %%xmm1', f'vmovdqa %%xmm2, %%xmm1\\n insertps ${imm}, %%xmm3, %%xmm1')
    add(f'vinsertps {imm:#x} mem', f'vinsertps ${imm}, 128(%0), %%xmm2, %%xmm1', f'vmovdqa %%xmm2, %%xmm1\\n insertps ${imm}, 128(%0), %%xmm1')
for op, n, lanes in (('vpextrb', 1, (0, 7, 15, 17)), ('vpextrw', 2, (0, 3, 7, 9)), ('vpextrd', 4, (0, 1, 3, 5)),
                     ('vpextrq', 8, (0, 1, 3)), ('vextractps', 4, (0, 2, 3, 6))):
    if I386 and op == 'vpextrq':
        continue
    for i in lanes:
        li = i % (16 // n)
        r = 'rdx' if n == 8 else G32
        add(f'{op} {i} reg', f'{op} ${i}, %%xmm3, %%{r}', model=f'go = 0; memcpy(&go, b + {li * n}, {n});')
        add(f'{op} {i} mem', f'{op} ${i}, %%xmm3, 128(%0)', model=f'memcpy(mo, b + {li * n}, {n});')
for i in (0, 3, 7, 12):
    add(f'vpextrw c5 {i}', f'.byte 0xc5, 0xf9, 0xc5, 0xd3, {i}', model=f'go = 0; memcpy(&go, b + {(i % 8) * 2}, 2);')   # vpextrw edx, xmm3

o = []; w = o.append
w(f'''// Generated by tools/gen-vex-gpr-test.py{" --i386" if I386 else ""} -- do not edit.
//
// The VEX ops between vector and general registers or EFLAGS (see the
// generator).
#pragma GCC target("avx2")
#include <stdint.h>
#include <stdio.h>
#include <string.h>
static unsigned long checks, bad;
static uint64_t rs = 0x9e3779b97f4a7c15ull;
static uint64_t rnd(void) {{ rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }}
static void ldmx(unsigned v) {{ __asm__ volatile("ldmxcsr %0" :: "m"(v)); }}
static unsigned stmx(void) {{ unsigned v; __asm__ volatile("stmxcsr %0" : "=m"(v)); return v; }}
struct st {{ uint8_t a[32], b[32], d[32], out[32], m[64]; uint64_t g, gout, fl; }} __attribute__((aligned(32)));
#define GMASK {"0xffffffffull" if I386 else "~0ull"}
''')
PRE = f'"vmovdqu (%0), %%ymm2\\n vmovdqu 32(%0), %%ymm3\\n vmovdqu 64(%0), %%ymm1\\n mov 192(%0), %%{G}\\n push $0x8d7\\n popf\\n"'
POST = f'"\\n pushf\\n pop 208(%0)\\n vmovdqu %%ymm1, 96(%0)\\n mov %%{G}, 200(%0)\\n vzeroupper"'
for i, (name, vex, ref, model) in enumerate(F):
    w(f'__attribute__((noinline)) static void f{i}(struct st *t) {{ __asm__ volatile({PRE} "{vex}" {POST} :: "r"(t) : "memory", "cc", "{G}", "xmm1", "xmm2", "xmm3"); }}')
    if ref:
        w(f'__attribute__((noinline)) static void r{i}(struct st *t) {{ __asm__ volatile({PRE} "{ref}" {POST} :: "r"(t) : "memory", "cc", "{G}", "xmm1", "xmm2", "xmm3"); }}')
    if model:
        w(f'''static void m{i}(const uint8_t *a, const uint8_t *b, const uint8_t *d, const uint8_t *m, uint64_t g, uint8_t *o, uint8_t *mo, uint64_t *gop, uint64_t *fop) {{
    uint64_t go = g, fo = 0x8d7; (void) a; (void) b; (void) d; (void) m; (void) mo;
    memcpy(o, d, 32);
    {model}
    *gop = go; *fop = fo;
}}''')
w('static const struct { const char *name; void (*fn)(struct st *); void (*ref)(struct st *); void (*model)(const uint8_t *, const uint8_t *, const uint8_t *, const uint8_t *, uint64_t, uint8_t *, uint8_t *, uint64_t *, uint64_t *); int vec_out; } forms[] = {')
for i, (name, vex, ref, model) in enumerate(F):
    vec = 1 if ('insr' in name or 'insertps' in name or 'cvtsi2' in name) else 0
    w(f'    {{"{name}", f{i}, {"r%d" % i if ref else "NULL"}, {"m%d" % i if model else "NULL"}, {vec}}},')
w('};')
w(f'#define NFORMS {len(F)}')
w(r'''
static const unsigned modes[] = {0x1f80, 0x7f80, 0x9fc0};
int main(void) {
    static struct st t, u;
    for (int k = 0; k < 400; k++) {
        for (int fi = 0; fi < NFORMS; fi++) {
            for (unsigned mi = 0; mi < (forms[fi].ref ? 3u : 1u); mi++) {
                for (int i = 0; i < 32; i += 4) {
                    uint32_t v = (uint32_t) rnd();
                    static const uint32_t sp[] = {0x7fc00000, 0x7f800001, 0xff800000, 0x00000001, 0x80000000, 0x4f000000, 0xcf000001, 0x3fc00000, 0x5f000000, 0xdf000000};
                    if ((v & 7) == 0) v = sp[(v >> 3) % 10];
                    else if (k & 1) v = (v & 0x807fffff) | (((v >> 23) % 70 + 100) << 23);
                    memcpy(t.a + i, &v, 4); v = (uint32_t) rnd(); if ((v & 7) == 0) v = sp[(v >> 3) % 10]; else if (k & 1) v = (v & 0x807fffff) | (((v >> 23) % 70 + 100) << 23);
                    memcpy(t.b + i, &v, 4); v = (uint32_t) rnd(); memcpy(t.d + i, &v, 4);
                }
                if (k % 5 == 2) memcpy(t.b, t.a, 32);
                for (int i = 0; i < 64; i++) t.m[i] = (uint8_t) rnd();
                if (k & 2) memcpy(t.m, t.b, 32);
                t.g = rnd() & GMASK; if (k % 3 == 0) t.g = (uint64_t) (int64_t) (int32_t) t.g & GMASK;
                t.gout = 0; t.fl = 0;
                u = t;
                ldmx(modes[mi]);
                forms[fi].fn(&t);
                unsigned gf = stmx() & 0x3f, wf;
                uint8_t o[32], mo[64];
                uint64_t go, fo;
                if (forms[fi].ref) {
                    ldmx(modes[mi]);
                    forms[fi].ref(&u);
                    wf = stmx() & 0x3f;
                    memcpy(o, u.out, 32);
                    if (forms[fi].vec_out) memset(o + 16, 0, 16);
                    memcpy(mo, u.m, 64); go = u.gout; fo = u.fl;
                } else {
                    memcpy(mo, u.m, 64);
                    forms[fi].model(u.a, u.b, u.d, u.m, u.g, o, mo, &go, &fo);
                    if (forms[fi].vec_out) memset(o + 16, 0, 16);
                    wf = gf;
                }
                go &= GMASK;
                checks++;
                if ((memcmp(t.out, o, 32) || memcmp(t.m, mo, 64) || (t.gout & GMASK) != go || (t.fl & 0x8d5) != (fo & 0x8d5) || gf != wf) && bad++ < 40) {
                    printf("FAIL %s (%d, mode %#x): gpr %llx want %llx, flags %llx want %llx, mxcsr %#x want %#x, mem %s\n  got ",
                           forms[fi].name, k, modes[mi], (unsigned long long) t.gout, (unsigned long long) go,
                           (unsigned long long) (t.fl & 0x8d5), (unsigned long long) (fo & 0x8d5), gf, wf, memcmp(t.m, mo, 64) ? "DIFFERS" : "ok");
                    for (int i = 31; i >= 0; i--) printf("%s%02x", i % 8 == 7 ? " " : "", t.out[i]);
                    printf("\n  want");
                    for (int i = 31; i >= 0; i--) printf("%s%02x", i % 8 == 7 ? " " : "", o[i]);
                    printf("\n");
                }
            }
        }
    }
    ldmx(0x1f80);
    printf("NAME: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NFORMS, checks, bad);
    return bad != 0;
}''')
open(ARGS[0], 'w').write('\n'.join(o).replace('NAME: %s', NAME + ': %s'))
print(len(F), 'forms')
