#!/usr/bin/env python3
# Generates tests/manual/arm64/arm64_vldst_gadgets.c (usage: this script
# OUT.c): every AdvSIMD structure load/store form, checked against a model
# of the Arm ARM in the test. See the generated file's header.
import sys

ARR = {0: ('8b', '16b'), 1: ('4h', '8h'), 2: ('2s', '4s'), 3: ('1d', '2d')}
SUF = 'bhsd'
WB = ('none', 'imm', 'reg')
forms = []  # (kind, count, esz, q, lane, load, wb, rt)

for load in (1, 0):
    for kind, count in ((0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4)):
        for esz in range(4):
            for q in (0, 1):
                if kind == 1 and esz == 3 and q == 0:
                    continue          # LD2-4 have no .1d
                for wb in WB:
                    forms.append((kind, count, esz, q, 0, load, wb, 4))
            if count >= 3:
                forms.append((kind, count, esz, 1, 0, load, 'none', 30))
    for count in (1, 2, 3, 4):
        for esz, lanes in ((0, (0, 7, 15)), (1, (0, 5)), (2, (1, 3)), (3, (0, 1))):
            for lane in lanes:
                for wb in WB:
                    forms.append((2, count, esz, 0, lane, load, wb, 4))
            if count >= 3:
                forms.append((2, count, esz, 0, lanes[-1], load, 'none', 30))
for count in (1, 2, 3, 4):
    for esz in range(4):
        for q in (0, 1):
            for wb in WB:
                forms.append((3, count, esz, q, 0, 1, wb, 4))
        if count >= 3:
            forms.append((3, count, esz, 1, 0, 1, 'none', 30))

def asm_for(f):
    kind, count, esz, q, lane, load, wb, rt = f
    vr = [(rt + j) % 32 for j in range(count)]
    if kind == 2:
        lst = '{%s}[%d]' % (', '.join('v%d.%s' % (v, SUF[esz]) for v in vr), lane)
        mn = ('ld%d' if load else 'st%d') % count
        total = count << esz
    else:
        lst = '{%s}' % ', '.join('v%d.%s' % (v, ARR[esz][q]) for v in vr)
        if kind == 3:
            mn, total = 'ld%dr' % count, count << esz
        else:
            mn = ('ld%d' if load else 'st%d') % (1 if kind == 0 else count)
            total = count * (16 if q else 8)
    post = {'none': '', 'imm': ', #%d' % total, 'reg': ', x10'}[wb]
    return '%s %s, [x9]%s' % (mn, lst, post), vr

NL = chr(92) + 'n'
o = []
w = o.append
w('''// Generated by tools/gen-a64-vldst-test.py -- do not edit.
//
// Every AdvSIMD structure load/store form -- LD1-LD4/ST1-ST4 multiple,
// LD1-LD4/ST1-ST4 single lane, LD1R-LD4R -- with no writeback, post-index
// immediate and post-index register, register lists that wrap past v31,
// at placements that cross a page, end on one, sit mid-page and land on
// fresh (TLB-missing) pages, against a model of the Arm ARM written here.
// Faults: a load crossing into PROT_NONE, and a store crossing into a
// read-only page, deliver SIGSEGV at the instruction with the address in
// the bad page and every register (the V registers and the base) unchanged.
// It builds natively on an arm64 host too, where the hardware checks the
// model (the fault cases are Linux-only).
#define _GNU_SOURCE
#include <setjmp.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#if defined(__linux__)
#include <ucontext.h>
#define LBL(i) ".globl vldst_op_" #i "\\n vldst_op_" #i ":\\n"
#else
#define LBL(i) ""
#endif

typedef struct { uint8_t b[16]; } v128;
struct form {
    const char *name;
    int kind, count, esz, q, lane, load, wb, rt;
    void (*fn)(uint8_t *, const v128 *, v128 *, uint64_t *);
    const char *pc;
};
#define RM_VAL 0x123
''')
for i, f in enumerate(forms):
    text, vr = asm_for(f)
    w('__attribute__((noinline)) static void fn_%d(uint8_t *mem, const v128 *init, v128 *out, uint64_t *wb) {' % i)
    w('    __asm__ volatile(')
    for j, v in enumerate(vr):
        w('        "ldr q%d, [%%[init], #%d]%s"' % (v, 16 * j, NL))
    w('        "mov x9, %%[mem]%s"' % NL)
    w('        "mov x10, #%d%s"' % (0x123, NL))
    w('        LBL(%d)' % i)
    w('        "%s%s"' % (text, NL))
    for j, v in enumerate(vr):
        w('        "str q%d, [%%[out], #%d]%s"' % (v, 16 * j, NL))
    w('        "str x9, [%%[wb]]%s"' % NL)
    w('        :: [mem] "r"(mem), [init] "r"(init), [out] "r"(out), [wb] "r"(wb)')
    w('        : "x9", "x10", %s, "memory");' % ', '.join('"v%d"' % v for v in vr))
    w('}')
w('')
w('#if defined(__linux__)')
for i in range(len(forms)):
    w('extern char vldst_op_%d[];' % i)
w('#define PC(i) vldst_op_##i')
w('#else')
w('#define PC(i) 0')
w('#endif')
w('')
w('static const struct form forms[] = {')
for i, f in enumerate(forms):
    kind, count, esz, q, lane, load, wb, rt = f
    text, vr = asm_for(f)
    w('    {"%s", %d, %d, %d, %d, %d, %d, %d, %d, fn_%d, PC(%d)},' % (
        text, kind, count, esz, q, lane, load, WB.index(wb), rt, i, i))
w('};')
w('#define NFORMS %d' % len(forms))
w(open(sys.argv[0].replace('.py', '.tail.c')).read())
open(sys.argv[1], 'w').write('\n'.join(o))
print(len(forms), 'forms')
