#!/usr/bin/env python3
"""Write jit/guest-riscv64/rcache.S: the riscv64 guest's register-cache gadgets.

    python3 tools/gen-rv-rcache.py [OUTPUT]

A straight run of register-only instructions (gen.c gen_riscv64_try_rcache_run)
keeps up to four guest registers in host x23-x26 for the length of the run: one
gadget loads the ones the run reads before writing, each instruction is a gadget
specialised by HOST register -- `add x23, x24, x25` and the dispatch, no operand
words and no cpu_state traffic -- and one gadget stores the ones it wrote. Reads
of x0 are xzr. The run contains nothing that can fault, call C or leave the
block, so nothing between the load and the store can see cpu_state stale.

Gadgets (names below gadget_riscv64_):
  rcache_rr_<op>_<d><a><b>   d in 0-3, a/b in 0-3 or z (x0)      no operands
  rcache_ri_<op>_<d><a>      the immediate is one stream word    [imm]
  rcache_mv_<d><a>           addi rd, rs, 0                      no operands
  rcache_li_<d>              lui/auipc/li: the value             [value]
  rcache_ld_<mask>           load the host registers in mask     [off] per bit
  rcache_st_<mask>           store them                          [off] per bit
and the pointer tables gen.c indexes: rv_rcache_rr[op][d][a][b] (a/b index 4
is x0), rv_rcache_ri[op][d][a], rv_rcache_mv[d][a], rv_rcache_li[d],
rv_rcache_ld[mask], rv_rcache_st[mask]. The op orders are RR_OPS and RI_OPS
below and must match gen.c's enum rv_rcache_rr_op / rv_rcache_ri_op.
"""

import sys

HOST = [23, 24, 25, 26]
SRCS = ['0', '1', '2', '3', 'z']

def x(s):
    return 'xzr' if s == 'z' else 'x%d' % HOST[int(s)]

def w(s):
    return 'wzr' if s == 'z' else 'w%d' % HOST[int(s)]

def sx(body):
    return body + ['sxtw {d}, {wd}']

# Register-register ops, in rv_rcache_rr order.
RR_OPS = [
    ('add',   ['add {d}, {a}, {b}']),
    ('sub',   ['sub {d}, {a}, {b}']),
    ('sll',   ['lsl {d}, {a}, {b}']),
    ('slt',   ['cmp {a}, {b}', 'cset {d}, lt']),
    ('sltu',  ['cmp {a}, {b}', 'cset {d}, lo']),
    ('xor',   ['eor {d}, {a}, {b}']),
    ('srl',   ['lsr {d}, {a}, {b}']),
    ('sra',   ['asr {d}, {a}, {b}']),
    ('or',    ['orr {d}, {a}, {b}']),
    ('and',   ['and {d}, {a}, {b}']),
    ('mul',   ['mul {d}, {a}, {b}']),
    ('mulh',  ['smulh {d}, {a}, {b}']),
    ('mulhu', ['umulh {d}, {a}, {b}']),
    ('addw',  sx(['add {wd}, {wa}, {wb}'])),
    ('subw',  sx(['sub {wd}, {wa}, {wb}'])),
    ('sllw',  sx(['lsl {wd}, {wa}, {wb}'])),
    ('srlw',  sx(['lsr {wd}, {wa}, {wb}'])),
    ('sraw',  sx(['asr {wd}, {wa}, {wb}'])),
    ('mulw',  sx(['mul {wd}, {wa}, {wb}'])),
]

# Register-immediate ops (immediate in x10), in rv_rcache_ri order. Shifts use
# the register forms: the amount is < 64 (< 32 for the W forms) by decode.
RI_OPS = [
    ('addi',  ['add {d}, {a}, x10']),
    ('slti',  ['cmp {a}, x10', 'cset {d}, lt']),
    ('sltiu', ['cmp {a}, x10', 'cset {d}, lo']),
    ('xori',  ['eor {d}, {a}, x10']),
    ('ori',   ['orr {d}, {a}, x10']),
    ('andi',  ['and {d}, {a}, x10']),
    ('slli',  ['lsl {d}, {a}, x10']),
    ('srli',  ['lsr {d}, {a}, x10']),
    ('srai',  ['asr {d}, {a}, x10']),
    ('addiw', sx(['add {wd}, {wa}, w10'])),
    ('slliw', sx(['lsl {wd}, {wa}, w10'])),
    ('srliw', sx(['lsr {wd}, {wa}, w10'])),
    ('sraiw', sx(['asr {wd}, {wa}, w10'])),
]

def fill(lines, d, a, b='z'):
    return ['    ' + l.format(d=x(d), a=x(a), b=x(b), wd=w(d), wa=w(a), wb=w(b)) for l in lines]

def main():
    out = []
    o = out.append
    o('// GENERATED by tools/gen-rv-rcache.py -- do not edit; edit the generator.')
    o('// riscv64 register-cache gadgets: see the generator\'s docstring and')
    o('// gen.c gen_riscv64_try_rcache_run.')
    o('#include "gadgets.h"')
    o('')
    o('.text')
    for name, body in RR_OPS:
        for d in '0123':
            for a in SRCS:
                for b in SRCS:
                    o('.gadget rcache_rr_%s_%s%s%s' % (name, d, a, b))
                    out.extend(fill(body, d, a, b))
                    o('    gret')
    for name, body in RI_OPS:
        for d in '0123':
            for a in SRCS:
                o('.gadget rcache_ri_%s_%s%s' % (name, d, a))
                o('    ldr x10, [_ip]')
                out.extend(fill(body, d, a))
                o('    gret 1')
    for d in '0123':
        for a in SRCS:
            o('.gadget rcache_mv_%s%s' % (d, a))
            o('    mov %s, %s' % (x(d), x(a)))
            o('    gret')
    for d in '0123':
        o('.gadget rcache_li_%s' % d)
        o('    ldr %s, [_ip]' % x(d))
        o('    gret 1')
    for kind, insn in (('ld', 'ldr'), ('st', 'str')):
        for mask in range(1, 16):
            bits = [i for i in range(4) if mask >> i & 1]
            o('.gadget rcache_%s_%d' % (kind, mask))
            for i, bit in enumerate(bits):
                o('    ldr x%d, [_ip, #%d]' % (9 + i, 8 * i))
            for i, bit in enumerate(bits):
                o('    %s x%d, [_cpu, x%d]' % (insn, HOST[bit], 9 + i))
            o('    gret %d' % len(bits))

    # Pointer tables: in .data, since .quad symbol references in .text are an
    # illegal text relocation on Mach-O.
    o('')
    o('.data')
    o('.balign 8')
    def table(name, entries):
        o('.global NAME(%s)' % name)
        o('NAME(%s) :' % name)
        for e in entries:
            o('    .quad %s' % ('0' if e is None else 'NAME(gadget_riscv64_%s)' % e))
    table('rv_rcache_rr', ['rcache_rr_%s_%s%s%s' % (n, d, a, b)
                           for n, _ in RR_OPS for d in '0123' for a in SRCS for b in SRCS])
    table('rv_rcache_ri', ['rcache_ri_%s_%s%s' % (n, d, a)
                           for n, _ in RI_OPS for d in '0123' for a in SRCS])
    table('rv_rcache_mv', ['rcache_mv_%s%s' % (d, a) for d in '0123' for a in SRCS])
    table('rv_rcache_li', ['rcache_li_%s' % d for d in '0123'])
    table('rv_rcache_ld', [None] + ['rcache_ld_%d' % m for m in range(1, 16)])
    table('rv_rcache_st', [None] + ['rcache_st_%d' % m for m in range(1, 16)])
    o('.text')

    path = sys.argv[1] if len(sys.argv) > 1 else 'jit/guest-riscv64/rcache.S'
    with open(path, 'w') as f:
        f.write('\n'.join(out) + '\n')

main()
