#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_vex_imm.c, or with --i386 i386_vex_imm.c
# (usage: this script [--i386] OUT.c).
#
# The VEX ops with an imm8 or a lane-local unary shape (AVX/AVX2): VPSHUFD/
# HW/LW, VSHUFPS/PD, VPERMILPS/PD imm, VPALIGNR, VPBLENDW, VBLENDPS/PD,
# VPBLENDD, VMPSADBW, VDPPS/PD, VROUNDPS/PD/SS/SD, VCVTDQ2PS/PS2DQ/TPS2DQ,
# VRCPPS/SS, VRSQRTPS/SS, VMOVSLDUP/SHDUP/DDUP -- VEX.128 and VEX.256,
# register and memory, against the same op's SSE form on the same machine,
# half by half with the high lane's own imm8 where the op has one (VBLENDPS
# bits 7:4 ...), result and MXCSR flags under three modes. camd runs it too.
import sys
I386 = '--i386' in sys.argv
ARGS = [a for a in sys.argv[1:] if a != '--i386']
NAME = 'i386_vex_imm' if I386 else 'amd64_vex_imm'
SH8 = [0x00, 0x1b, 0x4e, 0xb1, 0xe4, 0xff, 0x93, 0x6c]
# (vex mnemonic, sse mnemonic, shape, imms, high-lane imm transform, float, L-allowed)
# shape: 3 = dst, s1, s2 (+imm); 2 = dst, src (+imm); s = scalar 3-operand
OPS = [
    ('vpshufd', 'pshufd', 2, SH8, 'i', 0, 3), ('vpshufhw', 'pshufhw', 2, SH8, 'i', 0, 3),
    ('vpshuflw', 'pshuflw', 2, SH8, 'i', 0, 3), ('vpermilps', 'pshufd', 2, SH8, 'i', 0, 3),
    ('vshufps', 'shufps', 3, SH8, 'i', 0, 3), ('vshufpd', 'shufpd', 3, list(range(16)), 'i>>2', 0, 3),
    ('vpermilpd', 'PERMILPD', 2, list(range(16)), 'i>>2', 0, 3),
    ('vpalignr', 'palignr', 3, [0, 3, 8, 15, 16, 20, 31, 32], 'i', 0, 3),
    ('vpblendw', 'pblendw', 3, [0x00, 0xff, 0xa5, 0x3c], 'i', 0, 3),
    ('vblendps', 'blendps', 3, [0x00, 0xff, 0xa5, 0x3c, 0x0f, 0xf0], 'i>>4', 0, 3),
    ('vpblendd', 'blendps', 3, [0x00, 0xff, 0xa5, 0x3c, 0x0f, 0xf0], 'i>>4', 0, 3),
    ('vblendpd', 'blendpd', 3, list(range(16)), 'i>>2', 0, 3),
    ('vmpsadbw', 'mpsadbw', 3, [0, 7, 14, 21, 28, 35, 42, 49, 56, 63], 'i>>3', 0, 3),
    ('vdpps', 'dpps', 3, [0xff, 0xf1, 0x3c, 0x71, 0x0f], 'i', 1, 3),
    ('vdppd', 'dppd', 3, [0x33, 0x31, 0x13, 0x22], 'i', 1, 1),
    ('vroundps', 'roundps', 2, list(range(16)), 'i', 1, 3), ('vroundpd', 'roundpd', 2, list(range(16)), 'i', 1, 3),
    ('vroundss', 'roundss', 's', list(range(16)), 'i', 1, 1), ('vroundsd', 'roundsd', 's', list(range(16)), 'i', 1, 1),
    ('vcvtdq2ps', 'cvtdq2ps', 2, None, '', 1, 3), ('vcvtps2dq', 'cvtps2dq', 2, None, '', 1, 3),
    ('vcvttps2dq', 'cvttps2dq', 2, None, '', 1, 3), ('vrcpps', 'rcpps', 2, None, '', 1, 3),
    ('vrsqrtps', 'rsqrtps', 2, None, '', 1, 3), ('vrcpss', 'rcpss', 's', None, '', 1, 1),
    ('vrsqrtss', 'rsqrtss', 's', None, '', 1, 1), ('vmovsldup', 'movsldup', 2, None, '', 0, 3),
    ('vmovshdup', 'movshdup', 2, None, '', 0, 3), ('vmovddup', 'movddup', 2, None, '', 0, 3),
]
MODES = [0x1f80, 0x7f80, 0x9fc0]
o = []; w = o.append
w(f'''// Generated by tools/gen-vex-imm-test.py{" --i386" if I386 else ""} -- do not edit.
//
// The VEX imm8 and lane-local unary ops against their SSE forms on the same
// machine (see the generator).
#pragma GCC target("avx2")
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static unsigned long checks, bad;
static void check(const char *what, int k, const uint8_t *got, const uint8_t *want, unsigned gf, unsigned wf) {{
    checks++;
    if ((memcmp(got, want, 32) != 0 || gf != wf) && bad++ < 40) {{
        printf("FAIL %s (%d): flags %#x want %#x\\n  got ", what, k, gf, wf);
        for (int i = 31; i >= 0; i--) printf("%s%02x", i % 8 == 7 ? " " : "", got[i]);
        printf("\\n  want");
        for (int i = 31; i >= 0; i--) printf("%s%02x", i % 8 == 7 ? " " : "", want[i]);
        printf("\\n");
    }}
}}
static uint64_t rs = 0x9e3779b97f4a7c15ull;
static uint64_t rnd(void) {{ rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }}
static void ldmx(unsigned v) {{ __asm__ volatile("ldmxcsr %0" :: "m"(v)); }}
static unsigned stmx(void) {{ unsigned v; __asm__ volatile("stmxcsr %0" : "=m"(v)); return v; }}
struct st {{ uint8_t a[32], b[32], d[32], out[32], m[64]; }} __attribute__((aligned(32)));
static void fill(uint8_t *p, int fp) {{
    for (int i = 0; i < 32; i += 4) {{
        uint32_t v = (uint32_t) rnd();
        if (fp) {{
            static const uint32_t sp[] = {{0x7fc00000, 0x7f800001, 0xff800000, 0x00000001, 0x80000000, 0x4f000000, 0xcf000001, 0x3fc00000}};
            v = (v & 7) == 0 ? sp[(v >> 3) & 7] : (v & 0x807fffff) | (((v >> 23) % 60 + 100) << 23);
        }}
        memcpy(p + i, &v, 4);
    }}
}}
''')
# references
def ref_name(op, imm):
    return f'r_{op}_{imm if imm is not None else "n"}'
refs = set()
for vop, sop, shape, imms, hi, fp, lm in OPS:
    hi_imms = set()
    for imm in (imms or [None]):
        cand = [imm]
        if imm is not None:
            if hi == 'i>>2': cand.append(imm >> 2)
            if hi == 'i>>3': cand.append(imm >> 3)
            if hi == 'i>>4': cand.append(imm >> 4)
        for c in cand:
            key = (sop, c)
            if key in refs: continue
            refs.add(key)
            ia = '' if c is None else f'${c}, '
            if sop == 'PERMILPD':
                body = f'"movdqu (%1), %%xmm0\\n shufpd ${c & 3}, %%xmm0, %%xmm0\\n movdqu %%xmm0, (%2)"'
            elif shape == 2:
                body = f'"movdqu (%1), %%xmm1\\n {sop} {ia}%%xmm1, %%xmm0\\n movdqu %%xmm0, (%2)"'
            else:
                body = f'"movdqu (%0), %%xmm0\\n movdqu (%1), %%xmm1\\n {sop} {ia}%%xmm1, %%xmm0\\n movdqu %%xmm0, (%2)"'
            if shape == 2 and sop != 'PERMILPD':
                body = f'"movdqu (%0), %%xmm0\\n movdqu (%1), %%xmm1\\n {sop} {ia}%%xmm1, %%xmm0\\n movdqu %%xmm0, (%2)"'
            w(f'static void {ref_name(sop, c)}(const uint8_t *x, const uint8_t *y, uint8_t *r) {{ __asm__ volatile({body} :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1"); }}')
fi = 0
forms = []
def vexfn(body):
    global fi
    w(f'''__attribute__((noinline)) static void f{fi}(struct st *t) {{
    __asm__ volatile("vmovdqu (%0), %%ymm2\\n vmovdqu 32(%0), %%ymm3\\n vmovdqu 64(%0), %%ymm1\\n"
                     "{body}\\n vmovdqu %%ymm1, 96(%0)\\n vzeroupper" :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3");
}}''')
    fi += 1
    return fi - 1
for vop, sop, shape, imms, hi, fp, lm in OPS:
    for imm in (imms or [None]):
        ia = '' if imm is None else f'${imm}, '
        for L, x in ((256, 'ymm'), (128, 'xmm')):
            if not (lm & (2 if L == 256 else 1)):
                continue
            mx = 'xmm' if (vop == 'vmovddup' and L == 128) else x
            if shape == 3 or shape == 's':
                shapes = [('reg', f'{vop} {ia}%%{x}3, %%{x}2, %%{x}1', 'ab'), ('mem', f'{vop} {ia}128(%0), %%{x}2, %%{x}1', 'am'),
                          ('d=s2', f'{vop} {ia}%%{x}1, %%{x}2, %%{x}1', 'ad')]
            else:
                shapes = [('reg', f'{vop} {ia}%%{x}3, %%{x}1', 'bb'), ('mem', f'{vop} {ia}128(%0), %%{x}1', 'mm')]
            for lab, body, src in shapes:
                i = vexfn(body)
                himm = imm
                if imm is not None:
                    himm = {'i': imm, 'i>>2': imm >> 2, 'i>>3': imm >> 3, 'i>>4': imm >> 4}[hi]
                forms.append((i, f'{vop} {"" if imm is None else imm} {L} {lab}', ref_name(sop, imm), ref_name(sop, himm), L, src, fp, 1 if shape == 's' else 0,
                              1 if (vop == 'vmovddup' and lab == 'mem' and L == 128) else 0))
w('struct form { const char *name; void (*fn)(struct st *); void (*lo)(const uint8_t *, const uint8_t *, uint8_t *); void (*hi)(const uint8_t *, const uint8_t *, uint8_t *); int L; const char *src; int fp, scalar, m64; };')
w('static const struct form forms[] = {')
for i, name, lo, hi, L, src, fp, scalar, m64 in forms:
    w(f'    {{"{name}", f{i}, {lo}, {hi}, {L}, "{src}", {fp}, {scalar}, {m64}}},')
w('};')
w(f'#define NFORMS {len(forms)}')
w(f'static const unsigned modes[] = {{{", ".join(hex(m) for m in MODES)}}};')
w(r'''
int main(void) {
    static struct st t;
    for (int k = 0; k < 40; k++) {
        for (unsigned mi = 0; mi < sizeof modes / sizeof modes[0]; mi++) {
            for (int fi = 0; fi < NFORMS; fi++) {
                const struct form *f = &forms[fi];
                if (!f->fp && mi > 0) continue;
                fill(t.a, f->fp); fill(t.b, f->fp); fill(t.d, f->fp); fill(t.m, f->fp); fill(t.m + 32, f->fp);
                struct st in = t;
                ldmx(modes[mi]);
                f->fn(&t);
                unsigned gf = stmx() & 0x3f;
                const uint8_t *s1 = f->src[0] == 'd' ? in.d : f->src[0] == 'm' ? in.m : f->src[0] == 'b' ? in.b : in.a;
                const uint8_t *s2 = f->src[1] == 'm' ? in.m : f->src[1] == 'd' ? in.d : in.b;
                uint8_t m64[32] = {0}, want[32] = {0};
                if (f->m64) { memcpy(m64, in.m, 8); s2 = m64; }
                ldmx(modes[mi]);
                f->lo(s1, s2, want);
                unsigned wf = stmx() & 0x3f;
                if (f->L == 256) {
                    ldmx(modes[mi]);
                    f->hi(s1 + 16, s2 + 16, want + 16);
                    wf |= stmx() & 0x3f;
                }
                check(f->name, k, t.out, want, gf, wf);
            }
        }
    }
    ldmx(0x1f80);
    printf("NAME: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NFORMS, checks, bad);
    return bad != 0;
}''')
open(ARGS[0], 'w').write('\n'.join(o).replace('NAME: %s', NAME + ': %s'))
print(len(forms), 'forms')
