#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_vex_int.c, or with --i386 i386_vex_int.c
# (usage: this script [--i386] OUT.c).
#
# The VEX integer ops (AVX/AVX2: 66 0F, 66 0F38, the shift groups), every
# form: VEX.128 and VEX.256, register and memory sources, the destination
# aliasing either source -- each checked against the same op's SSE form
# run on the same machine, half by half: VEX.128 is the SSE result with bits
# 255:128 zeroed, VEX.256's high half the SSE op on the high halves (the
# ops are lane-local), a shift's count s2's low quadword in both. The SSE
# forms are themselves checked against an AMD Ryzen (amd64_sse_int and its
# kind), and camd runs this test too.
import sys
I386 = '--i386' in sys.argv
ARGS = [a for a in sys.argv[1:] if a != '--i386']
NAME = 'i386_vex_int' if I386 else 'amd64_vex_int'

BIN = '''punpcklbw punpcklwd punpckldq packsswb pcmpgtb pcmpgtw pcmpgtd packuswb punpckhbw punpckhwd
punpckhdq packssdw punpcklqdq punpckhqdq pcmpeqb pcmpeqw pcmpeqd paddq pmullw psubusb psubusw pminub
pand paddusb paddusw pmaxub pandn pavgb pavgw pmulhuw pmulhw psubsb psubsw pminsw por paddsb paddsw
pmaxsw pxor pmuludq pmaddwd psadbw psubb psubw psubd psubq paddb paddw paddd
pshufb phaddw phaddd phaddsw pmaddubsw phsubw phsubd phsubsw psignb psignw psignd pmulhrsw pmuldq
pcmpeqq packusdw pcmpgtq pminsb pminsd pminuw pminud pmaxsb pmaxsd pmaxuw pmaxud pmulld'''.split()
UN = 'pabsb pabsw pabsd'.split()
UN128 = ['phminposuw']
SHX = 'psrlw psrld psrlq psraw psrad psllw pslld psllq'.split()
SHI = 'psrlw psrld psrlq psraw psrad psllw pslld psllq psrldq pslldq'.split()
SHI_COUNTS = [0, 1, 3, 7, 8, 15, 16, 31, 32, 63, 64, 200]

R = 'e' if I386 else 'r'
o = []; w = o.append
w(f'''// Generated by tools/gen-vex-int-test.py{" --i386" if I386 else ""} -- do not edit.
//
// The VEX integer ops (AVX/AVX2), every form, against their SSE forms on the
// same machine, half by half (see the generator). {"Built -m32: xmm0-7." if I386 else "xmm0-15."}
#pragma GCC target("avx2")
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static unsigned long checks, bad;
static void check(const char *what, int k, const uint8_t *got, const uint8_t *want) {{
    checks++;
    if (memcmp(got, want, 32) != 0 && bad++ < 40) {{
        printf("FAIL %s (%d):", what, k);
        for (int i = 31; i >= 0; i--) printf("%s%02x", i % 8 == 7 ? " " : "", got[i]);
        printf("\\n  want         ");
        for (int i = 31; i >= 0; i--) printf("%s%02x", i % 8 == 7 ? " " : "", want[i]);
        printf("\\n");
    }}
}}
static uint64_t rs = 0x9e3779b97f4a7c15ull;
static uint64_t rnd(void) {{ rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }}

// the state: a s1, b s2 (32 bytes each), m s2 in memory, d the destination's
// old value, out the result
struct st {{ uint8_t a[32], b[32], d[32], out[32], m[64]; }} __attribute__((aligned(32)));
''')
forms = []
def form(name, vex_asm, ref_fn):
    forms.append((name, vex_asm, ref_fn))

# The SSE reference: one 128-bit SSE op on (x, y) -> x, into r
for op in BIN + UN + UN128:
    w(f'''static void sse_{op}(const uint8_t *x, const uint8_t *y, uint8_t *r) {{
    __asm__ volatile("movdqu (%0), %%xmm0\\n movdqu (%1), %%xmm1\\n {op} %%xmm1, %%xmm0\\n movdqu %%xmm0, (%2)"
                     :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1");
}}''')
for op in SHX:
    w(f'''static void sse_{op}(const uint8_t *x, const uint8_t *y, uint8_t *r) {{
    __asm__ volatile("movdqu (%0), %%xmm0\\n movdqu (%1), %%xmm1\\n {op} %%xmm1, %%xmm0\\n movdqu %%xmm0, (%2)"
                     :: "r"(x), "r"(y), "r"(r) : "memory", "xmm0", "xmm1");
}}''')
for op in SHI:
    w(f'static void sse_{op}_i(const uint8_t *x, int c, uint8_t *r) {{ switch (c) {{')
    for c in SHI_COUNTS:
        w(f'    case {c}: __asm__ volatile("movdqu (%0), %%xmm0\\n {op} ${c}, %%xmm0\\n movdqu %%xmm0, (%1)" :: "r"(x), "r"(r) : "memory", "xmm0"); break;')
    w('    }\n}')

# the VEX forms: t->a in ymm2 (s1), t->b in ymm3 (s2), t->d in ymm1 (dst), result from ymm1
regs = [('1', '2', '3')] if I386 else [('1', '2', '3'), ('9', '12', '14')]
def vexfn(i, body):
    w(f'''__attribute__((noinline)) static void f{i}(struct st *t) {{
    __asm__ volatile("vmovdqu (%0), %%ymm2\\n vmovdqu 32(%0), %%ymm3\\n vmovdqu 64(%0), %%ymm1\\n"
                     "vmovdqu %%ymm2, %%ymm{regs[-1][1]}\\n vmovdqu %%ymm3, %%ymm{regs[-1][2]}\\n vmovdqu %%ymm1, %%ymm{regs[-1][0]}\\n"
                     "{body}\\n vmovdqu %%ymm1, 96(%0)\\n vzeroupper"
                     :: "r"(t) : "memory", "xmm1", "xmm2", "xmm3"{'' if I386 else ', "xmm9", "xmm12", "xmm14"'});
}}''')
# shapes: (label, asm template with D S1 S2 placeholders, reference: which inputs)
SH = []
for L, yx in ((256, 'ymm'), (128, 'xmm')):
    SH.append((f'{L} reg', L, '{op} %%{x}3, %%{x}2, %%{x}1', 'ab'))
    SH.append((f'{L} mem', L, '{op} 128(%0), %%{x}2, %%{x}1', 'am'))
    SH.append((f'{L} d=s1', L, '{op} %%{x}3, %%{x}1, %%{x}1', 'db'))
    SH.append((f'{L} d=s2', L, '{op} %%{x}1, %%{x}2, %%{x}1', 'ad'))
    if not I386:
        SH.append((f'{L} hi regs', L, '{op} %%{x}14, %%{x}12, %%{x}9\\n vmovdqu %%ymm9, %%ymm1', 'ab'))
fi = 0
table = []
def add_bin(op, shapes, kind):
    global fi
    for lab, L, tmpl, src in shapes:
        x = 'ymm' if L == 256 else 'xmm'
        if kind == 'un':
            if 'd=s1' in lab or 'd=s2' in lab:
                continue
            tmpl2 = tmpl.replace('%%{x}2, ', '').replace(', %%{x}2', '').replace('%%{x}12, ', '')
            body = tmpl2.format(op='v' + op, x=x)
        else:
            body = tmpl.format(op='v' + op, x=x)
        vexfn(fi, body)
        table.append((fi, f'v{op} {lab}', op, L, src, kind))
        fi += 1
for op in BIN:
    add_bin(op, SH, 'bin')
for op in UN:
    add_bin(op, SH, 'un')
for op in UN128:
    add_bin(op, [s for s in SH if s[1] == 128], 'un')
for op in SHX:
    sh = [s for s in SH]
    for lab, L, tmpl, src in sh:
        x = 'ymm' if L == 256 else 'xmm'
        body = tmpl.format(op='v' + op, x=x).replace('128(%0), %%' + x + '2', '128(%0), %%' + x + '2')
        # the count operand is always an xmm / m128
        body = body.replace(f'%%ymm3, %%ymm', '%%xmm3, %%ymm').replace(f'%%ymm1, %%ymm2, %%ymm1', '%%xmm1, %%ymm2, %%ymm1').replace('%%ymm14, %%ymm12', '%%xmm14, %%ymm12')
        vexfn(fi, body)
        table.append((fi, f'v{op} {lab}', op, L, src, 'shx'))
        fi += 1
for op in SHI:
    for c in SHI_COUNTS:
        for L, x in ((256, 'ymm'), (128, 'xmm')):
            for lab, body in ((f'{L} ${c}', f'v{op} ${c}, %%{x}2, %%{x}1'), (f'{L} ${c} d=s', f'v{op} ${c}, %%{x}1, %%{x}1')):
                vexfn(fi, body)
                table.append((fi, f'v{op} {lab}', op, L, 'a' if 'd=s' not in lab else 'd', 'shi', c))
                fi += 1
w('struct form { const char *name; void (*fn)(struct st *); void (*ref)(const uint8_t *, const uint8_t *, uint8_t *); '
  'void (*refi)(const uint8_t *, int, uint8_t *); int L, kind, count; const char *src; };')
w('static const struct form forms[] = {')
for row in table:
    i, name, op, L, src, kind = row[:6]
    c = row[6] if len(row) > 6 else 0
    ref = f'sse_{op}' if kind != 'shi' else 'NULL'
    refi = f'sse_{op}_i' if kind == 'shi' else 'NULL'
    k = {'bin': 0, 'un': 1, 'shx': 2, 'shi': 3}[kind]
    w(f'    {{"{name}", f{i}, {ref}, {refi}, {L}, {k}, {c}, "{src}"}},')
w('};')
w(f'#define NFORMS {len(table)}')
w(r'''
int main(void) {
    static struct st t;
    for (int k = 0; k < 200; k++) {
        for (int fi = 0; fi < NFORMS; fi++) {
            const struct form *f = &forms[fi];
            for (int i = 0; i < 32; i++) { t.a[i] = (uint8_t) rnd(); t.b[i] = (uint8_t) rnd(); t.d[i] = (uint8_t) rnd(); }
            for (int i = 0; i < 64; i++) t.m[i] = (uint8_t) rnd();
            if (k % 4 == 1) memcpy(t.b, t.a, 32);
            if (k % 4 == 2) for (int i = 0; i < 32; i++) t.b[i] &= 0x8f;     // pshufb/shift: small values
            if (k % 4 == 3) for (int i = 0; i < 32; i += 8) memset(t.b + i + 1, 0, 7);   // shift counts in range
            if (f->kind == 2 && (k & 1)) { memset(t.b + 1, 0, 7); memset(t.m + 1, 0, 7); }
            struct st in = t;
            f->fn(&t);
            // the operands as the instruction saw them
            const uint8_t *s1 = f->src[0] == 'd' ? in.d : in.a;
            const uint8_t *s2 = f->src[1] == 'm' ? in.m : f->src[1] == 'd' ? in.d : in.b;
            if (f->src[0] == 'd' && f->src[1] == 0) s1 = in.d;
            uint8_t want[32] = {0};
            if (f->kind == 0) {
                f->ref(s1, s2, want);
                if (f->L == 256) f->ref(s1 + 16, s2 + 16, want + 16);
            } else if (f->kind == 1) {
                f->ref(s2, s2, want);
                if (f->L == 256) f->ref(s2 + 16, s2 + 16, want + 16);
            } else if (f->kind == 2) {
                f->ref(s1, s2, want);
                if (f->L == 256) f->ref(s1 + 16, s2, want + 16);   // the count: s2's low quadword
            } else {
                const uint8_t *s = f->src[0] == 'd' ? in.d : in.a;
                f->refi(s, f->count, want);
                if (f->L == 256) f->refi(s + 16, f->count, want + 16);
            }
            check(f->name, k, t.out, want);
        }
    }
    printf("NAME: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NFORMS, checks, bad);
    return bad != 0;
}''')
text = '\n'.join(o).replace('NAME: %s', NAME + ': %s')
if I386:
    text = text.replace('"r"(t)', '"r"(t)')
open(ARGS[0], 'w').write(text)
print(len(table), 'forms')
