#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_avx512_cmp.c, or with --i386
# i386_avx512_cmp.c (usage: this script [--i386] [--answers FILE] OUT.c).
#
# AVX-512 compares and tests into an opmask: VPCMPEQ/GT B/W/D/Q, VPCMP and
# VPCMPU B/W/D/Q under every predicate (and imm8s with high bits), VPTESTM
# and VPTESTNM, at VL 128/256/512, register, memory and {1toN} sources,
# with and without a write mask; elements are made equal often enough for
# EQ/LE/NLT to matter. Then encodings whose #UD-or-not is part of the answer.
# The result k register (all 64 bits) and the signal are hashed per form and
# checked against Intel SDE's (`sde64 -ptr-raise -spr -- ./test hashes` on
# camd, passed back with --answers); the i386 test takes the amd64 answers.
import sys
I386 = '--i386' in sys.argv
args = [a for a in sys.argv[1:] if a != '--i386']
answers = {}
if '--answers' in args:
    i = args.index('--answers')
    for line in open(args[i + 1]):
        k, v = line.rsplit(' ', 1)
        answers[k] = v.strip()
    del args[i:i + 2]
NAME = 'i386_avx512_cmp' if I386 else 'amd64_avx512_cmp'
OPS = [('vpcmpeqb', 0, None), ('vpcmpeqw', 0, None), ('vpcmpeqd', 4, None), ('vpcmpeqq', 8, None),
       ('vpcmpgtb', 0, None), ('vpcmpgtw', 0, None), ('vpcmpgtd', 4, None), ('vpcmpgtq', 8, None),
       ('vptestmb', 0, None), ('vptestmw', 0, None), ('vptestmd', 4, None), ('vptestmq', 8, None),
       ('vptestnmb', 0, None), ('vptestnmw', 0, None), ('vptestnmd', 4, None), ('vptestnmq', 8, None)]
for n, bc in (('vpcmpb', 0), ('vpcmpw', 0), ('vpcmpd', 4), ('vpcmpq', 8), ('vpcmpub', 0), ('vpcmpuw', 0),
              ('vpcmpud', 4), ('vpcmpuq', 8)):
    OPS.append((n, bc, [0, 1, 2, 3, 4, 5, 6, 7, 0x0d, 0xfa]))
VL = [(128, 'xmm'), (256, 'ymm'), (512, 'zmm')]
F = []
for op, bc, imms in OPS:
    for imm in (imms or [None]):
        im = '' if imm is None else f'${imm}, '
        nm = op if imm is None else f'{op} ${imm}'
        for L, x in VL:
            for mk, mn in (('', ''), ('%{%%k2%}', 'm')):
                F.append((f'{nm} {L} reg{mn}', f'{op} {im}%%{x}3, %%{x}2, %%k1{mk}'))
                F.append((f'{nm} {L} mem{mn}', f'{op} {im}(%1), %%{x}2, %%k1{mk}'))
                if bc:
                    n = L // (8 * bc)
                    F.append((f'{nm} {L} bcst{mn}', f'{op} {im}(%1)%{{1to{n}%}}, %%{x}2, %%k1{mk}'))
UD = {'vpcmpeqd ok': '62 f1 6d 48 76 cb', 'vpcmpeqd z': '62 f1 6d c9 76 cb', 'vpcmpd ok': '62 f3 6d 48 1f cb 01',
      'vpcmpeqd W1': '62 f1 ed 48 76 cb', 'vpcmpeqq W0': '62 f2 6d 48 29 cb'}
if not I386:
    UD.update({'vpcmpeqd R': '62 71 6d 48 76 cb', "vpcmpeqd R'": '62 e1 6d 48 76 cb', 'vpcmpeqd B': '62 d1 6d 48 76 cb'})
for k, b in UD.items():
    F.append((f'ud {k}', 'ud:' + ', '.join('0x' + x for x in b.split())))
R = 'e' if I386 else 'r'
o = []; w = o.append
w(f'''// Generated by tools/gen-avx512-cmp-test.py{" --i386" if I386 else ""} -- do not edit.
//
// AVX-512 compares and tests into an opmask, against Intel SDE (see the
// generator). (No target pragma: the harness itself must not use AVX-512.)
#include <setjmp.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
static uint64_t rs;
static uint64_t rnd(void) {{ rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }}
struct st {{ uint8_t a[64], b[64], m[64]; uint64_t k2, k1, ok1; }} __attribute__((aligned(64)));
static sigjmp_buf jb;
static volatile int sig;
static void handler(int s) {{ sig = s; siglongjmp(jb, 1); }}
#define LOAD "vmovdqu64 (%0), %%zmm2\\n vmovdqu64 64(%0), %%zmm3\\n kmovq 192(%0), %%k2\\n kmovq 200(%0), %%k1\\n"
''')
for i, (name, asm) in enumerate(F):
    if asm.startswith('ud:'):
        w(f'''__attribute__((noinline)) static void f{i}(struct st *t) {{
    __asm__ volatile(LOAD "mov %1, %%{R}ax\\n .byte {asm[3:]}\\n kmovq %%k1, 208(%0)" :: "r"(t), "r"(t->m) : "memory", "{R}ax", "xmm1", "xmm2", "xmm3");
}}''')
    else:
        w(f'''__attribute__((noinline)) static void f{i}(struct st *t) {{
    __asm__ volatile(LOAD "{asm}\\n kmovq %%k1, 208(%0)" :: "r"(t), "r"(t->m) : "memory", "xmm2", "xmm3");
}}''')
w('static const struct { const char *name; void (*fn)(struct st *); } forms[] = {')
for i, (name, asm) in enumerate(F):
    w(f'    {{"{name}", f{i}}},')
w('};')
w(f'#define NF {len(F)}')
if answers:
    w('static const uint64_t want[NF] = {')
    for name, asm in F:
        w(f'    {answers[name]}ull,')
    w('};')
else:
    w('static const uint64_t want[NF];   // (run with "hashes" under SDE)')
w(r'''
static int run(void (*fn)(struct st *), struct st *t) {
    sig = 0;
    if (!sigsetjmp(jb, 1))
        fn(t);
    return sig;
}

int main(int argc, char **argv) {
    int print = argc > 1 && !strcmp(argv[1], "hashes"), dump = argc > 1 && !strcmp(argv[1], "dump");
    unsigned long checks = 0, bad = 0;
    static struct st t;
    signal(SIGILL, handler);
    for (int fi = 0; fi < NF; fi++) {
        uint64_t h = 0xcbf29ce484222325ull;
        rs = 0x9e3779b97f4a7c15ull;
        for (const char *c = forms[fi].name; *c; c++) rs = (rs ^ (uint8_t) *c) * 0x100000001b3ull;
        int ud = !strncmp(forms[fi].name, "ud ", 3);
        for (int k = 0; k < (ud ? 1 : 24); k++) {
            for (int i = 0; i < 64; i += 8) {
                uint64_t r;
                r = rnd(); memcpy(t.a + i, &r, 8);
                r = rnd(); memcpy(t.b + i, &r, 8);
                r = rnd(); memcpy(t.m + i, &r, 8);
            }
            /* equal (and near) elements: copy a's bytes to b and m in random runs */
            for (int i = 0; i < 64; i++) {
                uint64_t r = rnd();
                if (r & 1) t.b[i] = t.a[i];
                if (r & 2) t.m[i] = t.a[i];
                if ((r & 12) == 12) t.b[i] = (uint8_t) (t.a[i] + 1);
            }
            if (k == 3) memcpy(t.b, t.a, 64);
            if (k == 4) for (int i = 0; i < 64; i++) t.a[i] = t.b[i] = t.m[i] = (uint8_t) (i & 1 ? 0x80 : 0x7f);
            t.k2 = rnd(); t.k1 = rnd();
            if (k == 2) t.k2 = 0;
            t.ok1 = 0;
            int sg = run(forms[fi].fn, &t);
            for (int b = 0; b < 8; b++) h = (h ^ ((t.ok1 >> (8 * b)) & 0xff)) * 0x100000001b3ull;
            h = (h ^ (unsigned) sg) * 0x100000001b3ull;
            if (dump)
                printf("%s %d: sig %d k1 %016llx\n", forms[fi].name, k, sg, (unsigned long long) t.ok1);
        }
        if (print) printf("%s %#llx\n", forms[fi].name, (unsigned long long) h);
        checks++;
        if (!print && !dump && h != want[fi] && bad++ < 40)
            printf("FAIL %s\n", forms[fi].name);
    }
    if (!print && !dump)
        printf("NAME: %s (%d forms, %lu checks, %lu mismatches)\n", bad ? "FAIL" : "PASS", NF, checks, bad);
    return bad != 0;
}''')
open(args[0], 'w').write('\n'.join(o).replace('NAME: %s', NAME + ': %s'))
print(len(F), 'forms')
