#!/usr/bin/env python3
# Generates tests/manual/x86/amd64_shift.c (usage: this script OUT.c).
import sys
GRP = ['rol', 'ror', 'rcl', 'rcr', 'shl', 'shr', 'sal', 'sar']
SUF = {8: 'b', 16: 'w', 32: 'l', 64: 'q'}
CREG = {8: '%%cl', 16: '%%cx', 32: '%%ecx', 64: '%%rcx'}
o = []; w = o.append
w('''// Generated by tools/gen-amd64-shift-test.py -- do not edit.
//
// ROL ROR RCL RCR SHL SHR SAL(/6) SAR in 8/16/32/64 bits, by 1, by CL (every
// count 0-63, so the 5/6-bit mask and the 8/16-bit RCL/RCR modulus) and by
// an imm8, on a register (AH..BH included) and on memory, against a model of
// the SDM: the result, and the flags it defines -- CF, OF for a count of 1,
// SF/ZF/PF for the shifts; a masked count of 0 changes nothing, but a 32-bit
// register is still written (zero-extended), as on hardware. /6 is SHL. The
// model is checked against real hardware (an AMD Ryzen): undefined flags are
// left out, since they differ between vendors. The gadgets
// are math.S's amd64_shift_mem* and amd64_shift_rr* and the narrower native
// shift families before them.
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static unsigned long checks, bad;
static void check(const char *what, long k, uint64_t got, uint64_t want) {
    checks++;
    if (got != want && bad++ < 40)
        printf("FAIL %s (%ld): %#llx, want %#llx\\n", what, k, (unsigned long long) got, (unsigned long long) want);
}
#define CF 0x1
#define PF 0x4
#define AF 0x10
#define ZF 0x40
#define SF 0x80
#define OF 0x800
static uint64_t rs = 0x243f6a8885a308d3ull;
static uint64_t rnd(void) { rs ^= rs << 13; rs ^= rs >> 7; rs ^= rs << 17; return rs; }

// the SDM; f_in the flags before (CF used by RCL/RCR, the rest kept where untouched)
static uint64_t model(int g, int bits, uint64_t v, unsigned count, uint64_t f_in, uint64_t *f_out) {
    uint64_t m = bits == 64 ? ~0ull : (1ull << bits) - 1, msb = 1ull << (bits - 1);
    v &= m;
    unsigned c = count & (bits == 64 ? 63 : 31);
    uint64_t f = f_in, r = v;
    if (g == 6) g = 4;
    if (g == 2 || g == 3) {
        unsigned e = bits < 32 ? c % (bits + 1) : c;
        if (e == 0) { *f_out = f; return v; }
        int cf = (f & CF) != 0;
        for (unsigned i = 0; i < e; i++) {
            int out;
            if (g == 2) { out = (r & msb) != 0; r = ((r << 1) & m) | cf; }
            else { out = r & 1; r = (r >> 1) | (cf ? msb : 0); }
            cf = out;
        }
        f = (f & ~CF) | (cf ? CF : 0);
        if (e == 1) {
            int of = g == 2 ? (((r & msb) != 0) ^ cf) : (((r & msb) != 0) ^ ((r & (msb >> 1)) != 0));
            f = (f & ~OF) | (of ? OF : 0);
        }
        *f_out = f; return r;
    }
    if (c == 0) { *f_out = f; return v; }
    if (g == 0 || g == 1) {
        unsigned e = c % bits;
        if (e) r = g == 0 ? ((v << e) | (v >> (bits - e))) & m : ((v >> e) | (v << (bits - e))) & m;
        int cf = g == 0 ? (r & 1) : (r & msb) != 0;
        f = (f & ~CF) | (cf ? CF : 0);
        if (c == 1) {
            int of = g == 0 ? (((r & msb) != 0) ^ cf) : (((r & msb) != 0) ^ ((r & (msb >> 1)) != 0));
            f = (f & ~OF) | (of ? OF : 0);
        }
        *f_out = f; return r;
    }
    int cf = 0, of = 0;
    if (g == 4) {
        r = c >= 64 ? 0 : (v << c) & m;
        if (c <= (unsigned) bits) cf = (v >> (bits - c)) & 1;
        if (c == 1) of = ((r & msb) != 0) ^ cf;
    } else if (g == 5) {
        r = v >> c;
        if (c <= (unsigned) bits) cf = (v >> (c - 1)) & 1;
        if (c == 1) of = (v & msb) != 0;
    } else {
        int64_t sv = bits == 64 ? (int64_t) v : (int64_t) (v << (64 - bits)) >> (64 - bits);
        r = (uint64_t) (sv >> c) & m;
        cf = c <= (unsigned) bits ? (int) ((uint64_t) sv >> (c - 1)) & 1 : (v & msb) != 0;
    }
    f &= ~(uint64_t) (CF | OF | AF | ZF | SF | PF);
    f |= (cf ? CF : 0) | (of ? OF : 0) | (r == 0 ? ZF : 0) | (r & msb ? SF : 0) |
         (__builtin_parity((unsigned) (r & 0xff)) ? 0 : PF);
    *f_out = f; return r;
}
''')
forms = []   # (name, g, bits, kind(0 one,1 cl,2 imm), where(0 reg, 1 high, 2 mem), asm)
for bits in (8, 16, 32, 64):
    s = SUF[bits]
    reg = {8: '%%dl', 16: '%%dx', 32: '%%edx', 64: '%%rdx'}[bits]
    for g, op in enumerate(GRP):
        enc = {0: 'D0', 1: 'D2'}
        for kind in (0, 1, 2):
            cnt = '$1, ' if kind == 0 else (f'{CREG[8]}, ' if kind == 1 else '$IMM, ')
            if op == 'sal':
                # gas emits /4 for sal: hand-encode /6 (66/REX as needed)
                pre = {8: '', 16: '.byte 0x66\\n', 32: '', 64: '.byte 0x48\\n'}[bits]
                opc = {(8, 0): 0xd0, (8, 1): 0xd2, (8, 2): 0xc0}.get((bits, kind), {0: 0xd1, 1: 0xd3, 2: 0xc1}[kind])
                regasm = f'{pre}.byte 0x{opc:02x}, 0xf2' + (', IMMB' if kind == 2 else '')          # /6, rm = rdx/edx/dx/dl
                memasm = f'{pre}.byte 0x{opc:02x}, 0x36' + (', IMMB' if kind == 2 else '')          # /6, (%rsi)
                forms.append((f'sal{s} /6 reg k{kind}', g, bits, kind, 0, regasm))
                forms.append((f'sal{s} /6 mem k{kind}', g, bits, kind, 2, memasm))
                continue
            forms.append((f'{op}{s} reg k{kind}', g, bits, kind, 0, f'{op}{s} {cnt}{reg}'))
            if bits == 8:
                forms.append((f'{op}b %dh k{kind}', g, bits, kind, 1, f'{op}b {cnt}%%dh'))
            forms.append((f'{op}{s} mem k{kind}', g, bits, kind, 2, f'{op}{s} {cnt}(%%rsi)'))
for i, f in enumerate(forms):
    name, g, bits, kind, where, asm = f
    imm = 1 + (i * 7) % 63
    a = asm.replace('$IMM', f'${imm}').replace('IMMB', f'{imm}')
    w(f'''__attribute__((noinline)) static void f{i}(uint64_t *d, uint8_t *mem, uint64_t cl, uint64_t *fl) {{
    uint64_t rd = *d, f, fin = *fl;
    __asm__ volatile("push %4\\n popfq\\n {a}\\n pushfq\\n pop %0"
                     : "=&r"(f), "+d"(rd) : "c"(cl), "S"(mem), "r"(fin) : "cc", "memory");
    *d = rd; *fl = f;
}}''')
w('struct form { const char *name; int g, bits, kind, where; void (*fn)(uint64_t *, uint8_t *, uint64_t, uint64_t *); unsigned imm; };')
w('static const struct form forms[] = {')
for i, f in enumerate(forms):
    name, g, bits, kind, where, asm = f
    imm = 1 + (i * 7) % 63
    w(f'    {{"{name}", {g}, {bits}, {kind}, {where}, f{i}, {imm}}},')
w('};')
w(f'#define NFORMS {len(forms)}')
w('''
int main(void) {
    static uint8_t buf[64] __attribute__((aligned(16)));
    for (int k = 0; k < 256; k++) {
        for (int fi = 0; fi < NFORMS; fi++) {
            const struct form *f = &forms[fi];
            uint64_t d = rnd(), memv = rnd(), cl = k & 63;
            if (k % 5 == 0) d = memv = 0x8000000000000001ull;
            uint64_t fin = 0x202 | (rnd() & (CF | PF | AF | ZF | SF | OF));
            uint8_t *mem = buf + 16 + (k % 8);
            memcpy(mem, &memv, 8);
            uint64_t d0 = d, fl = fin;
            f->fn(&d, mem, cl, &fl);
            unsigned count = f->kind == 0 ? 1 : f->kind == 1 ? (unsigned) cl : f->imm;
            uint64_t m = f->bits == 64 ? ~0ull : (1ull << f->bits) - 1, wf;
            uint64_t src = f->where == 2 ? memv : f->where == 1 ? d0 >> 8 : d0;
            uint64_t r = model(f->g, f->bits, src, count, fin, &wf);
            // only the flags the SDM defines (the rest differ between vendors):
            // a masked count of 0 changes nothing; AF is undefined after a
            // shift; OF is defined for a count of 1 only; CF for SHL/SHR at or
            // past the width is undefined; RCL/RCR by a multiple of width+1 is
            // a zero-bit rotate and changes nothing.
            unsigned mc = count & (f->bits == 64 ? 63 : 31);
            int g = f->g == 6 ? 4 : f->g;
            uint64_t def = CF | PF | AF | ZF | SF | OF;
            if (mc) {
                if (g >= 4) def &= ~(uint64_t) AF;
                if (mc != 1) def &= ~(uint64_t) OF;
                if ((g == 4 || g == 5) && mc >= (unsigned) f->bits) def &= ~(uint64_t) CF;
            }
            check(f->name, fi * 1000 + k, fl & def, wf & def);
            if (f->where == 2) {
                uint64_t cur; memcpy(&cur, mem, 8);
                check(f->name, fi * 1000 + k, cur, (memv & ~m) | r);
                check(f->name, fi * 1000 + k, d, d0);
            } else if (f->where == 1) {
                check(f->name, fi * 1000 + k, d, (d0 & ~0xff00ull) | (r << 8));
            } else {
                check(f->name, fi * 1000 + k, d, f->bits == 32 ? r : f->bits == 64 ? r : (d0 & ~m) | r);
            }
        }
    }
    printf("amd64_shift: %s (%d forms, %lu checks, %lu mismatches)\\n", bad ? "FAIL" : "PASS", NFORMS, checks, bad);
    return bad != 0;
}''')
open(sys.argv[1], 'w').write('\n'.join(o))
print(len(forms), 'forms')
